### ISSUE TITLE
XbimModel.Delete() is throwing Method Not Implemented Exception

### ISSUE THREAD

**Issue by mccune** [xBimTeam/XbimEssentials#1]
I am attempting to create a method to delete elements in a model; however, I get the follwoing exception from the code below.

Exception:
"The method or operation is not implemented."

Code:

        public static string Delete(XbimModel IfcModel, IfcElement IfcElement)
        {
            try
            {
                List<IPersistIfcEntity> m_IPersistObjects = IfcModel.Instances.OfType("IfcElement", true).ToList(); ;
                
                foreach (IPersistIfcEntity m_PersistObj in m_IPersistObjects)
                {
                    IfcElement m_Element = m_PersistObj as IfcElement;

                    if(m_Element.Name.ToString().ToLower() == IfcElement.Name.ToString().ToLower())
                    {
                        // Delete existing 
                        using (XbimReadWriteTransaction txn = IfcModel.BeginTransaction("Delete IfcElement"))
                        {
                            IfcModel.Delete(m_PersistObj);
                        }
                        return c._Success;
                    }
                }    
            }
            catch { }
            return null;
        }

**Comment by AThorwesten** [comment]
Delete(m_PersistObj) calls Delete_Reversable(m_PersistObj) in IfcPersistedInstanceCache.cs, which is actually not implemented.

    public void Delete_Reversable(IPersistIfcEntity instance)
    {
        throw new NotImplementedException();
    }

**Comment by mccune** [comment]
Thanks AThorwesten. Is there another method implemented to delete objects that inherit from IfcRoot?

**Comment by SteveLockley** [comment]
In reality we have not handled delete so far. It is a complex issue as understanding the correct behavior for delete propagation is not explicitly defined in the IFC model schema.. We generally adopt a policy of copying out from one database to another to make models that do not contain what we want and leave behind the objects we don't . Look at XbimExtract in the Utilities project for an example of how to do this. It will propagate any dependency and copy those objects that are directly referenced automatically. Beware of the inverse relationships, they cause circular dependencies sometimes which means the whole model can get copied. What we need to do is have a mechanism to drop objects and then discard them rather like a garbage collector, but the thing that needs the attention to do this is the database engine. If you could provide more details on why you need to do this we might be able to offer better suggestions.

**Comment by CBenghi** [comment]
Closed because of long delay in user response, but the question stands, if somebody else is interested please reopen the issue.
