### ISSUE TITLE
Model.Saveas ReportProgressDelegate

### ISSUE THREAD

**Issue by JukkaMeklin** [xBimTeam/XbimEssentials#101]
Hello,

Is it possible to report saving progress. I tested it with following code, but couldn't get it to work

Public rpd As Xbim.Common.ReportProgressDelegate
rpd = AddressOf ProgressChanged

model.SaveAs(IfcFile, IfcStorageType.Ifc, rpd)

Private Sub ProgressChanged(percentProgress As Integer, userState As Object)
	MsgBox(percentProgress.ToString)
End Sub

Regards,
Jukka

**Comment by mmmggg** [comment]
Still not working. Small issue with the percent calculation.

` var percent = (int)((float)counter / (float)count);`

**should be:**
`var percentage = Convert.ToInt32(Convert.ToDouble(counter) / Convert.ToDouble(count) * 100);`

Missing the multiply operation.
