### ISSUE TITLE
Does WexBIM incorporates IfcSpace objects?

### ISSUE THREAD

**Issue by jdimyadi** [xBimTeam/XbimEssentials#102]
I've converted a model that only has IfcSpace objects to WexBIM and nothing is displayed. Does WexBIM actually have IfcSpace objects included or not?

**Comment by martin1cerny** [comment]
Yes it has but it is switched off by default in the viewer. Just set state to undefined for ifcspace.

**Comment by jdimyadi** [comment]
Thank you. I'll try it out, but first I need to learn how to set the state of a particular object in xViewer.

**Comment by jdimyadi** [comment]
I tried your suggestion using:

viewer.setState(xState.UNDEFINED, types.IFCSPACE);

but nothing was displayed. Please see attached my wexBIM file that should contains only IfcSpace objects.


[Test4_spaces.zip](https://github.com/xBimTeam/XbimEssentials/files/1281086/Test4_spaces.zip)

**Comment by martin1cerny** [comment]
All your spaces have a transparent colour so they are not visible. If you set them to a non-transparent colour you will see them
```js
viewer.setState(State.UNDEFINED, 454);
viewer.defineStyle(0, [255,0,0,255]);
viewer.setStyle(0, 454);
```
![image](https://user-images.githubusercontent.com/773078/36732892-4c8a5b4e-1bcf-11e8-908a-32c7b5716bc0.png)

**Comment by martin1cerny** [comment]
So, this is xBIM Web UI issue really, not xBIM Essentials.
