### ISSUE TITLE
ItemSet of ItemSet in IfcCartesianPointList2D

### ISSUE THREAD

**Issue by eugeneeek** [xBimTeam/XbimEssentials#105]
In entity IfcCartesianPointList2D we have property "IItemSet<IItemSet<IfcLengthMeasure>> @CoordList".
This property initialized in constructor and we may use "Add" method for adding new items. But item in that case is ItemSet and as it constructor is internal we cann't create instance of this type.
So please help me, say how work with this property (@CoordList)?

**Comment by martin1cerny** [comment]
Hi @eugeneeek , you have to use `IfcCartesianPointList2D.Coordlist.GetAt(int index)`. Where is you specify `index` the same as `length` it will create new one for you. I know this is not very intuitive but lists don't have public constructors to make sure they  are always part of the model and all changes are tracked inside of transactions.

**Comment by eugeneeek** [comment]
I understand now. Thanks a lot!
