### ISSUE TITLE
Unable to convert IFC to Wexbim.

### ISSUE THREAD

**Issue by Dhruti03** [xBimTeam/XbimEssentials#106]
Hello,
I'm facing an exception while converting IFC file to wexbim. While creating context it gives exception. I have attached the snap of exception and IFC file. Please let me know the solution asap.
Thanks.

![breakmode](https://user-images.githubusercontent.com/30585303/30476731-8a423e8a-9a28-11e7-8b58-79c431e39105.png)

**Comment by Dhruti03** [comment]
Hello, 
I'm facing an exception while converting IFC file to wexbim. While creating context it gives exception at the time of creating geometry object on line "geomModel = Engine.Create(shape);". I have attached the snap of exception and IFC file. Please let me know the solution asap.
[Model_5.zip](https://github.com/xBimTeam/XbimEssentials/files/1309818/Model_5.zip)

Thanks.
![coverterror](https://user-images.githubusercontent.com/30585303/30530474-a0e66f42-9c64-11e7-94eb-3c7c306ab63e.png)

**Comment by martin1cerny** [comment]
There is no file attached hence it is impossible to reproduce the exception.

**Comment by martin1cerny** [comment]
Closing as this is clearly xBIM Geometry issue, nothing to do with xBIM Essentials. To help xBIM Team to solve the issue you will need to add some sample data and minimal code to reproduce the issue.
