### ISSUE TITLE
Exceptions when using Create(model).SomeExpressType().

### ISSUE THREAD

**Issue by Artoymyp** [xBimTeam/XbimEssentials#109]
One cannot use `Xbim.Ifc4.Interfaces.Create` factory functions with default value (`null`) for the argument `init`.
For example:
```
using (var m = IfcStore.Create(IfcSchemaVersion.Ifc2X3, XbimStoreType.InMemoryModel)) {
	var c = new Create(m);
	using (var tr = m.BeginTransaction()) {
		var s1 = c.ExtrudedAreaSolid((s) => { }); // Ok
		var s2 = c.ExtrudedAreaSolid(); // 'System.NullReferenceException' in Xbim.Ifc2x3.dll
	}
}
```
Is there a reason why default value is not safe? I propose to either remove the default value or handle the null-value.

**Comment by martin1cerny** [comment]
This class hasn't been used very much since it was created and I always use initializers to write better readable code. But you are right, this is dangerous error which needs to be caught in compile time. I've just pushed commit to develop which fixes this.

Martin
