### ISSUE TITLE
IFC Unit Symbol

### ISSUE THREAD

**Issue by BisiAden** [xBimTeam/XbimEssentials#111]
Hi, 
  I am trying to export unit symbols from my application into .ifc files. I have done this with length, area, volume and mass and it works fine. But I am having troubles doing the same with Time and other derived units. 

I want the units column to display "s" - seconds under property section when a particular item that has a time property is clicked. 
Please, I would love it if you can help I have been trying to get a solution for this for over 3 weeks now. 

Thank you, 
Bisola Adeniyi

**Comment by martin1cerny** [comment]
Hi @BisiAden , can you give us more detail about what you are trying to achieve? It is not very obvious from your description. Can you add some code examples, data examples and screenshots please?

**Comment by BisiAden** [comment]
HI, thanks for replying, 
  I created an IFC file with a pipe, and at the moment when the file is uploaded in Bim Vision and I click on the pipe, its properties are displayed as below.

![ifc1](https://user-images.githubusercontent.com/29728570/31374220-fcb4e5d8-ad94-11e7-862e-90fc98062e2f.PNG)

In the pipe properties all the values are displayed as expected but not all the units are displayed as expected. For example, the BaseFlow and the DeignFlow should be in "m/s" but they are not displaying anything. 
 After investigating the section of my code handling this, which I copy-pasted below:

![ifc2](https://user-images.githubusercontent.com/29728570/31374511-2f239e6e-ad96-11e7-9ded-bc414baf3a95.PNG)

what I noticed is, for some reason, the units for metre, metre2 and mass has the symbol method method "m" and "m2", but the units for second and metresec do not have any string assigned the method symbol. Unfortunately, I can not manually assign it because method Symbol is a read only method.

Below is a screenshot taken when in debug mode for clarity:
![image](https://user-images.githubusercontent.com/29728570/31374939-dd3da16a-ad97-11e7-9072-0c8dce3088bb.png)
Here the Symbol property is assigned "m"

![image](https://user-images.githubusercontent.com/29728570/31374977-0003d354-ad98-11e7-8ce7-afe61eb7e986.png)
Here the Symbol property is not assigned anything.

Please, I would appreciate your help I have been battling this more a very long time now. Looking forward for your response. 

Thanks

**Comment by martin1cerny** [comment]
`Symbol` property is only there as a convenience member implemented in xBIM to simplify visualization of the data and it only shows symbol for a few basic units. Bim Vision will have its own ways to present data based on IFC definitions. Or is Bim Vision your product based on xBIM?

**Comment by BisiAden** [comment]
Not necessarily. But I am using Bim Vision just for testing because its free and its the only one I know. Do you have any idea as to IFC file reader I could use? 
Also, Do you know how I can make the units visible in Bim Vision?
