### ISSUE TITLE
Problem with IIfcLightFixture

### ISSUE THREAD

**Issue by Cymap-NZ** [xBimTeam/XbimEssentials#112]
Hi First few steps with the XBIM LIB. Following the example have a small test app that can query an IFC file and return walls windows floors, and a few basic HVAC items.  

I'm now experimenting with adding  entities into the IFC model.

` _var LightFitting = model.Instances.New<IIfcLightFixture>;_ `

however this line barfs, as IIfcLightFixture does not inherit from IInstantiableEntity.  
So essentially is a read only object?? Any reason for this?
 IF I look up a more basic item like IfcWallStandardCase I can add one of those to the model as it it does inherit from IInstantiableEntity.  My interest is in being able to add HVAC data into an IFC model. But if all the definitions are read only then currently it wont be possible?

**Comment by Cymap-NZ** [comment]
var LightFitting = model.Instances.New<IIfcLightFixture>; 
Is the line of code that barfs!

**Comment by Cymap-NZ** [comment]
var LightFitting = model.Instances.New'<IIfcLightFixture>';

**Comment by Cymap-NZ** [comment]
var LightFitting = model.Instances.New IIfcLightFixture; brackets are lost in copy paste!

**Comment by Cymap-NZ** [comment]
looking @ IFC documentation, this is a subclass of a flowterminal.  But Flow terminal also does not inherit from IInstantiableEntity, so not certain how you would insert this type of object into an IFC file?

**Comment by martin1cerny** [comment]
You just can instantiate interface. So, you can do `model.Instances.New<IfcLightFixture>;`, but you can't do `model.Instances.New<IIfcLightFixture>;`. That also means that while for data querying you can use IFC4 interfaces, for data creation you have to use types specific for the actual IFC schema version (IFC2x3 or IFC4). This is necessary because some classes from IFC4 don't exist in IFC2x3.

**Comment by Cymap-NZ** [comment]
Hi Thanks martin, makes perfect sense, will need to keep track of the version open, and insert only objects that are relevant to the standard of the open model.  Have yet to get my head around how exactly that will be done, as a light fixture is actually a sub-class of flow terminal, so presumably you place a flow terminal and attach the light fixture to that, and of course the flow terminal, might be hosted by a ceiling, which of itself is part of a room/space.

**Comment by martin1cerny** [comment]
Yes, you will need to study [IFC documentation](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/) to learn how new data should be structured. xBIM is a complete implementation and will allow you to create everything defined in the standard.
