### ISSUE TITLE
Tessellation is done in floats, resulting in loss of precision

### ISSUE THREAD

**Issue by AlainBolduc** [xBimTeam/XbimEssentials#113]
Hi XBim Team, 

one of our colleagues made a pull request to fix an issue where some prcision was lost when the project units are in milimeters. 

Is it possible for you to take a look to his pull request (PR #103)?

Some customers are waiting or this fix, so it is important to us!

Thank you very much!

**Comment by martin1cerny** [comment]
Merged now.

**Comment by CBenghi** [comment]
Hi @AlainBolduc, @martin1cerny ,

I think this merge might break the format, I've not got  a lot of time to check right now, but there are a couple of unit tests that fail after the merge.
We probably need to have a more comprehensive look at the changes, as we must retain compatibility of the xbim formats that other people have already produced, 

I think we need to store in the model information that differentiates the float vs. double size.

The tests that fail are:
Test Name:	GeometryBinaryRead
Test Name:	ReadAndWriteWexBimFile

Claudio

**Comment by hansmei** [comment]
Bump, any fix to this yet?

**Comment by martin1cerny** [comment]
Did you try the latest `develop` branch? It should be fixed in there.

**Comment by andyward** [comment]
Fixed in 5.0
