### ISSUE TITLE
UWP compatibility

### ISSUE THREAD

**Issue by jat110** [xBimTeam/XbimEssentials#114]
To what extent is Xbim compatible with UWP applications (e.g. for Hololens)? Are there plans for expansion in the future?

**Comment by CBenghi** [comment]
Hello,
personally, I think that a .Net standard/.Net Core port would be more feasible.
For other devices I'd think of a service based approach, the information could be exchanged with xbim if encapsulated in appropriate service calls.

Any specific project in mind?

Claudio

**Comment by jat110** [comment]
Many thanks for the suggestion. I've had a look and it seems like a lot of work to get it going, so I'll try a workaround using a different application. Thanks!

**Comment by pabloinigoblasco** [comment]
Anything new on this line?

**Comment by martin1cerny** [comment]
This project is all .NET Standard except for Esent implementation of IModel. As long as you use in-memory IModel implementation, so you should be able to use it in UWP with no problem.

**Comment by pabloinigoblasco** [comment]
Correct XbimEssentials works on UWP.
Now I realize I am having that issue with xbim.geometry.

Maybe this is not the correct place to create an issue about xbim.geometry, but this is the error I am getting:

**ARM64**
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Xbim.Geometry.Engine.Interop 5.1.403 is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763) / win10-arm64-aot. Package Xbim.Geometry.Engine.Interop 5.1.403 supports: net472 (.NETFramework,Version=v4.7.2)	TestUWP	C:\Users\pblasco\source\repos\TestUWP\TestUWP\TestUWP.csproj	1	

**x64**
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Xbim.Geometry.Engine.Interop 5.1.403 is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763) / win10-x64-aot. Package Xbim.Geometry.Engine.Interop 5.1.403 supports: net472 (.NETFramework,Version=v4.7.2)	TestUWP	C:\Users\pblasco\source\repos\TestUWP\TestUWP\TestUWP.csproj	1

**Comment by martin1cerny** [comment]
We have a branch of `Xbim.Geometry` which is ported to .NET Core 3. You may want to check it. We plan to work on this and would be happy for any feedback.
