### ISSUE TITLE
PR might break the binary format

### ISSUE THREAD

**Issue by CBenghi** [xBimTeam/XbimEssentials#115]
Just a quick note, 
https://github.com/xBimTeam/XbimEssentials/pull/103 might break the binary format, we have to check that old xbim files still work.
Claudio

**Comment by CBenghi** [comment]
I've looked at the xbim format in WindowsUI and it seems to work, can we confirm that the web format.

**Comment by martin1cerny** [comment]
I've just fixed it. All tests regarding binary geometry and wexBIM pass now.
