### ISSUE TITLE
Is IIfcRelAssociatesMaterial.RelatingMaterial_set(...) not fully implemented in Ifc2x3.Interfaces?

### ISSUE THREAD

**Issue by Artoymyp** [xBimTeam/XbimEssentials#117]
I see that now only values of type IfcMaterialList are allowed as value for set accessor of property
public partial class @Xbim.Ifc2x3.ProductExtension.IfcRelAssociatesMaterial : IIfcRelAssociatesMaterial
{
	IIfcMaterialSelect IIfcRelAssociatesMaterial.RelatingMaterial {get;set;}
}

All other implementations of IIfcMaterialSelect are ignored.

Is it by design or just waiting for an implementation?

**Comment by martin1cerny** [comment]
Can you explain what do you mean by *ignored* please? As far as I know *all* implementations of `IIfcMaterialSelect` interface are implemented: 

```
IfcMaterialDefinition 
IfcMaterial
IfcMaterialLayer
IfcMaterialLayerSet
IfcMaterialProfile
IfcMaterialProfileSet
IfcMaterialConstituent
IfcMaterialConstituentSet
IfcMaterialUsageDefinition 
IfcMaterialLayerSetUsage
IfcMaterialProfileSetUsage
IfcMaterialList 
```

May it just be the case that your data actually doesn't contain any of these?

**Comment by Artoymyp** [comment]
Sorry for not being specific enough.
Please look at the file https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.Ifc2x3/Interfaces/IFC4/IfcRelAssociatesMaterial.cs
The set-accessor of property RelatingMaterial is processing only IfcMaterialList-type values and null-values. Other incoming values are not used at all. Because of it I cannot set values of other types (e.g. IfcMaterialLayerSet) through the IIfcRelAssociateMaterial interface.

**Comment by martin1cerny** [comment]
Thanks for clarification. Yes, this is definitely a bug. Using IFC4 interfaces to actually change IFC2x3 data was developed as an addition to reading and this particular case went through unnoticed. Thanks for spotting this out. We are going to regenerate the library shortly to upgrade our implementation of IFC4 from Add1 to Add2 and I'll make sure we will target this issue as well.

**Comment by Artoymyp** [comment]
Thank you.

**Comment by rwggit** [comment]
https://github.com/xBimTeam/XbimEssentials/blob/1f4e47ad68ab8d12c8a3eae66ec0b4393ae44746/Xbim.Ifc2x3/Interfaces/IFC4/IfcRelAssociatesMaterial.cs#L59

I think this line is wrong, but changing MaterialResource.IfcMaterialList to MaterialResource.IfcMaterialSelect does not result in a correct IFC-File. The Material in IfcRelAssociatesMaterial in my IFC-output-file ist still unset.

**Comment by Artoymyp** [comment]
rwggit, can it be that you are actually assigning some Ifc4 implementation of IIfcMaterialSelect? And so your operator "as Ifc2x3.MaterialResource.IfcMaterialSelect" is returning null? Can you check it out?

**Comment by rwggit** [comment]
I tried to assign an Ifc2X3 IfcMaterial. This failed because this is not an MaterialResource.IfcMaterialList. After changing MaterialResource.IfcMaterialList to MaterialResource.IfcMaterialSelect the assignment worked and ifcmateriallist (and also IIfcRelAssociatesMaterial.RelatingMaterial) was not null. But still the Material in the IFC-output-file was unset.

**Comment by martin1cerny** [comment]
Silly question: Did you commit the transaction?

**Comment by rwggit** [comment]
Yes I did. If I didn't no material would be in my IFC-output-file.
But don't worry any longer. Now I create the material in my element-constructor which is pure Ifx2X3 or Ifc4. So this problem is resolved for me.
Thanks.

**Comment by martin1cerny** [comment]
Great, This is cleaner approach anyway because there are minor differences in schemas and using IFC4 interfaces to change IFC2x3 models might result in unexpected results in several places unless you understand them in depth.
