### ISSUE TITLE
Late binding capabilities?

### ISSUE THREAD

**Issue by I-Sokolov** [xBimTeam/XbimEssentials#119]
Is there any support for late binding features?
Sometimes classes and attributes must be configurable and can not be hardcoded.

(Well... it should be possible with reflection. Maybe easy with reflection and I just have to refresh my mind after years in native C++ World:)

_String typeName = “IfcWall”
IfcObject ifcObj = **….how a code to create object given typeName looks like**?

String attrName = “PredefindType”
If (**… how to check ifcObj has the attribute?**)
            {
            String value = “JOIST”;
            **… how to check the value is valid for enumeration**
            **… how to assign the value to attribute with given name of an object**
            }_

**Comment by martin1cerny** [comment]
Yes, you will need to use reflection. That will allow you to do all you need. Because we use reflection for some tasks as well you can try to do `IPersistEntity.ExpressType`. That will give you reflected metadata about the specific object.

**Comment by martin1cerny** [comment]
I take you were successful in using reflection for your task. If not, reopen the issue please.
