### ISSUE TITLE
How can I get the EntityLabel that i have use to get an IfcProduct?

### ISSUE THREAD

**Issue by soniagagliardi** [xBimTeam/XbimEssentials#12]
Hello,
I have to get the EntityLabel of an product in particular to be used in the following code:

var product  = model.Instances[entityLabel] as IfcProduct;
var propertyRelations = product.IsDefinedBy.OfType<IfcRelDefinesByProperties>();
........
........

This I need to get the geometry of the product.

**Comment by CBenghi** [comment]
Hi Sonia,
I'm not quite getting the point of the question you're asking.
What have you got to identify the product?
I've noticed that you have been asking a few questions lately, if you feel it might be easier to have a chat and address a few of your issues in one go you can ping me on Skype, my name is Claudio Benghi and the username is Bonghi.
Best,
Claudio

**Comment by soniagagliardi** [comment]
Hi Claudio,

thanks for your availability , I already solved.
