### ISSUE TITLE
How to get IfcWindow associated with a space?

### ISSUE THREAD

**Issue by jdimyadi** [xBimTeam/XbimEssentials#121]
Appreciate if anyone can help me on how to get a list of IfcWindow or IfcDoor that is associated with a space object please. I guess one would first find the space boundaries then find related walls, which then reveal any openings and windows or doors. But, I keep getting null using XBIM

**Comment by I-Sokolov** [comment]
I do not think the question is to xbim.
It is not common that IFC model defines relationships between windows and doors.
It depends on MVD.
Coordination View, Reference View and Design Transfer View do not specify windows to space association.
As I know only Facility Management (COBie) require the relations.
In FM you can search IfcRelContainedInSpatialStructure (door/window belongs to one space) and IfcRelSpaceBoundary (may boud 0..2 spaces)

**Comment by martin1cerny** [comment]
@I-Sokolov is right, this information is often not contained in the data. Even in COBie doors are more complicated than this. IFC contains a constrain than any object should be referenced at most once by  IfcRelContainedInSpatialStructure. But door is usually related to two spaces unless it is an external door. But there are other relations you might want to check. I did some work on this and this picture shows most of the relations usable to infer the containment/relation . You just need to be careful as some of these can give you ambiguous results.

![simple_floor_plan_relations_and_geometry](https://user-images.githubusercontent.com/773078/32824718-530afb52-c9e2-11e7-87cd-dc03289988f4.png)

**Comment by I-Sokolov** [comment]
Space boundaries are not in the scope of coordination views also.
For different COBie versions there are different agreements is the door belongs to space where open from or where open to (both are not working for double sweeps-:)

**Comment by martin1cerny** [comment]
True, but what we see in models is that many vendors are more relaxed about minimal requirements of Coordination View and put more information in. I worked with model from Revit 2011 recently and even that contained `IFCRELCONTAINEDINSPATIALSTRUCTURE` and `IFCRELSPACEBOUNDARY` for doors in the model. Problem was that it said the door was a boundary of up to five spaces. Here is the snippet for fun:

```
#247772=IFCDOOR('25mEn80iT1BPct7W6c3es1',#34,'D1-Single:1000mm Door Type:1000mm Door Type:375860',$,'1000mm Door Type',#247771,#247766,'375860',2100.,1000.);
#247817=IFCRELFILLSELEMENT('0a_GcMFK97MxSnmNSX5kY8',#34,$,$,#247616,#247772);
#440682=IFCRELCONTAINEDINSPATIALSTRUCTURE('0fzIUYJDz5KPWdUwCXqrCt',#34,$,$,(#160377,#160430,#160491,#160544,#160594,#160643,#160689,#160736,#160771,#160911,#161036,#161089,#161124,#161417,#161510,#161549,#161596,#161642,#161677,#161723,#161772,#161825,#161872,#161920,#161969,#162018,#162066,#162115,#162172,#162220,#162274,#162388,#162419,#162472,#162569,#162600,#162638,#162676,#162736,#162796,#162834,#162887,#162974,#163027,#163080,#163145,#163198,#163274,#163365,#163441,#163517,#163593,#163669,#163744,#163842,#163925,#164009,#164055,#164102,#164148,#164197,#164246,#164292,#164340,#164388,#164436,#164484,#164532,#164578,#164653,#164699,#164753,#164829,#164864,#164912,#164958,#165006,#165052,#165105,#165140,#165240,#165288,#165334,#165388,#165434,#165531,#165579,#165626,#165672,#165718,#165764,#165810,#165856,#165891,#165926,#165972,#166020,#166067,#166113,#166161,#166208,#166254,#166302,#166349,#166395,#166443,#166490,#166536,#166584,#166631,#166677,#166725,#166772,#166818,#166864,#166912,...
#445172=IFCRELSPACEBOUNDARY('0aEM3RqRj7AARE31gBQ8dk',#34,'1stLevel',$,#11021,#247772,#11075,.PHYSICAL.,.EXTERNAL.);
#445223=IFCRELSPACEBOUNDARY('2dtsVl$rnBLhYQOWt8Ok99',#34,'1stLevel',$,#11909,#247772,#11979,.PHYSICAL.,.EXTERNAL.);
#453900=IFCRELSPACEBOUNDARY('3HVMlBTnPAfhSH9p6Q5mb9',#34,'1stLevel',$,#147252,#247772,#147349,.PHYSICAL.,.EXTERNAL.);
#454183=IFCRELSPACEBOUNDARY('0JVghZLJ94CflzWfyv6BF5',#34,'1stLevel',$,#151257,#247772,#151434,.PHYSICAL.,.EXTERNAL.);
#454279=IFCRELSPACEBOUNDARY('0TWyOszt14jPBoM3rPEDaA',#34,'1stLevel',$,#152878,#247772,#152976,.PHYSICAL.,.EXTERNAL.);
```

**Comment by jdimyadi** [comment]
Thanks, gents.
