### ISSUE TITLE
How to add a light source to an IfcLampType

### ISSUE THREAD

**Issue by KonstantinHamm** [xBimTeam/XbimEssentials#123]
Hi all, 
first of all I want to thank you for that awesome piece of software that you are creating. Keep up the good work!

My question is: How do I add a light source like IfcLightSourceGoniometric to an IfcLampType? 
I already have the IfcLightDistributionData at hand. Here is the piece that I've tried to implement:

```
private IfcLightSourceGoniometric CreateLightSourceGoniometric(int luminousFlux)
{
	return _ifcExportModel.IfcStore.Instances.New<IfcLightSourceGoniometric>(l =>
	{
		l.LuminousFlux = luminousFlux;
                // Correct photometric data is present
		l.LightDistributionDataSource = LoadDataSource(_ifcExportModel.IfcStore);
		l.Name = "Photometry xyz";
		l.ColourAppearance = _ifcExportModel.IfcStore.Instances.New<IfcColourRgb>(c =>
		{
			c.Red = 244;
			c.Green = 241;
			c.Blue = 66;
		});
	});
}

private IfcFlowTerminal CreateSingleIfcLamp(ILightSource lightSource)
{
    var lampName = GetLampNameSave(lightSource);
    var lampDescription = GetLampTypeDescriptionSave(lightSource);
    var goniometricShapeDefinition = CreateLightSourceGoniometric
        (lightSource.LightSourceInformation.Value.LampLightFlux.Value);

    var shapeRepresentation = _ifcExportModel.IfcStore.Instances.New<IfcShapeRepresentation>(s =>
    {
        s.ContextOfItems = _ifcExportModel.IfcStore.Instances.OfType<IfcGeometricRepresentationContext>
           ().FirstOrDefault();
        s.Items.Add(goniometricShapeDefinition);
    });

    var productDefinitionShape = _ifcExportModel.IfcStore.Instances.New<IfcProductDefinitionShape>
        (pds =>
    {
        pds.Representations.Add(shapeRepresentation);
    });

    var lampFlowTerminal = _ifcExportModel.IfcStore.Instances.New<IfcFlowTerminal>(lft =>
    {
        Guid lftGuid;
        lft.GlobalId = IfcGloballyUniqueId.FromGuid(Guid.TryParse(lightSource.GlobalId, out lftGuid) ? lftGuid : Guid.NewGuid());
        lft.Representation = productDefinitionShape;
    });

    lampFlowTerminal.IsTypedBy = _ifcExportModel.IfcStore.Instances.New<IfcLampType>(lamp =>
    {
        lamp.Name = lampName;
        lamp.Description = lampDescription;
    });

    return lampFlowTerminal;
	
   // After I've created this IfcFlowTerminal the lamp is connected via ports to an IfcLightFixture. 
}
```
Am I creating and adding the LightSourceGoniometric the right way? Unfortunately I could not find an Ifc-Viewer / Editor that is able to visualize the light distribution curve.

**Comment by martin1cerny** [comment]
Hi @KonstantinHamm ,

there is a facility in xBIM to check if the data you have created is valid IFC according to schema constrains and rules. However, specific implementation should be directed by information requirements of the receiving application.

Martin

**Comment by KonstantinHamm** [comment]
Hi @martin1cerny, 
can you provide a code snippet how to do a validation on a IfcFlowTerminal/LightFixtureType?

Thank you in advance.

Konstantin

**Comment by CBenghi** [comment]
@KonstantinHamm,
if you wish to validate without code you can use the feature of XbimXplorer.
It's a bit hidden.

You can download xbimxplorer from [here](http://docs.xbim.net/downloads/xbimxplorer.html).
To access the validation features you have to enable the developer mode in the settings (In the menu select view->settings).

Then select in the menu View->Developer windows->IFC Validation

![image](https://user-images.githubusercontent.com/5476273/33718391-1f60efda-db55-11e7-8dc2-517670cc89d5.png)

Press the "Validate model" button and the validation report is presented in the text as shown above.
If you look at Xplorer code you'll see how to do validation programmatically, if interested.

**Comment by martin1cerny** [comment]
Or in code, in case you needed automated quality check:
```cs
using (var model = IfcStore.Open(file, null, 0))
{
    var v = new IfcValidator
    {
        ValidateLevel = ValidationFlags.All,
        CreateEntityHierarchy = true
    };
    var errors = v.Validate(model);
    foreach (var validationResult in new IfcValidationReporter(errors))
    {
        Console.WriteLine(validationResult);
    }
}

```

**Comment by KonstantinHamm** [comment]
Thank you for your help. I will use the code and where able to find a problem where
