### ISSUE TITLE
IfcIndexedPolyCurve

### ISSUE THREAD

**Issue by iwacky** [xBimTeam/XbimEssentials#128]
--- This is not an issue but an help request ---

Hi team,
I would like to create some geometries with the IFC4 class [`IfcIndexedPolyCurve`](http://www.buildingsmart-tech.org/ifc/IFC4/Add1/html/schema/ifcgeometryresource/lexical/ifcindexedpolycurve.htm):

 - I need to create an `IfcCartesianPointList[2-3]D`
 - and an `IfcSegmentIndexSelect` as `IfcLineIndex` or `IfcArcIndex`.

My problem occurs when I try to add some points to `IfcCartesianPointList3D`.
xBIM waiting for an `ItemSet<IfcLengthMeasure>` but I cannot create it.

I do not understand arguments waited by constructor:
`new ItemSet<IfcLengthMeasure>(...)`

Some help will be welcome.
Regards

**Comment by martin1cerny** [comment]
Please, see [my instructions here](https://github.com/xBimTeam/XbimGeometry/issues/87).

**Comment by iwacky** [comment]
Thank you very much Martin!

**Comment by martin1cerny** [comment]
You are welcome.
