### ISSUE TITLE
IFC4 support

### ISSUE THREAD

**Issue by AlainBolduc** [xBimTeam/XbimEssentials#13]
Hi, I see there is a dev branch for IFC4 support.

Do you have an estimate on when it will be ready and promoted to master branch? 

Thanks!

**Comment by CBenghi** [comment]
Hi,
It's difficult to commit to a time frame at the moment, but I expect that
it should happen in a couple of months.

Feel free to use the develop version and provide feedback on its structure.

On 10 Dec 2015, at 14:05, Alain Bolduc <notifications@github.com> wrote:

Hi, I see there is a dev branch for IFC4 support.

Do you have an estimate on when it will be ready and promoted to master
branch?

Thanks!

—
Reply to this email directly or view it on GitHub
<https://github.com/xBimTeam/XbimEssentials/issues/13>.

**Comment by SteveLockley** [comment]
The IFC4 in the latest develop branch is virtually complete, as is the geometry support. We will be upgrading and publishing to master branch in the next 4 weeks. It passes all unit and regression tests.

**Comment by AlainBolduc** [comment]
Is there an update on the time frame for this? We are very excited to see IFC4 support moved to Master branch!

**Comment by martin1cerny** [comment]
Hi @AlainBolduc , our resources are currently located on development of new functionality in `develop` branch. However, moving the latest development to `master` is in the plan.
