### ISSUE TITLE
Change model colour

### ISSUE THREAD

**Issue by JonathanSiddle** [xBimTeam/XbimEssentials#130]
Hey Guys, 

I am investigating using Xbim to change the colour of all the elements within a IFC file. I am using the buildingSMART duplex model for testing (https://www.nibs.org/?page=bsa_commonbimfiles). I have code that can be used to re-colour most of the model, however, furniture elements remain their original colour. Any advice you could provide on this would be appreciated.

Cheers 

**Code:**

```csharp
var baseSurfaceStyles = model.Instances.OfType<IIfcColourRgb>();
foreach (var style in baseSurfaceStyles)
{
   using (var txn = model.BeginTransaction("Change shading colour"))
   {
      style.Red = (0.0 / 255.0);
      style.Green = (0.0 / 255.0);
      style.Blue = (255.0 / 255.0);
      txn.Commit();
   }
}
```

**Original model:**
![originalmodel](https://user-images.githubusercontent.com/1248358/35621402-225a15b6-067c-11e8-9fb1-f3150e8e77f6.png)

**Model with new colour:**
![colourmodel](https://user-images.githubusercontent.com/1248358/35621410-265908de-067c-11e8-946c-94383c5a382a.png)

**Comment by martin1cerny** [comment]
Check if furniture actually has any style applied. What you see might be the default colour when none is defined. Styling is not mandatory in IFC.

**Comment by CBenghi** [comment]
@JonathanSiddle,
On a side note, if you are only interested in visualisation it's much easier to produce your custom LayerStyler and set the colours there.

**Comment by JonathanSiddle** [comment]
Hey, thanks for the quick reply! Yes, I think it is getting the default colour from: 

https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Ifc/XbimColourMap.cs

Are there any examples of how to add styling to an object? I had a look through the example of creating a wall from scratch but have not yet figured out how to manually add a new style.

**Comment by martin1cerny** [comment]
You will need to have a look at [IFC documentation](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcstyleditem.htm) to see how styling is assigned to geometry representation.

**Comment by CBenghi** [comment]
@JonathanSiddle,
in your model issue the command 

```
se tt IFCSTYLEDITEM[0] Styles Styles Styles SurfaceColour
```
to have a look at the hierarchy of elements that styles one entity.

In one of my versions of duplex the response looks like this:
![image](https://user-images.githubusercontent.com/5476273/35670940-d42280d4-0731-11e8-8ca4-2909fe8de98a.png)

where item 59 is the representation that we are styling.

**Comment by JonathanSiddle** [comment]
Thanks for the help @CBenghi and @martin1cerny I think I have figured this out. For reference I have included a snippet from a modified version of the example for creating a wall [(Proper Wall in 3D)](http://docs.xbim.net/examples/proper-wall-in-3d.html) that changes the colour of the wall to orange: 

```cs
//model as a swept area solid
var body = model.Instances.New<IfcExtrudedAreaSolid>();
body.Depth = height;
body.SweptArea = rectProf;
//body.StyledByItem.
body.ExtrudedDirection = model.Instances.New<IfcDirection>();
body.ExtrudedDirection.SetXYZ(0, 0, 1);

//parameters to insert the geometry in the model
var origin = model.Instances.New<IfcCartesianPoint>();
origin.SetXYZ(0, 0, 0);
body.Position = model.Instances.New<IfcAxis2Placement3D>();
body.Position.Location = origin;

//*****************************************************************
//**************Start creating style with colour
//*****************************************************************

var orange = model.Instances.New<IfcColourRgb>();
orange.Red = (255.0 / 255.0);
orange.Green = (69.0 / 255.0);
orange.Blue = (0.0 / 255.0);

var newStyleRendering = model.Instances.New<IfcSurfaceStyleRendering>();
newStyleRendering.SurfaceColour = orange;

var newSurfaceStyle = model.Instances.New<IfcSurfaceStyle>();
newSurfaceStyle.Styles.Add(newStyleRendering);

var newStyleAssignment = model.Instances.New<IfcPresentationStyleAssignment>();
newStyleAssignment.Styles.Add(newSurfaceStyle);

var newStyledItem = model.Instances.New<IfcStyledItem>();
newStyledItem.Item = body;
newStyledItem.Styles.Add(newStyleAssignment);

//*****************************************************************
//**************End creating style with colour
//*****************************************************************

//Create a Definition shape to hold the geometry
var shape = model.Instances.New<IfcShapeRepresentation>();
var modelContext = model.Instances.OfType<IfcGeometricRepresentationContext>().FirstOrDefault();
shape.ContextOfItems = modelContext;
shape.RepresentationType = "SweptSolid";
shape.RepresentationIdentifier = "Body";
shape.Items.Add(body);
```

![wallwithcolour](https://user-images.githubusercontent.com/1248358/35677490-adad5454-0747-11e8-8f47-c0151a963331.png)

**Comment by martin1cerny** [comment]
You are welcome. shall we close the issue now?

**Comment by TuanAnhDEO** [comment]
Hello @martin1cerny 
I have the code that is used to recolor the wall in the model, however, I have an error as shown in the image. Can you give me an advice, thanks in advance.
Any advice you can provide on this would be greatly appreciated.
![image](https://user-images.githubusercontent.com/90577351/133458906-1f36d300-8cf8-4fcc-bc34-1d34b049be79.png)

**Comment by martin1cerny** [comment]
You are mixing classes and interfaces in your code. `Instances.New<>()` can only be used on non-abstract classes.

**Comment by TuanAnhDEO** [comment]
Hello @martin1cerny
Thanks for your comment. I tried following the instructions in the exemple UPDATE but i didn't succeed https://docs.xbim.net/examples/basic-model-operations.html 
I'm sorry about this suggestion, I hope you can show me an example of updating an element's property. 
Thank you for your help.

**Comment by martin1cerny** [comment]
Also, colour of the object is not a property. You need to change styling of representation items.

**Comment by martin1cerny** [comment]
See this question and solution: https://github.com/xBimTeam/XbimEssentials/issues/183
