### ISSUE TITLE
Unity 3D : IfcStore.Open

### ISSUE THREAD

**Issue by Doraxbe** [xBimTeam/XbimEssentials#131]
Hi everyone,

I've tried these pas few days to use xBIM in Unity 3D. I've seen a few other people here who managed to do it... but I can't and I feel stupid. 
I've tried to explain everything I've tested to make it work and hope that someone can help me. I'd be really greatful.

I'll add that this is my first attempt at using Unity with GitHub. For this project, I did the following steps : 

1. Create the project in Unity
2. Created the asset folder and its Editor subfolder
3. Changed the Edit/Project Settings/Player to use Experimental (.NET 4.6 Equivalent)
4. Created a C# class and then opened it in Visual Studio
5. Quit Visual Studio
6. Created the nuget.config file and put it in the Unity project folder, containing these code lines : 
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="repositoryPath" value=".\Assets\packages" />
    </config>
</configuration>
```
7. Installed the xBIM Essentials with its 3 dependencies : log4net, ManagedEsent, SharpZipLib with NuGet
8. Went back to Unity
9. Removed some of the .dll where there were more than 1 reference (by Unity) (Example : only kept the log4net.dll from the packages\log4net.2.0.8\lib\net40-full folder) in order not to get the following error message in Unity : 

> error CS1703: An assembly `log4net' with the same identity has already been imported. Consider removing one of the references

10. Was happy when no more error were found in the project and tried a very simple code just to load an IFC file... there it is : 

```
using UnityEngine;
using UnityEditor;
using System.IO;
using System;
using Xbim.Ifc;

public class IfcImporter
{
    [MenuItem("Tools/IfcImporter/Load IFC")]
    static void LoadIfcFromMenu()
    {
        var IfcFilePath = EditorUtility.OpenFilePanel("test", "", "ifc");
        Debug.Log(IfcFilePath);

        if (File.Exists(IfcFilePath))
        {
            Debug.Log("The file exists !");
        }
        if (!string.IsNullOrEmpty(IfcFilePath))
        {
            LoadIfcStore(IfcFilePath);
        }
    }

    static void LoadIfcStore(string ifcFilePath)
    {
        using (var model = IfcStore.Open(ifcFilePath, null, -1))
        {
            model.Close();
        }
    }
}
```

11. Clicked on the brand new Menu on Unity and got the following error :

> TypeLoadException: Failure has occurred while loading a type.
IfcImporter.LoadIfcStore(System.String ifcFilePath) (at Assets/IfcImporter/Editor/IfcImporter.cs:27)
IfcImporter.LoadIfcFromMenu () (at Assets/IfcImporter/Editor/IfcImporter.cs:21)

I've tested some other codes found there and there... but I always get this same error. So I'm sure I did something wrong somewhere, or maybe I forgot to do something. 

I am using : 

- Microsoft Visual Studio Community 2017
- Unity Pro 2017.3.0f3

Note : when I tried importing the the xBIM Geometry in Visual Studio with NuGet, I got the "Project unavailable" error. If someone could also tell me how to get rid of this error, I'd also be very grateful

**Comment by liszto** [comment]
I will take a look at your problem tomorrow morning. 
I use xBim + Unity and ifcStore.Open works fine in my version. I use the same unity version and VS than you !

**Comment by liszto** [comment]
@Doraxbe I just tried your code in my unity project and everything works fine.
I can try with your nuget logic (maybe it's the issue) cause currently I rebuild myself all dll based on xBim.Essentials and xBim.Geometry project on Github and moved the dll into my Unity plugin folder.

**Comment by Doraxbe** [comment]
Hi Lizto,

Nope, I put my problem on hold, hoping someone would help me and now you did.
I would have prefered a solution with nuget but I'm grateful for your fix

If it's still OK for you, I'd like you to test with nuget, hoping you could help me find where the problem is.
Best Regards an thanks a lot

**Comment by liszto** [comment]
As soon as I have enough time I'll take a look to the nuget + unity solution

**Comment by liszto** [comment]
@Doraxbe I test quickly to set a nuget package configuration into my project to what could happen in yours.
My setup is this one and everything is fine : 
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="log4net" version="2.0.5" targetFramework="net46" />
  <package id="ManagedEsent" version="1.9.4" targetFramework="net46" />
  <package id="SharpZipLib" version="0.86.0" targetFramework="net46" />
  <package id="Xbim.Essentials" version="4.0.29" targetFramework="net46" />
</packages>`
 
All this stuff is in my packages.config.
I tried mutiple thing and it seems your issue is linked to your log4net version ! I supposed you set its value to 2.0.8 instead you must use the 2.0.5 with xBim.Essentials current version on nuget server.

If you set its value to 2.0.8 the result is an error during the `var model = IfcStore.Open(fileName, null, -1)` with this result : 
`TypeLoadException: Failure has occurred while loading a type.`

But if you set the nuget package value for log4net to 2.0.5 everything is fine !

Have fun in your development now ;)

**Comment by Doraxbe** [comment]
@liszto Again, thanks a lot. I've followed your instructions and everything works fine. 

> Have fun in your development now ;)

I will !
