### ISSUE TITLE
[QUESTION] Is it possible to retrieve an object from ifc model based on a productid from wexBim file ?

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#134]
I ask this question to know if there is a way to make a fast corresponding bridge between both file format.
If it's not possible I will have to probably generate my own ifc parsing to generate all the geometry which could be long 🗡 👨 .

**Comment by martin1cerny** [comment]
Yes, it is possible. Get ID from wexBIM and use it as an `EntityLabel` to get the `IfcProduct` from IFC model.

**Comment by liszto** [comment]
Indeed ! Totally missed this one ! Thanks !
