### ISSUE TITLE
Possible bug on XbimEssentials/Xbim.Ifc4/GeometryResource/IfcSurface

### ISSUE THREAD

**Issue by m-andres** [xBimTeam/XbimEssentials#135]
Hello,

I tried to get different instances of IfcSurface from different example IFC models, and the code seemed to crash when attempting to access any entity being a subtype of IfcSurface (i.e. IfcBoundedSurface, IfcElementarySurface, IfcSweptSurface, and their corresponding subtypes...)

For example, I tried the following in a model where such an instance (#5806 IFCCURVEBOUNDEDPLANE ...) exists:
var cbp = model.Instances.FirstOrDefault<IIfcCurveBoundedPlane>(r => r.EntityLabel == 5806);

Not sure, but I am afraid that there could be a bug on the programming of the Getter for Dim
According to IFC standard, Dim for IfcSurface should always be := 3, right?

I would greatly appreciate your help! Thanks

**Comment by martin1cerny** [comment]
Yes, you are right. This one was implemented manually using pattern from IFC2x3 but that was incomplete because there are new surface types in IFC4. Fixed in the latest `develop`.
