### ISSUE TITLE
Position data stored as floats, not doubles

### ISSUE THREAD

**Issue by hansmei** [xBimTeam/XbimEssentials#136]
I'm currently looking into creating a custom IFC reader/writer. However: I'm facing a problem with the geometry when I use your code. The problem originates from the Essentials pack, which is why I post the error here.

The IFC files I want to parse are using real world coordinates. Hence a point placed at position like this (or at even larger coordinates) is not uncommon:
#341= IFCCARTESIANPOINT((83344.4216871024,1192293.28162466,77.5516800709526));

When i read out the tesselated geometry, the positioning of all geometry is off. The reason is because you are using floats (not doubles) to parse the geometry data in the Vec3-struct (line 93  in MeshUtils.cs)  at Xbim.Tesselator.Vec3

This is what my result looks like with the current floats usage. The image are showing what should be perfect circular pillars.
![image](https://user-images.githubusercontent.com/3462703/37019346-4b143174-2118-11e8-97e5-e650076bf4d1.png)

The use of floats instead of doubles also applies to casts in the geometry module, but the source originates from the definition of Vec3 in the mentioned file. Can you please change this to use doubles instead? Without it, most of the IFC files I want to parse are useless.

The IFCs I want to parse originates from Autodesk Civil 3d.

**Comment by hansmei** [comment]
Sorry, I see this is already posted in #113. Would be great to get a fix though

**Comment by andyward** [comment]
Fixed in 5.0
