### ISSUE TITLE
Multiple values returned from Basequantites of Ifc Spaces

### ISSUE THREAD

**Issue by DavidBerger98** [xBimTeam/XbimEssentials#139]
I am using Xbim essentials to extract data from the Ifc files that I need (i.e. the basequantities from the ifcspaces like height, volume, perimeter etc.) It works perfectly. However, there is one particular file where Xbim returns multiple values for the same quantity of an IfcSpace. For example:

[IfcSpace] 1.9.2.B1.1
Height: 4400 MILLIMETRE
NetPerimeter: 20399.998835 MILLIMETRE
GrossPerimeter: 20399.998835 MILLIMETRE
NetFloorArea: 21.6 SQUAREMETRE
GrossFloorArea: 21.6 SQUAREMETRE
GrossVolume: 95.04 CUBICMETRE
NetVolume: 95.04 CUBICMETRE
Perimeter: 20.4 MILLIMETRE
GrossPerimeter: 20.4 MILLIMETRE
NetPerimeter: 20.4 MILLIMETRE
GrossCeilingArea: 21.6 SQUAREMETRE
GrossFloorArea: 21.6 SQUAREMETRE
NetFloorArea: 21.6 SQUAREMETRE
GrossVolume: 95039992.31 CUBICMETRE
NetVolume: 95039992.31 CUBICMETRE

As you can see for instance for ‘NetVolume’ there is a value of 95.04 CUBICMETRE and one of 95039992.31 CUBICMETRE present. The second one makes no sense, but the numbers are quite similar except the position of the decimal point.
I could not find any problem in my code, which is very similar to the code I found in a forum post from one of the devs from Xbim essentials. And I also could not find an occurence of the second values (the  95039992.31 CUBICMETRE) in the Ifc file itself.

I included my code down below. Unfortunately I cannot include the IFC file itself, since it contains sensible data. I know the issue must be in the IFC file, but I hope that this problem may already be known and that someone knows how I could avoid this.

Thank you in advance for any help.

Here is the code I used:

using System;
using System.Collections.Generic;
using System.Linq;
using Xbim.Ifc;
using Xbim.Ifc4.Interfaces;
using Xbim.Ifc2x3.Kernel;
using Xbim.Ifc2x3.QuantityResource;
using Xbim.Ifc2x3.MeasureResource;
using Xbim.Ifc2x3.Extensions;

namespace IfcFileManagerService
{
    public static class Test
    {
        public static void PrintIfc(string ifcFilePath, string logFilePath)
        {
            using (var model = IfcStore.Open(ifcFilePath))
            {
                var project = model.Instances.FirstOrDefault<IIfcProject>();
                PrintIfcRec(project, 0, logFilePath);
            }
        }

        private static void PrintIfcRec(IIfcObjectDefinition ifcObj, int n, string path)
        {
            Logger.Log($"{Indent(n)}[{ifcObj.GetType().Name}] {ifcObj.Name}", path);
            var spatialElement = ifcObj as IIfcSpatialStructureElement;
            if (spatialElement != null)
            {
                IfcObject obj = ifcObj as IfcObject;
                IEnumerable<IfcPhysicalSimpleQuantity> quantities = obj.PhysicalSimpleQuantities.Select(s => (IfcPhysicalSimpleQuantity)s);
                foreach (IfcPhysicalSimpleQuantity quantity in quantities)
                {
                    string unit = quantity.Model.Instances.OfType<IfcUnitAssignment>().Select(s => s.GetUnitFor(quantity)).Select(s => s.FullName).First();
                    double value = (Double)quantity.GetSpecificValue();
                    Logger.Log($"{Indent(n+1)}{quantity.Name}: {value} {unit}", path);
                }
            }
            foreach (var child in ifcObj.IsDecomposedBy.SelectMany(r => r.RelatedObjects))
                PrintIfcRec(child, n+1, path);
        }

        private static string Indent(int n)
        {
            return new String(' ', n);
        }
    }
}

**Comment by martin1cerny** [comment]
Hi David, as you said, the problem is most likely in the data. So, if you
can't share the file or a part of it I'm afraid we can't help you. You can
obviously investigate the file yourself. It isn't that hard.

Dne pá, 23. 3. 2018 15:52 uživatel David Berger <notifications@github.com>
napsal:

**Comment by DavidBerger98** [comment]
Hi Martin,
Yes, you were right. I could find multiple definitions of the Basequantites for the same ifcspace in the ifcfile.
Thanks a lot for your time!

**Comment by martin1cerny** [comment]
You are welcome @DavidBerger98.
