### ISSUE TITLE
[QUESTION] Outdated files in repository but not in solution ?

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#143]
Hello,
I'm currently investigate on performance issue in my Unity project based on your dll.
I just make so performance test on multiple files and my finale conclusion is there is some issue with the combo dll + Unity.
Because for example, when I try to call ifcStore.Open() on the lakeside.ifc file : 
xPlorer from your xbim.UI project : 4.040sec to open the file
my unity project : 15-17sec roughly

I have no other idea so, I think : Unity is maybe handling really bad dll when they involve huge data proccess.
So I try to import all the C# native stuff into Unity and let the C++ dll as dll cause the current performance impact is on the ifcstore.open.

And during my quite long cleaning proccess to make it work (or almost work...) I found a lot of file that seems to be still in your project but totally obsolete : 

ObjectDefinition
FileViewSomethingThatIDidntWriteIamSad

GeometryCacheFile
MeshGeometry

IfcInstanceKeyedCollection
IfcInstancesExtensions

XbimIndex
XbimIndexSomethingThatIDidntWriteIamSad
XbimHeaderTable
XbimSQLLite
XbimTransaction

IfcFilterDictionary

XbimP21Decoder

=== And in C# geometry part === 

CoPlanarComparer
Matrix3DExtensions

Is it safe to make a pull request with a clean on those obsolete and almost safe to remove files ?

**Comment by martin1cerny** [comment]
Yes, I think this is safe.
