### ISSUE TITLE
[QUESTION] Issue with native file, is it normal ?

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#144]
Hello again,
after doing all my cleaning proccess in ticket #143 I can finall start my project but....
During the execution of this one, I fall on this case : 
`Exception: Express Type is not defined for PersistEntity
Xbim.Common.Metadata.ExpressType..ctor (System.Type type) (at Assets/Plugins/Common/Xbim.Common/Metadata/ExpressType.cs:129)
Xbim.Common.Metadata.ExpressMetaData..ctor (System.Reflection.Module module) (at Assets/Plugins/Common/Xbim.Common/Metadata/ExpressMetaData.cs:108)
Rethrow as Exception: Error reading Entity Meta Data
Xbim.Common.Metadata.ExpressMetaData..ctor (System.Reflection.Module module) (at Assets/Plugins/Common/Xbim.Common/Metadata/ExpressMetaData.cs:142)
Xbim.Common.Metadata.ExpressMetaData.GetMetadata (System.Reflection.Module module) (at Assets/Plugins/Common/Xbim.Common/Metadata/ExpressMetaData.cs:79)
Xbim.IO.Memory.MemoryModel..ctor (Xbim.Common.IEntityFactory entityFactory, System.Int32 labelFrom) (at Assets/Plugins/Common/Xbim.IO/Memory/MemoryModel.cs:128)
Xbim.Ifc.IfcStore.Open (System.String path, Xbim.Ifc.XbimEditorCredentials editorDetails, System.Nullable`1[T] ifcDatabaseSizeThreshHold, Xbim.Common.ReportProgressDelegate progDelegate, Xbim.IO.Esent.XbimDBAccess accessMode) (at Assets/Plugins/Common/Xbim.Ifc/IfcStore.cs:333)`

Is it due to the fact that I try to execute the code without building the dll file associated ?
If you have any hint on this issue (which is maybe my last one, I could be really great)

**Comment by martin1cerny** [comment]
This has definitely nothing to do with geometry dlls. It is more likely that your runtime has different behaviour for reflection. When this code runs in .NET runtime it never calls `ExpressType` constructor for `PersistEntity` type because it doesn't exist in the schema implementation DLL at first place and is filtered out from the inheritance hierarchy later on. It might be an issue with reflection type identity in your Unity runtime (comparing `typeof(PersistEntity) == currentType`).

**Comment by liszto** [comment]
Sorry to bother you again after 21 days off.
Was on another project part.

I tried to figure out why this issue happen in my Unity project. I spotted sometimes really odd, when I do a ifcStore.open on the file named "Samplehouse4.ifc" unity version returned ifc2X3 instead of your test unit into xBimEssentials returns ifc4.
Maybe it could be related to this ?

Otherwise as far as I check (for now) the type that triggered this issue is this one : 
Type ==> (currentType parsed) Xbim.Common.PersistEntity // (Typeof) Xbim.Common.PersistEntity

**Comment by martin1cerny** [comment]
Whatever it is, this issue appears to be specific to your runtime environment. It doesn't happen with any version of .NET and I'm sorry but we don't have any resources to support other platforms. If you can provide a repeatable test code and data example for .NET I'm happy to investigate the issue.

**Comment by liszto** [comment]
indeed I can easily understand your constraints concerning "support other platforms".
I will try to investigate from my side to find exactly what happen in the unity runtime environment.
Yesterday I stopped during the parsing loop. I think the issue come from there in Unity and if I found a fix I will maybe create a unity branch of your main project.

Really the safest thing to do.

**Comment by liszto** [comment]
Ok I finally understand what happen and I will try to find can I solve this :/

In fact in your code when the process reaches this part : 
`var typesToProcess = module.GetTypes().Where( t => typeof(IPersist).IsAssignableFrom(t) && t != typeof(IPersist) && !t.IsEnum && !t.IsInterface && t.IsPublic && !typeof(IExpressHeaderType).IsAssignableFrom(t)).ToList();`

the only DLL triggered at this moment is xBim.Ifc4.dll (or at least the associated module) so the test succeed. I try to add manually the persistentity and it made your code crashed. I think it's impossible from your side to filter only what you want because the PersistEntity succeed to pass all the "Where" test.

At least now I have the same thing than in Unity. In unity in fact there is no dll notion per namespace, it seems to be the case in your project even if I didn't find where your assembly are defined.

They released something recently that allow my to simulate other assembly module than theirs which are : 
Assembly-CSharp-firstpass.dll
Assembly-CSharp-Editor-firstpass.dll
Assembly-CSharp-Plugins-firstpass.dll
Assembly-CSharp-Editor-Plugins-firstpass.dll

the link to their system is here (not for you caue I think you won't have a look at this, but for people that could fall in this case) : 
https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html

In this way I could maybe be allowed to create or at least simulate your .DLL logic and in this way avoid this big lumber room assembly :/

**Comment by martin1cerny** [comment]
Yes, you are right. `PersistEntity` lives in Xbim.Common which is different module. Schema implementations live in their own modules so PersistEntity should not ever get in `typesToProcess`. In fact, you may face bigger problems if modules are merged in this way in Unity because `ExpressMetadata` may contain mixture of IFC2x3 and IFC4 types. This will cause the parser to crash because IFC4 entities will not be possible to assign as IFC2x3 members.

**Comment by liszto** [comment]
So I finally succeeded to execute all the native C# source code within unity without any dll import.
By using the asmdef system it "fakes" assembly logic in unity scope and create on C# project par asmdef and generate in a temp folder the associated dll accordingly.

BUT

I gain nothing in term of generation / parsing time.

So I dig a lil' bit and the issue come from the parser.Parse(); line 581 in MemoryModel.
I compare the xBim UI call to this method and the unity one and the gap is really huge.
xBim viewer calls this part in 3.6sec whereas Unity calls in 16.5sec

I had to check that maybe tomorrow but I start to be really tired to investigate further and further on this issue :(

**Comment by martin1cerny** [comment]
Well, `parser.Parse()` is doing all the work to actually parse the data. You will need to dig a layer or two deeper to find what is the slow part. Also, remember to benchmark this in release mode. Parsing consists of large number of small actions and difference between non-optimised compiled code and optimised compiled code is typically significant.

**Comment by martin1cerny** [comment]
There is a setting in the C# project which says that when compiling in RELEASE configuration compiler should apply code optimization. These optimization certainly have a significant impact on the parser performance.

**Comment by liszto** [comment]
Ok thanks for this hint ! 
I will take a look at this first !

The odd thing is even in "Debug" mode in visual studio with xBim.UI solution it seems to be really fast. But there is maybe something different between your VS project in Debug and unity's one. It's a good start at least !

**Comment by liszto** [comment]
lil update : 
it can't be due to compiler parameter cause if I use the dll or the native code in Unity the duration is the same (still long).
The same dll will be faster during xBim viewer usage. So I think it's clearly something in the code logic that is managed differently in the mono environment.

[Investigation in progress but it could take some time]

**Comment by martin1cerny** [comment]
...still open after several months. Can I close this now?

**Comment by liszto** [comment]
Hello @martin1cerny 
sorry for the lack of update on this topic. 
The issue still exists but it's probably due to mono / unity stuff. 
I could re-open it or comment it later with my potential solution if I finally find one.

This "issue" is actually on low priority here due to the amount of others tasks to do.
