### ISSUE TITLE
XBimFace in C#: Location

### ISSUE THREAD

**Issue by TweeZz** [xBimTeam/XbimEssentials#145]
Hi,

I have an 'XBimFace' object retrieved from calling engine.CreateFace(..). When I put that object while debugging in a watch, I can see it has a Location property. However, I'm not able to figure out a way how to get to that Location property in my code. I can cast my instance to the IXbimFace interface. But that interface doesn't have a Location property.
How can I retrieve the Location from a XBimFace object?

**Comment by TweeZz** [comment]
I was able to retrieve it using reflection. Maybe there's a different way?
`var value = face.GetType().GetProperty("Location").GetValue(face);`

**Comment by martin1cerny** [comment]
It is just a [direct member](https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.Geometry.Engine/XbimFace.h#L99) of XbimFace. Anything related to geometry engine should be asked in [XbimGeometry project](https://github.com/xBimTeam/XbimGeometry).

**Comment by TweeZz** [comment]
Yes, it is a direct member. But it's a member I'm not able to access in C#.

**Comment by martin1cerny** [comment]
I see. That would require changes both in Essentials and in Geometry Engine. Is it a problem to use the reflection as you do now? If you cache the `PropertyInfo` it shouldn't be a significant hit.

**Comment by martin1cerny** [comment]
Most of the people using xBIM use higher level API after geometry is all triangulated and ready for presentation. That's most possibly why.

**Comment by CBenghi** [comment]
@martin1cerny, 
I don't see a problem exposing the interface. I think it was most likely oversight.
I could easily change both essentials and geometry for this.
Do you see any drawbacks?
Claudio

**Comment by martin1cerny** [comment]
No, I don't think it is a problem. I just don't have XbimGeometry set up on
my computer to do it.

Dne pá, 20. 4. 2018 17:58 uživatel Claudio Benghi <notifications@github.com>
napsal:

**Comment by CBenghi** [comment]
Hello, 
I've revised the interface and implemented the property in geometry.
This should close the issue.
Feel free to reopen if needed.
