### ISSUE TITLE
An unhandled exception of type when openning the LakesideRestaurant.wexbim file 

### ISSUE THREAD

**Issue by luoyuke** [xBimTeam/XbimEssentials#149]
this is a repost/update from the issue that I opened in the wrong sector https://github.com/xBimTeam/XbimWebUI/issues/179
so basically an error is thrown when Visual studio reading this wexbim file, which looks perfectly normal in the webViewer.

after trying to run the code in console app. the error still exists. I'm convinced that it must be a problem with the .wexbim file itself. I uploaded 2 files, one is the original sample LakesideRestaurant.wexbim from the xBimTeam/XbimWebUI that gives me the error, the other is created by the example script below which can be read successfully by visual studio and Unity using the same script.

var wexBimFilename = Path.ChangeExtension(fileName, "wexBIM");
using (var wexBiMfile = File.Create(wexBimFilename))
...

there's clearly something, using the wexbim viewer I can open both, but I can only read the xbim that I generated directly from IFC in apps. Is there anyway to look into it and solve this? 

#### Expected behavior:
read trianglulation streamfile (LakesideRestaurant.wexbim)
'var triangulation = br.ReadShapeTriangulation();'
#### Actual behavior or exception details:
An unhandled exception of type 'System.ArgumentOutOfRangeException' occurred in mscorlib.dll
Additional information: Non-negative number required.
![capture](https://user-images.githubusercontent.com/29041573/38830572-0fee3c64-41bd-11e8-88d2-ac8f4827341c.PNG)

#### Versions of xBIM Packages:
Xbim.Essentials 4.029 from Nuget
Wexbim sample LakesideRestaurant.wexbim
[lakeside.zip](https://github.com/xBimTeam/XbimEssentials/files/1916948/lakeside.zip)

#### Minimal code (or steps) to reproduce the issue:
see screenshot

#### Minimal file to reproduce the issue:
*(IFC files need to be zipped to be uploaded. Than just drag & drop here)*

**Comment by martin1cerny** [comment]
You may have noticed there is a `version` in the wexBIM file header. Lakeside.wexbim file from the WebUI project is version **1** whereas current version (tested in Essentials) is **2**. There are only minor differences in the semantics of the file but some parts use double precision floats in version 2.

**Comment by luoyuke** [comment]
thanks for the insight, knowing this is relief.
