### ISSUE TITLE
Deleting / Removing stuff from the xbim model

### ISSUE THREAD

**Issue by Jero9999** [xBimTeam/XbimEssentials#15]
Is there any plan to migrate the examples and documentation from version 2 to version 3?
My current issue is that I have to remove some elements out of an IFC model and I can't find a good way to do that. 

Is there a forum or something that xBim users use. Google has not been my friend so far.

**Comment by CBenghi** [comment]
The logic for cascading the deletion of elements is quite complicated to manage.
I think your best approach for reducing files is to build a new ones copying the elements of interest.
Does this seam to be an acceptable approach to your case? If so ping us again here. 
There's no strong place where the community meets other than here. We'll have to work on this.
Best,
Claudio

**Comment by Jero9999** [comment]
Thanks for the reply. I thought that might be the answer. I know about it being complicated to manage. That's pretty much why I was hoping you guys had already done it.
I agree with the copying relevant bits into a new model. I actually tried it using the XBimModel.InsertCopy() but I kept getting Assert errors. It looks like it is designed to do what I want though. Any suggestions?

    _Model.CreateFrom(ifcFilename, xbimDbFilename, null, true, true);
    var outputModel = new XbimModel();
    
    using (var transaction = outputModel.BeginTransaction("add to representation"))
    {
    	outputModel.InsertCopy(_Model.IfcProject, transaction);
    	outputModel.Validate(transaction.Modified(), Console.Out);
    	transaction.Commit();
    }

**Comment by CBenghi** [comment]
Apologies for the long wait, i'll be testing this in the next couple of days and come back to you.

**Comment by SteveLockley** [comment]
Work has commenced to migrate samples. See the develop branch for the latest state, now we support Ifc4 the remainder will be migrated over, any help greatly appreciated

**Comment by martin1cerny** [comment]
Shall we close this issue?

**Comment by Jero9999** [comment]
Yup. No longer an issue

**Comment by jojobs** [comment]
Hi Steve, Martin. Claudio,

I have similar problem, I want to filter walls and create the Spatial view.

I have used the following code, but it is not populating the tree (Only project number appears on the tree). Could you please help?

private void OpenIfcFile(object s, DoWorkEventArgs args)
        {
            var worker = s as BackgroundWorker;
            var ifcFilename = args.Argument as string;

            var model = new XbimModel();
            var modelCopy = new XbimModel();
            try
            {
                _temporaryXbimFileName = Path.GetTempFileName();
                SetOpenedModelFileName(ifcFilename);             

                if (worker != null)
                {
                    model.CreateFrom(ifcFilename, _temporaryXbimFileName, worker.ReportProgress, true);
                    string tempFileName = "";
                    modelCopy = XbimModel.CreateModel(tempFileName);

                    modelCopy.AutoAddOwnerHistory = false;
                    using (var txn = modelCopy.BeginTransaction())
                    {
                        var copied = new XbimInstanceHandleMap(model, modelCopy);
                        //modelCopy.InsertCopy(model.IfcProject, txn);
                        foreach (var item in model.Instances)
                        {
                            var ifctype = item.IfcType();
                            if (ifctype.IfcTypeEnum == IfcEntityNameEnum.IFCPROJECT || 
                                ifctype.IfcTypeEnum == IfcEntityNameEnum.IFCBUILDING ||
                                ifctype.IfcTypeEnum == IfcEntityNameEnum.IFCBUILDINGSTOREY ||
                                ifctype.IfcTypeEnum == IfcEntityNameEnum.IFCSITE ||
                                ifctype.IfcTypeEnum == IfcEntityNameEnum.IFCWALLSTANDARDCASE )
                            {
                                modelCopy.InsertCopy(item, copied, txn, false);
                            }                        
                        }
                       
                        txn.Commit();
                    }

                    var context = new Xbim3DModelContext(modelCopy);//upgrade to new geometry represenation, uses the default 3D model
                    context.CreateContext(geomStorageType: XbimGeometryType.PolyhedronBinary,  progDelegate: worker.ReportProgress,  adjustWCS: false);
            
                    if (worker.CancellationPending) //if a cancellation has been requested then don't open the resulting file
                    {
                        try
                        {
                            model.Close();
                            if (File.Exists(_temporaryXbimFileName))
                                File.Delete(_temporaryXbimFileName); //tidy up;
                            _temporaryXbimFileName = null;
                            SetOpenedModelFileName(null);
                        }
                        catch (Exception ex)
                        {
                            Log.Error(ex.Message, ex);
                        }
                        return;
                    }
                }
                args.Result = modelCopy;
                    
            }
            catch (Exception ex)
            {
                var sb = new StringBuilder();
                sb.AppendLine("Error reading " + ifcFilename);
                var indent = "\t";
                while (ex != null)
                {
                    sb.AppendLine(indent + ex.Message);
                    ex = ex.InnerException;
                    indent += "\t";
                }

                args.Result = new Exception(sb.ToString());
            }
        }

**Comment by andyward** [comment]
Answered on #57
