### ISSUE TITLE
Empty '\X2\\X0\' strings cannot be read from an ifc file.

### ISSUE THREAD

**Issue by Artoymyp** [xBimTeam/XbimEssentials#150]
#### Expected behavior:
Such a string should be read as empty string.

#### Actual behavior or exception details:
Such files are not viewed in XbimExplorer at all with a messages of type:
ERROR	Xbim.IO.Step21.XbimP21Parser Entity 70    IFCPROJECT, error at parameter 3-Name value = 'Test \X2\\X0\Test \X4\\X0\Test'

#### Versions of xBIM Packages:
4.0.0.0

#### Minimal code (or steps) to reproduce the issue:
```cs
        [TestMethod]
        [DeploymentItem("TestFiles\\EmptyMultibyteString.ifc")]
        public void ToleratesEmptyMultibyteStringsTest()
        {
            using (IfcStore store = IfcStore.Open("EmptyMultibyteString.ifc")) {
                IIfcProject project = store.Instances.OfType<IIfcProject>().SingleOrDefault();
                Assert.AreEqual("Test Test Test", (string)project.Name);
            }
        }
```

#### Minimal file to reproduce the issue:
[EmptyMultibyteString.zip](https://github.com/xBimTeam/XbimEssentials/files/1938916/EmptyMultibyteString.zip)

PS: As I see it the fix is pretty simple. Please refer to the commit https://github.com/xBimTeam/XbimEssentials/commit/fcd22dc8fcb720dcadc9d2ebbba014003aed98f5.
Sorry, I have failed to create a pull request.

**Comment by martin1cerny** [comment]
Thanks for spotting this out. As far as I can tell, this is invalid data. You should advice originator of the file to fix this. But you are right, there is no reason for xBIM to fail in this case. You **did** create a [pull request](https://github.com/xBimTeam/XbimEssentials/pull/120) and I will review it soon. Thank you very much. This kind of contribution is highly appreciated.

**Comment by martin1cerny** [comment]
Closing, because the pull request was accepted. Thanks for a valuable contribution!
