### ISSUE TITLE
Error during UnitTests on xBim.IO.Esent PersistedEnitytInstanceCache class in develop branch

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#154]
#### Expected behavior:
Not crashing on UnitTest

#### Actual behavior or exception details:
![image](https://user-images.githubusercontent.com/408031/39293051-2efeb674-4938-11e8-80b8-4837fd53064a.png)

This issue always happened in PersistedEnitytInstanceCache.cs at line 1448 when you're coming from xBimIntanceCollection.cs at line 56.

I'm currently using Visual Studio Community 2017 just to precise.

#### Versions of xBIM Packages:
just be on the current develop branch

#### Minimal code (or steps) to reproduce the issue:
Just execute one of the 5 following tests : 
- CopyAllEntitiesTest
or any tests in "ValidationTests.cs"

**Comment by martin1cerny** [comment]
I was at it literally 5 minutes ago. I just removed the assertion because it fires false assertion when model entity requests inverse relation and there are no entities for that in the model. I'm going to push it shortly.

**Comment by liszto** [comment]
Ok I'll let you close this when you will push it ;) 

thanks again for the speed !

**Comment by martin1cerny** [comment]
Fixed in 7c83f00eb4299b96e88cb4e46dc3bc958cf3875e
