### ISSUE TITLE
True North offset

### ISSUE THREAD

**Issue by Vizzr** [xBimTeam/XbimEssentials#156]
The building has a 5 degrees difference to True North in Revit, but when reading it with xBim it says that the angle to True North is 95 degrees.

This is the code I use to calculate the True North:

```
double xDiff = geoRepresentation.TrueNorth.X;
double yDiff = geoRepresentation.TrueNorth.Y;
return Math.Atan2(yDiff, xDiff) * (180 / Math.PI);
```

X: -0.087155742747658
Y: 0.996194698091746
Z: NaN

Am I doing something wrong?
How can I fix this offset?

**Comment by Vizzr** [comment]
I probably figured it out.
This returns the right values:

`double y = geoRepresentation.TrueNorth.Y;
return Math.Acos(y) * (180 / Math.PI);`

Would this be okay to use?

**Comment by martin1cerny** [comment]
No, it wouldn't. The problem is that `Math.Atan2()` returns [angle to X](https://msdn.microsoft.com/en-us/library/system.math.atan2(v=vs.110).aspx) while true north is an [angle to Y](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcgeometricrepresentationcontext.htm). So, there will always be a difference of 90 degrees.

**Comment by Vizzr** [comment]
Would the:

double y = geoRepresentation.TrueNorth.Y; 
return **Math.Acos(y)** * (180 / Math.PI);
solution be fine then?

Since that is an angle to Y.

I do get the right values.

**Comment by martin1cerny** [comment]
Your solution will only work with direction vectors of length 1 which might not be the case. Also, acos results are only defined on range <0, π> so you will **not get** oriented angle <0, 2π>. Azimuth is always oriented angle. In other words, you will not know is you have the right result or if it is shifted by π.
