### ISSUE TITLE
[QUESTION] Is there a way to retrieve IfcSpace associated to IfcFurniture ?

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#158]
This issue is not really an issue but more a question as the title says.

Is there any kind of relation present directly in the "low level" object like a furniture / object / etc...
Currently I do this : 

`IIfcSpatialStructureElement test = elementToFind as IIfcSpatialStructureElement;
var spaceChildren = test.ContainsElements.SelectMany(rel => rel.RelatedElements);`

then I can get all the element present in the IfcSpace (at least for the furniture) but is there a way to reverse this ?
For example this : 
`IIfcFurniture myFurniture;
myFurniture.IsContainedBy ....`

**Comment by martin1cerny** [comment]
You can do a global search:

```cs
var spaces = model.Instances
    .Where<IfcRelContainedInSpatialStructure>(r => r.RelatedElements.Contains(myFurniture))
    .Select(r => r.RelatingStructure);
```
