### ISSUE TITLE
When creating an IFC how do you set the modelviewdefinition

### ISSUE THREAD

**Issue by sanderobdeijn** [xBimTeam/XbimEssentials#159]
I'm using the following code to create a new IfcStore.
IfcStore model = IfcStore.Create(credentials, IfcSchemaVersion.Ifc2X3, XbimStoreType.InMemoryModel);

But the modelviewdefinition isn't set.
How can I set this?
the model.header.modelviewdefinition only has a getter and I don't see a way to set it some other way.

**Comment by martin1cerny** [comment]
It only has a getter because view model is not a STEP21 or EXPRESS concept. It is just an item in `Header.FileDescription.Description` string list. So, this will set the view model to the Coordination View:

```cs
model.Header.FileDescription.Description.Add("ViewDefinition [CoordinationView]");
```

**Comment by sanderobdeijn** [comment]
I'm using the ifc checking tool from the IAI
https://www.iai.kit.edu/english/1302.php

My resulting ifc keeps getting this error.

Message Type | ERROR
-- | --
Rule Type | HEADERDEFINITION
Message Code | IFC_HEADER_02
Message String | Missing ViewDefinition in description field of file  header
No futher checks possible
Recommendation | See "Header Implementation Guide" for more details

Do I have to set something else to fix this error?

**Comment by martin1cerny** [comment]
Did you run the snippet I put above? After you saved the file, does it contain this line?

```
FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');
```

**Comment by sanderobdeijn** [comment]
Yes, I have run your snippet. But the file description wasn't filled in the IFC.
After some debugging, I found that the property is correctly set, but after starting a new transaction the list of descriptions is emptied.
I have gotten this to work now by setting the file description after all my transactions have been committed.

But is this how it is supposed to work?
I would prefer to set this property in my project setup and then create new transaction for my building my elements.

**Comment by martin1cerny** [comment]
This is a potential bug. Can you open a new issue with code snippet to reproduce the behaviour?

**Comment by sanderobdeijn** [comment]
opened issue #161
