### ISSUE TITLE
[QUESTION] Merging IFC Files with xBim ?

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#160]
Hello guys,
my question is quite simple, is it possible to merge 2 or more ifc files into a new one ?

From what  read in your blog and in your code it seems to be quite complex and the only part that is similar to a merge is your IModel.CopyTo method but it's definietly not a merge but much more an extract from the current model to a new file, like a "filter type file creator".

Many software seems to handle that, so I wanna know if it's something you will plan in your roadmap or have you any hint that could help me to start this from my side ?

My basic logic currently is to add an ifc file which will be a model from the industry and try to "insert" it in a room of your sample house (or any other building). In this way I can filter it later with the room space logic and manage it as any other objet from the base ifc file.

It's probably my last main issue for my whole project here at my company cause all other thing are almost ok for the core of our project.
This merging process will be quite important cause I need to import a lot of IoT ifc file during some building edition process to display them in the building. So any help would be welcomed :D 

Maybe I can use the "Federation" notion but if I use this, I need to be able to change the transform for all "imported object" in the main ifc file. In this way I can have a small file (federated one) to aggregate all ifc files needed for my final appartment rendering.
And after the federation creation, I need to be able to "move them" to display them at the right place to generate the geometry in a correct way.

But from what I can see in your WindowUI project you can display all federated element into the same scene but you cannot save it into wexBim, am I right ?

**Comment by martin1cerny** [comment]
In our wexBIM web viewer you can load as many IFC files as you wish. It will overlay all of them. So, federation should not be a problem with this. But if your sub-models are not spatially coordinated all approaches will fail. You need to have the data spatially aligned for all scenarios.

**Comment by liszto** [comment]
After creating a federation (even in my code base) is it possible to generate a new ifc file which will be the combination of the X ifc present in my federation file ?

My main concern is the generation of a merged file of all my ifc. 
I can maybe try to manage their positionning relatively to my 'main' ifc file to move them before the federation process.

**Comment by martin1cerny** [comment]
No, federation as we understand it is just a overlay which allows for uniform presentation and data access. It doesn't merge the data in any way. You can use new empty model and `model.InsertCopy()` function to merge bits and pieces of models but the logic to create a true merge is not trivial. You will need to deal with relative placement corrections, spatial elements identification and reassignment, filtering of duplicities and their reassignments and other tasks. Many of these need user interaction to make the process reliable and to produce user-expected results.

**Comment by liszto** [comment]
@kozintsev I sent you a direct email if you wanna explain which is your solution ;)

**Comment by liszto** [comment]
@martin1cerny I finally made it ! 
I have some more question about my basic merging process but currently I can create a new file with some files in it. I have one question and you can maybe answer me on this point. When people (I mean other tools like revit or whatever) create an aggregate of multiple bim files into one project. It's possible to export an ifc with all the components BUT do them convert all the measure into one SI Unit or not ?

Cause my current process is to take each ifc file in entry, convert them into my final final file unit system (most of time a common SI but it's based on user choices). I didn't alter my initial file I just slightly change it's IfcStore representation in memory before the InsertCopy to insert it directly in the right "format". Is it something logical or is it totally dumb ? 

My other question is, how can I figure out the merge between 2 ifc version (2x3 and 4) cause currently the map creation for the insert copy rejects maybe due to incompatibility between format. Do I have to "change" the ifc version in the ifc file (quite dirty) to allow him to insert it in my final one, which will be in "IFC4" imo.

I probably forget many thing but it's basically my current direction and at least, I succeed to recreat an object in mm whereas it was in ft in it's initial ifc file.

**Comment by martin1cerny** [comment]
Congratulations @liszto. To your points:

1) Revit will certainly convert all into one unit. In fact, it only uses feets internally and everything else is just a UI presentation. In that sense, it doesn't have to do any conversions. The IFC exporter will just use one scale factor for all the data.

2) Converting units in IFC file is possible but might get tricky very quickly. But that is an extensive topic exceeding the GitHub issue. 

3) xBIM doesn't support merge from varying IFC versions. It might be possible to alter the `InsertCopy()` function to do that but it is certainly not straightforward. Feel free to contribute with the enhancement (preferably in form of alternative function rather than altering the existing one).

**Comment by liszto** [comment]
Thanks for the quick answer !
1. It's good to know how Revit can do to try to mimic maybe their logic (even if I'm not a huge fan of Autodesk :p I could help to think to a "not so bad way to do it" ).

2. Create a formula to convert the unit in my IFC wasn't the hardest part but detect all the IFC part where  I need to apply it is quite harder cause there is a lot of ifc element that I was ignoring (stupidly) like the extrudedsolidarea etc... But as you said it's an extensive topic which is not really related to this issue.

3. I will try to take a look at cause it could be really useful to merge 2 ifc files without the same ifc extension (2x3 and 4)

**Comment by liszto** [comment]
I will try to setup 3 methods (generic if possible) that will execute those actions : 
- FindObjectAndReferences
- ReplaceObjetAndReferences
- DeleteObjectAndReferences

I would do the most generic code but I'm facing an issue between the "geometric data" and the "product data".
For the product it seems to be qutie easy to retrieve an object and all its references, I mean I tried at least for some basic stuff like project or site (I don't dig to far currently for this cause I'm trying to progres step by step).

But for the "Geometric data" it seems to be quite MOAR complicated :/ Cause I didn't find any relation logic between a point and an assignment for example. 
**Is there another way than keep a point reference and check each element property that could reference this point object ? :/** 
Each time I try to figure out all the link between component into the bim documentation, I can't find any logical link for this :/

**Comment by martin1cerny** [comment]
All geometry definitions are to be found in the hierarchy starting from `IfcProduct.Representation`.

**Comment by liszto** [comment]
mm I'm stuck in this merge process (much more in the InsertCopy adaptation)
I'm trying to convert an IfcElectricHeaterType into an IfcSpaceHeater but when I try to get a value from the Ifc.2x3.... object to write it into the Ifc.4... object even when I try to dig in the properties fields I have some issue.
The fun fact is even if I get the Property.GetValue from the 2x3 which is recognized as a "system.object" its type is always a "2x3" so when I try to write it with my propertyInfo.SetValue() the process stop cause it can find that value.
When I check the value in the VS debugger nothing can reveal it but the inherent type value stay something related to 2x3 :( 

I never worked with all the reflection logic stuff cause everybody always said me it was something quite dirty. But in your full templated system, it's the most useful thing that you can use. So it's quite hard for me to find a viable solution.

I was thinking to create an object dynamically OTA at runtime but I think it's really ubercrappy to do this x).

If you have just an idea on this runtime type switch. I think when I will have solve this thing, I won't be far to solve this ifc2x3 <=> ifc4 switch.

**Comment by martin1cerny** [comment]
As I said before. It is all doable but certainly not easy. When you work with two schemas you need to need to use two sets of reflected types because reflection will always work on a specific type. So, if you get a reflection type from IFC2x3 source object you can't use it to set the value on IFC4 target object. You have to find the equivalent IFC4 type, get equivalent PropertyInfo and use that to set the value of IFC4 object. If you use IFC4 interfaces it will make your life easier but you still need to have two sets of reflected types and property accessors for the two schemas.

**Comment by liszto** [comment]
Yeah that's what I'm doing my last concern is this value transfert from IFC2x3 to IFC4.
The most complicated part is to do that and keeping the code in a "template way" cause without this template logic it will fall in a specific case code and it will be impossible to handled.

I will continue what I'm doing cause I truely think it could be the right direction and at least what you said right above seems to confirm it.

**Comment by andyward** [comment]
Closing as I think the discussion has run its course.
