### ISSUE TITLE
how to write multiple property set into IFCMaterial

### ISSUE THREAD

**Issue by luoyuke** [xBimTeam/XbimEssentials#165]
#### Expected behavior:
I'm trying to map Revit Material Thermal/Physical Properties onto IFCMaterial.HasProperties. The current code that I wrote does add Properties on IFCMaterial but not in the PropertySet Stucture like IFC4add2 documented as  Property Sets for Objects. When I retrieve all the SingleValue from a IFCMaterial, the result is kind of broken and duplicated. Can you tell me what is the right way to do it?

#### Minimal code (or steps) to reproduce the issue:
```cs
using (var model = IfcStore.Open(file.ifc))
{

IList<Element> materials = collector.WherePasses(MaterialsCategoryfilter).WhereElementIsNotElementType().ToElements();
foreach (Element e in materials)
{
Material material = e as Material; // Revit API, Store all properties in double
//...

//The Xbim IFC edit part:
var IFCMaterial = model.Instances.FirstOrDefault<IIfcMaterial>(m => m.Name == material.Name); 

using (var txn = model.BeginTransaction("Material Properties Extension"))
{
//Pset_MaterialCommon
var MaterialProperties = model.Instances.New<IfcMaterialProperties>();
                        MaterialProperties.Name = "Pset_MaterialCommon";
                        MaterialProperties.Properties.Add(model.Instances.New<IfcPropertySingleValue>(p =>
                        {
                            p.Name = "MolecularWeight";
                            p.NominalValue = new IfcMolecularWeightMeasure(MolecularWeight);
                        }));
                        MaterialProperties.Properties.Add(model.Instances.New<IfcPropertySingleValue>(p =>
                        {
                            p.Name = "Porosity";
                            p.NominalValue = new IfcNormalisedRatioMeasure(Porosity);
                        }));
                        MaterialProperties.Properties.Add(model.Instances.New<IfcPropertySingleValue>(p =>
                        {
                            p.Name = "MassDensity";
                            p.NominalValue = new IfcMassDensityMeasure(MassDensity);
                        }));
MaterialProperties.Material = (IfcMaterialDefinition)IFCMaterial;

//Pset_MaterialThermal
                        var MaterialProperties_1 = model.Instances.New<IfcMaterialProperties>();
                        MaterialProperties_1.Name = "Pset_MaterialThermal";
...
MaterialProperties_1.Material = (IfcMaterialDefinition)IFCMaterial;

//Pset_MaterialHygroscopic
                        var MaterialProperties_2 = model.Instances.New<IfcMaterialProperties>();
                        MaterialProperties_2.Name = "Pset_MaterialHygroscopic";
...
MaterialProperties_2.Material = (IfcMaterialDefinition)IFCMaterial;

//Some other Psets ... 
txn.Commit();
}}
model.SaveAs(filePath + fileName + ".ifc");
}.....

//This part reads SingleValue from IFCMaterial.hasproperties
foreach (var IfcMaterial in IfcMaterials)
 {
Console.WriteLine("Material: " + IfcMaterial.Name +", has properties: "+ IfcMaterial.HasProperties.Any());
foreach (var property in IfcMaterial.HasProperties)
{
           Console.WriteLine(property.Name + property.EntityLabel);
           var singleVals = property.Properties.OfType<IfcPropertySingleValue>();
           if (singleVals == null) continue;
           foreach (var singleVal in singleVals)
           {
                Console.WriteLine($"foreach: {singleVal.Name} , {singleVal.NominalValue}");
           }
 }
}
}
```

#### Minimal file to reproduce the issue:
*(IFC files need to be zipped to be uploaded. Than just drag & drop here)*
//Console displays
[ConsolePropertie.txt](https://github.com/xBimTeam/XbimEssentials/files/2038164/ConsolePropertie.txt)
//IFC Sample of a Compound Wall from Revit after property editting
[IFCBuilding.txt](https://github.com/xBimTeam/XbimEssentials/files/2038168/IFCBuilding.txt)

**Comment by martin1cerny** [comment]
Can you be more specific about what is *kind of broken and duplicated*? I can only see that you don't set up name of the property set containing DynamicViscosity, YoungModulus, ShearModulus, PoissonRatio and ThermalExpansionCoefficient properties. Also, you use the same name (like *Pset_MaterialMechanical*) for different property sets. I can only assume there are residual coding errors after you cut & pasted the code. There are also many *IfcMaterialProperties* objects with no material assigned so they are data orphans effectively. You should seriously revise your code for your own errors.

**Comment by martin1cerny** [comment]
I'm sorry, but I'm not interested in the complete C# code. If you think xBIM is doing something wrong, isolate the minimal code + data example independent of Revit or anything else which will fail under clean conditions. 

Say you think  material is created twice, this would be a good test to prove it:

```cs
public void Test()
{
	// model.ifc should be as small as possible and provided with the test
	using(var model = IfcStore.Open("model.ifc"))
	{
		var count = model
			.Instances
			.OfType<IfcMaterialProperties>()
			.Count();
			
		using (var txn = model.BeginTransaction("Test"))
		{
			var properties = model.Instances.Create<IfcMaterialProperties>();
			txn.Commit();
		}
		
		var countAfter = model
			.Instances
			.OfType<IfcMaterialProperties>()
			.Count();
		
		if (countAfter > count + 1)
			throw new Exception("Created more than one properties object!");
	}
}
```

I'm sorry but I will not be able to investigate large files and extensive code examples.

**Comment by luoyuke** [comment]
After going thru the IFC4add2 documentation about MaterialProperties having a S:1 relation with the Material it references to. Also the PropertySet SubTypes are deleted. I guess that creating every property as SingleValue is the easy way to go. 
'MaterialProperties.Material = (IfcMaterialDefinition)IFCMaterial;' 
As long as I only define MaterialProeprties once per Material it works perfectly fine.

**Comment by martin1cerny** [comment]
So, the problem was not on the xBIM side to close this up.

**Comment by nikilsss** [comment]
Hi i am going through same issue with adding multiple properties in an entity.is it solved ? If yes then please can you tell me the solution as well

**Comment by martin1cerny** [comment]
You can create more instances of [IfcMaterialProperties](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcmaterialproperties.htm) to store multiple property sets for any IfcMaterialDefinition.
