### ISSUE TITLE
Help with Validation Error

### ISSUE THREAD

**Issue by MDIFC** [xBimTeam/XbimEssentials#167]
Is it possible to get an explanation on how to fix this following error  "Issue of type EntityWhereClauses on IfcProduct.WR1."  that I am getting with the XBim Explorer Validation Tool.

I have attached the file as a txt file.

[rtc 3 new.txt](https://github.com/xBimTeam/XbimEssentials/files/2053629/rtc.3.new.txt)

**Comment by MDIFC** [comment]
var b = Model.Instances.New<Xbim.Ifc2x3.ProductExtension.IfcBuildingElementProxy>();
b.GlobalId = new Xbim.Ifc2x3.UtilityResource.IfcGloballyUniqueId(Xbim.Ifc2x3.UtilityResource.IfcGloballyUniqueId.ConvertToBase64(Guid.NewGuid()));
b.OwnerHistory = spatialStructure.IfcRelContainedInSpatialStructure<IfcRelContainedInSpatialStructure>().OwnerHistory;
                       
if ((name != null) && (name.Length > 0)) b.Name = name;
if ((description != null) && (description.Length > 0)) b.Description = description;
prvIfcObject = b;
b.CompositionType = Xbim.Ifc2x3.ProductExtension.IfcElementCompositionEnum.ELEMENT;

Above is the code written for creating a new BuildingElementProxy - do I have to add the following line?
b.ObjectPlacement = ??????
Not sure what the Object Placement should equal

**Comment by martin1cerny** [comment]
Yes, you need to set `ObjectPlacement` of every product which has any representation. Object placement is what it says - placement of the object. It defines where the representation of the object should be placed. For mode detail see the [documentation](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html) please.
