### ISSUE TITLE
Culture specific typenames

### ISSUE THREAD

**Issue by alierol** [xBimTeam/XbimEssentials#17]
Hello,

I would like to report a problem and suggest a fix in lfcMetaData.cs. The problem is related to the uppercase type names stored in `TypeNameToIfcTypeLookup.` The `AddParent` method adds culture dependent upper case type names in the dictionary `TypeNameToIfcTypeLookup,` which causes crashes as the type can not be found later when the program runs under Turkish language. In Turkish upper case 'i' is an uppercase 'I' with a dot over it. This may be an issue in similar languages as well.

The suggested fix is:

In lfcMetaData.cs line 195
`string typeLookup = baseParent.Name.ToUpper()`
should be changed to 
`string typeLookup = baseParent.Name.ToUpperInvariant()`

This is working fine for the time being but I am not sure if such a fix won't be needed elsewhere.

**Comment by martin1cerny** [comment]
Thank you very much for spotting this @alierol. I've fixed it in the develop branch.
