### ISSUE TITLE
Calling IfcStore.Create with a "XbimEditorCredentials" create 2 IfcOrganization

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#172]
Create an IfcStore with xBimCredentials must only create one IFCORGANIZATION.
I'm actually on the "develop" branch but I think it's the same thing in master (didn't tho)

```
var credentials = new XbimEditorCredentials
{
	ApplicationDevelopersName = "Test",
	ApplicationFullName = "Test-2",
	ApplicationIdentifier = "Test-2" + ".exe",
	ApplicationVersion = "1.0",
	EditorsFamilyName = "Team",
	EditorsGivenName = "Unity",
	EditorsOrganisationName = "Ubiant"
};
var model = IfcStore.Create(credentials, IfcSchemaVersion.Ifc4, XbimStoreType.InMemoryModel);
using (var txn = model.BeginTransaction("Initialise Model and basic space info"))
{
        var project = model.Instances.New<IfcProject>();
	//set the units to SI (mm and metres)
	project.Initialize(ProjectUnits.SIUnitsUK);
	project.Name = projectName;
        txn.Commit();
}
model .SaveAs("TestDesigner.ifc", Xbim.IO.IfcStorageType.Ifc);
```

This will create 2 IFCORGANIZATION one with "Ubiant" by getting the `EditorsOrganisationName` and the other one will have the `ApplicationFullName `

The issue comes from the fact that you called `DefaultOwningUser` and `DefaultOwningApplication` during the IfcStore creation if the xBimCredentials are defined. And both of them didn't check if the IFCORGANIZATION already exists. So it will call twice this line : 
`Instances.New<Ifc4.ActorResource.IfcOrganization>()`
or 
`Instances.New<Ifc2x3.ActorResource.IfcOrganization>()`

depending of the FileSchema from the model.

EDIT : I created a Pull Request to fix this issue #173

**Comment by martin1cerny** [comment]
While so deep in the investigation, could you submit a pull request to `develop` branch please? Bugfixes are greatly appreciated, thank you!

**Comment by liszto** [comment]
It's done, I edit my post with it right above ;).
