### ISSUE TITLE
[QUESTION] How to call SetXYZ from IfcCartesianPoint with no dependancies on namespace ?

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#174]
Hi,
in my code I retrieve all the IfcCartesianPoint by doing this : 

`IEnumerable<IIfcCartesianPoint> m_cartesianPointList = model.Instances.OfType<IIfcCartesianPoint>();`

In this way I don't have to specify a particular namespace and it can handle both ifc format but after this I wanna call the `ifcCartesianPoint.SetXYZ()` cause in my case I wanna patch them without thinking to the current fileschema but it can't be done cause by default it seems to take the Ifc4.GeometryResources cause I call this "using" on top.

It's impossible to not mention it cause otherwise it will create an ambigous statement due to ifc2x3 and ifc4.

If you have an idea concerning this ?

**Comment by martin1cerny** [comment]
Because you are using IFC4 interfaces you need to use IFC4 `structs` for data. It will get translated. Give it a try.

**Comment by liszto** [comment]
mmm so it must implicitly cast by the project ?

Cause basically I was doing this  : 

```
IEnumerable<IIfcCartesianPoint> m_cartesianPointList = model.Instances.OfType<IIfcCartesianPoint>();
foreach (var item in m_cartesianPointList)
{
	IfcCartesianPoint itemConverted = (IfcCartesianPoint)item;
	if (itemConverted.Dim > 2)
		itemConverted.SetXYZ(item.X * nConvertValueMeter, item.Y * nConvertValueMeter, item.Z * nConvertValueMeter);
}
```

But by doing this, it will automatically try to retrieve the method from the ifc4 namespace and will create an "InvalidCastException" during the process of file in IFC2x3.

**Comment by liszto** [comment]
My previous answer solve the issue but it fails right after due to some InsertCopy / BeginTransaction between 2 unrelated model (ifc2x3 and ifc4) which is currently not supported as we talk in this ticket #160 cause I didn't already check this.. :(

**Comment by martin1cerny** [comment]
I see. You are missing the actual method `SetXYZ()` right? That is actually only a shortcut for `point.Coordinates` list. You can modify that directly.

```cs
// not tested
itemConverted.Coordinates[0] *= scale;
itemConverted.Coordinates[1] *= scale;
```
