### ISSUE TITLE
[QUESTION] What is the most logical thing to do in a deprecated case between IFC2x3 and IFC4

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#175]
Hello guys,
sorry to bother you again with a one more question 😈 .
But with my luck, I'm trying to parse a file that contained this : 

> #7634= IFCELECTRICHEATERTYPE('1PJXy4VsH72xUAwt7RTlcE',#4001,'AirHeater_WAH11',$,$,(#7714,#7736,#7745,#7776),(#7632),'4674',$,.ELECTRICPOINTHEATER.);

But IFCELECTRICHEATERTYPE is now deprecated and can't be imported into an IFC4 project without any issue :/
Have you something in your project that allow us to port those specials cases into the IFC4 ?
My first idea was to get the upper class (even if I don't know how to do it right now) so if this one is still in use I can rewrite the line with it and removing the useless part from the inherited type. Maybe it's quite dirty... :/

But when I read this lil' erratum : 
http://www.buildingsmart-tech.org/implementation/ifc-implementation/ifc-impl-agreements/cv-2x3-166

it doesn't seem to be as simple as I thought :/

If you have any idea on what is the cleanest way to do it ?

**Comment by martin1cerny** [comment]
No, xBIM doesn't have any code to translate between IFC2x3 and IFC4 in either way. It only has IFC4 interfaces implemented on top of IFC2x3 classes to it is possible to work with both schemas in a uniform way. But it is not possible to save IFC2x3 to IFC4 and vice versa. I did think about doing that and this is one of the problems to solve to do it. I didn't do it in the end because it didn't fit in any project. It is doable but you will have to make several decisions like this.

**Comment by liszto** [comment]
Yeah indeed. 
That was just to be sure that you didn't have any convertion class between 2x3 and 4 to manage the changes present in the ifc4 when it's something that could definietly break the 2x3 file.

I will see to manage this.

So for you the most common thing is to create a project based on the fileschema of the first file you will merge ? Cause if you have to merge multiple ifc files with different fileschema you have to do a choice. For me it's to keep a merged file in the most recent fileschema revision but maybe i'm wrong on this point ? :/

**Comment by liszto** [comment]
ok that's why I make this decision by converting from 2x3 to 4 you already did a lot of work for me :) 

So... Time to work ! Thanks again for your answer !

**Comment by martin1cerny** [comment]
Are you planning to contribute your merge code to xBIM? Your kind of contribution would certainly be greatly appreciated.

**Comment by liszto** [comment]
As soon I have something stable yes indeed it's definietly something that could be usefull !
I think it will take some time to have something stable due to all specific cases. but as soon as I have something good (according to me) I will create a ticket or a pull request to discuss on a possible submission in your project @martin1cerny

**Comment by martin1cerny** [comment]
That would be great. I'm looking forward seeing something interesting :-)

**Comment by liszto** [comment]
Just to let you  know @martin1cerny, my current merging process logic : 
- Raw merge from X ifc4 file currently working without any collision test, the display is ok in any bim viewer except Bim Vision that create some artifact but I really don't know why... there some odd cartesian point value whereas in my file they are ok. (I need to check this later) And in your viewer it's ok too, Revit too... etc...
My principal point (as we said above) it will always create an IFC4 file in output no matter the IFC format entry

My next step are : 
- Raw merge from X ifc2x3 and ifc4 which is my current my task.
- In the "same" time, I need to manage each "DELETED or MOVED or MODIFIED" state between IFC2x3 and IFC4 to allow me to merge those specific case
_And lil' bit later_
- Detect in which IfcSpace the current merge object is added to redirect it's spatial in the right space. If it's not in a space, there is two options (according to me) : 
=> the first one is to associate it to the IfcBuildingStorey 
=> the second one is to create a space but it could be really "touchy" to do it without any user interaction.
- Probably I missed others things... but who knows :-) 

From a unity side (which is not important for you, but it is for me)
-  I will have to manage all those geometry type to render them in a proper way into Unity by converting them from IFC Geometry Data to Unity Mesh
