### ISSUE TITLE
[QUESTION] CodeGenerator and custom code region

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#176]
I often see this code part in a lot of files : 
```
#region Custom code (will survive code regeneration)
	//## Custom code
	//##
#endregion
```

If I use it anywhere in your auto generated code all the code in it will be ignored and returned without any modification ? I need to know it for all the conversion stuff between ifc2x3 and ifc4.

P.S : Maybe a mail address to contact you could be useful (not to spam you) but to ask that kind of question without spamming the github except if you think it's still relevant to be asked here.

**Comment by martin1cerny** [comment]
Please, check recent my commits to find the address. I don't want to post it in plain text here but Git is not GDPR aware :-)

And yes, whatever you put in between these comments will survive regeneration of the code. But for your purpose it might be better to create partial implementations in a folder somewhere aside. Also, **only do that if you need to extend interface definitions or access private members**. 

I'd prefer to see it as a separate code if possible.

**Comment by liszto** [comment]
Ok for the Partial class, I would try to stay as close as possible as you currently do in your library (it seems important to me to dec this in the same way).

So I have a one more question in this ticket : 

I found this for example in your "IfcActorRole.cs" file in the Ifc2x3 namespace : 

```
//## Custom code to handle setting of enumeration of Role
				//##
				switch (value)
				{
					case Ifc4.Interfaces.IfcRoleEnum.SUPPLIER:
						Role = IfcRoleEnum.SUPPLIER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.MANUFACTURER:
						Role = IfcRoleEnum.MANUFACTURER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.CONTRACTOR:
						Role = IfcRoleEnum.CONTRACTOR;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.SUBCONTRACTOR:
						Role = IfcRoleEnum.SUBCONTRACTOR;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.ARCHITECT:
						Role = IfcRoleEnum.ARCHITECT;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.STRUCTURALENGINEER:
						Role = IfcRoleEnum.STRUCTURALENGINEER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.COSTENGINEER:
						Role = IfcRoleEnum.COSTENGINEER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.CLIENT:
						Role = IfcRoleEnum.CLIENT;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.BUILDINGOWNER:
						Role = IfcRoleEnum.BUILDINGOWNER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.BUILDINGOPERATOR:
						Role = IfcRoleEnum.BUILDINGOPERATOR;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.MECHANICALENGINEER:
						Role = IfcRoleEnum.MECHANICALENGINEER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.ELECTRICALENGINEER:
						Role = IfcRoleEnum.ELECTRICALENGINEER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.PROJECTMANAGER:
						Role = IfcRoleEnum.PROJECTMANAGER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.FACILITIESMANAGER:
						Role = IfcRoleEnum.FACILITIESMANAGER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.CIVILENGINEER:
						Role = IfcRoleEnum.CIVILENGINEER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.COMMISSIONINGENGINEER:
						//## Handle setting of COMMISSIONINGENGINEER member from 
                                               IfcRoleEnum in property Role
                                               Role = IfcRoleEnum.USERDEFINED;
                                               UserDefinedRole = "COMMISSIONINGENGINEER";
				               return;
						//##
					case Ifc4.Interfaces.IfcRoleEnum.ENGINEER:
						Role = IfcRoleEnum.ENGINEER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.OWNER:
						Role = IfcRoleEnum.OWNER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.CONSULTANT:
						Role = IfcRoleEnum.CONSULTANT;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.CONSTRUCTIONMANAGER:
						Role = IfcRoleEnum.CONSTRUCTIONMANAGER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.FIELDCONSTRUCTIONMANAGER:
						Role = IfcRoleEnum.FIELDCONSTRUCTIONMANAGER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.RESELLER:
						Role = IfcRoleEnum.RESELLER;
						return;
					case Ifc4.Interfaces.IfcRoleEnum.USERDEFINED:
						Role = IfcRoleEnum.USERDEFINED;
						return;
					default:
						throw new System.ArgumentOutOfRangeException();
				}
```

Does your code generator ignore the commented line with the "#custom code" cause when I read this switch case it seems to be write by someone not by a machine.

I made this assumption based on this : 
```
case Ifc4.Interfaces.IfcRoleEnum.COMMISSIONINGENGINEER:
	//## Handle setting of COMMISSIONINGENGINEER member from 
        IfcRoleEnum in property Role
        Role = IfcRoleEnum.USERDEFINED;
        UserDefinedRole = "COMMISSIONINGENGINEER";
	return;
	//##
```

And most of all (which an extra question in the extra question) why are you defined the "Role" as an USERDEFINED in that particular when it must be set to : 
` Role = IfcRoleEnum.COMISSIONINGENGINEER;` (maybe it's a bug ?)

Thanks again for your fast answer 👍

**Comment by martin1cerny** [comment]
Because IFC2x3 doesn't have `IfcRoleEnum.COMISSIONINGENGINEER` but IFC allows to define user defined value in this way. And it works bidirectionally from IFC4 interfaces.

**Comment by liszto** [comment]
mmm IFC2x3 has => "IfcRoleEnum.COMISSIONINGENGINEER" whereas IFC4 has => IfcRoleEnum.COMMISSIONINGENGINEER or maybe I missed something ?

In the IFC2x3 documentation it seems to be there : http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcactorresource/lexical/ifcroleenum.htm

**Comment by martin1cerny** [comment]
OK, I missed this one. Will change it so use the typo one.

**Comment by liszto** [comment]
So I think that answer to my question. This class is made by hand even if it's written auto-generated on top ? :)

**Comment by martin1cerny** [comment]
OK, I missed this one. Will change it so use the typo one.

**Comment by martin1cerny** [comment]
No, it is autogenerated. But there are parts of the implementation where automation would cost us more than manual implementation or where automation was simply not possible. But to keep the code together it there are these sections which survive regeneration of the code.

**Comment by liszto** [comment]
Ok I understand it's just code generator side and not in the current code that's why I didn't see the special "#region" tag. Thanks for the explanation.
