### ISSUE TITLE
Pushing IFC4x1 implementation to master branch

### ISSUE THREAD

**Issue by WindingWinter** [xBimTeam/XbimEssentials#177]
From what I can tell, it seems that [IFC4x1](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/) specification is not (yet) being supported in the Master branch, so entity like [ifcAlignment](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/schema/ifcproductextension/lexical/ifcalignment.htm) is not yet there.

Is it possible to include this?

**Comment by martin1cerny** [comment]
It is definitely time to push `develop` changes to `master`. I'll do it later this week.

**Comment by CBenghi** [comment]
In the meanwhile I'm updating geometry to OpenCASCADE 7.3.
Once that's done I'll have to implement the new geometry classes of 4 and 4.1
Perhaps in a couple of weeks we can publish Xbim 4.1throughout the different libs.

**Comment by CBenghi** [comment]
@martin1cerny,
I've realised that I've got some work to do on the validation function of WHERE clauses in the new schema.
Give me a couple of days to do that before you merge to master.
Claudio

**Comment by martin1cerny** [comment]
OK

**Comment by WindingWinter** [comment]
@CBenghi , @martin1cerny ,

I think even in[ `develop` branch](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.Ifc4/ProductExtension/IfcAlignment.cs), there are some ifcAlignment properties that are still missing, such as `Horizontal`, `Vertical` and `LinearRefMethod` ( see [here for official definition](http://www.buildingsmart-tech.org/mvd/IFC4x1/Alignment/1.0/html/schema/ifcproductextension/lexical/ifcalignment.htm))

Or do I misunderstand something?

**Comment by martin1cerny** [comment]
The documentation you link to is not the [final release](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html) but the old one. We implement the final release where these properties were [removed from the schema](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/schema/ifcproductextension/lexical/ifcalignment.htm).

**Comment by martin1cerny** [comment]
Yes, you are right. Closing now.
