### ISSUE TITLE
ifcLabel accented characters

### ISSUE THREAD

**Issue by YauronBis** [xBimTeam/XbimEssentials#180]
#### Expected behavior:
It’s about accentuation characters that does not exist in english language but exist in many other european language like : é è à ê î  ï  ñ  ô, etc...

For example,  an IFC File give : #30127= IFCSURFACESTYLE('M\X\8Etal-Fer',.BOTH.,(#11062));
So we have to read data as : #30127= IFCSURFACESTYLE('Métal-Fer',.BOTH.,(#11062));

#### Actual behavior or exception details:
But xbim read it (with and empty space)  as : #30127= IFCSURFACESTYLE('M tal-Fer',.BOTH.,(#11062));

#### Versions of xBIM Packages:
as i'm concern i think it's any xBim version as the same problem.

#### Minimal code (or steps) to reproduce the issue:
No specific code. Just load Model from any IFC file wrote in a not english culture.

#### Minimal file to reproduce the issue:
any IFC file from european language with accentued character, like french, spanish, german, ...

[MAISON YANNICK.zip](https://github.com/xBimTeam/XbimEssentials/files/2115129/MAISON.YANNICK.zip)

**Comment by martin1cerny** [comment]
That is because it is **not encoded correctly**. It should be `'M\X\E8tal-Fer'`.
See [IFC string encoding rules](http://www.buildingsmart-tech.org/implementation/get-started/string-encoding).

It is a **bug in your data**, not in xBIM. There is no way for xBIM to fix this wrong encoding.

**Comment by YauronBis** [comment]
Thanks about this. I did not know about these rules.
Now i get that xBIM manage them, so as you said, the wrong encoding is in my IFC data file.
