### ISSUE TITLE
How to use IfcSurfaceStyleRendering in order to customize IfcMaterial

### ISSUE THREAD

**Issue by WindingWinter** [xBimTeam/XbimEssentials#183]
I want to render an `IfcMaterial` using `IfcSurfaceStyleRendering`, but couldn't find any example on how to do so. Reading the schema doesn't lead to anywhere.

Is there an example on how to render an `IfcMaterial` using `IfcSurfaceStyleRendering`?

**Comment by martin1cerny** [comment]
You need to navigate from `IfcStyledItem` to geometry representation on one side and to actual `IfcSurfaceStyleRendering` on the other. Relation to `IfcMaterial` is not mandatory. Than do what you want with RGBA definitions.

**Comment by WindingWinter** [comment]
Here's what I really got confused. 

I understand that the geometrical representation `IfcGeometricRepresentationItem` has a `StyledByItem` ( which is a list of `IfcStyledItem`) property in the name of `StyleByItem`, eg:

```
         IfcGeometricRepresentationItem wallRep;
         IEnumerable<IfcStyleItem> styledItems=  wallRep.StyledByItem;
```

But `wallRep.StyledByItem` cannot be added, hence, there is no way to assign `IfcStyleItem` to a `IfcGeometricRepresentationItem` 

Or is there a way that I am not aware of?

**Comment by martin1cerny** [comment]
This is an inverse relationship. You have to assign `IfcGeometricRepresentationItem` to `IfcStyleItem.Item` not the other way around. See [the documentation](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcstyleditem.htm) for relations between material, style and shape.

**Comment by WindingWinter** [comment]
I think I figure the answer out myself:

```
             var ifcStyleItem = Model.Instances.New<IfcStyledItem>
              (
                     (style) =>
                      {
                          style.Item = IfcGeometricRepresentationItem_Obj;  
                           IfcSurfaceStyle surfaceStyle = CreateSurfaceStyle();
                          style.Styles.Add(surfaceStyle);

                        }
               );

        private IfcSurfaceStyle CreateSurfaceStyle()
        {
    
            var surfaceStyle = Model.Instances.New<IfcSurfaceStyle>
            (
                (sStyle) =>
                {
                    sStyle.Name = "surface style";
                    sStyle.Side = IfcSurfaceSide.BOTH;
                    var surfaceRendering = Model.Instances.New<IfcSurfaceStyleRendering>
                    (
                        (sRendering) =>
                        {
                            var colorTuple = Convert(colorMedia);
                            sRendering.DiffuseColour = Model.Instances.New<IfcColourRgb>
                            (
                                (color) =>
                                {
                                    color.Name = "DiffusionColor";
                                    color.Blue = 1;
                                    color.Green = 0;
                                    color.Red = 0;
                                }
                            );

                            sRendering.DiffuseTransmissionColour = Model.Instances.New<IfcColourRgb>
                              (
                                  (color) =>
                                  {
                                      color.Name = "DiffuseTransmissionColour";
                                      color.Blue = 1;
                                      color.Green = 0;
                                      color.Red = 0;
                                  }
                              );
                        }
                    );
                    sStyle.Styles.Add(surfaceRendering);
                }
            );
            return surfaceStyle;
        }

```

But then we have the problem of [cannot rendering the color correctly in XBimExplorer](https://github.com/xBimTeam/XbimWindowsUI/issues/89).

**Comment by martin1cerny** [comment]
Yes, this seems to be right. You just don't need to create thousands identical styles. It is better to have them as a reusable resource/dictionary of styles. It will make your result more conscious. But what you do should be valid. I'm not sure why our viewer is not picking it up. Will investigate

**Comment by martin1cerny** [comment]
I think I see the problem now. You are assigning the optional attributes to `IfcSurfaceStyleRendering` but you are not setting the mandatory one which is `IfcSurfaceStyleRendering.SurfaceColour`.
