### ISSUE TITLE
Ifczip with additional files

### ISSUE THREAD

**Issue by imsmk** [xBimTeam/XbimEssentials#185]
Hi,
there is a little issue with ifcstore opens an ifczip file.
Ifczip can also contains non model files.
#### Expected behavior:
Ifcstore  analyse only model files, not attachments.

#### Proposal:
ifcstore open in  line 342
instead
```cs
if (!zipEntry.IsFile) continue; // 
```
add additional condition 
```cs
if (!zipEntry.IsFile || zipEntry.Name.StorageType() == IfcStorageType.Invalid) continue; 
```

**Comment by martin1cerny** [comment]
You are welcome to create a Pull Request to our **develop** branch.
