### ISSUE TITLE
ifcxml with quantities

### ISSUE THREAD

**Issue by imsmk** [xBimTeam/XbimEssentials#187]
Hi,

XbimXmlReader4  don't find all quantities in ifcxml.
 
There's an example model QuantityTest attached, which contains a site with a quantityset "TestQuantities" with only one IfcQuantityArea.

#### reproduce the issue:
```cs
[TestMethod]
        public void CheckQuantity()
        {
            var path = @"QuantityTest.ifcxml";
            var store = Xbim.Ifc.IfcStore.Open(path);
            var site = store.Instances.FirstOrDefault<IIfcSite>(r => r.Name == "S");
            var rel = site.IsDefinedBy
                    .Where(r => r.RelatingPropertyDefinition is IIfcElementQuantity)
                    .FirstOrDefault();
            Assert.IsNotNull(rel);
        }
``` 
#### Minimal file to reproduce the issue:
[QuantityTest.zip](https://github.com/xBimTeam/XbimEssentials/files/2158727/QuantityTest.zip)

**Comment by imsmk** [comment]
Hi Martin,
the model refers to [IFC4](http://www.buildingsmart-tech.org/ifcXML/IFC4/final/ifcXML4.xsd) without Addendum1. They change it in [Add1](http://www.buildingsmart-tech.org/ifcXML/IFC4/Add1/IFC4_ADD1.xsd).

original: [IFC4Final](http://www.buildingsmart-tech.org/ifc/IFC4/final/html/schema/ifckernel/lexical/ifcreldefinesbyproperties.htm)
```xml
<xs:element name="IfcRelDefinesByProperties" type="ifc:IfcRelDefinesByProperties" substitutionGroup="ifc:IfcRelDefines" nillable="true"/>
 <xs:complexType name="IfcRelDefinesByProperties">
  <xs:complexContent>
   <xs:extension base="ifc:IfcRelDefines">
    <xs:sequence>
     <xs:element name="RelatedObjects" type="ifc:IfcObjectDefinition" nillable="true" maxOccurs="1"/>
     <xs:element name="RelatingPropertyDefinition">
      <xs:complexType>
       <xs:group ref="ifc:IfcPropertySetDefinitionSelect"/>
      </xs:complexType>
     </xs:element>
    </xs:sequence>
   </xs:extension>
  </xs:complexContent>
 </xs:complexType>
```
So in newer models (IFC4Add1 and above) ,it will never happens, but this one is "final" ifc4 xml exported from older program.
It would be nice, if XbimxmlReader4 can handle that.

**Comment by martin1cerny** [comment]
I see. They also changed the cardinality of the attribute from [1:1] to [1:?] which is important. The fix would need to go in [here](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.IO/Xml/XbimXmlReader4.cs#L425). Can you try to fox it and submit a pull request? Contribution would be highly appreciated.

**Comment by imsmk** [comment]
OK, I'll have a look.
Question: I am not certain whether it's a good idea to only enhance the condition [here](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.IO/Xml/XbimXmlReader4.cs#L398)  ?

**Comment by martin1cerny** [comment]
Yes, you are probably right. It's been a long time since I was in this part of the code :-)
