### ISSUE TITLE
May I know how to assign a colour to IfcShapeRepresentation or IfcExtrudedAreaSolid?

### ISSUE THREAD

**Issue by michealChin** [xBimTeam/XbimEssentials#19]
I just go through the HelloWallExample where a wall (IfcWallStandardCase) is been added to a model and save to a file. I just wonder is there a way to assign colour to the wall?

**Comment by martin1cerny** [comment]
Yes, there is. You need to use [IfcStyledItem](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcpresentationappearanceresource/lexical/ifcstyleditem.htm). You will need to have a look on the [IFC2x3](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html) or [IFC4](http://www.buildingsmart-tech.org/ifc/IFC4/Add1/html/) schema. IFC4 is fully implemented in develop branch now.
