### ISSUE TITLE
IfcDerivedUnit Dimensions Property throws exception

### ISSUE THREAD

**Issue by imsmk** [xBimTeam/XbimEssentials#190]
IfcDerivedUnit with an IfcDerivedUnitElement of Unit Type IfcConversionBasedUnit has no Dimension.
so that the implementation of the getter for dimensions of IFCDerviceUnit throws System.NullReferenceException  

#### Minimal code (or steps) to reproduce the issue:
```cs
[TestMethod]
        public void CheckIfcDerivedUnit()
        {
            var path = @"UnitTest.ifcxml";
            var store = Xbim.Ifc.IfcStore.Open(path);
            var derivedUnit = store.Instances.FirstOrDefault<IfcDerivedUnit>(u => u.UnitType == IfcDerivedUnitEnum.USERDEFINED);
            var conversionBasedUnit = store.Instances.FirstOrDefault<IIfcConversionBasedUnit>();
            // dim_cbu is null
            var dim_cbu = conversionBasedUnit.Dimensions;
            // System.NullReferenceException   
            var dim_derivedUnit = derivedUnit.Dimensions;
           
        }
```
Testfile:
[UnitTest.zip](https://github.com/xBimTeam/XbimEssentials/files/2202935/UnitTest.zip)

**Comment by martin1cerny** [comment]
I put a code in to avoid the `NullReferenceException` but note that your file is not valid. `Dimentions` is a mandatory attribute of `IfcConversionBasedUnit`. Also your unit component `IfcSIUnit` is missing names. There might be other as well.

**Comment by imsmk** [comment]
thanks.
But I'm not sure.
 
I do a XSD check, and it seems valid.
I know, in the documentation of add1 for `IfcSIUnit ` is written cardinality [1:1]
[add1](http://www.buildingsmart-tech.org/ifc/IFC4/Add1/html/link/ifcsiunit.htm)
but in add2 is not 
[add2](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcsiunit.htm)

am I miss something ?

**Comment by martin1cerny** [comment]
If there is no `?` in cardinality field it is mandatory.

**Comment by martin1cerny** [comment]
...but looking at it again there is a mismatch between XSD and EXPRESS schema definition. XSD says it is optional but EXPRESS says it is not optional. EXPRESS definition is the primary one and is certainly right in this case because `IfcSIUnit` without the name doesn't make a sense.

**Comment by imsmk** [comment]
thanks for clarification
so XSD is wrong on `ifcSIUnit `
that also applies to   `Dimensions `on `IfcConversionBasedUnit `, right ?

**Comment by martin1cerny** [comment]
Yes, I'd say so.

**Comment by imsmk** [comment]
thanks a lot.
I cooperate with some vendors of bim software and their model is also wrong because they validate only against ifc-xsd and not EXPRESS. 
Do you know where the mismatch between xsd and exp is documented?

**Comment by martin1cerny** [comment]
This is a first time I noticed that. I'd generally discourage people (both developers and users) from using IFCXML for many other reasons as well.
