### ISSUE TITLE
How to set gradient color for IfcTriangulatedFaceSet based on z values 

### ISSUE THREAD

**Issue by WindingWinter** [xBimTeam/XbimEssentials#191]
I have an `IfcTriangulatedFaceSet`, and based on the `z `property in `IfcTriangulatedFaceSet.Coordinates`, I want to assign a gradient of colors to each element ( ie:   `IfcTriangulatedFaceSet.CoordIndex`)

I want to achieve something like this:

![contourlines](https://user-images.githubusercontent.com/13161574/43115117-091ccb88-8f35-11e8-890d-0fec1cb74dd3.png)

Where the terrain is represented by `IfcTriangulatedFaceSet`.

The [IfcStyledItem](https://github.com/xBimTeam/XbimEssentials/issues/183#issuecomment-407267387) seems to be able to set only one color per `IfcRepresentationItem`, and unable to provide a rich gradient of colors for the whole `IfcTriangulatedFaceSet` object.

Any idea how this can be done?

**Comment by martin1cerny** [comment]
You might be able to achieve this with [texture style](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcsurfacestylewithtextures.htm) but I'm not sure how many tools will pick this up as it is not very common in authoring tools. There is no direct support for colour gradients in IFC of any version as far as I know.

**Comment by WindingWinter** [comment]
I see, is XBimExplorer picking this texture style up?

**Comment by martin1cerny** [comment]
I was never deeply involved in the xBimXplorer but I don't think it handles textures.
