### ISSUE TITLE
[UNITY ISSUE] Database creation with Esent fail on Unity/mono

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#192]
Whe I try to load a file by using the ESENT database system it always failed with this error : 
```
Illegal index definition // Microsoft.Isam.Esent.Interop.EsentIndexInvalidDefException: Illegal index definition
  at Microsoft.Isam.Esent.Interop.Api.Check (System.Int32 err) [0x0000a] in D:\Project\Designer\Designer\Assets\Scripts\Bim-Library\Scripts\Xbim\Common\Esent.Interop\Api.cs:2972 
  at Microsoft.Isam.Esent.Interop.Api.JetCreateIndex (Microsoft.Isam.Esent.Interop.JET_SESID sesid, Microsoft.Isam.Esent.Interop.JET_TABLEID tableid, System.String indexName, Microsoft.Isam.Esent.Interop.CreateIndexGrbit grbit, System.String keyDescription, System.Int32 keyDescriptionLength, System.Int32 density) [0x00015] in D:\Project\Designer\Designer\Assets\Scripts\Bim-Library\Scripts\Xbim\Common\Esent.Interop\Api.cs:1219 
  at Xbim.IO.Esent.EsentEntityCursor.CreateTable (Microsoft.Isam.Esent.Interop.JET_SESID sesid, Microsoft.Isam.Esent.Interop.JET_DBID dbid) [0x000f3] in D:\Project\Designer\Designer\Assets\Scripts\Bim-Library\Scripts\Xbim\Common\Xbim.IO\Esent\EsentEntityCursor.cs:109 
  at Xbim.IO.Esent.PersistedEntityInstanceCache.CreateDatabase (System.String fileName) [0x0002f] in D:\Project\Designer\Designer\Assets\Scripts\Bim-Library\Scripts\Xbim\Common\Xbim.IO\Esent\PersistedEntityInstanceCache.cs:124 
UnityEngine.Debug:Log(Object)
Xbim.IO.Esent.PersistedEntityInstanceCache:CreateDatabase(String) (at Assets/Scripts/Bim-Library/Scripts/Xbim/Common/Xbim.IO/Esent/PersistedEntityInstanceCache.cs:130)
Xbim.IO.Esent.PersistedEntityInstanceCache:ImportStep(String, Stream, Int64, ReportProgressDelegate, Boolean, Boolean, Int32) (at Assets/Scripts/Bim-Library/Scripts/Xbim/Common/Xbim.IO/Esent/PersistedEntityInstanceCache.cs:743)
Xbim.IO.Esent.PersistedEntityInstanceCache:ImportStep(String, String, ReportProgressDelegate, Boolean, Boolean, Int32) (at Assets/Scripts/Bim-Library/Scripts/Xbim/Common/Xbim.IO/Esent/PersistedEntityInstanceCache.cs:736)
Xbim.IO.Esent.EsentModel:CreateFrom(String, String, ReportProgressDelegate, Boolean, Boolean, Nullable`1) (at Assets/Scripts/Bim-Library/Scripts/Xbim/Common/Xbim.IO/Esent/EsentModel.cs:446)
Xbim.Ifc.IfcStore:Open(String, XbimEditorCredentials, Nullable`1, ReportProgressDelegate, XbimDBAccess, Int32) (at Assets/Scripts/Bim-Library/Scripts/Xbim/Common/Xbim.Ifc/IfcStore.cs:313)
```

All is fine with the MemoryModel so far. I try on 2 files of 1Mo and 103Mo, both are fine on MemoryModel but failed with ESENT. Any idea concerning this issue ?

I think it will be something related to Unity once again but just in case I prefer to ask you, if it sounds familiar :/

**Comment by SteveLockley** [comment]
Do you have very long path names to the file you are creating as the esent db?

**Comment by liszto** [comment]
I don't think the path is too long but there is special character like "é" ignored by the Path.GetTempPath() so my final path is : 
**C:\Users\AURLIE~1\AppData\Local\Temp\Xbim.4487f519-1f54-47fd-87f0-4c03b089f211**

I removed the configmanager calls from the 
`GetXbimTempDirectory()` 
cause it didn't work on Unity Engine (it seems) so it will use the temp folder which is fine for us.

**Comment by liszto** [comment]
In my last post, I see this : 
"+{0}\0{1}\0{2}\0\0"
from your side what did you expect as result from this line ?

Cause in the `var labelIndexDef` the value is "+IfcType" without the {1} and the {2}. 
I think you expect this "+IfcType\0SecondaryKey\0EntityLabel\0\0" right ?

**Comment by liszto** [comment]
Ok I pushed further my test and I succeeded to at least make progress the 
`IfcStore.Open()`
to the full progress bar (100%) and after it seems to freeze...

Basically I replaced JetCreateIndex with JetCreateIndex2 and this one avoid the Illegal Index Definition.
For example these lines in EsentEntityCursor (and every other ...Cursor classes) : 

`Api.JetCreateIndex(sesid, tableid, entityTableLabelIndex, CreateIndexGrbit.IndexPrimary, labelIndexDef, labelIndexDef.Length, 100);`

are replaced by : 

```
JET_INDEXCREATE[] jET_INDEXCREATs = new JET_INDEXCREATE[1];
jET_INDEXCREATs[0] = new JET_INDEXCREATE();
jET_INDEXCREATs[0].grbit = CreateIndexGrbit.IndexPrimary;
jET_INDEXCREATs[0].szKey = labelIndexDef;
jET_INDEXCREATs[0].cbKey = labelIndexDef.Length;
jET_INDEXCREATs[0].szIndexName = entityTableLabelIndex;
jET_INDEXCREATs[0].ulDensity = 100;
Api.JetCreateIndex2(sesid, tableid, jET_INDEXCREATs, jET_INDEXCREATs.Length);
```

Now I will try to fix the final loading part that them to freeze, but if you have any idea of why the "JetCreateIndex2" is working and not "JetCreateIndex" it will be a pleasure to hear why ? 👍

**Comment by liszto** [comment]
Still on the database issue, I can't understand why the PersistedEntityInstanceCache is empty whereas when I look at the database file generated in temp seems to have all the informations needed.
I know it's a binary one but I can see some clear information like the bim file used to generate it, property field etc...

I'm still using the CreateIndex2 cause CreateIndex still return Illegal Index Definition :/

Any ideas ?

**Comment by liszto** [comment]
Another update, if someone as information. Cause the value that create the exception are : 

```
sesid : JET_SESID(0x5c5e09a0)
tableid : JET_TABLEID(0x612b3020)
indexName : EntByLabel
grbit : IndexPrimary
keyDescription : +IfcType\0SecondaryKey\0EntityLabel\0\0
keyDescriptionLength : 35
density : 100
```

Result from the JET_Err : Illegal index definition => Microsoft.Isam.Esent.Interop.EsentIndexInvalidDefException: Illegal index definition

in the following code part :  

```
//Now create a table for the indexed properties
using (var transaction = new Transaction(sesid))
{
```

**Comment by liszto** [comment]
Quick edit, I found at least one issue in the mono/unity engine with Marshalling, I don't know if this issue is related with my database creation trouble but it happens on the same line than my "JetCreateIndex"
related issue in Unity that I created and validated by their QA team : 
https://issuetracker.unity3d.com/issues/strings-are-not-fully-read-when-slash-0-null-character-is-used

**Comment by tiemin** [comment]
Thank you for your posting.

I'm trying to build EDBViewer on CentOS.
I have troubleshoot to build ESENT.dll
Let me know the version of mono, wine, ESENT, EsentInterop.dll.

Would you share video that building it step by step?

Regards.

**Comment by andyward** [comment]
My understanding is that liszto is building on Unity on Mono on Windows so unlikely to help on CentOS

Esent is native unmanaged DLL on all Windows machines, provided as standard by Microsoft. It's the same database tech used by Microsoft Exchange, which I'd guess you're interested in it for EDBViewer

I'm no great expert on wine or Linux/Windows interop, but I can't see how you'd get this working under CentOS. 

EsentInterop.dll is just a set of P/invoke wrappers to marshal between the managed .net and unmanaged x86/x64 code.  We use the latest 1.9.4 from https://www.nuget.org/packages/ManagedEsent/ and https://github.com/Microsoft/ManagedEsent

**Comment by tiemin** [comment]
**Andyward, Thank you for your posting.**

- I was confused with Unity on Linux.
- I realized it is impossible to run ESENT.dll on Linux machine.
- My trouble is I don't know the EDB file structure. EDB file structure is private for last version.

**Comment by liszto** [comment]
I need to recheck this asap. I try to do this, this morning !

**Comment by liszto** [comment]
I tried to open an ifc file with a 100Mo size with the dll from xBim 5.0 it seems to work.
I tried with a threshold ultra low something like 1 and opened any other ifc files and it seems to work too.

**Comment by andyward** [comment]
Great! Assuming you using the Xbim.Essentials package? Worth noting that depending on the environment, the 100MB threshold may be ignored in v5 - it only kicks in when XBIM.IO.Esent is available.

So just to verify this before we close, because `IfcStore` now dynamically uses different model strategies it might be worth forcing it to use the Esent model by adding `IfcStore.ModelProviderFactory.UseEsentModelProvider();` when you start the program. 

(Normally I'd recommend IfcStore.ModelProviderFactory.UseHeuristicModelProvider(); which provides the v4 behaviour and switching at 100MB)

**Comment by liszto** [comment]
Ok I'll try this and I will update as soon as I have a result

**Comment by andyward** [comment]
That'll be because Xbim.IO.Esent is not referenced. I suspect that's 'by design' as XBIM.IO.Esent is only compatible with net47 targets. It'll be skipped in netstandard based environments.

So I guess that's 'case closed' for now. It works, but you're using the MemoryModel for all operations under Unity (regardless of model size). Obviously that may have performance / resource issues in larger models, especially as you can't persist to an XBIM format

I think we've got another ticket open to look at other persistent stores for IModels:  #59

**Comment by liszto** [comment]
Just to add a final note to this ticket : 
Using `UseEsentModelProvider` still trigger the issue even with last xBim revision which is logical cause the issue cas coming from ESENT himself with unity/mono environment.

Otherwise it works well :) 

Thansk again @andyward  !
