### ISSUE TITLE
Xbim.Tessellator bugfix proposal

### ISSUE THREAD

**Issue by Scarmentado** [xBimTeam/XbimEssentials#193]
#### Expected behavior:

[Imgur](https://i.imgur.com/JvrAOMU.jpg)

#### Actual behavior or exception details:

[Imgur](https://i.imgur.com/PkkKtBC.jpg)

#### Versions of xBIM Packages:

- xBIM Essentials: 4.0.1807.31494

#### Minimal code (or steps) to reproduce the issue:

Load joined IFC file into Xbim Explorer.

#### Minimal file to reproduce the issue:

[prbec.zip](https://github.com/xBimTeam/XbimEssentials/files/2245802/prbec.zip)

------- More Explanations -------
Hello Xbim Team,

In the Xbim.Tesselator Component, XbimTessellator.cs file, MeshPolyhedronBinary Method.
The verticesCount variable is initialized like that:
`uint verticesCount = (uint)triangulation.Coordinates.CoordList.Count();`

It's seems ok in `ìf` statement ("we have normals..." case) but in the `else` statement, the var is not updated to `triangulatedMesh.VertexCount` and during `WriteIndex` calls, we pass a bad verticesCount value and in some cases, the index is encoded on two bytes rather than four. And the tessellation is wrong. The `ReadShapeTriangulation` extension method is not be able to read the binary.

My correction:
[Imgur](https://i.imgur.com/uFStneo.jpg)

In advance thank you ! 

Marc

**Comment by martin1cerny** [comment]
Can you submit a pull request? Putting your fix in would be a great contribution and much appreciated.

**Comment by Scarmentado** [comment]
I wanted ... :)
I can't push directly on develop branch, and I have not any fork. What is the best way to transmit you my pull request ?
I m not really aware about Github.

**Comment by martin1cerny** [comment]
Please, see the documentation here: https://help.github.com/articles/creating-a-pull-request/

**Comment by Scarmentado** [comment]
It's ok.
Thank you
