### ISSUE TITLE
about writexml

### ISSUE THREAD

**Issue by Febfire** [xBimTeam/XbimEssentials#197]
If i convert ifc to xml by this https://github.com/xBimTeam/XbimEssentials/blob/master/Profiling.WritingXml/Program.cs#L31
Does this xml file contains properties,geometry and decomposition tree informations?
Or just properties?

**Comment by Febfire** [comment]
And I have anothor question.
When i pass JsonWriter as a writer to XbimXmlWriter4,like this
"public void Write(IModel  model, JSONWritter output, IEnumerable<IPersistEntity> entities = null)".
I got some errors at 
![menu saveimg savepath20180816114907](https://user-images.githubusercontent.com/37166494/44186174-79ec9600-a14a-11e8-9485-0015175f5d4b.jpg)
What should i do?
forgive my stupid.
thanks in advance.

**Comment by martin1cerny** [comment]
This will save complete model as IFCXML.

**Comment by martin1cerny** [comment]
As you can see the code is for XML so it will not work for JSON.
