### ISSUE TITLE
Long-running transations reaching the maximum database file when open large IFC files

### ISSUE THREAD

**Issue by adam9000** [xBimTeam/XbimEssentials#199]
Hi! First of all, thank you very much for this amazing framework!

Can I change the size of the ESENT database?

When I try to open a large IFC file (1 GB), I'm getting this error:

Xbim.Exchange (6028) XbimInstance5871a89c-14b6-4868-ba00-6d3b8fc78335: The version store for this instance (0) has reached its maximum size of 255Mb. It is likely that a long-running transaction is preventing cleanup of the version store and causing it to build up in size. Updates will be rejected until the long-running transaction has been completely committed or rolled back. 
Possible long-running transaction: 
	SessionId: 0x000000001A720B60 
	Session-context: 0x0000000000000000 
	Session-context ThreadId: 0x0000000000000000 
	Cleanup: 1

Thank you in advance.

**Comment by martin1cerny** [comment]
Database is flushing the content itself. It is more likely there is some monstrous object in the data which makes the database to fail. Something like a triangulated geometry with millions of triangles. Is that possible?

**Comment by adam9000** [comment]
Thanks Martin...

I do know that large IFC files probably will produce a large amount of work to get the geometry done.

But unfortunately I can't restrict, or control, the size of the real world user's projects...

My question is if there is a way to customize the database size, so this excellent framework can meet this kind of scenario.

Seams to me that ESENT databases limits are established by who's using it. If so, maybe a property in future releases can expose this type of customizations, likewise we can found in the ModelFactors class.

And, sorry man, I posting this question here only after research the entire issues in all the xBim projects, search the code, googling, etc... trying figure it out the problem.

**Comment by martin1cerny** [comment]
I understand your need to solve this and I appreciate you invested your time to resolve it yourself first. I don't have resources to work on this issue in my spare time so I'll try to point you to places where you might find a solution:

1. You can have a look at [ESENT System Parameters](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.IO/Esent/PersistedEntityInstanceCache.cs#L47) to see if you can configure the database to handle your file.
2. You can try to lower [TransactionBatchSize](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.IO/Esent/XbimReadWriteTransaction.cs#L22) which is 100 entities by default. This is used when loading data from the file into the database.

Please, let me know if you manage to process the file.

**Comment by adam9000** [comment]
Thank you so much Martin.

I'll update you ASAP.

**Comment by adam9000** [comment]
Hi Martin

Now I can convert some large files, so today was a very good day!

(I pull a request to fix another problem with JSON conversion on the XbimExchange project)

But, back to current subject, [the correct place to deal with this problem is here](https://github.com/xBimTeam/XbimEssentials/blob/develop/Xbim.IO/Esent/PersistedEntityInstanceCache.cs#L591).

Just for starters, I double the value...

`...
jetInstance.Parameters.MaxVerPages = 4096*4;
...
`

...and one of my big IFC files can be converted!

I'll test the gigantic one overnight. Tomorrow we see the results...

**Comment by adam9000** [comment]
Hi Martin

Playing with MaxVerPages makes the magic.

I have the performance reports of the ESENT usage for the gigantic file conversion. If you want them, I can attach in here later.

Thanks for the help.

**Comment by martin1cerny** [comment]
You are welcome.
