### ISSUE TITLE
Problem in getting quantities

### ISSUE THREAD

**Issue by PMiraLopes** [xBimTeam/XbimEssentials#2]
Hi guys I'm a begginner user of the xBim project, and I'm trying to create a BIM explorer interface, the problem that I'm currently facing is that I can get all IFC products and quantities, butI don't know how to related them. For example, for a wall I want to get what are its quantities. 

I was reading and testing the code provided in the documentation section, but it seems to be out of date, and some function do not exist anymore. So how can I get the quantities related with some IFC product?

Sorry for posting here.

Thanks!

**Comment by CBenghi** [comment]
Hi Pedro,
sorry for the long delay, I'm afraid your question went unnoticed.
You generally look at relationships to identify associations.
For instance a wall will have a list of propertysets associated to it via its IsDefinedBy (inverse) property.
I'm happy to help you extract them if you are still interested.
Drop another line here if you are.
Best,
Claudio
