### ISSUE TITLE
Methods to rotate Model in the 3D Viewer

### ISSUE THREAD

**Issue by GLFichera** [xBimTeam/XbimEssentials#201]
Hi everybody. Sorry if maybe this isn't the right section. I would ask if there are several methods to rotate the model in the 3D Viewer without use the mouse right click. Thanks.

**Comment by liszto** [comment]
I think it would be better on that repository : 
https://github.com/xBimTeam/XbimWindowsUI

The only other way that I know is to use your keyboard with left and right arrow
