### ISSUE TITLE
Segmented Load

### ISSUE THREAD

**Issue by YauronBis** [xBimTeam/XbimEssentials#203]
#### Expected behavior:
Partially load an IFC file by selecting the scope from a perimeter value.

#### Actual behavior or exception details:
Loading an IFC file means loading every entity. If the file is really big, it take long time, juste to get back Site's Address

#### Versions of xBIM Packages:
Every one

### Kind of prototype
`
<Flags>
public enum ePerimeters
   Site
   Units
   Locations
   Materials
   BuildingElements
   PropertySets
   Geometrics
end enum
...
sub main()
   _model = IfcStore.Open(Path:= ..., Perimeter = ePerimeters.Locations)
end sub
`

**Comment by martin1cerny** [comment]
`IfcStore` can open the model in-memory or using local database with pre-processed data. The default threshold is 50MB. So, if your file is >50MB and you didn't specify in-memory mode explicitly it should open it as a local DB where data is not cached. With local DB (Esent) it only loads the data you as for into memory. Can you post a proper code example which could be repeated please?

**Comment by martin1cerny** [comment]
This is possible now just using negated logic. You can pass a list of types you want to ignore to the model:

```cs
var readTypes = new[] {
    typeof(IIfcSite),
    typeof(IIfcPostalAddress)
};
var ignoreTypes = typeof(EntityFactoryIfc4)
    .Assembly.GetTypes()
    .Where(t => t.IsClass && t.IsPublic && !t.IsAbstract && !readTypes.Any(rt => rt.IsAssignableFrom(t)))
    .Select(t => t.Name.ToUpperInvariant())
    .ToArray();

var model = MemoryModel.OpenReadStep21(file, ilog, progDel, ignoreTypes);
var site = model.Instances.FirstOrDefault<IIfcSite>();
var address = site.SiteAddress;
```

This will still scan through a complete model but will skip everything except for the site and address so it will be quite fast.
