### ISSUE TITLE
Exception "...is not a valid IFC file format, ifc, ifcxml, ifczip and xBIM are supported." while opening an ifcXML file

### ISSUE THREAD

**Issue by klacol** [xBimTeam/XbimEssentials#204]
At this repo we collect sample to deveop an format for transporting product data with IFC:

https://github.com/buildingSMART/ProductData

I tried to open this file with Xbim Essentials:

https://github.com/buildingSMART/ProductData/blob/master/IFC4%20Library/IkeaKitchenCabinets.ifcXML

#### Expected behavior:
The file can be opened without exception

#### Actual behavior or exception details:
I get this exception

`System.IO.FileLoadException: "C:\Temp\IkeaKitchenCabinets.ifcxml is not a valid IFC file format, ifc, ifcxml, ifczip and xBIM are supported."
`

#### Versions of xBIM Packages:
4.0.29

#### Minimal code (or steps) to reproduce the issue:
```cs
using (var xmlModel = IfcStore.Open(fileName))
            {
            }
```

**Comment by martin1cerny** [comment]
IFC4 Addendum2 is not yet pushed to `master` branch. If you use the `develop` branch it will work. We are just about to push `develop` to `master` but it I'm waiting for @CBenghi to finish some work before. You can get current develop NuGet packages from MyGet package sources listed [here](http://docs.xbim.net/) (bottom of the page). Develop is very stable and is usable in production environments in its current state.

**Comment by klacol** [comment]
Ok, Thanks, that workes like a charm. I can open some files, and for other I get errors, which are related to the schema. I will post them in separate issues.
