### ISSUE TITLE
Error, when opening an ifcXML file: "IsTypedBy is not an IPersistEntity type"

### ISSUE THREAD

**Issue by klacol** [xBimTeam/XbimEssentials#205]
At this repo we collect sample to develop a format for transporting product data with IFC:
https://github.com/buildingSMART/ProductData

I tried to open this file with Xbim Essentials:
https://github.com/buildingSMART/ProductData/blob/master/IFC4%20Library/IkeaKitchenCabinets.ifcXML

Expected behavior:
The file can be opened without exception

Actual behavior or exception details:
I get this exception

`ERROR - IsTypedBy is not an IPersistEntity type`

Versions of xBIM Packages:
Xbim.Essentials 4.0.30-V024

Minimal code (or steps) to reproduce the issue:

`using (var xmlModel = IfcStore.Open(fileName)) {   }`

The attribute `IsTypedBy` should be ok IMHO:
http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcsystemfurnitureelement.htm

> IsTypedBy (Type: IfcRelDefinesByType@RelatedObjects), S[0:1],  Set of relationships to the object type that provides the type definitions for this object occurrence. The then associated IfcTypeObject, or its subtypes, contains the specific information (or type, or style), that is common to all instances of IfcObject, or its subtypes, referring to the same type.IFC4 CHANGE  New inverse relationship, the link to IfcRelDefinesByType had previously be included in the inverse relationship IfcRelDefines. Change made with upward compatibility for file based exchange.

Version of IFC:
IFC4 Add2

**Comment by klacol** [comment]
Ok, works like a charm with "Xbim.Essentials.4.0.30-V030". Thanks.

Yes, the usage of ifcXML is not very widespread in the IFC community, but as it is one of the allowed formats, we could try to support and use it. Especially in the situations, where it can be used quite well, e.g. in purely data orientend information exchange, without geometry.

In other sample files, there are two more of such messages. 

[bSDD product room sample.ifcXML](https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/bSDD%20product%20room%20sample/bSDD%20product%20room%20sample.ifcXML)
[EN1304 clay roofing tiles and fittings.ifcxml](https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/EN1304%20clay%20roofing%20tiles%20and%20fittings/EN1304%20clay%20roofing%20tiles%20and%20fittings/EN1304%20clay%20roofing%20tiles%20and%20fittings.ifcxml)
[Fireray 50100RV Linear Smoke Detectors.ifcXML](https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/Fireray%2050100RV%20Linear%20Smoke%20Detectors/Fireray%2050100RV%20Linear%20Smoke%20Detectors.ifcXML)

> IfcPropertySetTemplate is not assignable to IfcRelDefinesByProperties.RelatedObjects

   
[bricks catalogue sample including request.ifcXML](https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/HC%20(Italy)/Bricks%20Catalogue/bricks%20catalogue%20sample%20including%20request.ifcXML)
[bricks catalogue sample.ifcXML](https://github.com/buildingSMART/ProductData/blob/master/SampleFiles/HC%20(Italy)/Bricks%20Catalogue/bricks%20catalogue%20sample.ifcXML)

> IfcTypeProduct is not assignable to IfcMetric.DataValue

**Comment by martin1cerny** [comment]
> IfcPropertySetTemplate is not assignable to IfcRelDefinesByProperties.RelatedObjects

This is correct. `IfcRelDefinesByProperties.RelatedObjects` can only contain [IfcObjectDefinition](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcreldefinesbyproperties.htm). And `IfcPropertySetTemplate` **is not** `IfcObjectDefinition`.

> IfcTypeProduct is not assignable to IfcMetric.DataValue

`IfcMetric.DataValue` has to be `IfcMetricValueSelect`. And `IfcTypeProduct` is **not in** `IfcMetricValueSelect`. So, this assignment is also illegal.

**Comment by martin1cerny** [comment]
I'm actually surprised if those pass the XSD validation test.

**Comment by klacol** [comment]
ok, this can be closed, Thanks
