### ISSUE TITLE
Clean JFM temp file on model close

### ISSUE THREAD

**Issue by sladerster** [xBimTeam/XbimEssentials#206]
#### Expected behavior:
After opening ifc model with ifcDatabaseSizeThreshHold set, system is creating temporary file in %temp%, but when I dispose IfcStore, I expect that this file must be deleted. But temp file is left in temp dir.

#### Actual behavior or exception details:
Temporary file is left in %temp% folder.

#### Versions of xBIM Packages:
4.0.29

#### Minimal code (or steps) to reproduce the issue:
var ifcFileName1 = @"d:\IFC\Building1.ifc";
using (var model = IfcStore.Open(ifcFileName1, ifcDatabaseSizeThreshHold: 0.1))
{
    model.Close();
}

#### Minimal file to reproduce the issue:
[Building1.zip](https://github.com/xBimTeam/XbimEssentials/files/2388428/Building1.zip)

**Comment by andyward** [comment]
OK. I think the bigger issue of XBIM files being left undeleted has been fixed for a while. I definitely confirmed it OK when working on IfcStore recently. 

What i did discover is that Esent has c
