### ISSUE TITLE
Error while converting IFC to WexBIM file

### ISSUE THREAD

**Issue by fouziyapatel** [xBimTeam/XbimEssentials#212]
Hello,

IfcStore openModel = IfcStore.Open(fileName);

Above stated line returns null i.e. openModel = null 

#### Exception details:

> 
> Too many errors in file, parser execution terminated
> 
> Xbim.IO 
> 
>  at Xbim.IO.Step21.XbimP21Parser.TrySetObjectValue(IPersist host, Int32 paramIndex, Int32 refId, Int32[] listNextLevel) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\XbimP21Parser.cs:line 413
>    at Xbim.IO.Step21.XbimP21Parser.SetObjectValue(String value) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\XbimP21Parser.cs:line 278
>    at QUT.Gppg.ShiftReduceParser`2.Reduce(Int32 ruleNumber) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:line 332
>    at QUT.Gppg.ShiftReduceParser`2.Parse() in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:line 263
>    at Xbim.IO.Memory.MemoryModel.LoadStep21(Stream stream, Int64 streamSize, ReportProgressDelegate progDelegate) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:line 536
>    at Xbim.IO.Memory.MemoryModel.LoadStep21(String file, ReportProgressDelegate progDelegate) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:line 550
>    at Xbim.Ifc.IfcStore.Open(String path, XbimEditorCredentials editorDetails, Nullable`1 ifcDatabaseSizeThreshHold, ReportProgressDelegate progDelegate, XbimDBAccess accessMode) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.Ifc\IfcStore.cs:line 362
>    at ePMBeta.Logics.ModelConverter.GetModel(String fileName) in D:\DemoProject\ePMBeta\ePMBeta\ePMBeta\Logics\ModelConverter.cs:line 97
> 

Please suggest the possible solution by which I can fix this error and generate Wexbim file successfully.

**Comment by fouziyapatel** [comment]
Hello @martin1cerny,
Thanks for the prompt reply.

**Comment by martin1cerny** [comment]
Can I close this now?

**Comment by martin1cerny** [comment]
Can I close this now?
