### ISSUE TITLE
IfcStore. Open error for Revit IFC4 file

### ISSUE THREAD

**Issue by frvicent** [xBimTeam/XbimEssentials#219]
#### Expected behavior:
Save file as WexBim from IFC4 file from Revit 2019

#### Actual behavior or exception details:
   en Xbim.IO.Memory.MemoryModel.<>c__DisplayClass68_0.<LoadStep21>b__0(String name, Nullable`1 label, Boolean header, Int32[]& ints) en C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:línea 513
   en Xbim.IO.Step21.XbimP21Parser.SetType(String entityTypeName) en C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\XbimP21Parser.cs:línea 196
   en Xbim.IO.Parser.P21Parser.DoAction(Int32 action) en C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\StepP21Parser.y:línea 137
   en QUT.Gppg.ShiftReduceParser`2.Reduce(Int32 ruleNumber) en C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:línea 330
   en QUT.Gppg.ShiftReduceParser`2.Parse() en C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:línea 263
   en Xbim.IO.Memory.MemoryModel.LoadStep21(Stream stream, Int64 streamSize, ReportProgressDelegate progDelegate) en C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:línea 535
   en Xbim.IO.Memory.MemoryModel.LoadStep21(String file, ReportProgressDelegate progDelegate) en C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:línea 550
   en Xbim.Ifc.IfcStore.Open(String path, XbimEditorCredentials editorDetails, Nullable`1 ifcDatabaseSizeThreshHold, ReportProgressDelegate progDelegate, XbimDBAccess accessMode) en C:\BuildAgent\work\77d7b8e93613846d\Xbim.Ifc\IfcStore.cs:línea 362

#### Versions of xBIM Packages:
Xbim.Essentials 4.0.29

#### Minimal code (or steps) to reproduce the issue:
```cs
const string fileName = "myFile.ifc";
            using (var model = IfcStore.Open(fileName))
            {
                //var context = new Xbim3DModelContext(model);
                //context.CreateContext();
                var wexBimFilename = Path.ChangeExtension(fileName, "wexBIM");
                using (var wexBiMfile = new FileStream(wexBimFilename, FileMode.Create))
                {
                    using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
                    {
                        model.SaveAsWexBim(wexBimBinaryWriter);
                        wexBimBinaryWriter.Flush();
                        wexBimBinaryWriter.Close();
                    }
                    wexBiMfile.Close();
                }


```

#### Minimal file to reproduce the issue:
*(IFC files need to be zipped to be uploaded. Than just drag & drop here)*
![error](https://user-images.githubusercontent.com/45031354/48475066-44fce780-e7fc-11e8-8c2e-5f39628b9f10.PNG)

**Comment by andyward** [comment]
Can you provide the IFC file you're using ('myFile.ifc')?

**Comment by frvicent** [comment]
I've found the  same issue in XbimGeometry 
https://github.com/xBimTeam/XbimGeometry/issues/134
So, I'll close this because the incidence has already been treated
Thanks for your attention anyway.
