### ISSUE TITLE
There was no argument keepLabels to method InsertCopy

### ISSUE THREAD

**Issue by kozintsev** [xBimTeam/XbimEssentials#22]
I found a bug in file (developer version):

D:\GitHub\XbimEssentials\Xbim.IO\Esent\EsentModel.cs line 1032:

It was:

        public T InsertCopy<T>(T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, bool includeInverses, bool keepLabels) where T : IPersistEntity
        {
            var txn = CurrentTransaction as XbimReadWriteTransaction;
            return Cache.InsertCopy(toCopy, mappings, txn, includeInverses, propTransform);
        }

Necessary:

        public T InsertCopy<T>(T toCopy, XbimInstanceHandleMap mappings, PropertyTranformDelegate propTransform, bool includeInverses, bool keepLabels) where T : IPersistEntity
        {
            var txn = CurrentTransaction as XbimReadWriteTransaction;
            return Cache.InsertCopy(toCopy, mappings, txn, includeInverses, propTransform, keepLabels);
        }

**Comment by martin1cerny** [comment]
Thanks for spotting this. I've fixed this in the code now.
