### ISSUE TITLE
[QUESTION] When the master will be stable enough to be pulled

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#221]
Hello guys ! 
First of all really good job for this HUGE update of xBim. I think it's a really good step forward with all the stuff you bring in like own dev logger / improve parser / drop ESENT announcement ( in future) / etc...

So my question is in the title but is it safe to use the current master state or do we need to wait a lil more ?

**Comment by martin1cerny** [comment]
Everything if little bit flying in the air as you have noticed these days. Once on the job we want to do more tidying up and need to bring xBIM Geometry up to speed with these changes as well to the two core projects are up to date at least. So, I'd say it should be stable enough in about two weeks time. Once stable we will push to NuGet. That is when you can consider it stable I'd say.

**Comment by liszto** [comment]
Ok, good to know ! 
Currently I'm using only Essentials due to Geometry issue (in unity) will see how it goes after your update so.
I stay in touch and I can close this topic I think.

Thanks again !
