### ISSUE TITLE
wexBIM not correctly generated

### ISSUE THREAD

**Issue by frvicent** [xBimTeam/XbimEssentials#222]
When I try to save SampleHouse4.ifc as wexBIM file, the size of file is only 1Kb with apparently any information.
Any error throw, but the file seems to have no information.
Any way to get wexBIM file with IFC 4 files?

Xbim.Ifc 5.0.0.0

```csharp
            using (var m = IfcStore.Open("SampleHouse4.ifc", null, -1))
            {
                using (var bw = new BinaryWriter(new FileStream("SampleHouse4.wexBIM", FileMode.Create)))
                {
                    m.SaveAsWexBim(bw);
                    bw.Close();



                }

            }
```

![wexbim](https://user-images.githubusercontent.com/45031354/49165036-9c3ca500-f330-11e8-96c9-29ab82d95620.PNG)

[SampleHouse4.zip](https://github.com/xBimTeam/XbimEssentials/files/2625681/SampleHouse4.zip)

**Comment by martin1cerny** [comment]
You have to [process the geometry first](https://github.com/xBimTeam/XbimSamples/blob/master/CreateWexBIM/Program.cs#L32).
