### ISSUE TITLE
[ISSUE] SaveAs doesn't set "FileName" in IfcStore as Open does.

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#223]
Hello,

When you open an "ifc" file with "ifcstore.Open()" it sets the FileName value. 
But when you save it with the "SaveAs(string sFileName)" method, it will not immediatly set the FileName variable is it intended or is it just smoething missing ?

Cause right after if we need to do a store.FileName its value is null and we have to set it manually.

**Expected behaviour** : 
Automatically set the FileName with the path gave to "SaveAs" method. It could be really useful when you create your own IfcStore not based on a file but by code.

**Comment by martin1cerny** [comment]
You are right, we should set it there. Can you submit a PR?

**Comment by liszto** [comment]
Yep I will asap !

**Comment by liszto** [comment]
My PR is here #224

**Comment by martin1cerny** [comment]
Resolved in PR from @liszto.
