### ISSUE TITLE
Avoid huge dll packing 

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimEssentials#235]
Hello,
Is there a way to remove some dll dependancies that are totally pointless for some project like the ASP.Net dependancies generated by ILogger.
But for me there is something like 75% of ".dll" in the dependancies which could be ignore because it is already .NET/C# native libraries embedded in our project by default. 
But if I didn't include them in my Unity project, I will have a lot of references errors (which is logic) in the main dll generated by your xBim project.

In the v4.X it was dependancy-free (except on some special dll like ICSharpZip, etc...)

If you have any hint to clean (it would be great)

**Comment by andyward** [comment]
Can you show what you mean? There shouldn't be any ASP.NET dependencies. There will be some transitive dependencies brought in through Microsoft.Extensions.Logging.dll, relating to DI and Configuration, but I don't think we can remove those and have an out the box logging experience.

Does Unit support the new SDK style projects - that really cleans up the dependency management if you can use that project format

**Comment by martin1cerny** [comment]
If you mix old package management with new projects there is a large number of very small system proxy dlls.

**Comment by liszto** [comment]
When Unity engine compile the script (and process dll file include into the project) it returns this : 

```
Assembly 'Assets/Plugins/Bim-Library/Scripts/Xbim/Common/Xbim.Common.dll' will not be loaded due to errors:
Unable to resolve reference 'Microsoft.Extensions.Logging.Abstractions'. Is the assembly missing or incompatible with the current platform?
Unable to resolve reference 'Microsoft.Extensions.Logging'. Is the assembly missing or incompatible with the current platform?
```

I built the "*.dll" directly through your Xbim.Essentials.sln and choose release target.

So I can include this particular dll but after I include it, it will ask me another and another... But maybe it's intended ?

**Comment by martin1cerny** [comment]
That is certainly not intended. We are sure it all works in Visual Studio and/or dotnet CLI tooling. 

`Microsoft.Extensions.Logging.Abstractions` and `Microsoft.Extensions.Logging` are the only two dependencies of `Xbim.Common.dll`. I wonder if Unity can deal with the [new *.csproj format](https://github.com/dotnet/project-system). It uses different syntax to express dependencies.

**Comment by martin1cerny** [comment]
Also, xBIM is now multitargeting .NET Standard 2.0 and .NET 4.7. You might want to check which one is better for Unity.

**Comment by liszto** [comment]
Unity uses its own compiler system based on mono so I don't really know what they do behind.
To work with Unity project, we use Visual Studio Community 2017 (as you do) cause Unity generates csproj to work with it. But internally I'm not sure they do this.

I can try to use your source file and embed them directly in my project (as I did before). 
Embed the dll file was a test to skip some unecessary compilation time in Unity by using directly your assemblies.

When I work with Unity, I can choose the "netstandard 2.0" or ".NET 4.x" target cause Unity target this one now. Basically just because we wanna cover crossplatform with a light build we most of time target "netstandard 2.0".

**Comment by liszto** [comment]
@martin1cerny that is that kind of syntax that you called new csproj format : 

```
<Reference Include="System.IO.Compression">
      <HintPath>C:/Program Files/Unity/Hub/Editor/2018.3.0f2/Editor/Data/NetStandard/compat/2.0.0/shims/netstandard/System.IO.Compression.dll</HintPath>
    </Reference>
```

**Comment by andyward** [comment]
Sorry I'm not that familiar with the Unity environment, but I thought it used standard VS csproj project files. If that's the case just using Nuget should bring in all the dependencies it needs, including any netstandard libs. My understanding is Unity is based on Mono, which now implements the netstandard2.0 contracts.

The new syntax ('SDK' format) csprojs are like this: 

https://github.com/xBimTeam/XbimUtilities/blob/aaef437b95583d0b53fc4cb46837b7a5e157a5da/XbimConvert/XbimConvert.csproj

vs the old format (MSBuild format):

https://github.com/xBimTeam/XbimUtilities/blob/8a3ec1a045365382770ac8d105d70e7b9aef81d2/XbimConvert/XbimConvert.csproj (+ packages.json)

You'll see the new format is much more succinct and only has direct dependencies, not the transitive dependencies included

**Comment by martin1cerny** [comment]
For your example, if you target .NET Core, this would be a regular NuGet package in the new csproj
```xml
<PackageReference Include="System.IO.Compression" Version="4.3.0" />
```

or if you target .NET framework it would be a plain reference:
```xml
<Reference Include="System.IO.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
```

**Comment by liszto** [comment]
From what I can see in unity csproj generated they still using the old monolitic csproj syntax :s

**Comment by liszto** [comment]
So the dll packing is compulsory in fact. 
Cause for example when I use Xbim.Common
it will need : 
Microsoft.Extensions.Logging.Abstractions
Microsoft.Extensions.Logging
and one of those need : 
Microsoft.Extensions.DependencyInjection.Abstractions
and this one need : 
Microsoft.Extensions.Options.dll
etc... etc... 

My basic question was this. It will be a long dependancy path from one dll to another.
But in your old xBim version it wasn't the case cause, it was working (at least in our project without all those dll).
Or maybe it was because you didn't call the ILogger interface but directly log4net instead ? 

Don't know if it's clear. My concern is this huge amount of dll dependancies induced by this ILogger (I think) which was inexistant prior 5.X version (or maybe I missed it).

**Comment by martin1cerny** [comment]
You are right, it wasn't there before. We introduce ILogger abstraction because it leaves the choice of specific logging framework on the application developer. Most common logging frameworks provide their implementations for `Microsoft.Extensions.Logging.Abstractions`. 

The long DLL chain is actually introduced because of `LoggerFactory` from `Microsoft.Extensions.Logging` package. The abstractions themselves are very lightweight and don't have other dependencies. @andyward , do you think we should review this dependency?

**Comment by liszto** [comment]
It's not really a problem for me (I just feared the assemblies' number) but when I get your 5.X version and I saw this linking chain i was "wooooh". But it's legit due to microsoft logger abstract class.

**Comment by andyward** [comment]
I think that's just the way .NET (along with most frameworks) is going - more smaller assemblies composed in an app.  

It's the Microsoft.Extentions.Logging package that introduces quite a lot of dependencies, especially on netfx. The main reason we need this is for the `LoggerFactory` in 
https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Common/XbimLogging.cs#L21

I guess we could implement our own ILoggerFactory implementation as a fall back but I'm not keen.

**Comment by liszto** [comment]
@andyward no it's not needed. And this ILogger could allow me to plug logger from Unity so it's not a bad thing.
Now I need to fgure out how to integrate this in Unity cause currently it seems to be in conflict with some method present in Microsoft Common Object Runtime Library (mscorlib) from mono. :/ 

EDIT : I found why this happens, I need to not include netstandard.dll.

EDIT 2 : I couldn't used the nuget package (implemented by a dev on a github)  for Unity. Cause during the download of all dependancies it takes a lot of useless stuff like each version of Cryptography for each platform (OSX, ubuntu, etc...)

**Comment by andyward** [comment]
OK. Can we close then?
