### ISSUE TITLE
[QUESTION]Any way to rotate an IfcPolyline?

### ISSUE THREAD

**Issue by Holgenberg** [xBimTeam/XbimEssentials#238]
I have managed to serialize the correct IfcCartesianPoints but in my data, an angle is included. Any way of rotating the Polyline along an axis?

**Comment by martin1cerny** [comment]
It depends on how you use the polyline. You will need to check IFC documentation to see how transformations work in IFC.


From: Holgenberg
Sent: 07 January 2019 17:38
To: xBimTeam/XbimEssentials
Cc: Subscribed
Subject: [xBimTeam/XbimEssentials] [QUESTION]Any way to rotate an IfcPolyline?(#238)

I have managed to serialize the correct IfcCartesianPoints but in my data, an angle is included. Any way of rotating the Polyline along an axis?

**Comment by Holgenberg** [comment]
Thanks, I've got it.
