### ISSUE TITLE
Slow performance Layer members

### ISSUE THREAD

**Issue by ehtick** [xBimTeam/XbimEssentials#239]
When trying to find the members in a layer it takes a very long time.

Download this model http://openifcmodel.cs.auckland.ac.nz/Model/Details/305

20160125WestRiverSide Hospital-Ifc2x3-Autodesk_Hospital_Sprinkle_2015.ifc

Layers = model.Instances.OfType<IIfcPresentationLayerAssignment>().ToList();

 foreach (var l in Layers)
                    {
                        if (l.AssignedItems != null && l.AssignedItems.Count() > 0)
                        {
                            foreach (var ai in l.AssignedItems)
                            {
                                IIfcShapeRepresentation srep = ai as IIfcShapeRepresentation;

                                if (srep != null)
                                {
                                    if (srep.OfProductRepresentation != null)
                                    {
                                        IIfcProductDefinitionShape prod = pp.Where(x => x.Representations.Contains(srep)).FirstOrDefault() as IIfcProductDefinitionShape;

                                        if (prod != null)
                                        {
                                            if (prod.ShapeOfProduct != null)
                                            {
                                                var sop = prod.ShapeOfProduct.First();
                                            }
                                        }
                                    }
                                }
                            }
                        }
Opening the model takes 6.8 seconds
get layers 0 seconds
iteration 48,5 seconds

This is i think because xbim uses IEnumerable<T> and using this in multiple loops leads to very bad performance, in my own code i create lists first for a lot off situations and this helps.
I think it would be better to add generated entities in the Instances and also add them to a local list.
This would make the looking up of items much faster.

Or is there a faster way?

Regards

Eddy

**Comment by andyward** [comment]
Hard to say as that code doesn't build. What are you iterating over (i.e. `Layers`)? What is `pp`?

It would also help to know what version of XBIM are you are on, and what IModel implementation you're using. This is potentially a case where Esent will outperform the MemoryModel.

**Comment by martin1cerny** [comment]
The best would be if you could post a compilable test code. As Andy said, this depends on many aspects. Keeping these `IEnumerables` in lists is not possible because these represent inverse relationships which are basically inverse lookups for bidirectional relations. See IFC documentation for more details about inverse relations. Considering these usually leads to a lot more performant code.

**Comment by andyward** [comment]
Closing - please re-open if you have a repro
