### ISSUE TITLE
[Question] Vertex normals of XbimTriangulatedMesh object.

### ISSUE THREAD

**Issue by RodionChachura** [xBimTeam/XbimEssentials#242]
Hello!

Is there any way to retrieve [vertex normal](https://en.wikipedia.org/wiki/Vertex_normal)s from [XbimTriangulatedMesh](https://github.com/xBimTeam/XbimEssentials/blob/f9562fc2bdd6f34ec667de70a3e4d19daa6986ef/Xbim.Tessellator/XbimTriangulatedMesh.cs) object?

I tied to find an answer in the source code but found only normals of triangles edges. Will appreciate any help.

**Comment by martin1cerny** [comment]
These are not normals of edges but normals of vertices you ask for.

**Comment by RodionChachura** [comment]
@martin1cerny, yes. I am searching for vertices normals but found only edges normals. Is there a way to obtain vertices normals?

**Comment by martin1cerny** [comment]
As I said, there is nothing like edge normal in `XbimTriangulatedMesh`. It only contains vertex normals. Just to be clear: Multiple vertices may use one point in the mesh. Indices are used to obtain all vertices from the point list. Every vertex has a normal. There is one normal per vertex per index. There might be multiple normals per point.

**Comment by martin1cerny** [comment]
OK, I can see your confusion now. What you think is the edge normal is actually normal of the first vertex of the edge.

**Comment by RodionChachura** [comment]
Each edge of a triangle face contains vertex normal. And since faces share the same vertices, we have **one or more normal per vertex**. Is there any way to have only **one normal per vertex**?

**Comment by martin1cerny** [comment]
No, because square would look like a sphere if all vertices referring to the same point had the same normal.

**Comment by RodionChachura** [comment]
Oh, thanks! Got it.
