### ISSUE TITLE
[Question] How to assign IfcAlignmentCurve to IfcAlignment?

### ISSUE THREAD

**Issue by cermitt** [xBimTeam/XbimEssentials#244]
Hi, I am working on a converter between a data format on infrastructure models to IFC on C#. I am trying to create a entity inheritance correctly. There is no problem to assign entities below. Somehow I could not assign IfcAlignmentCurve to IfcAlignment with existance properties on XBim. Has anyone ever worked on it?

```
**_#38=IFCALIGNMENT('id',$,$,'Alignment - (1)',$,#15,$,#39,$);_** (Expected)
#39=IFCALIGNMENTCURVE(#40,$,$);
#40=IFCALIGNMENT2DHORIZONTAL($,(#41,#43,#45,#47,#49,#51));
#41=IFCALIGNMENT2DHORIZONTALSEGMENT($,$,$,#42);
#42=IFCLINESEGMENT2D(#27,0.95405859805749416,12.715506959659196);
```

**Comment by martin1cerny** [comment]
Implementation in xBIM is based on the [final version of IfcAlignment](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/). In the latest (final) version the structure is different.

**Comment by cermitt** [comment]
Hi Martin,

Thank you for your quick response and the information. It works perfect now!

**Comment by martin1cerny** [comment]
Great! Closing the issue now.
