### ISSUE TITLE
Relation between ports of an IfcFlowFitting (Junction) and the properties

### ISSUE THREAD

**Issue by ossmoos** [xBimTeam/XbimEssentials#245]
I try to create a mesh of objects contained in the IFC file. The file mainly contains objects of type `IfcFlowSegment `and `IfcFlowFitting`. I can connect the objects by following the

` Ports >> RelatingPort >> ConnectedFrom >> RelatedPort >> ContainedIn >> RelatedElement` 

to it's contained RelatedElements. 

But I cannot create any relation between a Port and the properties on a singe fork of a junction (IfcFlowFitting) on the other side. 

My hope was that the index of the ports of an junction where generated always the same way. But unfortunately, the index are generated coincidentally.

Question:
Is there a way to determine which fork of an junction is connected to a pipe?

#### Assemblies and versions affected:

Version v4.0.30319

**Comment by martin1cerny** [comment]
Can you try to post a code sample representing your problem?

**Comment by ossmoos** [comment]
Thanks for the quick response! It's hard to explain it with existing code...

In the Xbim Xplorer I can see the ports of an junction:

![2019-01-24_15h39_27](https://user-images.githubusercontent.com/9989348/51685446-9db3e200-1fee-11e9-8b21-ae3535d6ff19.png)

How do you read the ports of an junction (in which order)? Do you use a pattern to set the index?

E.g.
![2019-01-24_15h45_45](https://user-images.githubusercontent.com/9989348/51685845-80334800-1fef-11e9-8d5d-2bcaf3edcee7.png)

OR
![2019-01-24_15h47_57](https://user-images.githubusercontent.com/9989348/51685854-84f7fc00-1fef-11e9-8bae-d5bdfd787f33.png)

OR 
![2019-01-24_15h48_21](https://user-images.githubusercontent.com/9989348/51685864-87f2ec80-1fef-11e9-8897-b4fee33f2ced.png)

Or is it done just by chance?

**Comment by martin1cerny** [comment]
This set of `IfcRelConnectsPortToElement` is not in any particular order. Your images represent a specific geometrical configuration but semantic connections are independent of the geometry. I'm still not quite sure what is your goal. If you try to express it in the code (or some kind of pseudo-code) it might become clearer.

**Comment by ossmoos** [comment]
OK, I try to explain it with pseudo-code. I refere to a property named "ConnectionType", but it could be any other property corresponding with a fork of a junction.

```csharp
using (var model = IfcStore.Open("file.ifc"))
{
    var pipes = model.Instances.OfType<IIfcFlowSegment>();

    foreach (IIfcFlowSegment pipe in pipes)
    {
        // Get the fitting that is connected to the current pipe (determined thru IfcRelConnectsPortToElement)
        IfcFlowFitting junction pipe.GetConnectedFitting();

        // The junction contains 3 properties, one for each fork of the junktion, read all of them.
        List<IIfcPropertySingleValue> properties = GetProperties(junction);

        Console.WriteLine("Connection type of the fork connected to the to " + pipe.ToString() + " is:");

        // I know the order of the ConnectionType-properties on the junction and on which fork they belong in the real world.
        // [Question]: How do I determine which property is corresponding with the connected fork?
        Console.WriteLine(properties["ConnectionTypeFork1].NominalValue.ToString());
        Console.WriteLine(properties["ConnectionTypeFork2].NominalValue.ToString());
        Console.WriteLine(properties["ConnectionTypeFork3].NominalValue.ToString());
    }
}
```

**Comment by martin1cerny** [comment]
If your data is structured in this way than it is not possible to relate the property of the junction to the pipe and it would be fault on the authoring SW side. May I ask what is the tool producing such a data? Can you share the sample file here?

The best way to structure this kind of data is this:

![connecteddistributionelements](https://user-images.githubusercontent.com/773078/51735048-94765400-2086-11e9-882f-90297797d883.png)

**Comment by ossmoos** [comment]
Thank you for your help so far!

This is the example IFC file generated by Autodesk Revit Version 2018. Have a closer look at the properties `'L'`, `'L1'`, `'Z'`, `'Z1'` and , `'Z2'`. These properties should be mapped to the corresponding Port.

For example, I know that `'L'` corresponds to Port A and B, `'L1'` corresponds with Port C. But how to determine which Port is A, B or C?

[Pipe-Junction example.zip](https://github.com/xBimTeam/XbimEssentials/files/2795363/Pipe-Junction.example.zip)

**Comment by martin1cerny** [comment]
Looking at the file I don't think this is possible to distinguish. My question would be: Is this autogenerated by Revit, or is it part of the parametric definition of the respective family?

I should also adjust my diagram as I realised there should be a port on both sides of the connection:

![connecteddistributionelements](https://user-images.githubusercontent.com/773078/51737983-567d2e00-208e-11e9-95da-2a1b85d3edc3.png)

**Comment by ossmoos** [comment]
Is there a way to determin to which fork a port is connected by analyzing the geometrical positions of the ports?

**Comment by martin1cerny** [comment]
Yes, in theory. But port doesn't have to have a position and/or geometry.

**Comment by ossmoos** [comment]
Do you have a hint where to start analyzing the geometrical dependncies? Would you do it with the XbimGemerty library?

**Comment by martin1cerny** [comment]
Closing as old question. Also, focus has moved to geometry analysis.
