### ISSUE TITLE
XML representations

### ISSUE THREAD

**Issue by Gonsco** [xBimTeam/XbimEssentials#248]
Question: I am comparing two IFC 4 files in XML format:

1) Generated with the Revit exporter (20170223_1515(x64) - Exporter 18.0.0.420 - Alternate UI 18.1.0.0)
2) Generated through the transformation of the same model exported in IFC STEP to XML using the XBIM lib (Xbim.Essentials.5.0.213). 

I used the default sample model provided in Revit 2018 (rac_basic_sample_project.rvt)

Even though both files can be validated (exceptuating a couple of very specific issues) against the same XSD, in this case http://www.buildingsmart-tech.org/ifc/IFC4/Add2/IFC4_ADD2.xsd, the resulting representation is very different.

In the second case (using XBIM library), and unlike the first one (using REVIT IFC exporter), the concepts appear in different depth levels. 

Apparently, this could hinders the development of parsers, especially those based on XPath.

Is there any reason to generate the XML files following this kind of structure using XBIM?

**Comment by martin1cerny** [comment]
As you said, both are valid IFC XML files. Any entity can be on any level of the hierarchy because there is no hierarchy in IFC schema. And because it is not a hierarchy but general object graph structure, references must be utilised in XML anyway. For that reason I wouldn't recommend using IFC XML + XPath for any job where reliability is required.

**Comment by Gonsco** [comment]
Parece que habrá que buscar alguna manera de re-formalizarlo, o buscar otro conversor que lo haga de la forma que nos interesa.



On Mon, Feb 11, 2019 at 4:36 PM Martin Černý <notifications@github.com<mailto:notifications@github.com>> wrote:

As you said, both are valid IFC XML files. Any entity can be on any level of the hierarchy because there is no hierarchy in IFC schema. And because it is not a hierarchy but general object graph structure, references must be utilised in XML anyway. For that reason I wouldn't recommend using IFC XML + XPath for any job where reliability is required.

**Comment by Gonsco** [comment]
Thanks Martin for the response!
I think that if one could choose, the first one seems easier to parse and, therefore, it would be a better option (even when the second representation is perfectly possible and legal). In my application case, unfortunately, I have no other option, but I understand that this is just my problem. Thanks anyway for this useful clarification.
