### ISSUE TITLE
StepModel.LoadStep21Header hangs, if it sis no IFC Content

### ISSUE THREAD

**Issue by BjDi** [xBimTeam/XbimEssentials#249]
f you call LoadStep21Header with a file, that has no ifc content, it hangs up in an endless loop.

#### Assemblies and versions affected:

XBim.Common v5.0.222 (master).
Anyway, why is it not part of the developer branche, too?

#### Steps (or code) to reproduce the issue:

If you call LoadStep21Header with a file, that has no ifc content, it hangs up in an endless loop.

```csharp
using(var stream = File.OpenRead(filename))
{
             header = StepModel.LoadStep21Header(stream);
             return true;
}
```

#### Minimal file to reproduce the issue:
see Zip-File

#### Expected behavior:

Should return null

#### Actual behavior or exception details:

Is in an endless loop

**Comment by martin1cerny** [comment]
It should just parse to the end of the file and return. Can you provide us with the file please?

**Comment by BjDi** [comment]
Hello Martin, 
before I tryed to attach that file as a 7z-Attachment and I didn't see that it has not benn accepted.
[NotAIfc.zip](https://github.com/xBimTeam/XbimEssentials/files/2859340/NotAIfc.zip)

**Comment by BjDi** [comment]
I didn't meant to close it, sorry

**Comment by martin1cerny** [comment]
Will investigate.
