### ISSUE TITLE
Multiplatform?

### ISSUE THREAD

**Issue by cesss** [xBimTeam/XbimEssentials#252]
Is Open BIM supposed to be multiplatform, or Windows-only? I only see ".sln" files for compiling the code, so, is it Windows only?

**Comment by andyward** [comment]
"It depends" - what are you trying to do?

XBIM Essentials is a C# library targeting .NET Framework (Windows only) and (since v5) .NET Standard. .NET standard runs cross platform - through implementations like .NET Core 2.x and Mono. So you can **use** the built libraries cross-platform (with some caveats #213 ).

If you really want to build the software yourself you should be able to use the free cross-platform [VSCode](https://code.visualstudio.com/) with the C# Omnisharp extensions. (I've just tested and it builds fine).

On a Mac, Visual Studio for Mac is now available. That said if you just want to use the software you shouldn't need to build it from scratch - get the pre-built packages from nuget.

**Comment by SBRK** [comment]
The possibility of building on Linux was discussed here https://github.com/xBimTeam/XbimEssentials/issues/98

I would also be interested on how much work would be needed to have only the parts needed for IFC to wexbim conversion work on Linux

**Comment by martin1cerny** [comment]
To go from IFC you essentially need the complete xBIM stack from xBIM Common through schemas implementations (IFC2x3, IFC4, IFC5 in the future) to geometry engine. Geometry engine uses mixed mode assembly at the moment which is not supported in .NET Core hence making geometry processing locked to Windows for now. We have a plan to reimplement the geometry engine to be .NET Core compatible but that is a complete rewrite, not an evolutionary step.

So, to make it short: It is not possible at the moment.

**Comment by foaqsejkDev** [comment]
Hello Martin,
good to hear that. That would be great. :)

**Comment by andyward** [comment]
Closing this here, should really track in Geometry Repo

**Comment by cesss** [comment]
> "It depends" - what are you trying to do?
> 
> XBIM Essentials is a C# library targeting .NET Framework (Windows only) and (since v5) .NET Standard. .NET standard runs cross platform - through implementations like .NET Core 2.x and Mono. So you can **use** the built libraries cross-platform (with some caveats #213 ).
> 
> If you really want to build the software yourself you should be able to use the free cross-platform [VSCode](https://code.visualstudio.com/) with the C# Omnisharp extensions. (I've just tested and it builds fine).
> 
> On a Mac, Visual Studio for Mac is now available. That said if you just want to use the software you shouldn't need to build it from scratch - get the pre-built packages from nuget.

Thanks a lot for your detailed reply. My source code environment is multiplatform and keeping it multiplatform is one of its main rules. I understand that _it's possible_ to build  OpenBIM in a number of platforms, but that's not enough for me to consider using it. I'll use other IFC libraries that have a multiplatform design.

**Comment by martin1cerny** [comment]
As we said above: If you don't need geometry engine, xBIM is multiplatform and you can use it. If you need to process geometry for visualization you will need to use something else for now.

**Comment by cesss** [comment]
Yes, I understood that. It's just that my multiplatform requirements are a bit higher, no additional technologies should be incorporated in my environment. But thanks a lot for the details.

**Comment by andyward** [comment]
@cesss you might be interested in an XBIM-based cloud service (PaaS) we've built which is obviously X-Platform. Email if interested.

**Comment by secomDevs** [comment]
Dear xBIM Team,
are there any new informations regarding the X-Plattform usage of xbim geometry?
Best regards
