### ISSUE TITLE
Reading Step

### ISSUE THREAD

**Issue by tasibalint** [xBimTeam/XbimEssentials#253]
I m trying to read a StepFile with the StepFileHeader Read. I m making a binaryreader from a cube.step file and when i reach stepFileHeader.Read(binaryReader) it throws an System.IO.EndOfStreamException. The exception probably happens at  
>public void Write(BinaryWriter binaryWriter)
>        {
>            _fileDescription.Write(binaryWriter);
because the _filedescription in Header is almost done
#### Assemblies and versions affected:

Xbim.Essentials 5.0.213

#### Steps (or code) to reproduce the issue:

*A simple set of steps to reproduce the issue. Provide a small sample file is required and/or 
a small sample of the failing code (or reference a commit / gist)*

```csharp

using Xbim.Ifc;
using Xbim.Ifc4.Interfaces;
using Xbim.Common.Step21;
using System.IO;

    class Program
    {
        static void Main(string[] args)
        {
 ModelObject modobj = new ModelObject();
            StepFileHeader header = new StepFileHeader(StepFileHeader.HeaderCreationMode.InitWithXbimDefaults,modobj);
            string fileName = "stp_Cube.step";
            BinaryReader reader = new BinaryReader(File.Open(fileName, FileMode.Open));
            header.Read(reader);
            Console.WriteLine(header.FileDescription);
            Console.ReadKey();
}
}

```

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Then just drag & drop here*
[stp_Cube.zip](https://github.com/xBimTeam/XbimEssentials/files/2930794/stp_Cube.zip)

#### Expected behavior:

read a step file

#### Actual behavior or exception details:

step file isnt read to the end i think last binaryReader.ReadString(); throws the exception

**Comment by andyward** [comment]
.STEP files are actually a different Schema to IFC and we don't support them in XBIM. While both STEP and IFC-SPF are based on EXPRESS languages, the schema for each is different. STEP is typically used for product data exchange, while IFC is for the wider building/construction data

The parser should probably handle this better, but fundamentally it's a completely different file format you're trying to load.

**Comment by martin1cerny** [comment]
This actually doesn't even use the parser. If it did, it would get the header populated at least.

```cs
using (var f = File.OpenRead(fileName))
{
    var schemas = StepModel.GetStepFileSchemaVersion(f);
    foreach (var schema in schemas)
        Console.WriteLine(schema);
}
```

will actually tell you that the schema is `'AUTOMOTIVE_DESIGN { 1 0 10303 214 1 1 1 1 }'`
