### ISSUE TITLE
[Question] IfcStore.SaveAsIfc filtered with list of IIfcProducts ? 

### ISSUE THREAD

**Issue by Bissy29** [xBimTeam/XbimEssentials#256]
Dear Team,

My objective is to generate from an IFC a sub-ifc (e.g. a floor, a space) having as input the list of IIfcProducts that must be included in sub-ifc file.

I observed there is such option but only when saving an wexbim, as the IfcStore.SaveAsWexbim has an optional parameter (`IEnumerable<IIfcProduct> products`).

Is there anything similar to obtain a filtered IFC?

Thank you in advance for your support!

Alexandru

**Comment by andyward** [comment]
It sounds like you want to be using `IfcStore.InsertCopy`. This populates a new model with a subset of the source model's products. You can pass in an `IEnumerable<IIfcProduct>`. The code is at:

https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Ifc/Extensions/IfcStoreCopyItemsExtensions.cs

**Comment by Bissy29** [comment]
Thanks @andyward for your suggestion! 

I already used IfcStore.InsertCopy but is extremely slow (there were cases when it took seconds and there were cases when it took up to 20 minutes). I used this initially to create a filtered wexbim but then I discovered that I can pass the products in IfcStore.SaveAsWexbim which is lightning fast (couple of seconds) comparing to the old approach IFC -> InsertCopy in IFC2 -> IFC2.SaveAsWexbim().

Additionally, I reported some issues reg. the output of InsertCopy but did not get a response yet -> https://github.com/xBimTeam/XbimEssentials/issues/240

Thanks!
Alex

**Comment by andyward** [comment]
So `SaveAsWexBim` is really just serialising the 3D geometry to our Wexbim format. There's no semantic data in that file - just representation. As such it's pretty simple operation.

InsertCopy is doing a lot more work as it needs to traverse all parts of the graph to rebuild the new sub-model. 

While there may be some optimisations to be made in the InsertCopy implementation, it's inevitably a complex solution to a general problem. If you want a partial model, you may be better off extracting in your own structures. E.g. A bit like the https://github.com/xBimTeam/XbimExchange DPOW approach.

**Comment by andyward** [comment]
Did this help resolve the problem @Bissy29 ?

**Comment by Bissy29** [comment]
Hi @andyward

Sorry for the late reply - I just managed to have a look into DPOW project but I do not really find it appropriate as I want to stick to IFC standard and not creating different structures. Therefore I will stick to InsertCopy in new IFC even though it takes a while.

Thanks!
Alex
