### ISSUE TITLE
Opening Model metadata without geometry

### ISSUE THREAD

**Issue by ndegier** [xBimTeam/XbimEssentials#257]
Hi guys,

Currently, I am only interested in the metadata of a IFC model, but it seems that the IfcStore.Open function automatically processes all geometric data too. This results in performance loss, so we would like to skip the geometry part. Is this possible?

Thanks in advance!

Niek

**Comment by andyward** [comment]
Actually `IfcStore.Open` doesn't generate the geometry. You need to create a 3DContext to do that, which is an optional step - demonstrated in the https://github.com/xBimTeam/XbimEssentials#3-generating-geometry example

It might be worth explaining what the performance issue you're seeing is, and what you expect.

**Comment by ndegier** [comment]
Thanks for the quick reply! 

So I'm currently 'transforming' the model's metadata from xBim to a more simplified class architecture. This means that my algorithm basically processes all objects and properties after the xBim library did its processing. For models with a lot of metadata, my algorithm performs similarly to your IfcStore.Open function, so that is no issue. However, the issue occurs when I process a (relatively) large model with mostly geometric data and almost no metadata. The specific model i'm talking about is around 200mb, has 77 IfcObjectDefinitions in total, and most of the objects have little to no properties/quantities/etc. 

My algorithm finishes in about 30ms, but The IfcStore.Open function takes almost a minute to process the file, but my algorithm finishes in about 30ms, which led me to believe that the geometric data was also considered in the IfcStore.Open function.

**Comment by martin1cerny** [comment]
Yes, you are right. `IfcStore` is reading all the data. Because IFC is general graph we make sure that data integrity is not broken. If you do what you want you are creating incomplete sub-graph and you need to be very careful how you define the border where the data integrity is to be broken.

**Comment by andyward** [comment]
If the model is 200MB you'll also be using the EsentModel my default which incurs a cost of building the .xbim Esent file. You may want to try forcing the IfcStore to use the Memory Model (by setting `ifcDatabaseSizeThreshHold` parameter to -1, which may be faster in this scenario

**Comment by andyward** [comment]
Can we close?
