### ISSUE TITLE
Using refletions for parsing IFC entities

### ISSUE THREAD

**Issue by Noranius** [xBimTeam/XbimEssentials#260]
I investigated to adjust your code for our own IFC extension. For that I examined Xbim.Ifc4.EntityFactoryIfc4. In that file you parse all Entity strings manually. With a simple usage of reflections you can save approx 650 lines of code.

#### Steps (or code) to reproduce the issue:

Type me = this.GetType();
Console.WriteLine(me.Assembly.FullName);
Console.WriteLine(me.Name);

#### Minimal file to reproduce the issue:
not necessary

#### Expected behavior:
like before, only saving code and improve maintability

#### Actual behavior or exception details:
works as designed

#### Additional Details

I can provide the solution if you are interested (pull request)

**Comment by Noranius** [comment]
I tested the idea. Hence, I extended the static constructor of the EntityFactoryIfc4. It creates a dictionary from the assembly with the types to speed up the later parsing:

```
static EntityFactoryIfc4()
{
	_assembly = typeof(EntityFactoryIfc4).Assembly;
	Type[] assemblyTypes = _assembly.GetTypes();
        foreach (Type aType in assemblyTypes)
        {
            try
            {
                if (aType.Name.StartsWith("Ifc") && !aType.Namespace.Contains(".Interfaces")
                    && aType.GetInterface(nameof(IInstantiableEntity)) != null))
                {
                    EntityFactoryIfc4.typeDictionary.Add(aType.Name.ToUpperInvariant(), aType);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }
}
```
Due to this, I changed the New method accordingly:

```
public IInstantiableEntity New(IModel model, string typeName, int entityLabel, bool activated)
{
    if (model == null || string.IsNullOrWhiteSpace(typeName) || entityLabel < 0)
        throw new ArgumentNullException();

    var name = typeName.ToUpperInvariant();
    Type entityType = EntityFactoryIfc4.typeDictionary[name];
    ConstructorInfo cInf = entityType.GetConstructor (BindingFlags.NonPublic | BindingFlags.Instance, //the constructor is internal
        null, new Type[] { typeof(IModel), typeof(int), typeof(bool) }, null);
    IInstantiableEntity result = (IInstantiableEntity)cInf.Invoke(new object[] { model, entityLabel, activated });
    return result;
}
```
Another advantage now would be an easy extension if you want to use your own IFC entities. You can write your own assembly and with a static method add all classes to the `typeDictionary`.

I don't know, for what the New method with the typeID is designed for. However, with a custom attribute at each class, this would be extensible, too. See [https://docs.microsoft.com/de-de/dotnet/standard/attributes/writing-custom-attributes](url).

Can you give me a feedback about these two things, please?

Sincerely Noran

**Comment by martin1cerny** [comment]
Hi @Noranius ,

thanks for the suggestion. Our implementation doesn't use reflection because it is several times slower than calling the constructor directly. Maintainability is not a problem because our implementation of the schema is code-generated as well as the `EntityFactory` class so these are always granted to be aligned. 

Normal IFC file of uncompressed size 1GB might contain approximately 12 000 000 entities. Emulating this on my computer will add about 5 seconds to the time necessary to open the file.

At the same time the absolute difference might not be critical. You would certainly want to cache the constructors, not just types as retrieving the constructor every time would add unnecessary time as well.

**Comment by martin1cerny** [comment]
My test case:

```cs
using System;
using System.Collections.Generic;
using System.Diagnostics;

namespace ConsoleApp5
{
    class Program
    {
        static void Main(string[] args)
        {
            const int count = 10000000;
            var label = 0;
            var parent = new TestObject(label++, null, true);

            var ctor = typeof(TestObject).GetConstructors()[0];

            var result = new List<object>();
            var w = Stopwatch.StartNew();

            for (int i = 0; i < count; i++)
            {
                var o = new TestObject(label++, parent, true);
                result.Add(o);
            }

            w.Stop();
            Console.WriteLine($"{result.Count} objects created in {w.ElapsedMilliseconds}ms using direct constructor.");
            result.Clear();

            w.Restart();
            for (int i = 0; i < count; i++)
            {
                var o = ctor.Invoke(new object[] { label++, parent, true });
                result.Add(o);
            }

            w.Stop();
            Console.WriteLine($"{result.Count} objects created in {w.ElapsedMilliseconds}ms using reflection.");
        }

    }

    public class TestObject
    {
        private int _label;
        private TestObject _parent;
        private bool _activated;

        public TestObject(int label, TestObject parent, bool activated)
        {
            _label = label;
            _parent = parent;
            _activated = activated;
        }

    }
}
```

**Comment by Noranius** [comment]
The idea of storing the constructors is much better. I came accross that idea mostly, because I need to extend the entities and doing it manually is a bit cumbersome. 

I asked your associate andyward about auto generated classes from a IFC schema. He said that there is currently no time to undertake the ifc 4x2 support. 

So, finally I started to change the code of you. I'm not sure because i would have to implement the whole extension of IFC 4x2.

**Comment by andyward** [comment]
Hi Mathias.

Sorry I didn't put your username together with the email you sent. I think I said we couldn't commit to a date to provide 4x2 support, but it's something we're planning. But at the moment it's a draft schema so we'd need to manage it in a private branch. 

I'd hope we get around to #259 in the next month or so. Rather than hand crafting a build of the ifc schema it would make sense for us to use the code gen tooling we have to build out a ifc4x2 schema.

**Comment by Noranius** [comment]
Of course, I understand this and don't want to stress. Only thinking aloud. Thank youfor the ideas and information.
