### ISSUE TITLE
Delete IFCSpace / IFCBuildingStorey leads to corrupt IFC file

### ISSUE THREAD

**Issue by Bissy29** [xBimTeam/XbimEssentials#261]
I am currently trying to delete a space from an IFC file but it leads to a corrupt output IFC file that won't open anymore (I am using BIM Vision for viewing IFC files).

Initial IFC structure:

![IFC structure](https://user-images.githubusercontent.com/5812307/57371833-20267300-7194-11e9-8a63-52a019a9c017.PNG)

Entity ID structure:

![IFC structure entityId](https://user-images.githubusercontent.com/5812307/57371907-55cb5c00-7194-11e9-9a5d-65e89891b3a8.PNG)

If I delete a space containing 0 elements (Space 2, EntityLabel = 2414) it works fine but if I try to delete the space 1 (containing a wall and a window) and I save the IFC file - it becomes corrupt.

My approach:
- delete all ifcProducts contained in space 0:  the wall (EntityLabel=163) and the window (EntityLabel = 2195)
- delete the space (EntityLabel = 2413)
- SaveAsIFC

Code:

```csharp
        void DeleteSpace()
        {
            var model = IfcStore.Open("A_wall.ifc");
            var ctx = new Xbim3DModelContext(model);

            var window = model.Instances.OfType<IIfcProduct>().Where(p => p.EntityLabel == 2195).FirstOrDefault();
            var wall = model.Instances.OfType<IIfcProduct>().Where(p => p.EntityLabel == 163).FirstOrDefault();
            var space = model.Instances.OfType<IIfcProduct>().Where(p => p.EntityLabel == 2413).FirstOrDefault();

            using (var txn = model.BeginTransaction("removeElements"))
            {

                model.Delete(window);              
                model.Delete(wall);              
                model.Delete(space);
                txn.Commit();
            }

            using (var writer = new FileStream("Adjusted_A_wall.ifc", FileMode.Create))
            {
                model.SaveAsIfc(writer);
                writer.Close();
            }
        }
```

I am using NuGet Xbim.Essentials 5.0.249

I mention that it works fine if I delete only the window, wall or empty space but if I try to combine these steps it's not working

![Error](https://user-images.githubusercontent.com/5812307/57374313-e4db7280-719a-11e9-8599-6e9d1eea8754.PNG)

I attached the original IFC file and edited one.

Thanks!
Alex

[Original and edited IFC file.zip](https://github.com/xBimTeam/XbimEssentials/files/3157141/Original.and.edited.IFC.file.zip)

**Comment by martin1cerny** [comment]
Hi Alex,

deleting objects from IFC is not as easy as you might think. xBIM will make sure that data integrity is maintained. That means that when you delete the object and save the file, there will be no reference from any other object to the object you deleted. However, that doesn't mean that it meats other IFC schema requirements like mandatory attributes. Checking your modified data against the schema gives these errors:

```
2019-05-09 10:11:56,129 ERROR - #125=IfcLocalPlacement is invalid.
    IfcLocalPlacement.PlacesObject must have no more than 1 item(s). It has at least 2.

2019-05-09 10:11:56,147 ERROR - #132=IfcLocalPlacement is invalid.
    IfcLocalPlacement.PlacesObject must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,166 ERROR - #159=IfcProductDefinitionShape is invalid.
    IfcProductDefinitionShape.ShapeOfProduct must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,171 ERROR - #183=IfcRelDefinesByProperties is invalid.
    IfcRelDefinesByProperties.RelatedObjects must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,188 ERROR - #214=IfcRelDefinesByProperties is invalid.
    IfcRelDefinesByProperties.RelatedObjects must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,207 ERROR - #2187=IfcProductDefinitionShape is invalid.
    IfcProductDefinitionShape.ShapeOfProduct must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,209 ERROR - #2404=IfcLocalPlacement is invalid.
    IfcLocalPlacement.PlacesObject must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,209 ERROR - #2204=IfcRelDefinesByProperties is invalid.
    IfcRelDefinesByProperties.RelatedObjects must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,210 ERROR - #2213=IfcRelDefinesByProperties is invalid.
    IfcRelDefinesByProperties.RelatedObjects must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,215 ERROR - #2232=IfcRelContainedInSpatialStructure is invalid.
    IfcRelContainedInSpatialStructure.RelatingStructure is not optional.
    IfcRelContainedInSpatialStructure.RelatedElements must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,218 ERROR - #2245=IfcRelAggregates is invalid.
    IfcRelAggregates.OwnerHistory is not optional.

2019-05-09 10:11:56,222 ERROR - #2256=IfcRelAssociatesMaterial is invalid.
    IfcRelAssociatesMaterial.RelatedObjects must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,223 ERROR - #2268=IfcRelAssociatesMaterial is invalid.
    IfcRelAssociatesMaterial.RelatedObjects must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,224 ERROR - #2274=IfcRelDefinesByType is invalid.
    IfcRelDefinesByType.RelatedObjects must have at least 1 item(s). It has 0.

2019-05-09 10:11:56,227 ERROR - #2396=IfcRelFillsElement is invalid.
    IfcRelFillsElement.RelatedBuildingElement is not optional.

2019-05-09 10:11:56,229 ERROR - #2414=IfcSpace is invalid.
    IfcSpace.OwnerHistory is not optional.

2019-05-09 10:11:56,231 ERROR - #2419=IfcApplication is invalid.
    IfcApplication.ApplicationIdentifier is not optional.
```

If you want to do the deletion properly you will need to isolate the complete data island you want to delete and make sure it doesn't overlap with other data in the file. This is certainly uneasy.

Saying so, xBIM Xplorer will open your modified IFC file OK because it doesn't rely on schema constraints that much:

![image](https://user-images.githubusercontent.com/773078/57438217-b36ab180-7243-11e9-910b-7849ed0a7446.png)

**Comment by Bissy29** [comment]
Thank you @martin1cerny for clarification! I will analyze in future the feasibility of adding such functionality of isolating data related to an object that will be deleted.

All the best!
Alex

**Comment by Bissy29** [comment]
Hi @martin1cerny, 

I did some further analyses and the only issue not tolerated by the viewer in this case which makes the file "corrupt" after objects deletion is related to IFCRELCONTAIEDINSPATIALSTRUCTURE - even if the objects linked to spatial structure were deleted (wall and window) and even if the spatial structure itself was deleted (the space), the IFCRELCONTAIEDINSPATIALSTRUCTURE related to these objects is not removed.

Therefore this line in original file:
`#2232=IFCRELCONTAINEDINSPATIALSTRUCTURE('1jgGHY1qf5PRmXJI1KBcs1',#41,$,$,(#163,#2195),#2413);`

Becomes after deletion:
`#2232=IFCRELCONTAINEDINSPATIALSTRUCTURE('1jgGHY1qf5PRmXJI1KBcs1',#2415,$,$,(),$);`

I might not have the whole context but from my point of view this line becomes obsolete and should be deleted if either the list of objects assigned to spatial structure becomes empty, either the spatial structure referenced is deleted. Am I missing something? 

Thank you!
Alex

Validation checks step by step:
![image](https://user-images.githubusercontent.com/5812307/57511326-52a5ac80-7309-11e9-92ac-f2f1c3909bd6.png)

**Comment by martin1cerny** [comment]
It is still a valid STEP21 line with owner history and global ID. You can implement such a 'purge' functions but there is no way to automate this generally. It has to be part of your data processing.

**Comment by Bissy29** [comment]
Ok @martin1cerny, thanks for advice and fast feedback! I will close the issue.

All the best,
Alex
