### ISSUE TITLE
Error "Database in use" on IfcStore.Open()

### ISSUE THREAD

**Issue by Gecc42** [xBimTeam/XbimEssentials#262]
Hello,

I have an error when opening a IFC file exported from SolidWorks 2018.
This error occurs on IfcStore.Open().
The message I get when opening the IFC with xBimExplorer is on the picture attached below.

![xBim_opening_error](https://user-images.githubusercontent.com/50831214/58021007-1b55ad80-7b0a-11e9-9e61-80f7291f1445.png)

The version of xBim I use is 4.0 and the IFC version is IFC4.

I think there is a issue with the IFC file but I have no information about which element cause the trouble. Unfortunatly I can't attach the IFC file, I'm sorry.

Have you any information on what could cause this error ?

Thank you in advance.

**Comment by martin1cerny** [comment]
Can you try with the latest xBIM 5 libraries to confirm if it is still an issue with the latest code?

**Comment by Gecc42** [comment]
Thanks for your fast answer.

I've been trying to update xbim to version 5 but I have a little issue : 
I work with Visual Studio 2015 and I have a project which target .NET 4.7.
When I want to install the nuget package of Xbim.Geometry, one of the dependencies (Microsoft.Extensions.Logging 2.1.1) is not .NET 4.7 compatible, so the installation fails.

Is there something I'm doing wrong ?

**Comment by andyward** [comment]
Sounds weird. M.E.Logging should definitely support .net4.7 

Did you upgrade your project to 4.7 before you upgraded the nuget packages? There was a nuget issue a few people ran into in v5 https://github.com/xBimTeam/XbimEssentials/issues/233#issuecomment-448186626

**Comment by Gecc42** [comment]
I created a new C# DLL project targeting .NET 4.7, and without doing anything else I open the nuget managment window and trying to install XBim package V5 (Xbim.Essentials or Xbim.Geometry), and I get the following error from VS during the installation :

_Error Unable to install the package "Microsoft.Extensions.Logging 2.1.1". You are trying to install this package in a project targeting".NETFramework,Version=v4.7", but the package does not contain any content files or assembly references compatible with this infrastructure. For more information, contact the package creator. 0_

**Comment by andyward** [comment]
I've just tried this, admittedly in VS2019 with no problem.

Sounds like you've got something amiss environmentally in VS2015. Can you install M.E.Logging 2.1.1 directly from nuget (rather than transitively through Essential)?

It's actually Xbim.Common that introduces this dependency, so you could also try adding that package directly.

**Comment by Gecc42** [comment]
I have the same error if I try to install Microsoft.Extensions.Logging directly.
I think you right, the issue probably comes from VS2015 but I don't understand why.
Thank you for your information I'll try to find a solution or I'll install VS2017 or VS2019 in order to test Xbim 5 on the import issue.

**Comment by andyward** [comment]
I'd make sure you've got the latest version VS2015, and the relevant .NET Framework development tools installed (in the Visual Studio Installer).  

If it's just that one file causing issues the chances are it's an issue in XBIM (or handling of a strange configuration). If you can share it we'll take look in the latest to see if anything is up

**Comment by Gecc42** [comment]
I have VS2015 Community Update 3 and .NET 4.7 runtime and SDK installed, so everything seems fine, but still the package error. I'm also on Windows 7 SP1.

However I tested with VS2019 Community and, like you, no problem.

So with XBim 5, I haven't the open error.
It's a good new but unfortunately I can't switch to VS2017 or VS2019 for now. I'll try to find a solution with VS2015.

**Comment by andyward** [comment]
Thinking about this after a few days, you'll be limited to Xbim v4 with VS2015 since we changed to the new 'SDK' format project files in v5.  I would use the [4.0.29 tag](https://github.com/xBimTeam/XbimEssentials/tree/v4.0.29) (the master version of v4.x) in favour of the _xbimv4.x_ maintenance branch (where there may be a un-tested fixes)

Both `IfcMechanicalFastener` and `IfcProtectiveDevice` have been in XBIM v4 for years (late 2015), but I suppose it's possible there's an data issue. Does opening the file in V5 raise any warning?

**Comment by Gecc42** [comment]
Ok thank you for the confirmation that Xbim 5 can't run with VS2015.
I'm already using the 4.0.29 version.

With my quick test with VS2019 and XBim 5, I simply tested the open() function on my IFC file but I haven't recorded logs. However I didn't have an exception like with xbim 4.

**Comment by Gecc42** [comment]
Hello,

Here a sample IFC file on which I have the "Database in use" error which occurs on IfcStore.Open() : https://we.tl/t-QDsZNEAXWl

The file is created by SolidWorks 2018.
I'm using xBim 4.0.29 but I have the same error with xBim 5.
The error also occurs with XbimXplorer.

I would like to know if this error is caused by a issue on the IFC or if it's a xBim bug.
I have the same error with other files exported from Solidworks 2018, but not always...

Thank you in advance.

**Comment by Gecc42** [comment]
I think I found the issue.
The SolidWorks 2018 IFC export is writing "IFCOVERING" instead of "IFCCOVERING".
So xBim do not reconize this object.
However this information is not present in the exception message.

**Comment by martin1cerny** [comment]
If you watch the log you should see a warning there saying that the type of the object is not recognised.

**Comment by Gecc42** [comment]
Indeed I see the error in the XBimExplorer log windows.

However in my code, the Open() function raise an exception before logging this error, I don't understand why (maybe it's because i'm using 4.0.29 version). And the exception message simply said that an "object reference not set to an instance of an object".

**Comment by martin1cerny** [comment]
Yes, this is handled more gracefully in xBIM 5.

**Comment by Gecc42** [comment]
Hello,

I've encounter the same error with another file, but this time the error is not due to a wrongly-spelled name. I think the error is caused by the IFCBUILDINGELEMENTCOMPONENT objects (I'm not sure) but I don't understand why. 

Could you help me to identify the origin of this error ?
You can't get the sample file here : https://we.tl/t-fiVOBeYETB

Many thanks
