### ISSUE TITLE
Is there any way to automatically export IPersistEntity properties to XML?

### ISSUE THREAD

**Issue by darek2000** [xBimTeam/XbimEssentials#264]
Hi,

I'm looking for a solution how to export IPersistEntity (with all properties) to xml format (file). Can I use some xbim library or I have to create my own xml parser for that?

thanks
Dariusz

**Comment by andyward** [comment]
What are you trying to do? Do you really want to export all Ifc entities to XML?

Best bet would be to take a look at the CobieLiteUK Exchanger project in https://github.com/xBimTeam/XbimExchange/

This however only exports IIfcProducts (filtered according to rules you can customise). So it won't be the full IFC file.

It allows you to map IFC to a COBIe style output and generate a file in JSON, XML, XLS etc. You'd be better off going with JSON as these files can get really large once unpacked.

If you really want a full version of the IFC in XML, you probably just want to use IfcXML, which the IfcStore can export to. But interpreting the ifcXML is not simple...

**Comment by SteveLockley** [comment]
Is there a reason you don't want to use IfcXML, cbim supports both versions *ifc2 and 4 and is an in-built export option

**Comment by SteveLockley** [comment]
I suggest you look at the code for the IfcXml export to see how to traverse the model and write it out

**Comment by darek2000** [comment]
@andyward @SteveLockley I think I will - thanks for all the details. I was considering to use ifcXml but I wanted to confirm that first if it is a proper way. here is a brief description of the tool I work on: the tool is a WPF app (based on xbimXplorer) which allows user to manually select entity(entites) inside XbimTreeView (SpatialView), which triggers model's elements selection inside DrawingControl3D and allows user (by clicking dedicated UI button) to send selected IPersistEntity(s) data (GUID, IIfcPropertySet, IIFcTypeObject, IIfcRelAssociatesMaterial, IIfcElementQuantity). At the moment, I use some delimiter-based string-based dataset but I came to conclusion that there should be some way to serialize those data into XML and send it out, hence my question
