### ISSUE TITLE
How to set transparency or color on IPersistEntity?

### ISSUE THREAD

**Issue by darek2000** [xBimTeam/XbimEssentials#265]
Hi,

is there any way to set color (or transparency) on specific IPersisentEntity? Should it be done by using IfcMaterialProperties or some (direct) property which holds ARGB? thanks

Dariusz

**Comment by martin1cerny** [comment]
You need to use/modify [IfcStyledItem](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcstyleditem.htm) for all representation items of the product.

**Comment by andyward** [comment]
Yes, See #183 

Note that it's unlikely this will immediately affect the 3D view as you'd need to rebuild the scene.
