### ISSUE TITLE
how to get ifcLocalPlacement's attributes

### ISSUE THREAD

**Issue by Wolgraph** [xBimTeam/XbimEssentials#267]
Hi. Working with Unity. I'm triyng to get the position of an object in my model, so I can change it with a custom mesh. In Revit I have a box which represent a painting and In Unity I want to replace it with the actual mesh of a painting.
I've follower the guide in the website, but it's not enough to do what I need.

this is what I wrote:

```
void Start()
    {
        var ifcmodel = IfcStore.Open(@"D:\Desktop\Prova IFC\Filename.ifc");
        using (var txn = ifcmodel.BeginTransaction())
        {
            var requiredProduct = new IIfcProduct[0]
                .Concat(ifcmodel.Instances.OfType<IIfcBuildingElementProxy>());
            {
                foreach (var product in requiredProduct)
                {                 
                    if (product.ObjectType == "paintingName")
                    {
                        var placement = product.ObjectPlacement.ReferencedByPlacements;
                        foreach (var place in placement)
                        {
                            Debug.Log(place.RelativePlacement.ToString());

                        }


                    }
                }
            }
        }
    }
```

I know this is not correct, but I've been trying for a whole day how to read those coordinates and orientation.

this is the IFC text
#15= IFCDIRECTION((0.,1.,0.));
#19= IFCDIRECTION((0.,0.,1.));
#7040= IFCCARTESIANPOINT((-7090.6712384874,-87.24353782889,0.));
#7042= IFCAXIS2PLACEMENT3D(#7040,#19,#15);
#7043= IFCLOCALPLACEMENT(#147,#7042);
#7044= IFCBUILDINGELEMENTPROXY('3prwM6xk52KOmlHFwnH884',#41,'FamilyName',$,'TypeName',#7043,#7038,'303226',$);

**Comment by martin1cerny** [comment]
You have rightly picked up that placement in IFC is mostly stored as a hierarchy where you need to combine all the components of the tree upwards. But your call goes downwards so it won't be right.

```cs
foreach (var product in model.Instances.OfType<IIfcProduct>())
{
    var indent = "";
    Console.WriteLine($"Product #{product.EntityLabel}={product.GetType().Name.ToUpperInvariant()}");
    var placement = product.ObjectPlacement;
    while (placement != null)
    {
        indent += "  ";
        if (placement is IIfcGridPlacement gridPlacement)
        {
            // handle grid placement
            Console.WriteLine($"{indent}Grid placement");
            continue;
        }
        else if (placement is IIfcLocalPlacement localPlacement)
        {
            // handle local placement
            if (localPlacement.RelativePlacement is IIfcAxis2Placement3D ap3d)
            {
                Console.WriteLine($"{indent}Placement 3D:");
                Console.WriteLine($"{indent}Location: {ap3d.Location.ToString()}");
                Console.WriteLine($"{indent}Orientation X: {ap3d.RefDirection.ToString()}");
                Console.WriteLine($"{indent}Orientation Z: {ap3d.Axis.ToString()}");
            }
            else if (localPlacement.RelativePlacement is IIfcAxis2Placement2D ap2d)
            {
                Console.WriteLine($"{indent}Placement 2D:");
                Console.WriteLine($"{indent}Location: {ap2d.Location.ToString()}");
                Console.WriteLine($"{indent}Orientation X: {ap2d.RefDirection.ToString()}");
            }

            // walk up the placement tree
            placement = localPlacement.PlacementRelTo;
            continue;
        }
    }
}

```

**Comment by Wolgraph** [comment]
Thanks for the reply.
Meanwhile I've found a temp solution that worked, but now comes a question.
Do I need to have the context created in this script to do this?
I've made some test with my Unity's solution and I've found out my ifclocalplacrment was empty.  It may be cause by the fact I searched for it in the wrong direction as you said, but I'm still pretty dumb to this.

**Comment by martin1cerny** [comment]
No, you don't need to have the `XbimContext3D` created for this to work. It is purely semantic data. And yes, I'm sure your code always returned `null` because placement of `IfcBuildingElementProxy` is hardly ever referenced further down in the hierarchy.

**Comment by Wolgraph** [comment]
Awesome! Thanks a lot! 
I'll et you know it this works for me and then close.
Hopefully this will help me in the overwriting phase, too.

**Comment by martin1cerny** [comment]
You are welcome. I'm closing the issue now. Feel free to reopen if needed.
