### ISSUE TITLE
Save .xbim file fail

### ISSUE THREAD

**Issue by chenxx08** [xBimTeam/XbimEssentials#268]
xbim.* 5.1.239

Version store out of memory (cleanup already attempted)
   在 Microsoft.Isam.Esent.Interop.Api.JetUpdate(JET_SESID sesid, JET_TABLEID tableid, Byte[] bookmark, Int32 bookmarkSize, Int32& actualBookmarkSize) 位置 c:\codeplex\EsentInterop\Api.cs: 行号 2561
   在 Microsoft.Isam.Esent.Interop.Update.Save(Byte[] bookmark, Int32 bookmarkSize, Int32& actualBookmarkSize) 位置 c:\codeplex\EsentInterop\Update.cs:行号 86
   在 Xbim.IO.Esent.EsentShapeInstanceCursor.AddInstance(IXbimShapeInstanceData instanceData)
   在 Xbim.IO.Esent.EsentGeometryInitialiser.AddShapeInstance(XbimShapeInstance shapeInstance, Int32 geometryId)
   在 Xbim.IO.Esent.PersistedEntityInstanceCache.ImportModel(IModel fromModel, String xbimDbName, ReportProgressDelegate progressHandler)
   在 Xbim.Ifc.HeuristicModelProvider.Persist(IModel model, String fileName, ReportProgressDelegate progDelegate)
   在 Xbim.Ifc.IfcStore.SaveAs(String fileName, Nullable`1 format, ReportProgressDelegate progDelegate)

**Comment by CBenghi** [comment]
Hello,
Please provide more information to reproduce.
Re-open when done.
Thanks,
Claudio
