### ISSUE TITLE
IfcStore.Open(azure blob url)  && Stream Options

### ISSUE THREAD

**Issue by sadwik** [xBimTeam/XbimEssentials#269]
Hi Team,
I am trying to open Ifc file which is hosted on azure 
IfcStore.Open("https:/portalname.blob.core.windows.net/rootfolder/SampleHouse.ifc") 

I am getting following error.
System.NotSupportedException: 'The given path's format is not supported.'

If i try using stream option, i am not able to extract any data.

using (var model = IfcStore.Open(memStream, Xbim.IO.StorageType.Ifc, Xbim.Common.Step21.XbimSchemaVersion.Ifc4, Xbim.IO.XbimModelType.MemoryModel, null, 
                            Xbim.IO.XbimDBAccess.Exclusive ,null, -1))

**Comment by andyward** [comment]
You won't be able to open it from an http link using `IfcStore.Open(string...)` - that's intended for local file systems.

What's the issue when you use `IfcStore.Open(Stream..)`? As long as the stream is seekable it should work. Can you share a fuller code example?

**Comment by sadwik** [comment]
Ok, not able to find the issue. 
But we are not able retrieve objects from stream which we are getting from azure, but a stream from a local path is retrieves objects without issues. 

Closing this since it has nothing to do with xBIM components
