### ISSUE TITLE
Add Element to IfcBuildingStorey

### ISSUE THREAD

**Issue by michealChin** [xBimTeam/XbimEssentials#27]
Dear xBim Team,

I created a storey (IfcBuildingStorey) and a few columns (IfcColumn). I would like to add column into IfcBuildingStorey.  

public static void WriteColumn(Column w, XbimModel model, IfcBuilding building, double min, double max, IfcBuildingStorey storey)
        {
            IfcColumn wall = CreateColumn(model, w, min, max);
            if (wall != null)
            {
                AddPropertiesToColumn(model, wall);                
            }
            using (XbimReadWriteTransaction txn = model.BeginTransaction("Add Storey"))
            {                
                storey.AddElement(wall);
                building.AddElement(wall);
                txn.Commit();
            }
        }

I write the code as above. But storey.AddElement() throw out an exception saying "Unable to cast object of type 'Xbim.Ifc2x3.SharedBldgElements.IfcColumn' to type 'Xbim.Ifc2x3.ProductExtension.IfcSpatialStructureElement'." .

May I know how to correctly assign a relation between Building Storey and an elements?
Thanks!

**Comment by theebow** [comment]
Hi, I don't know if there is purpose with your problem
but it seem to have mistake here :

storey.AddElement(wall);
building.AddElement(**wall**);  => building.AddElement(**storey**);

**Comment by michealChin** [comment]
Hi, 

building.AddElement(wall);

This code is copy from the HelloWall samples. I think it should be correct.

**Comment by theebow** [comment]
oh yes, i see, but HelloWall sample should be out of date
AddElement function doesn't exist now. I had some troubles with this sample
i will back today to tell you what i did in place of AddElement
;o)

**Comment by michealChin** [comment]
Hi,

Ya, agree with that. I think there is a bugs in AddElement. Can you show me how to properly add an element ( Wall, Column, Beam, Slab) into an IfcBuildingStorey? Thanks in advance!

**Comment by theebow** [comment]
something like that =>

            ```




            using (XbimReadWriteTransaction txn = mIfcModel.BeginTransaction("Add Wall"))
            {
                //building.AddElement(wall);

                IfcOwnerHistory ifcOwnerHistory = mIfcModel.IfcProject.OwnerHistory;
                //need to create the relationship
                mIfcModel.Instances.New<IfcRelAggregates>(rdbp =>
                {
                    rdbp.OwnerHistory = ifcOwnerHistory;
                    rdbp.Name = "Object Association";
                    rdbp.Description = "wall associated to etage";
                    rdbp.RelatedObjects.Add(wall);
                    rdbp.RelatingObject = etage;
                });

                //need to create the relationship
                mIfcModel.Instances.New<IfcRelAggregates>(rdbp =>
                {
                    rdbp.OwnerHistory = ifcOwnerHistory;
                    rdbp.Name = "Object Association";
                    rdbp.Description = "wall associated to building";
                    rdbp.RelatedObjects.Add(wall);
                    rdbp.RelatingObject = building;
                });

                IEnumerable<IfcRelContainedInSpatialStructure> relcsss = mIfcModel.Instances.OfType<IfcRelContainedInSpatialStructure>();
                IfcRelContainedInSpatialStructure relcss;

                if (relcsss.Count() > 0)
                {
                    relcss = relcsss.ElementAt(0);
                    relcss.RelatedElements.Add(wall);
                }

                if (mIfcModel.Validate(txn.Modified(), Console.Out) == 0)
                {
                    txn.Commit();
                }
            }

```

**Comment by michealChin** [comment]
Hi

It sounds cool! 

how about adding the relationship between wall and IfcBuildingStorey?

**Comment by michealChin** [comment]
IfcBuildingStorey storey;
                using (XbimReadWriteTransaction txn = model.BeginTransaction("Create Storey"))
                {
                    storey = model.Instances.New<IfcBuildingStorey>();
                     //txn.Commit();
                }
Hi,

I think I know where is the problem. When I add the BuildingStorey, I didn't call the txn.Commit(). Anyway thanks for your time!

**Comment by kozintsev** [comment]
micheal,

you need to create reletion between IfcBuildingStorey and Building, for example:

                var ifcRel = toModel.Instances.New<IfcRelAggregates>();
                ifcRel.RelatingObject = building;
                ifcRel.RelatedObjects.Add(buildingStory);
