### ISSUE TITLE
IfcXml validation tests failing due to missing XSDs from buildingsmart-tech.org re-org

### ISSUE THREAD

**Issue by andyward** [xBimTeam/XbimEssentials#273]
We have a number of tests that dynamically download the various ifcxml XSD schema to validate the data. These are currently breaking because links to BS XSDs such as http://www.buildingsmart-tech.org/ifcXML/IFC4/Add1/IFC4_ADD1.xsd are now invalid.

The CI build excludes some of these tests with a TestCategory `IfcXml` but a number of them are missing this. And of course the tests still fail locally.

E.g. This build failed:

https://dev.azure.com/xBIMTeam/xBIMToolkit/_build/results?buildId=542&view=ms.vss-test-web.build-test-results-tab&runId=1000466&resultId=100157&paneView=debug

**Comment by martin1cerny** [comment]
Tests are pointing to local XSDs: https://github.com/xBimTeam/XbimEssentials/commit/fc6907ab0a6e51ad4783f16a666be69b3fb2a148

**Comment by martin1cerny** [comment]
@andyward we can enable XML tests again.

**Comment by martin1cerny** [comment]
All tests passing: https://dev.azure.com/xBIMTeam/xBIMToolkit/_build/results?buildId=560
