### ISSUE TITLE
Is there any way to identify the field Ifc PipeFitting in IFC 4.1?

### ISSUE THREAD

**Issue by Linshyo** [xBimTeam/XbimEssentials#274]
Can the program support the display of field Ifc Pipe Fitting in IFC 4.1?

**Comment by andyward** [comment]
Can you be clearer about what you want to do / display? If you want to find Pipefitting in code you'd do something like:

```csharp
using (var model = IfcStore.Open("yourmodel.ifc"))
{
    var pipeFittings = model.Instances.OfType<IIfcPipeFitting>();
}
```
