### ISSUE TITLE
How to calculate Location and quantity info from IfcElement object. 

### ISSUE THREAD

**Issue by ashish1691** [xBimTeam/XbimEssentials#276]
![image](https://user-images.githubusercontent.com/51786431/62142915-c5249800-b30c-11e9-9950-1c536f2dd617.png)

I want to extract above highlighted property data from IfcElement object.

**Comment by martin1cerny** [comment]
What did you try?

**Comment by ashish1691** [comment]
I got the site and building info from model(IfcStore) object. But I'm not able to get data of federated floor, Top and bottom elevation, Distance to next floor, global top and bottom elevation and Global X & Y.

**Comment by ashish1691** [comment]
> What did you try?

**Comment by BalintBende** [comment]
Sorry if this is off topic.
But how can we get the coordination (x,yz) values from an IIfcCartesianPoint? I need 3 double value for example.

**Comment by martin1cerny** [comment]
Did you try 

```
IIfcCartesianPoint.X
IIfcCartesianPoint.Y
IIfcCartesianPoint.Z
```

?

**Comment by ashish1691** [comment]
> ![image](https://user-images.githubusercontent.com/51786431/62142915-c5249800-b30c-11e9-9950-1c536f2dd617.png)
> 
> I want to extract above highlighted property data from IfcElement object.

Just need to know if these properties are stored into IfcElement object or do i have to calculate these from element geometry.

**Comment by BalintBende** [comment]
`double x;
      if (placement is IIfcAxis2Placement3D ap3d) {
        if (ap3d.Location != null)
          x=ap3d.Location;`

I have a placement of a building element object. I get IIfcAxis2Placement3D then call Location attributes, but it hasn't got x, y or z attributes.

**Comment by ashish1691** [comment]
try this

double x; if (placement is IIfcAxis2Placement3D ap3d) { if (ap3d.Location != null) x=ap3d.Location.X;

**Comment by BalintBende** [comment]
Oh thanks guys, the problem was that I used Xbim.Ifc2x3.Interfaces not Ifc4. Anyway is it possible with Xbim.Ifc2x3.Interfaces?

**Comment by martin1cerny** [comment]
IFC4 interfaces access IFC2x3 data. Try it out.

**Comment by BalintBende** [comment]
Thank you guys! It works, sorry for distracting your conversation.

**Comment by ashish1691** [comment]
What i am searching for are component properties.
![image](https://user-images.githubusercontent.com/51786431/62294025-a7c80900-b487-11e9-91de-77e3f644bee2.png)


Is there any way to get these properties from IfcElement object.
Image shows data of component properties of IfcColumn.

**Comment by bertt** [comment]
@ashish1691 see https://github.com/bertt/ifc2geojson/blob/master/src/ifc2geojson.core/IfcParser.cs#L48
