### ISSUE TITLE
Is there a way to easily get the Material name belonging to an IfcBuildingElement?

### ISSUE THREAD

**Issue by BalintBende** [xBimTeam/XbimEssentials#278]
*I would like to collect informations and attributes that describes well a building element object. For example name, description, material name etc. Get name and description is quite easy, but material is not. Anyway I can get all of IfcMaterial objects from IfcStore, but which belongs to the selected building element object.*

Anyway can someone recommend an efficient tool to compare 2 building elements for example? My idea to get all attributes and analyse each, but some generic solution would be better to use.

**Comment by martin1cerny** [comment]
You need to use [material relation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcrelassociatesmaterial.htm).

**Comment by martin1cerny** [comment]
Generic solution to compare two elements doesn't exist because it always depends on the use case scenario. Anything related to the element can form part of its identity (attributes, properties, aggregations, materials, connections, geometry, placement, ...)

**Comment by BalintBende** [comment]
Thank you for the quick answer. Material relation helped me to find the name.
