### ISSUE TITLE
Underlying Units of Single Property Values (PSET)

### ISSUE THREAD

**Issue by Cymap-NZ** [xBimTeam/XbimEssentials#280]
Started trying to retrieve data from IFC 4.x files for some basic reporting. The Xbim lib, is fantastic, and in conjunction with Linq its very easy to drill down quite complex relations with very little code.  

One Issue I'm having is I've written a couple of global functions to get either a Single Property Value (and return its value, from an Optional parameter Propertyset Name.  

Whilst this is great, Ive noticed that if I return the whole IIfcPropertySingleValue (instead of its value) IN almost every single instance, the Units are Null??   But If I look at the actual line of data in the Raw IFC file :

#704= IFCPROPERTYSINGLEVALUE('Actual Power Load',$,IFCPOWERMEASURE(300),$);
I can see the units are mapped to the IFCPOWERMEASURE.  
This relation doesn't seem accessible via Xbim, unless I'm missing something?? 

![image](https://user-images.githubusercontent.com/32688638/62431466-d7bf2700-b77b-11e9-9683-91727d7a2114.png)

**Comment by martin1cerny** [comment]
Hi @Cymap-NZ , I'm glad you find xBIM useful. xBIM is certainly not hiding the unit of a property from you. The property could be explicitly defined as the last attribute in your case but it isn't (the last `$` in your example).  What you are referring to is a data-type of the value:

```cs
var value = property.NominalValue;
if (value != null)
    // this will write 'IfcPowerMeasure' in your case
    Console.WriteLine($"Type of the value: {value.GetType().Name}");
```

Note that this is not a unit but type of the value (measure). The unit in your case might be something like Watt [W].

**Comment by Cymap-NZ** [comment]
Thanks Martin, that was exactly what I was after, as any reporting of engineering quantities aren't of much use if you cant drill down and show units etc.  Thank you for the feedback.
