### ISSUE TITLE
How to get all common Property sets of an object?

### ISSUE THREAD

**Issue by BalintBende** [xBimTeam/XbimEssentials#281]
*I would like to filter all common property sets from all property sets of an IfcProduct. Can someone recommend a solution to do this? To get all common property set names into a List<string> for IfcProduct types would be very useful. For example if I have an IfcWallStandardCase I get back all Pset_WallCommon names: Reference,AcousticRating,FireRating, etc. Thanks in advance!*

**Comment by bekraft** [comment]
You have to crawl down into the ‘IsDefinedBy’ subrelations. See https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcobject.htm. The endpoints holds a select between single property set or a set of property set. Once flattened your are able to scan by a given set name.

**Comment by andyward** [comment]
Closing but reopen if you need help still

**Comment by BalintBende** [comment]
Hello,

I found out this solution, it works fine.

It would be closed, thanks.

Cheers,
Balint

```
//IFCRELDEFINESBYPROPERTIES
var ifcProperties = product.IsDefinedBy
        .Where(r => r.RelatingPropertyDefinition is IIfcPropertySet)
        .SelectMany(r =>
          ((IIfcPropertySet) r.RelatingPropertyDefinition)
          .HasProperties)
        .OfType<IIfcPropertySingleValue>();

//IFCRELDEFINESBYTYPE
var ifcTypeProperties = product.IsTypedBy
        .SelectMany(t => t.RelatingType.HasPropertySets)
        .OfType<IIfcPropertySet>()
        .SelectMany(pset => pset.HasProperties)
        .OfType<IIfcPropertySingleValue>();
