### ISSUE TITLE
How to add a wall to a building in Ifc 2x3

### ISSUE THREAD

**Issue by baoluuu** [xBimTeam/XbimEssentials#285]
As is shown in the sample, there is building.AddElement(wall) method in Ifc4.But  Ifc2x3  dosen't have the same method,I remember there used to be. My question is if I want to add a wall to a building, is there any substitution method for Ifc2x3?

**Comment by andyward** [comment]
I would use the approach demonstrated at http://docs.xbim.net/examples/basic-model-operations.html which supports writing any IFC schema. 

E.g. using `var newWall = model.Instances.New<IfcWall>();` where `IfcWall` is from the same schema the model implements. 

If you look at the code in `AddElement` that's pretty much all it's doing anyway. https://github.com/xBimTeam/XbimEssentials/blob/42b04efb619be89a377f8f578c9d811fa1d1881b/Xbim.Ifc4/ProductExtension/IfcSpatialStructureElement.cs#L116

**Comment by martin1cerny** [comment]
This is just a shortcut. To get better performance I would recommend working with IFC schema directly anyway. To achieve this the code would be like this:

 

private static void AddElement(IfcSpatialElement building, IfcProduct element)

{

    // it is a good idea to keep this relation in some kind of dictionary/cache if you are

    // going to use it multiple times. 'ContainsElements' is an inverse relationship which

    // means that it has to search the whole model to get it.

    var rel = building.ContainsElements.FirstOrDefault() ?? 

        building.Model.Instances.New<IfcRelContainedInSpatialStructure>(

            r => r.RelatingStructure = building);

    rel.RelatedElements.Add(element);

    

}

**Comment by baoluuu** [comment]
Thanks for the kind answers!
