### ISSUE TITLE
Door creation - Family or user defined objects creation and addition

### ISSUE THREAD

**Issue by MigVega** [xBimTeam/XbimEssentials#286]
*Is it possible to create an element that consists of more elements?  e.g. a detailed door (a solid result of different operations of extruded solids with different materials). Is it possible to embed all these elements in a single object, or into what is also called a Family? Or could I somehow copy this Family from one model to the other? Is there any way to add it and position it correctly in the new model?*

**Comment by LukasMHD** [comment]
Couldn't you just attach an IfcMaterialConstituentSet to the Door element?

**Comment by MigVega** [comment]
Thank you @andyward!
I am talking about just the visual representation of a Door, so I guess I have to use IfcRepresentation, but I still don't know how could I add such and element with xBIM to my model.
I would be grateful if you could provide me with a code example to add a Door e.g. with a glazed panel in an opening previously created in a wall.

**Comment by MigVega** [comment]
> Couldn't you just attach an IfcMaterialConstituentSet to the Door element?

Thank you for your answer @LukasMHD, but the metadata of the Door's material is not the only I would like to add, but also the geometry or visual representation.

**Comment by martin1cerny** [comment]
You should have a look at our [example](http://docs.xbim.net/examples/proper-wall-in-3d.html). It shows how to use xBIM to create new data. If you want to have a door consisting of partial components with their own material, geometry and properties you should use [aggregation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcrelaggregates.htm) as Andy already said. `IfcDoor` wouldn't have any representation in that case but would only point to its components using the [relation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcrelaggregates.htm).

**Comment by MigVega** [comment]
> You should have a look at our [example](http://docs.xbim.net/examples/proper-wall-in-3d.html). It shows how to use xBIM to create new data. If you want to have a door consisting of partial components with their own material, geometry and properties you should use [aggregation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcrelaggregates.htm) as Andy already said. `IfcDoor` wouldn't have any representation in that case but would only point to its components using the [relation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcrelaggregates.htm).

Thanks @martin1cerny, yeah the wall example has been very useful for me to understand how to create SweptSolids, what is useful to create the walls and openings. But I would like to add the rest of the objects in my model, like doors, windows, furniture and so on. How could I add these elements with xBIM?
 For example, how did you create the model in the [homepage of xBIM](http://docs.xbim.net)? The source code of a "HelloHouse" example would be just what I need! Or at least just how to add a door would give me more clues.

**Comment by martin1cerny** [comment]
This sample model was created using BIM authoring tool and exported to IFC. We didn't create this from code. You will have to dive deep in [IFC documentation] and use xBIM to create all the entities and their relations. xBIM is 100% implementation of the standard so you can use it to create anything defined in IFC standard. It is also a good idea to take some (simple) existing models to study data structures and relations.

[This is a simple wall with two windows:](https://github.com/xBimTeam/XbimEssentials/files/3615210/OneWallTwoWindows.zip) 

![image](https://user-images.githubusercontent.com/773078/64942490-76ee3880-d869-11e9-9046-8722e35a1039.png)
