### ISSUE TITLE
Changing property value

### ISSUE THREAD

**Issue by LukasMHD** [xBimTeam/XbimEssentials#287]
Hello, 
I have been usin Xbim for some time now, thank you for this amazing program!

I am having an issue with changing or setting a property value, I have studied your examples and tried lots of the solutions there but can't seem to get it working.
I tried to access a property value to change it, but when navigating to the property and trying to set the value like this: 
`prop.NominalValue.Value= 999;`
I get an error message telling me the value is protected. 

I have also tried to create a new property to attach it to the IfcProject entity, but this results in an error as IfcProject cannot be casted as an IfcObject

`using (var model = IfcStore.Open(strFilename, editor))

            {

                var buildingProject = model.Instances.FirstOrDefault<IIfcProject>();      
                IEnumerable<IfcRelDefinesByProperties> relations = buildingProject.IsDefinedBy.OfType<IfcRelDefinesByProperties>();

                using (var txn = model.BeginTransaction("Attaching LCC calculation result to IFC file"))

                {

                    foreach (IfcRelDefinesByProperties rel in relations)

                    {

                        IfcPropertySet pSet = rel.RelatingPropertyDefinition as IfcPropertySet;

                        if (pSet == null) continue;

                        if (pSet.Name.Equals("Auto_LCC_Template_IfcProject"))

                        {

                            pSet.HasProperties.Add(model.Instances.New<IfcPropertySingleValue>(p =>

                            {

                                p.Name = "Pset_ProjectCompleteCost";

                                p.NominalValue = new IfcMonetaryMeasure(2837468);

                            }));

                        }

                        rel.RelatedObjects.Add(buildingProject);

                    }

                    txn.Commit();

                }

                string savedFile = strFilename + "LCC_result_added

                model.SaveAs(savedFile);`

Any help is  appreciated :)

**Comment by martin1cerny** [comment]
If you have a look at the [documentation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/alphabeticalorder-entities.htm), you will see that `IfcProject` is not a sub-type of the `IfcObject`. Therefore it can't use `IfcRelDefinesByProperties` to define properties. 

For your first issue: All property values are typed, you can't just assign a number. This would work (if length is what you want to set. Any value type implementing `IfcValue` can be used):

```cs
prop.NominalValue= new IfcLengthMeasure(999);
```

**Comment by LukasMHD** [comment]
Thank you, that helped a lot 👍
