### ISSUE TITLE
Add new property

### ISSUE THREAD

**Issue by divyanatsteel** [xBimTeam/XbimEssentials#289]
Hi,
Please help me I got this error "This factory only creates types from its assembly" I am trying to add new property     model.Instances.New<IfcRelDefinesByProperties>(rel => {
                        rel.RelatedObjects.Add(entity);
                        rel.RelatingPropertyDefinition = model.Instances.New<IfcPropertySet>(pset => {
                            pset.Name = "Basic set of properties";
                            pset.HasProperties.AddRange(new[] {
                    model.Instances.New<IfcPropertySingleValue>(p =>
                    {
                        p.Name = "Text property";
                        p.Description="DATA";
                       // p.NominalValue = new IfcText("Any arbitrary text you like");
                    }),
                    model.Instances.New<IfcPropertySingleValue>(p =>
                    {
                        p.Name = "Length property";
                       // p.NominalValue = new IfcLengthMeasure(56.0);
                    }),
                    model.Instances.New<IfcPropertySingleValue>(p =>
                    {
                        p.Name = "Number property";
                       // p.NominalValue = new IfcNumericMeasure(789.2);
                    }),
                    model.Instances.New<IfcPropertySingleValue>(p =>
                    {
                        p.Name = "Logical property";
                       // p.NominalValue = new IfcLogical(true);
                    })
                });
                        });
                    });
                    txn.Commit();

**Comment by martin1cerny** [comment]
This means you are either trying to create IFC2X3 objects in IFC4 model or
vice versa. Check the namespaces you are using.

**Comment by divyanatsteel** [comment]
thank you

**Comment by divyanatsteel** [comment]
how to hide all yellow color entities means selected entities reinforcement showing is it possiable how get the all selected entityl
![color](https://user-images.githubusercontent.com/55271797/66022878-e595ec00-e521-11e9-8a08-b8d4e22c572a.PNG)
abel  values

**Comment by andyward** [comment]
Please open a new issue - this issue is closed. Also I think you'll need to be clearer about what you want to achieve, and mayne show what you've tried already.
