### ISSUE TITLE
Not rendering correct wexBIM after conversion

### ISSUE THREAD

**Issue by ivanstef** [xBimTeam/XbimEssentials#29]
Hi guys,
After I updated the myget packages to the latest the browser stopped rendering correct the model after it's been converted to wexBIM. I attach screenshots of the problem.
![building1](https://cloud.githubusercontent.com/assets/5886640/14101682/9f02699c-f59e-11e5-97a9-e6eed7bb50a8.PNG)
![rac_basic_sample](https://cloud.githubusercontent.com/assets/5886640/14101683/9f067cee-f59e-11e5-8a93-70e34f41ff6b.PNG)

**Comment by martin1cerny** [comment]
Hi @ivanstef ,
do you run `master` or `develop`?

**Comment by ivanstef** [comment]
Hi @martin1cerny I just got the latest packages from https://www.myget.org/feed/xbim-develop/package/nuget/Xbim.Essentials. With 4.0.0-V157 it is working great. 
Also in both versions I get the following error while trying to load one particular file that I can send to you if you want:

xbim-binary-reader.debug.js:77 Uncaught RangeError: byte length of Float32Array should be a multiple of 4

**Comment by martin1cerny** [comment]
If you could share the IFC file it might be helpful. I'll check what has changed in between the versions. The latest `develop` release is using upgraded version of geometry engine which should be more performant but it not well tested yet. So this might be the first issue.

**Comment by ivanstef** [comment]
I emailed it to you at martin1cerny@gmail.com

**Comment by martin1cerny** [comment]
Will have a look.

**Comment by martin1cerny** [comment]
I had a look on the file you sent me and it was failing completely because there are boolean operations in the data which result in an empty geometry and wexBIM file reader didn't cope with this case correctly. It is fixed now in the latest version.

Because you didn't provide us with the file presenting the rendering error on your pictures above we were not able to have a look on that one.

**Comment by ivanstef** [comment]
I checked it out. It is working great. The problem with the rendering still remains. I am sending you the problematic file.
[rac_basic_sample_project.zip](https://github.com/xBimTeam/XbimEssentials/files/208342/rac_basic_sample_project.zip)

**Comment by SteveLockley** [comment]
I have checked this with the latest version on develop and it is no longer repeatable. Closing the issue
<img width="506" alt="basic sample" src="https://cloud.githubusercontent.com/assets/8222629/18920176/82d4f6ba-8598-11e6-80ed-9af90ee28206.PNG">
