### ISSUE TITLE
How to know which IEntityCollection a generic selected element of my model belongs to

### ISSUE THREAD

**Issue by save2004** [xBimTeam/XbimEssentials#291]
How to know which IEntityCollection a generic selected element of my model belongs to

Xbim.Essentials 4.0.29

My problem

I'd like to have the possibility to click on an element of my model and to find all its own properties.
I followed the guide avaible on:
http://docs.xbim.net/examples/using-linq-for-optimal-performance.html

All ok if I know the IEntityCollection of my elment (if it is a door, or a windows... and so on). In this case it is very easy and all the necessary code is just written from Xbim Team.

But if I don't know which IEntityCollection my element belongs to.... how can I do?
I find my element (product) by its own Entity Label as the following code shows

             c#
              using (var model = IfcStore.Open("file.ifc"))
              {
                    var product = model.Instances[EntityLabel];
              }

and then I can find its ExpressType (product.ExpressType).... But I am not able to find IEntityCollection of this "product"..... How can I do? 

All this code otherwise is unusable (in this case we think to know that we are finding a door):

           var theDoor = model.Instances.FirstOrDefault< IIfcDoor >(d => d.GlobalId == id);
           var properties = theDoor.IsDefinedBy
                 .Where(r => r.RelatingPropertyDefinition is IIfcPropertySet)
                 .SelectMany(r => ((IIfcPropertySet)r.RelatingPropertyDefinition).HasProperties)
                 .OfType<IIfcPropertySingleValue>();
           foreach (var property in properties)
                 Console.WriteLine($"Property: {property.Name}, Value: {property.NominalValue}");

**Comment by save2004** [comment]
Actually I wrote this code for check if the element selected is a door or a wall or a windows... and so on. It is not efficient..... how can I improve my code?


using (var model = IfcStore.Open(ifcModel))
            {
                var product = model.Instances[elem];
                string type = Convert.ToString(product.ExpressType);
               
                //in this way I find GUID
                int posi1 = Convert.ToString(product).IndexOf("(");
                int posi2 = Convert.ToString(product).IndexOf(")");
                int lungh = posi2 - posi1;
                string nuovo = Convert.ToString(product).Substring(posi1 + 1, lungh - 1);
                var descr = nuovo.Substring(0, nuovo.Length).Split(new string[] { "," }, StringSplitOptions.None);
                string GUID = descr[0].Substring(1, descr[0].Length - 2);

               //so now I check... NOT EFFICIENT.... :(
                if (product is IIfcWallStandardCase)
                {
                    var oggetto = model.Instances.FirstOrDefault<IIfcWallStandardCase>(o => o.GlobalId == GUID);                    
                    var properties = oggetto.IsDefinedBy
                        .Where(r => r.RelatingPropertyDefinition is IIfcPropertySet)
                        .SelectMany(r => ((IIfcPropertySet)r.RelatingPropertyDefinition).HasProperties)
                        .OfType<IIfcPropertySingleValue>();

                    List<string> valori = new List<string>();
                    valori.Add("Global Id|" + oggetto.GlobalId);
                    //valori.Add("Name: " + oggetto.Name);
                    foreach (var property in properties)
                    {
                        valori.Add(property.Name + "|" + property.NominalValue);
                    }
                    ViewBag.VA = valori;
                }
                else if (product is IIfcWindow)
                {
                    /the same with "IfcWindow" now...
                }
                else if (product is IIfcDoor) { ... }
                else if (product is IIfcSlab) { ... }
            }

**Comment by martin1cerny** [comment]
I'm sorry, but this is not about xBIM. Please, search Microsoft documentation and guidelines for programming as well as relevant StackOverflow questions to learn more about .NET and C# programming.

**Comment by bekraft** [comment]
Maybe a little bit late - but as I understood you're looking for a back reference of an instance to its collection in your first comment, right? So you're trying to distinguish between models loaded at the same time? How about the ```.Model``` reference which is a container to the ```Instances[...]```?

**Comment by save2004** [comment]
> Maybe a little bit late - but as I understood you're looking for a back reference of an instance to its collection in your first comment, right? So you're trying to distinguish between models loaded at the same time? How about the `.Model` reference which is a container to the `Instances[...]`?

Hi bekraft,
I did it.... I wrote 

     var product = model.Instances[elem];

where "elem" is my Entity Label and I found "product.ExpressType" (for example). But I need to find all others properties of my "product". The problem is that I don't know if it is a door, or a wall and so on... so I can't use the code proposed by Xbim Team:

      var oggetto = model.Instances.FirstOrDefault<IIfcWallStandardCase>(o => o.GlobalId == GUID);

**Comment by andyward** [comment]
You just need to cast it to the correct type. Since C# 7.0, there's some 'pattern matching' syntax to make this dead easy. 

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/type-testing-and-cast#type-testing-with-pattern-matching

E.g. note the typed `wall` instance after the `is` check  

``` csharp

var item = model.Instances.FirstOrDefault(e => e.GlobalId == GUID);
if(item is IIfcWallStandardCase wall )
{
    var properties = wall.IsDefinedBy ...// etc
}
```

You can do this with the abstract parent classes so you can handle properties common across, say all IfcProducts.. e..g. rather than handle Walls, then Doors, then Windows + 100 others you can just do
``` csharp
if(item is IIfcProduct product )
{ /* Get the properties from product, which is IfcProduct */ }
```

**Comment by save2004** [comment]
Thank you so much @andyward for you comment!!! 
I am very gratefull for your C# theoretical references!!! 
I tried the code you propose, but I have some problem....

If I write; 

        var item = model.Instances.FirstOrDefault(e => e.Global.Id = GUID) 

I have an error on "GlobalId"; IPersistEntity does not contain a definition for GlobalId.... So I tried the following code:

        var item = model.Instances.FirstOrDefault<IIfcProduct>(e => e.Global.Id = GUID) 

In this way "item" is a IIfcProduct and I can write without errors the next code you propose....
But when I compile I have that "item" is null.....
