### ISSUE TITLE
IfcStore Open Consumes More memory than the STEPTools Libraries

### ISSUE THREAD

**Issue by Chandra123539** [xBimTeam/XbimEssentials#294]
while opening IFC files using ifcStore.Open(fileName), consumes more memory than StepTools libraries. for ex ( StepLibraries take 28 MB and xBIM consumes 77 MB during file open, when the actual IFC file size is 7MB ) . This happens for all files. 

we are using Platform x64.

#### Assemblies and versions affected:

( 5.1.259.0) ( xBIM essentails)

*A simple set of steps to reproduce the issue. Provide a small sample file is required and/or 
a small sample of the failing code (or reference a commit / gist)*

Open any IFC file and try to open using
IfcStore.Open and check the memory consumption.
if the same thing is done in Step Libraries, we could see the variation in files sizes.

#### Minimal file to reproduce the issue:

[SG2301.zip](https://github.com/xBimTeam/XbimEssentials/files/3797957/SG2301.zip)

#### Expected behavior:

Would be better to have explanation on why.

#### Actual behavior or exception details:

File Open Consumes more memory than Step Tools Libraries or Taking memory multi fold to the file size.

**Comment by andyward** [comment]
Would have to see a repro in both systems to comment better. And also some more data-points. But some initial thoughts:

**1. Are you using the right IModel implementation?**

Based on your other issue (#295) it sounds like you're using the MemoryModel. 

This takes a naive approach by loading the whole model into an in-memory representation of the IFC model. For large models you should use EsentModel which builds an indexed view of the model and will have a much lesser memory impact. I don't know how Steptools works to compare though

**2. How are you measuring the memory consumed?** 

What metric/perf counter are you using? At what point are you measuring? Have you done a GC collect first?

**3. Are you using 64bit Steptools?**

64 bit apps will typically utilize more RAM than the same 32bit apps, as addresses are obviously longer

**4. C++ vs .NET**

I'd guess the C++ data structures are lighter than xbim's. Then add in GC, LINQ etc. 

**5. They're different libraries doing slightly different things.**

I'd not sweat over 1x-3x differences. If it's 10x or non-linear we should take a look. Bottom line is does the library do what you want? When you've plugged in Esent can it work with the real world models for you?

**6. XBIM is free and open source**

If you think you can optimize it, I'm sure we'd be happy to take a PR :)

**Comment by andyward** [comment]
Sorry I didn't mean to close this before you confirm the state when using the Esent model

**Comment by Chandra123539** [comment]
Hi Andy,

Using EssentModel reduces the memory usage by almost 40 percent  while opening the model if we consume them in .NET executable. if we consume them in c++ executable, we do not find much improvement in memory usage ( around 10-15 percent). 

Please let me know if you have any idea on this.

Regards,
Chandra.

**Comment by andyward** [comment]
Sorry you'll have to provide some more context to what you're doing. I don't really understand what you mean by:

> if we consume them in c++ executable, we do not find much improvement in memory usage

Is that the Steptools library you're talking about?

If you want help investigating. what we'd need you to do is to share a small test program (in a repo we can access) demonstrating the issue. This will help us clarify some of the questions above (such as what you're doing & how you're measuring it)

**Comment by Chandra123539** [comment]
Sorry for creating the confusion over the statement that i have given. I will get back to you with proper
details.

**Comment by Chandra123539** [comment]
I have 2 things to explain.

 **First One is**:  Earlier we have used Steptools Libraries in our IFC Conversions. But, now we have removed them and started using the xBIM libraries for IFC conversions. Since we are replacing Steptools, we needed to compare the the Performance ( time and Memory)  and my Initial question was about this.

**Second One**: Since you mentioned that this comparison may not be a feasible thing, i have started to understand the ways by which , i can reduce the memory usage for the IFC Conversion using XBIM libraries.

So, I have gone through your documentation and then understood that EssentModel Provider would not store everything in memory and might be better than Memory model. That is why i have started exploring the Essent Model Details.

My Previous reply was not talking about Steptools. It was about using Xbim libraries in .NET Executable and C++ executable.

I am checking the peak memory of the Executable before and after the IFCStore open call for the sg2031.ifc file.

When Xbim libraries were used to open the File in .NET executable , Let us say it takes ( 30 MB), when the same Xbim libraries were used to open the File in an other C++ Executable, the same store open call consumes 50 to 55 MB.    So, i wanted to know why this difference occurs in 2 different
executables ( C++ and .NET) .

if you understand what i am saying, i can provide you the sample project files.

**Comment by Chandra123539** [comment]
**.NET executable Code:**

namespace App
{
    class Program
    {
      static void Main(string[] args)
        {
            IfcStore.ModelProviderFactory.UseEsentModelProvider();
            // Check the peak memory usage of the executable here
            var model = IfcStore.Open("SG2301.ifc");
            // and check the peak memory here
            // difference would be memory consumed for IfCstore Open call

        }

    }
}

**Comment by Chandra123539** [comment]
**C++ Executable Code** 

**1. Create a Sample MFC apllication**

**2. Create a .NET Dll**

             **i. Create an Interface and a method to OpeIFCstore.**

namespace BIM
{
    public struct DD
    {
        public int a;
        public int b;
    }
   public interface ITest
    {
        void OpenIFCStore();
    }
}

               **ii. Implement it** 

namespace BIM
{
    public class Class1:ITest
    {
        public void OpenIFCStore()
        {
// This is only to register this DLL as COM Interop
            DD CC = new DD();
            CC.a = 1;
            CC.b = 2;
               

            IfcStore.ModelProviderFactory.UseEsentModelProvider();
            var Model =IfcStore.Open("SG2301.ifc");

            
        }
    }
}

**3. Load the Dll in sample MFC application.**

ITestPtr M_test;

	HRESULT hr = S_OK;
	hr = CoCreateInstance(__uuidof(Class1), nullptr,
		CLSCTX_INPROC_SERVER, __uuidof(ITest), (void**)&M_test);

// Check peak Memory here
	M_test->OpenIFCStore();
// Check here also

**Comment by martin1cerny** [comment]
I'm sorry, but any difference measured between these two pieces of code are out of xBIM scope as our code is the same. The only difference can be caused by the actual runtime environment, different garbage collection strategies, interoperability layer between .NET and native code and other factors which are completely out of our control.

**Comment by Chandra123539** [comment]
Thanks martin for the reply. i have understood the situation.

**Comment by Chandra123539** [comment]
i have one more question.

 Does EssentModel provider increase the memory of the process at a later stage ( after Open Store) , when we start reading the properties and geometries one by one from the model.

i have observed it. Memory Model may consume more memory at the Open Store stage, but do not consume much after that. where as EssentModel seems like doing it in reverse.

Am i correct about this observation? Please correct me if i am wrong and explain the behavior.

**Comment by martin1cerny** [comment]
Esent model doesn't keep references to objects it gives you by default. So, if you hold them somewhere than yes, your application will consume more memory. If you let them go than GC should take care of them. It depends on your code.

**Comment by Chandra123539** [comment]
Ok Martin. Thanks for your reply.
