### ISSUE TITLE
Error when get object property sets

### ISSUE THREAD

**Issue by annpag** [xBimTeam/XbimEssentials#296]
Hi, 
i have a problem about ifc Properties. I would like to get all object properties from an IFC file, expecially custom properties added in the model using Revit. 
When i read the file (or open it using the last version of Xbim Explorer 5.1), i don't read all my properties, but others programs, like Solibri, show all of these.
I would like to send you my IFC file to show you the problem with this particular properties, can you support me?
This is my code to retrieve properties:

`var properties = item.IsDefinedBy
	.Where(r => r.RelatingPropertyDefinition is IIfcPropertySet)
	.SelectMany(r => ((IIfcPropertySet)r.RelatingPropertyDefinition).HasProperties)
	.OfType<IIfcPropertySingleValue>();`

Thanks

**Comment by martin1cerny** [comment]
You will need to be more specific about what kind of properties is not found. The line of code you have sent is limited to `IfcPropertySet` and `IfcPropertySingleValue`. There are also quantity sets and more complex kinds of properties in the schema and you can access them with xBIM as well. I'd recommend you to open the model in the viewer where you can see it, note the name, open the IFC file in a text editod, find it by name and identify the type of the property. You can than enhance the code to handle it as you need.

**Comment by annpag** [comment]
I understood my problem,  i was looking for `IfcPropertiesSingleValue` in the selected object, but these properties belongs to its "relatingType", so i had to check if relating type has properties.
Thank you for your time
