### ISSUE TITLE
Question about multi unit assignment

### ISSUE THREAD

**Issue by Melethainiel** [xBimTeam/XbimEssentials#298]
Hi,

I'm working on a project to add new property values into an existing IFC file.
Is there a way to use a different unit than the one in IfcUnitAssignment.

let's explain a bit more :

- I have a project with `IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);`. 
- If I add directly a new :
`IFCPROPERTYSINGLEVALUE('My parameter','My description',IFCLENGTHMEASURE(72),$);`
I got a new value in metre.
- if I add a unit before :
`#999= IFCSIUNIT(*,.LENGTHUNIT.,.CENTI.,.METRE.);` 
`IFCPROPERTYSINGLEVALUE('My parameter','My description',IFCLENGTHMEASURE(72),#999);`
I got a new value in centimeter but the value has been converted into centimeter -> I would like to have 72cm but I got 7200cm

Have you any idea how i could achieve this ?
Thank you

**Comment by martin1cerny** [comment]
Hi @Melethainiel,
your solution is perfectly correct. When you say

> I would like to have 72cm but I got 7200cm

it means that the IFC file has been read and interpreted by some SW. Because it is not common to define explicit units for properties in most of the BIM authoring tools I'd think that the SW you are using to view IFC data has a bug in it. Your file might be the first one to have a rich data like this.

Martin

**Comment by Melethainiel** [comment]
Hi @martin1cerny 

thank you ! 
I tried with BIMVision, Solibri and Revit and all of them gave me a bad result.
That's weird because with some units it's working (project in meter and custom unit in millimeter) and with others not (project in meter and custom unit in centimeter).
I'll see what I can do with that.

**Comment by martin1cerny** [comment]
Would you mind if I close this issue? It is not an xBIM issue but an issue with other tools which don't interpret the data correctly.

**Comment by Melethainiel** [comment]
Sure, I'll let you now if I got any update
