### ISSUE TITLE
Can I extend entities with Xbim? 

### ISSUE THREAD

**Issue by sheepwwf** [xBimTeam/XbimEssentials#301]
@martin1cerny Thank you for providing Xbim！
I want to extend Ifc Schema and add my own entities to the Schema,can this idea be realized with Xbim?

**Comment by martin1cerny** [comment]
We use our internal tooling to generate the schema and related infrastructure. But yes, if you follow the patterns, you can implement new entities and use xBIM to work with your extended schema. 

However, I would discourage you from doing so unless your activities are bound to one of buildingSMART development projects. Creation of IFC-like files which are actually not compatible with the official schema is decreasing general perceived reliability of the standard.
