### ISSUE TITLE
Xbim CCDL indicates medium license risk in BalckDuck ( open source review)

### ISSUE THREAD

**Issue by Chandra123539** [xBimTeam/XbimEssentials#302]
As part of Open source review process when we check for License risk for xBim , it indicates medium license risk.

#### Assemblies and versions affected:

5.1.0.257

#### Steps (or code) to reproduce the issue:

if we run scan on the xbim sample using black duck, we can find it.

#### Minimal file to reproduce the issue:

Please check the report attached.

![xbim license](https://user-images.githubusercontent.com/57258610/71064243-a415f400-2194-11ea-9a03-6fb903f54abe.png)

#### Expected behavior:

Please let us know on how to address this issue.

**Comment by martin1cerny** [comment]
Very interesting. Can you elaborate more on the type of risk caused by the license?

**Comment by Chandra123539** [comment]
i will get back to you once i find the exact risk.

**Comment by andyward** [comment]
I don't know BlackDuck but found [this article](https://securityboulevard.com/2019/03/sorting-through-open-source-license-risks/) which suggests BlackDuck flags up warnings where you _could potentially_ have a licence issue if you use the xbim software inappropriately. 

Unless you fork a version of the code and don't feed it back, it's not a problem.

From that article:

> ### Declared Conflict (Narrow Reach)
> Licenses in this category also have a declared conflict. However, they typically have less reach or are easier to use appropriately to prevent a conflict.
> 
> An example of this is the Common Development and Distribution License (CDDL). This license can be used in conjunction with commercial software. It requires that any source code combined in the same physical source files with code under the CDDL be made available under the CDDL. A safe way to use CDDL code would be to use it unmodified (or you must contribute your modifications back to the project).
> 
> NOTE: We flag this license only if the corresponding code is used improperly. If it is used properly, there are no open source license risks, and we assign the “No Conflict” status (explained below).

**Comment by Chandra123539** [comment]
can you explain the statement ( improper usage of the code). are there any chances of using the code improperly?

**Comment by martin1cerny** [comment]
As long as you just use the distributed NuGet packages you should be OK.
