### ISSUE TITLE
[Question] Why to put the @ before the Interface name?

### ISSUE THREAD

**Issue by Noranius** [xBimTeam/XbimEssentials#303]
I came across the following line of code in several code files:
https://github.com/xBimTeam/XbimEssentials/blob/cb6bfe1440201d8bf3f9ae1922635274011dacfc/Xbim.Ifc4/Kernel/IfcObject.cs#L27

I like the idea to use an interface for every instance because several functions stay the same independent from the ifc version. However, I don't know for what is the `@` before the name of the interface? Is it because both libraries (IFC 2x3 and IFC 4) contain the same Interfaces? 

And why use other projects the ifc4.interfaces only and no an interface defined above? See below for an example.

`using Xbim.Ifc4.Interfaces;`

https://github.com/xBimTeam/XbimGeometry/blob/8c5db8c8ea02662bfac6639b6136d478471b62cf/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L17

**Comment by martin1cerny** [comment]
We use code generation tool and there are cases where generated classes clash with reserved keywords in C#. The `@` prefix just makes sure that this is not a problem for the compiler. When used in code you can omit this and just type `IIfcObject` without `@`.
