### ISSUE TITLE
Unable to set control points to IfcBSplineSurface

### ISSUE THREAD

**Issue by anil1610** [xBimTeam/XbimEssentials#304]
Unable to set control points to IfcBSplineSurface

I am using below code to set control points of IfcBSplineSurface. 
I tried other possible ways that I can think of. But ifcBSplineSurface.ControlPoints.count is always showing zero.

This is working properly for a local instantiated List<List<XbimPoint3D>>. but not to ifcBSplineSurface.ControlPoints.count. 

Let me know if am missing something. 

```csharp
// fill control points
                for (int iU = 0; iU < iNoOfPtsInU; iU++)
                {
                    List<XbimPoint3D> VPoints = new List<XbimPoint3D>();

                    for (int iV = 0; iV < iNoOfPtsInV; iV++)
                    {
                     
                        XbimPoint3D Pt = new XbimPoint3D(ControlPts[iU][iV].X, ControlPts[iU][iV].Y, ControlPts[iU][iV].Z);
                        VPoints.Add(Pt);

                    }
                    ifcBSplineSurface.ControlPoints.Add(VPoints);
                }
```

**Comment by martin1cerny** [comment]
See #182 for solution. It is not an intuitive solution but keeps transactional control of all operations in xBIM model.

**Comment by anil1610** [comment]
Thank you for the response.

However with this I could create and fill IIfcCartesianPointList3D. But I still could not add the list to ifcBSplineSurface.ControlPointsList. 

This is the piece of code I am using...

 for (int iU = 0; iU < iNoOfPtsInU; iU++)
{
  IIfcCartesianPointList3D cartesianPointList = m_model.Instances.New<IfcCartesianPointList3D>();

  for (int iV = 0; iV < iNoOfPtsInV; iV++)
  {
cartesianPointList.CoordList.GetAt(iV).AddRange(new IfcLengthMeasure[] { ControlPts[itr].X, ControlPts[itr].Y, ControlPts[itr].Z });
  }

 ifcBSplineSurface.ControlPointsList.Add((IItemSet<IIfcCartesianPoint>)(cartesianPointList ));
}


this is crashing in the last line, exception is cannot type cast IIfcCartesianPointList to IItemSet<IIfcCartesianPoint>



I am facing same problem while filling the weights of the control points of the bspline surface.  I need to create an instance of list of IfcReal and add the list to list<list<IfcReal>>.

**Comment by anil1610** [comment]
![Capture](https://user-images.githubusercontent.com/59045029/71394562-19237680-2638-11ea-8645-43c90cb187c2.JPG)

Also when we create list of Cartesian points using IfcCartesianPointList3D, it is writing the points as IFCCARTESIANPOINTLIST3D. This is not how the bsplinesurface control points are represented in IFC file. They are represented as shown below. Hence I think IfcCartesianPointList3D is correct way for this case.

![Capture](https://user-images.githubusercontent.com/59045029/71394689-b1b9f680-2638-11ea-8e90-f26916047297.JPG)

**Comment by anil1610** [comment]
Any update on this issue... I am blocked on this issue....

**Comment by martin1cerny** [comment]
It is what it says. Invalid cast. `IfcCartesianPointList3D` is not `IItemSet<IItemSet<IfcCartesianPoint>>`.

```cs
var point = model.Instances.New<IfcCartesianPoint>(p => {
    p.X = ControlPts[itr].X;
    p.Y = ControlPts[itr].Y;
    p.Z = ControlPts[itr].Z;
});
ifcBSplineSurface.ControlPointsList.GetAt(iV).Add(point);
```

**Comment by anil1610** [comment]
Yes. IfcCartesianPointList3D is not IItemSet<IItemSet<IfcCartesianPoint>> is the issue I got when i tried to use  IfcCartesianPointList3D. 
Are you suggesting to use 
ifcBSplineSurface.ControlPointsList.GetAt(iV).Add(point); 
I think this will crash as there no memory created for iV (outer list / itemset)

The problem I am facing is creating on  list<list<XbimPoint3D>> CntrlPts
When i create inner list locally and do CntrlPts.Add(vPoints ), vPoints is not getting added to CntrlPts and the count is still showing as zero.

Could you demonstrate a working code snippet equivalent to 

 for (int iU = 0; iU < iNoOfPtsInU; iU++)
                {
                    List<XbimPoint3D> VPoints = new List<XbimPoint3D>();

                    for (int iV = 0; iV < iNoOfPtsInV; iV++)
                    {
                     
                        XbimPoint3D Pt = new XbimPoint3D(ControlPts[iU][iV].X, ControlPts[iU][iV].Y, ControlPts[iU][iV].Z);
                        VPoints.Add(Pt);

                    }
                    ifcBSplineSurface.ControlPoints.Add(VPoints);
                }

**Comment by anil1610** [comment]
To my surprise ifcBSplineSurface.ControlPointsList.GetAt(iV).Add(point); is working thank you for the resolution.
