### ISSUE TITLE
Load ifc model incomplete

### ISSUE THREAD

**Issue by chenxx08** [xBimTeam/XbimEssentials#307]
Xbim.Essentials:5.1.267
Xbim.Geometry:5.1.254

Open in BIMVision:
![image](https://user-images.githubusercontent.com/4447956/64218120-f3d8f400-cef2-11e9-8267-3e0e686d9275.png)
Open in XBIM:
![image](https://user-images.githubusercontent.com/4447956/64218155-179c3a00-cef3-11e9-99ba-fdcd2d15e3ce.png)

When opened with xbim, only one element is displayed.

The ifc file:
[1.zip](https://github.com/xBimTeam/XbimGeometry/files/3572254/1.zip)

**Comment by andyward** [comment]
This model seems to have line breaks in the middle of the encoded string names on the 5 BuildingElementProxies. E.g # 124 

```
#124=IFCBUILDINGELEMENTPROXY('1DI990qfv8v9AdzXbbf1ZT',#16,'','0
, PQ\X\C7\X\F8\X\

BC\X\E4 - PQ2\X\B6\X\DC\X\B9\X\B9\X\BE\X\AE\X\A3\X\A8\X\B2\X\BB\X\B0\X\FC\X\BA\X\AC\X\A3\X\A9\X\B5\X\BDPQ\X\D6\X\D0\X\BC\X\E4\X\B7\X\E7\X\BE\X\AE\X\A3\X\A8\X\B2\X\BB\X\B0\X\FC\X\BA\X\AC\X\A3\X\A9\X\CC\X\E5.dgn, Default:50954',$,
#134,#56,$,$);
...
```

I don't believe this is valid. But it's throwing the parser out anyway.  If you remove the line breaks manually the model loads without errors.

![image](https://user-images.githubusercontent.com/923699/71580143-65b6f800-2af7-11ea-9a31-c9e6bcee79d5.png)

**Comment by martin1cerny** [comment]
Line breaks in the string should be encoded:

> The IFC exchange format "STEP physical file" only allows characters represented by decimal value 32 to 126 from the code table in ISO 8859-1. Any other character, like some Western characters, like the German "Umlaut", Greek or Cyrillic letters, or Asian characters, has to be encoded before being exchanged as part of a string value.

https://technical.buildingsmart.org/resources/ifcimplementationguidance/string-encoding/
