### ISSUE TITLE
How to get location properties?

### ISSUE THREAD

**Issue by bertt** [xBimTeam/XbimEssentials#309]
I'm using XBim.Essentials to read from ifc file ("OneWallTwoWindows.ifc" - https://github.com/xBimTeam/XbimGltf/blob/develop/MainTests/Files/OneWallTwoWindows.ifc), but it's unclear to me how to get the IFCSite location properties as shown in Bim Vision:

![two_windows](https://user-images.githubusercontent.com/538812/71931201-89d0a400-319d-11ea-9983-f7581b26e7b2.png)

Code so far:

```
            var model = IfcStore.Open("OneWallTwoWindows.ifc");
            var ifcProject = model.FederatedInstances.OfType<IIfcProject>().FirstOrDefault();
            var site = ifcProject.Sites.FirstOrDefault();
            Assert.IsTrue(site.Name == "Default");
            // q: how to get from IIfcSite for Location: Project, Top Elevation, Bottom Elevation, Global Top Elevation, Global Bottom Elevation ?
            // q: how to get from IIfcSite for geometry: Has Own Geometry, GllobalX, GlobalY, GlobalZ. BundingBox (length, width, height) ?
```

Any pointers how to read these location/geometry properties?

**Comment by andyward** [comment]
XBIM implements the IFC schema(s) so [this page](https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcsite.htm) is a good place to start


You'll see site has the Long Lat and a base elevation. For a given element/product you should be able to follow the local placement chain to account for the absolute measurements.

**Comment by bertt** [comment]
Yes I can find the lon, lat, elevation values in this simple model (-0.12, 51.5, 0 using ifcSite.RefLongitude, ifcSite.RefLatitude, ifcSite.RefEleveation) but the other location properties as shown in BimVision are nowhere to be found. 

Most close comes for the IfcWall: 
((IIfcPlacement)((IIfcLocalPlacement)wall.ObjectPlacement).RelativePlacement).Location -> (-3603.11726927393, 475.257796099376, 0) but I'm wondering why the y values are different (475.257796099376 versus 305.257796).

**Comment by andyward** [comment]
Looks like a question for BIMVision. I'm guessing they have some additional coordinate mechanism going on. The site is at 0,0,0 in that model. Have you tried opening the model in another tool, like Solibri or BIM Collab?
