### ISSUE TITLE
Can not find geometry attributes to set during the creation of a new object

### ISSUE THREAD

**Issue by thmspl** [xBimTeam/XbimEssentials#310]
I'm trying to add new object to an IfcStore. I took the code from [Basic-Model-Operations Tutorial](https://docs.xbim.net/examples/basic-model-operations.html) where a new store with a new project and a new wall object will be created. Unfortunately in the example is not stated how to provide any geometry points or something like this.

I've created a new ifc file and in the file I was able to find those attributes provided as `IFCCARTESIANPOINT` like this (for example):

`#70 = IFCCARTESIANPOINT((-17036, 7681, 2600));`

How can I add such a point to a newly created IfcWall to define how big the wall is and what position if has?

Thank you for your help.

**Comment by martin1cerny** [comment]
See our example of 3D wall [here](http://docs.xbim.net/examples/proper-wall-in-3d.html). That contains all the code you need to start creating the geometry.

**Comment by thmspl** [comment]
Thank you! That was exactly what I was searching for.. I don't know why I haven't found this example with google..
