### ISSUE TITLE
Create an Array of IfcPropertySingleValue

### ISSUE THREAD

**Issue by manohargss** [xBimTeam/XbimEssentials#312]
We have a requirement of creating an Array of IfcPropertySingleValue. We are in a loop and creating a new object every time. Is there a way of allocating the Array once when we are exporting to an ifc file.

#### Steps (or code) to reproduce the issue:

*A simple set of steps to reproduce the issue. Provide a small sample file is required and/or 
a small sample of the failing code (or reference a commit / gist)*

```csharp
using (var model = IfcStore.Open("file.ifc"))
{
for_each( val in valArray)
{
    var Value = model.Instances.New<IfcPropertySingleValue>();
Value.Name = val.Name;
}
}

**Comment by martin1cerny** [comment]
Can you be more specific about the kind of array you would like to allocate? I'm not quite sure what the problem is.

**Comment by manohargss** [comment]
Hi Martin,
for e.g.:
#81=IFCPROPERTYSINGLEVALUE('LayerID',$,IFCTEXT('A-FLOR-STRS'),$);
#82=IFCPROPERTYSINGLEVALUE('Name',$,IFCTEXT('Stair:Residential - Right Open:319014:1'),$);
#83=IFCPROPERTYSINGLEVALUE('ObjectType',$,IFCTEXT('Stair:Residential - Right Open'),$);
#84=IFCPROPERTYSINGLEVALUE('SourceIdentifier',$,IFCTEXT('19SNioai18kO2Ht9UbW8_o'),$);
#85=IFCPROPERTYSINGLEVALUE('SystemPath',$,IFCTEXT('001\\ 307782\\ Building\\ Level 10\\'),$);
#86=IFCPROPERTYSINGLEVALUE('TYPE',$,IFCTEXT('STAIR FLIGHT'),$);
#87=IFCPROPERTYSINGLEVALUE('Tag',$,IFCTEXT('319014'),$);

You can see I have 7 properties
Right now I allocate 7 properties in for loop as:

pseudo code:
for (int i= 0 ; i<7 ;i++)
model.Instances.New<IfcPropertySingleValue>();

Is there a way to :
model.Instances.New<IfcPropertySingleValue>(7);
without running a for loop?

**Comment by andyward** [comment]
I'm not clear what the problem is. Why don't you want a loop?

I guess if you always had 7 properties and you wanted a static array you could do this more declarative like:

```csharp
var properties = Enumerable.Range(0, 7)
    .Select(e => model.Instances.New<IfcPropertySingleValue>()).ToArray();
properties[0].Name = "LayerID";
properties[0].NominalValue = new IfcText("A-FLOR-STRS");// or new IfcLengthMeasure(100) etc
// properties[1].Name // etc...
```

**Comment by manohargss** [comment]
I want to Allocate it only once right now in the for loop I allocate 7 times. In short, I want to minimize the number of allocations

**Comment by martin1cerny** [comment]
Well, you are creating 7 objects, so you need to allocate 7 objects and in a linear world you have to do this in some kind of loop. I'm afraid you are overthinking memory management here. If you are building some kind of list from these properties, you might set the capacity of that list first to avoid list resizing (causing memory re-allocations). But that is on your side of the code.

**Comment by manohargss** [comment]
To put it simply
int[] Array = new int[7];

just like above is it possible to do the below code?

model.Instances.New<IfcPropertySingleValue>(7);

**Comment by andyward** [comment]
_int_ is a .net Value type and will allocate on the stack. Model instances are reference types and so will be allocated on the heap. Quick summary: https://jonskeet.uk/csharp/memory.html

So an IfcPropertySingleValue[] is just going to be an array of pointers to the items in the heap. 

However you implement this it's going to be "syntatic sugar" - The outcome will be the same - there will be heap allocations managed by GC.

Unless you have an issue I'd not sweat the micro optimizations. If you've got a scenario that doens't work/perform log that and we'll investigate
