### ISSUE TITLE
problems publishing on server

### ISSUE THREAD

**Issue by save2004** [xBimTeam/XbimEssentials#313]
Hello, I have been using your work for reading .ifc files via the web for some time now.
I recently ran into a problem. When I run my ASP.NET MVC project with Visual Studio it works correctly, but when I publish it on the corporate server I can no longer see the 3D model corresponding to the .ifc file; I get error 500 Internal Server Error ....
Can you depend on me? Do I need to change anything in the code and use of the nuget xbim libraries? Or is it exclusively a server problem?
Thank you!!

The project is in .NET Framework 4.7.2
All the latest versios of nuget Xbim assemblies (xbim.essentials v5.274)

**Comment by martin1cerny** [comment]
You will need to be more specific about the error.

**Comment by andyward** [comment]
I would start here and enable error logging: https://stackoverflow.com/questions/5385714/deploying-website-500-internal-server-error

Have a check what has been deployed to the server vs what you see locally. Pay close attention to the Xbim Geometry dlls if you're deploying Geometry. Note that you need to deploy the correct version of x86 / x64 depending on whether your app pool is running under a 32 bit or 64 bit process

**Comment by save2004** [comment]
Thank you @andyward and @martin1cerny for your answers.
@andyward I know the issue related to the version of Xbim Geometry dlls files. In fact when I run the code with Visual Studio I use the 32 version, while when I publish it on the corporate server I use the 64 version.
I can't explain why it doesn't work anymore. 
For months, everything went well. For a few days it seems that it is impossible to work with ifc files. When the function is called

`public ActionResult GeometryFile(string wexBim)
        {            
            if (IsValidFile(wexBim, ".wexbim"))
            {
                var fileName = Path.Combine(DataDir, wexBim);
                return File(fileName, "application/octet-stream", wexBim);
            }
            return View("Error");
        }`
something goes wrong.. I get Error 500 (internal server error)
Perahps some permission denied to my web application? It is so strange….

**Comment by andyward** [comment]
If it's just that Action going wrong it's unlikely to be an XBIM issue (although I can't tell what you're doing in `IsValidFile()`). 

If it's failing to download a previously generated Wexbim file, then it's an issue accessing the file from disk. You've no exception handling in that action so if anything goes wrong (e.g. permissions, IO errors etc) then ASP.Net / IIS will just return a HTTP 500 error. Add some exception handling and hopefully it'll be clearer what the issue is.

**Comment by save2004** [comment]
I post the IsValideFile function


`private bool IsValidFile(string file, string expectedExtension)
        {            
            if (file.Contains(Path.DirectorySeparatorChar) || file.Contains(Path.VolumeSeparatorChar))
            {
                return false;
            }
            if (Path.GetExtension(file).ToLowerInvariant() != expectedExtension)
            {
                return false;
            }
            var filePath = Path.Combine(DataDir, file);
            if (!filePath.StartsWith(DataDir))
            {
                return false;
            }
            return System.IO.File.Exists(filePath);
        }`

> If it's failing to download a previously generated Wexbim file, then it's an issue accessing the file from disk. You've no exception handling in that action so if anything goes wrong (e.g. permissions, IO errors etc) then ASP.Net / IIS will just return a HTTP 500 error

exactly!!!!

> Add some exception handling and hopefully it'll be clearer what the issue is.

I will try!!! Thank you!!
