### ISSUE TITLE
How to find the IfcConnectionType ?

### ISSUE THREAD

**Issue by CamChatHel** [xBimTeam/XbimEssentials#314]
Hello,

I need help finding the IfcRelatedConnectionType. I have walls connected to each other with IfcRelConnectsPathElements. I already can find with Xbim the element IfcRelConnectsPathElements and the read the RelatingElement and RelatedElement. 
But I'm not able to read RelatedConnectionType or RelatingConnectionType.

I use a IFC4 file and the information is definitely there. I also can see it when I stop the code (see picture). But I can't access it.

That's my code so far:

```csharp
// Search all Elements, here all Walls
var items = model.Instances.OfType<IIfcWall>();

foreach (var wall in items)
 {
     var connectionTo = wall.ConnectedTo;
     foreach (var element in connectionTo)
                {
                   IIfcProduct relElement = element.RelatedElement;
                 //here a would expect something like:
                  var ConnectType = element.RelatedConnectionType;
                // but this doesn't work.
                }
  }
```

Thank's for your 

![XbimFrageConnection](https://user-images.githubusercontent.com/49938985/73256079-91de9b00-41c1-11ea-8e80-d496cf521553.png)

**Comment by martin1cerny** [comment]
Wrong place, wrong cast:

```cs
foreach (var wall in items)
{
    var connectionRelations = wall.ConnectedTo;
    foreach (var connectionRelation in connectionRelations)
    {
         // Related element            
        var relElement = connectionRelation.RelatedElement;

        // Connection type is defined on the relation if it is a IfcRelConnectsPathElements
        if (connectionRelation is IfcRelConnectsPathElements connPaths)
        {
            var connectType = connPaths.RelatedConnectionType;
        }
    }
}
```

**Comment by CamChatHel** [comment]
Thanks for your answer. unfortunately I don't get it... :( 
Even if there is a IfcRelConnectsPathElements my code don't go to the if-statement. It just ignore it.

**Comment by andyward** [comment]
Guessing it should probably be:

```csharp
using Xbim.Ifc4.Interfaces;

// Note the extra 'I' so we use the interface, not the Ifc2x3/4 implementation
if (connectionRelation is IIfcRelConnectsPathElements connPaths)
//...
```
