### ISSUE TITLE
ifcstore open fails for 2.8 GB IFC file

### ISSUE THREAD

**Issue by Chandra123539** [xBimTeam/XbimEssentials#315]
ifcstore open fails for 2.8 GB IFC file with exception 

Xbim.Common.Exceptions.XbimParserException: Parser failed on line 0, column 0 ---> Xbim.IO.Parser.BufferException: Index was outside data buffer
   at Xbim.IO.Parser.BuildBuffer.BufferElement.get_Item(Int32 index)
   at Xbim.IO.Parser.BuildBuffer.Read()
   at Xbim.IO.Parser.Scanner.GetCode()
   at Xbim.IO.Parser.Scanner.Scan()
   at Xbim.IO.Parser.Scanner.yylex()
   at Xbim.IO.Step21.XbimP21Scanner.Parse(Boolean onlyHeader)
   at Xbim.Common.Model.StepModel.LoadStep21(XbimP21Scanner parser)
   --- End of inner exception stack trace ---
   at Xbim.Common.Model.StepModel.LoadStep21(XbimP21Scanner parser)
   at Xbim.IO.Memory.MemoryModel.LoadStep21(XbimP21Scanner parser)
   at Xbim.Common.Model.StepModel.LoadStep21(Stream stream, Int64 streamSize, ReportProgressDelegate progDelegate, IEnumerable`1 ignoreTypes)
   at Xbim.Common.Model.StepModel.LoadStep21(String file, ReportProgressDelegate progDelegate)
   at Xbim.IO.Memory.MemoryModelProvider.Open(String path, XbimSchemaVersion schemaVersion, Nullable`1 ifcDatabaseSizeThreshHold, ReportProgressDelegate progDelegate, XbimDBAccess accessMode, Int32 codePageOverride)
   at Xbim.Ifc.IfcStore.Open(String path, XbimEditorCredentials editorDetails, Nullable`1 ifcDatabaseSizeThreshHold, ReportProgressDelegate progDelegate, XbimDBAccess accessMode, Int32 codePageOverride)

#### Assemblies and versions affected:

5.1.259.0

#### Steps (or code) to reproduce the issue:

1. Open the file using following code
using (var model = IfcStore.Open("070.ifc"))
{
    ...
}

#### Minimal file to reproduce the issue:

Please suggest a way to Upload file.( we have 400 MB zip file).

#### Expected behavior:

Should open IFC file with out any exception.

#### Actual behavior or exception details:

IFCStore Open Crashes with exception.

**Comment by CBenghi** [comment]
Hello,
I suppose one way to share would be a https://wetransfer.com/.
Try claudio.benghi@gmail.com, I have ways to share with other xbim team.
Best,
Claudio

**Comment by Chandra123539** [comment]
Hi Claudio,

I have uploaded file ( 070ifc.zip) using we transfer.

Regards,
Chandra.

**Comment by Chandra123539** [comment]
Thanks for your reply.

Chandra.

**Comment by Chandra123539** [comment]
Did any one get a chance to look into this?

Regards,
Chandra.

**Comment by CBenghi** [comment]
Apologies, it might take a while, we have a bit of queue going on.

**Comment by ehtick** [comment]
I can load large Ifc files without any problem, did you test that the Ifc file is correct?
Download solibri (free version) and try to load it.

**Comment by CBenghi** [comment]
The file in question throws a buffer exception on parsing.
I'm investigating it.

**Comment by CBenghi** [comment]
Looking at the parser code generated in Essentials I think that the maximum length of an IFC file that we can read is 2147483647 bytes long.When we exceed that limit there are signed integer overflows in the BuildBuffer class of GPLEX, which uses int pointers to the position in the file.

@martin1cerny, can you confirm?

**Comment by martin1cerny** [comment]
I would say that this is not a limit for the file but for a single read operation. So, there is a limit for a single record to be 2,147,483,647 bytes long. I would suggest to catch the place where this happens and to extract a portion of the file say 100 bytes before and 100 bytes after to see how the file looks like in that part. Can you share the file with me @CBenghi?

**Comment by CBenghi** [comment]
Sure @martin1cerny,
sharing in private.

**Comment by martin1cerny** [comment]
Right, I run a test and we do have a limit of 2,147,483,647 bytes on the file size. I didn't realise this before and @ehtick is possibly first one to push it to this boundary. This limit is in the generated scanner code. We use GPLEX scanner generator and it uses `int` to keep the position in the fil. When this overflows it obviously fails. We can only fix this by modifying the source code of GPLEX generator as any local changes would get lost with the next regeneration of the scanner. Saying so, IFC files of this size are usually hard to handle in most environments.

**Comment by Chandra123539** [comment]
Hi Martin,

Can this issue be addressed in future releases?

Regards,
Chandra.

**Comment by CBenghi** [comment]
@Chandra123539,

I'm looking at options for doing this, but it's quite extensive work to produce a strong result as it needs a significant rework with efficiency in mind, given the size of the models involved.
We will probably solve this in the long run, but if you need this in production within some short time-frame your best bet is to support the development.

I hope this helps,
Claudio

**Comment by Chandra123539** [comment]
Thanks for the info Claudio.

Regards,
Chandra.

**Comment by andyward** [comment]
Fixed in https://github.com/xBimTeam/XbimEssentials/commit/6517bc16042b3cfd820dd7eb45f72bbab92d13ad
