### ISSUE TITLE
Creation of large IFC files, creating instance of new objects crashing

### ISSUE THREAD

**Issue by anil1610** [xBimTeam/XbimEssentials#317]
I am trying to create an IFC file which has large geometry and property data. It has generated an incomplete file around 3GB, it is throwing exception  while creating new objects 
The exception is 
"Exception Occurred while creating the cartesian point and the exception message :Array dimensions exceeded supported range."

The last entity created is #36313950
![image](https://user-images.githubusercontent.com/59045029/73631404-e466fe00-467e-11ea-962f-2add94d0fb35.png)

I am creating the store with below options

                 m_model = IfcStore.Create(credentials, XbimSchemaVersion.Ifc2X3, XbimStoreType.InMemoryModel);

I changed storetype to EsentDatabase also but there is no change.

I am commit and begin transaction intermittently, but there is no use.

#### Assemblies and versions affected:

5.1.259.0

#### Steps (or code) to reproduce the issue:

m_model = IfcStore.Create(credentials, XbimSchemaVersion.Ifc2X3, XbimStoreType.InMemoryModel);

create objects in a loop of 10000000 count 

m_model.SaveAs(exportIFCProjectName, StorageType.Ifc);

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Then just drag & drop here*

#### Expected behavior:

we should be able to create large ifc files.

#### Actual behavior or exception details:

Not able to create large ifc files

**Comment by andyward** [comment]
It's hard to say what's going on without seeing the code behind `create objects in a loop of 10000000 count`, or a stack trace

I'm assuming you're running a 64 bit process. 

Both of these are guesses, but worth investigating :


1. Running into .Net's 2GB per object heap limit. See https://stackoverflow.com/a/37530672/5168875 for possible workaround
1. exceeding Int32.MaxValue entries (hard to believe as you're only showing ~36 million elements.)

**Comment by anil1610** [comment]
With the above workaround, it is working fine, hence closing the issue.

**Comment by andyward** [comment]
For reference, what was the workaround? The `gcAllowVeryLargeObjects` config setting?

**Comment by anil1610** [comment]
Yes.. I set gcAllowVeryLargeObjects to true in exe.config
