### ISSUE TITLE
Using Mono 

### ISSUE THREAD

**Issue by VegardAaberge** [xBimTeam/XbimEssentials#32]
I just want to know if it is possible to use mono with XbimEssentials or not. 

With IFC it works allright, but very limited functionality, and not supported. If I use XbimEssentials with this example http://www.overarching.it/wordpress/2014/03/05/xbim-data-investigation-and-export-overarching-2/

Then I first get an error related to Log4Net not being able to find configuration file. When I fix that by adding it in app.config then I get a TypeInitialzationException in  Xbim.IO.IfcPersistedInheritanceCache. This happens in XbimModel model = new XbimModel()

Do I have to use Windows server or is there any alternatives?

**Comment by martin1cerny** [comment]
Hi @VegardAaberge , It should be possible to use xBIM with Mono except for XbimModel. XbimModel is using [Esent database](https://msdn.microsoft.com/en-us/library/office/dn375980%28v=exchg.10%29.aspx) which is present on every Windows as an embedded database. In `develop` branch we developed in-memory model which is obviously platform independent. Also preferred way to open the model now is with `IfcStore.Open()`. `IfcStore` provides IFC specific functionality and can open both IFC2x3 and IFC4. It uses either Esent or in-memory model behind so you are better to specify you want to use the in-memory one.

**Comment by VegardAaberge** [comment]
Thanks for the help. I tried to use ifcStore.Open(), but it says it does not exist in the current context. Is that an ifc4 dependancy? In that case, how can I get the dll file?

**Comment by martin1cerny** [comment]
You need to use `develop` branch.
