### ISSUE TITLE
How to use this in Unity3D

### ISSUE THREAD

**Issue by innocence-ze** [xBimTeam/XbimEssentials#320]
I downloaded this and xbimGeometry from Nuget in visual studio 2019, and it workde. However, when I switched my window into Unity3D(2017/2018/2019), it showed some error about xbim. So I watched the reference of the project in the visual studio but I just found that the reference related to xbim were lost.

![QQ截图20200218213512](https://user-images.githubusercontent.com/24432283/74740878-ba285980-5296-11ea-8a7e-776048a6af65.png)
![QQ截图20200218213524](https://user-images.githubusercontent.com/24432283/74740881-bbf21d00-5296-11ea-89e1-91bdfb51f604.png)
![QQ截图20200218213549](https://user-images.githubusercontent.com/24432283/74741090-2a36df80-5297-11ea-84ef-b9019323c6fc.png)

**Comment by martin1cerny** [comment]
I'm sorry but we don't provide support for Unity3D. However, there are people in the community who are using xBIM with Unity. You can search our GitHub issues for their advice.
https://github.com/xBimTeam/XbimEssentials/issues?utf8=%E2%9C%93&q=is%3Aissue+unity
https://github.com/xBimTeam/XbimGeometry/issues?utf8=%E2%9C%93&q=is%3Aissue+unity

**Comment by innocence-ze** [comment]
Thanks, I have solved this problem by[https://github.com/xBimTeam/XbimGeometry/issues/170](#170 in xbimGeometry)
