### ISSUE TITLE
IfcWall not found by query

### ISSUE THREAD

**Issue by johnnyontheweb** [xBimTeam/XbimEssentials#322]
In some files (not all models) if I perform this query:
`imodel.Instances.OfType(Of IIfcWall)().OfType(Of IfcElement)`
I got empty, but if I perform this:
`imodel.Instances.OfType(Of IIfcWall)()`
I got the elements.

In addition I need to look at Openings property, and when using the second query I cannot cast the IfcWall to IfcElement.

Why this is happening only with some models? Is not IfcWall an IfcElement? How to efficiently cast IfcWall to IfcElement? thanks in advance

#### Assemblies and versions affected:
Xbim.Ifc4.dll v. 5.1.259.0

#### Steps (or code) to reproduce the issue:
I cannot attach the model because it's not mine. Requiesting permission...

**Comment by CBenghi** [comment]
The second type seems to be a concrete class name rather than the
Interface  IIfcElement.
Can you try again changing that?

**Comment by martin1cerny** [comment]
Please, make sure you are not mixing IFC2x3 and IFC4 namespaces. If you use IFC4 interfaces you should be safe and version agnostic as IFC2x3 implements IFC4 interfaces.

**Comment by johnnyontheweb** [comment]
Thanks for both quick responses.
Yes, I'm using IFC4 classes for reading a IFC2X3 file from Revit; I understood from xbim guides that I can use IFC4 interfaces to read both. Is that like this or on the contrary?
However, namespaces are not mixed, see my imports:
`Imports Xbim.Ifc
Imports Xbim.Common
Imports Xbim.Ifc4.Interfaces
Imports Xbim.Ifc4.Kernel
Imports Xbim.Ifc4.SharedBldgElements
Imports Xbim.Ifc4.GeometryResource
Imports Xbim.Ifc4.GeometricConstraintResource
Imports Xbim.Ifc4.ProductExtension
Imports Xbim.Ifc4.ProfileResource
Imports Xbim.Ifc4.MeasureResource
Imports Xbim.Ifc4.RepresentationResource
Imports Xbim.Ifc4.GeometricModelResource
Imports Xbim.Ifc4.MaterialResource
Imports Xbim.Ifc4.StructuralElementsDomain
Imports Xbim.Ifc4.PresentationAppearanceResource`

@CBenghi 
no Openings property for IIfcElement class. Using:
`imodel.Instances.OfType(Of IIfcWall)().OfType(Of IIfcElement)`
the query is successfull, but how to access Openings?

**Comment by CBenghi** [comment]
Use the HasOpenings enumerable from the Interface to get the relations that connect you to the openings.

**Comment by johnnyontheweb** [comment]
Thanks, I have to refactor all my code with interfaces.

**Comment by CBenghi** [comment]
@johnnyontheweb,
yes that's the reccomended practice to make your code future-proof.
It only becomes a bit more difficult when you are writing IFC, but reading should be quite easy.

1) Add the using statement to the ifc4 interfaces namspace.
2) Remove the using statement to the IFC2x3 namespaces from the beginning of the files, and then 
3) add the ```I``` before the types where error messages emerge.

Good luck

**Comment by johnnyontheweb** [comment]
Thanks, that's exactly what I'm doing

**Comment by johnnyontheweb** [comment]
However, I have several difficulties. For example, how to access LengthUnit in interface IIfcUnitAssignment?

**Comment by CBenghi** [comment]
Hi @johnnyontheweb,
I'm closing this issue again because the title topic is resolved.

If you have other questions such as the last one, please open a custom issue, with the background information to help us understand the situation and the intent, which is lacking here.
This will help other people find the information they need.

BTW, when you are converting to interfaces you'll have to look at the schema of ifc4 to understand how to update your code.
Best,
Claudio
