### ISSUE TITLE
Access all data through IFC4 interfaces - LengthUnit of a model

### ISSUE THREAD

**Issue by johnnyontheweb** [xBimTeam/XbimEssentials#324]
I'm trying to access lenght units by reading a IFC2x3 model and using IFC4 interfaces. I cannot understand (and I cannot find a suitable example) how to access the how to access LengthUnit in the interface IIfcUnitAssignment.
Please note that in IfcUnitAssignment is directly accessible. Can you please give some hints on that?

#### Assemblies and versions affected:
5.1

#### Steps (or code) to reproduce the issue:
        Dim Lunit as string ' e.g. mm, m, etc.
        If imodel.Instances.OfType(Of IIfcProject)().Count > 0 Then
            Dim proj = imodel.Instances.OfType(Of IIfcProject)().FirstOrDefault()
            If proj IsNot Nothing Then
                Lunit = ?????
            End If
        End If

#### Expected behavior:

to read the length unit of the project

#### Actual behavior or exception details:

I don't know how to access LengthUnit of the read model.

**Comment by CBenghi** [comment]
I suspect that you could use the Modelfactors property of Imodel.
Does that serve your purpose?

See
https://github.com/xBimTeam/XbimEssentials/blob/315182fb58a54c84f909793c8ed15eb6f8444ffa/Xbim.Common/IModel.cs#L84

**Comment by johnnyontheweb** [comment]
I don't think it suits my needs, I need a replacement for proj.UnitsInContext.LengthUnit.Symbol.
In other words I need the unit of length symbol (m, mm, in, etc.).
In imodel.modelfactors I found only LengthToMetresConversionFactor, which is a double. Is there any alternative?

Is there a sample project that I can use as a reference for reading IFC files with your interfaces?

**Comment by martin1cerny** [comment]
Have a look in IFC4 documentation. xBIM is a complete implementation.

**Comment by johnnyontheweb** [comment]
Docs: https://standards.buildingsmart.org/IFC/RELEASE/IFC4/FINAL/HTML/link/project-units.htm

Same problem again; ho to access? 
`        Dim Lunit as string ' symbol is needed (m, mm, etc.)

        If imodel.Instances.OfType(Of IIfcProject)().Count > 0 Then

            Dim proj = imodel.Instances.OfType(Of IIfcProject)().FirstOrDefault()

            If proj IsNot Nothing Then

                Dim unt As IIfcUnitAssignment = proj.UnitsInContext.Units

                If unt IsNot Nothing Then

                    Lunit = unt.???

                End If

            End If

        End If`

I cannot find a suitable query for unt. What do I need to look for?

**Comment by johnnyontheweb** [comment]
Solved:
`                Dim unt As IItemSet(Of IIfcUnit) = proj.UnitsInContext.Units
                If unt IsNot Nothing Then
                    Lunit = unt.OfType(Of IIfcNamedUnit).Where(Function(u) u.UnitType = IfcUnitEnum.LENGTHUNIT).FirstOrDefault().Symbol
                End If`

**Comment by CBenghi** [comment]
I've attempted a rewrite in c# in case somebody else needs it.
Please not this was not done in the editor and might have syntax errors

```csharp
var tmp = proj.UnitsInContext?.Units?.OfType<IIfcNamedUnit()>.Where(u=> u.UnitType == IfcUnitEnum.LENGTHUNIT).FirstOrDefault();
var Lunit = tmp?.Symbol;
```
