### ISSUE TITLE
Elements missing when reading the IFC.

### ISSUE THREAD

**Issue by BrunoMBuzzi** [xBimTeam/XbimEssentials#325]
I have an IFC file that have all elements shown correctly in Solibri, but it won't open on the Xbim Xplorer, and converting it to wexbim have missing elements

#### Minimal file to reproduce the issue:
[MODPADRAO_SOTAXAS.zip](https://github.com/xBimTeam/XbimEssentials/files/4324749/MODPADRAO_SOTAXAS.zip)

#### Expected behavior:
Have all the elements shown on the viewer with it's properties.

#### Actual behavior or exception details:
Message shown on Xbim Xplorer:
==== 10:47	ERROR	Xbim.IO.Step21.XbimP21Parser
Entity #15337 IFCPRESENTATIONLAYERASSIGNMENT, error at parameter 3-AssignedItems value = #13505=IFCCOLUMN

#### Additional Details
![image](https://user-images.githubusercontent.com/39279756/76532912-0ca00480-6456-11ea-8063-c0c3cedb20ee.png)

Solibri with all elements:
![image](https://user-images.githubusercontent.com/39279756/76532960-1c1f4d80-6456-11ea-88a3-0258f3c406ac.png)

Thanks,
Bruno

**Comment by martin1cerny** [comment]
It is what is says. Invalid IFC file with many errors. Solibri is just **pretending** it is OK but it isn't. There are hundreds of invalid assignments. IfcPresentationLayerAssignment can only contain IfcRepresentation or IfcRepresentationItem subtypes but there are actual products in there. Talk to author of the authoring SW if you can.

**Comment by BrunoMBuzzi** [comment]
> Talk to author of the authoring SW if you can.

I'll do that! Thanks a lot for your prompt reply.
