### ISSUE TITLE
How to add property to a specific entity in ifc2x3

### ISSUE THREAD

**Issue by alex4wtr** [xBimTeam/XbimEssentials#326]
Hello,

I'm trying to add a IfcPropertySingleValue to a specific propertySet of a specific entity. Furthermore it would be even nice to add also a self defined propertySet to the entity. I know it's possible with ifc4 like in the example described: http://docs.xbim.net/examples/basic-model-operations.html 

But whats with ifc 2x3? What is possible?

best regards

**Comment by martin1cerny** [comment]
Just change the namespaces to be Ifc2x3.

**Comment by alex4omnicon** [comment]
Thanks this works well. I thought I don't need to switch the namespaces by using the ifc4 interface. Is there a way to change the namespaces depending on the loaded ifc file (ifc2x3 or ifc4)?

**Comment by martin1cerny** [comment]
You can use 'Create' object which makes creation neutral to both namespaces. Be aware that this only allows creation of objects with reasonable mapping between IFC2x3 and IFC4. But that should be fine for properties and property sets.
