### ISSUE TITLE
Get parent object

### ISSUE THREAD

**Issue by BalintBende** [xBimTeam/XbimEssentials#327]
Hello!

Is it possible to have the parent object of an element?
For example I am going through the building elements and i would like to get building stories ids which it belongs.

Like in case of groups:
```
var systemIds = 
            objectDefinition
              .HasAssignments
              .Cast<IIfcRelAssignsToGroup>()
              .Select(x=>x.RelatingGroup.GlobalId);
```

Thanks in advance!

**Comment by martin1cerny** [comment]
Yes, you can use [IfcElement's](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcelement.htm) `ReferencedInStructures` and `ContainedInStructure`.

**Comment by bekraft** [comment]
There's no strong parent-child relationship in the IFC. You may have more than one parent. Spatial structures inherit from `IIfcSpatialElement` which extends `IIfcObjectDefinition`. Both have parent-child (or super-part) relationships. See [IfcRelContainedInSpatialStructure](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcrelcontainedinspatialstructure.htm) documentation.

```
public static IEnumerable<T> SuperObject<T>(this IIfcObjectDefinition p) where T : IIfcObjectDefinition
{
    return p
        .Decomposes
        .Select(s => s.RelatingObject).OfType<T>().Distinct();
}
```

```
public static IEnumerable<T> Parent<T>(this IIfcObjectDefinition o) where T : IIfcObjectDefinition
{
    var productSupers = o.SuperObject<T>();
    if (o is IIfcProduct p)
        return Enumerable.Concat(productSupers, new IIfcProduct[] { p.IsContainedIn }.OfType<T>()).Distinct();
    else
        return productSupers;
}
```

**Comment by BalintBende** [comment]
Hello guys,

Thank you very much for your answers. It works.
