### ISSUE TITLE
Another odd IFC2  schema name

### ISSUE THREAD

**Issue by prognostic-software** [xBimTeam/XbimEssentials#329]
We have some files from the clients that have Schema name as "IFC2X_FINAL"

This causes exception when opening these files. (see sample file attached)

#### Assemblies and versions affected:

*Which assemblies/packages and their versions are known to be affected. E.g. 

Xbim.Common.5.1.289

#### Steps (or code) to reproduce the issue:

```csharp
using (var model = IfcStore.Open("file.ifc")) //this should already produce exception
{
    ...
}
```

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Th
[Existing - Berth2_Cassions.zip](https://github.com/xBimTeam/XbimEssentials/files/4407982/Existing.-.Berth2_Cassions.zip)
en just drag & drop here*

#### Expected behavior:

File opens without any issue

#### Actual behavior or exception details:

Exception and file does not open with an error message

#### Additional Details

Have tried adding that Schema name and will create pull request. Seems to fix it correctly

**Comment by prognostic-software** [comment]
@martin1cerny It appears I do not have permission as a collaborator.
However, the change seems to be very straightforward
StepModel.cs
LoadStep21
L498
- var old2xSchemaNamesThatAreOK = new[] { "IFC2X2_FINAL", "IFC2X2" };
+ var old2xSchemaNamesThatAreOK = new[] { "IFC2X_FINAL", "IFC2X2_FINAL", "IFC2X2" };

**Comment by martin1cerny** [comment]
As you can see [here](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/), `IFC2X_FINAL` is 20 years old specification and it has been retired by buildingSMART. We use code generation based on *IFC2x3 TC1* and *IFC4 ADD2 TC1* schemas. IFC development team is trying to keep data compatible between versions but it is not always the case. So, while it is possible to read older schemas with some tolerance, it is possible that data will be misleading or incomplete. Therefore, I would advice against this change.

In terms of collaboration, you can use pull requests to contribute to the project or to suggest changes like this.

**Comment by prognostic-software** [comment]
Hi Martin, 

Thanks for the quick feedback. I can understand that this name is not in accordance with the standards. But since there is already some allowance for compatibility made, I thought I would propose this. 

We have over 1000 files received for a project from a client that contain this schema name in the files. These files open with commercial software without any issues (BimVision / Revit). We've also validated the files imported for correctness of data after making this change in xbim, against BimVision to ensure the data is not incomplete otherwise. So this change seems safe and seems to allow us to continue working with the client for the projects.

On side note, I cannot create any branches in this repository, and when I try to push my changes to development branch, I get following error "remote: Permission to xBimTeam/XbimEssentials.git denied to prognostic-software." This is why I couldn't create a pull request.

Regards

**Comment by martin1cerny** [comment]
You are right, we have already allowed some older schemas to get through. Still, be aware of potential unwanted consequences. These might be minor in their extent but large in their impact.

To create a pull request, follow [GitHub instructions here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) please.

**Comment by prognostic-software** [comment]
Ah ha! didn't know I could create a PR from a fork. There you go :)

**Comment by andyward** [comment]
Closing as fixed
