### ISSUE TITLE
Suppress IFC errors to allow convertion to wexBim 

### ISSUE THREAD

**Issue by bbuzzi** [xBimTeam/XbimEssentials#331]
I have some IFC models with errors when I open the Xbim Xplorer, but I can still open them and get other info the user needs. But when I try to convert to wexBim, so the user can check it online, these errors abort the convertion.

#### Steps (or code) to reproduce the issue:
Open an IFC with errors on the Xbim Xplorer.
Try to convert it to wexBim.

#### Expected behavior:
Suppress errors and convert the model to enable the user to see it online, even with errors on it.

#### Actual behavior or exception details:
The IFC file is not converted to wexBim.

#### Additional Details
I'm not sure if it's possible, but from the users perspective, the model can be opened in any other software, also the user received this model from it's suppliers, it's more of a technical problem rather than a business problem, I mean, the user don't care about this error, he just want to see the model, if I can't solve it, he's problably just going to drop using my product.

![image](https://user-images.githubusercontent.com/2326017/78139045-41243200-73fe-11ea-915e-9879ebe5c7ac.png)

**Comment by martin1cerny** [comment]
Which versions of libraries do you use in XbimXplorer? Which versions are you using to convert to wexBIM?

**Comment by martin1cerny** [comment]
Also - what is the error you see? Can you post the exception? Can you share the file (or part of it)?

**Comment by bbuzzi** [comment]
Hello Martin,

This is the exception:
System.AccessViolationException: Tentativa de leitura ou gravação em memória protegida. Normalmente, isso é uma indicação de que outra memória está danificada.
   em BRepBuilderAPI_Sewing.Add(BRepBuilderAPI_Sewing* , TopoDS_Shape* )
   em Xbim.Geometry.XbimCompound.Init(IEnumerable`1 faces, IIfcRepresentationItem theItem, ILogger logger)
   em Xbim.Geometry.XbimCompound.Init(IIfcConnectedFaceSet faceSet, ILogger logger)
   em Xbim.Geometry.XbimCompound.Init(IIfcClosedShell solid, ILogger logger)
   em Xbim.Geometry.XbimCompound.Init(IIfcFacetedBrep solid, ILogger logger)
   em Xbim.Geometry.XbimCompound.Init(IIfcManifoldSolidBrep solid, ILogger logger)
   em Xbim.Geometry.XbimCompound..ctor(IIfcManifoldSolidBrep solid, ILogger logger)
   em Xbim.Geometry.XbimGeometryCreator.Create(IIfcGeometricRepresentationItem geomRep, IIfcAxis2Placement3D objectLocation, ILogger logger)
   em Xbim.Geometry.Engine.Interop.XbimGeometryEngine.Create(IIfcGeometricRepresentationItem ifcRepresentation, ILogger logger) na C:\buildagent_os\_work\1\s\Xbim.Geometry.Engine.Interop\XbimGeometryEngine.cs:linha 74
   em Xbim.ModelGeometry.Scene.Xbim3DModelContext.<>c__DisplayClass39_0.<WriteShapeGeometries>b__0(Int32 shapeId, ParallelLoopState loopState) na C:\buildagent_os\_work\1\s\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:linha 1391
   em System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   em System.Threading.Tasks.Task.InnerInvoke()
   em System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   em System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   em System.Threading.Tasks.Task.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()
   em System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   em System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   em System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   em System.Threading.ThreadPoolWorkQueue.Dispatch()

It happens here:
    var context = new Xbim3DModelContext(model);
    context.CreateContext();

These are the packages I'm using:
![image](https://user-images.githubusercontent.com/2326017/78178330-d858ac00-7435-11ea-8dd4-6873dd9a49b2.png)

As for the IFC, I'll have to get to the client to see if I can share it, or if I can get a part of it, at least.

Appreciate your help.
Thanks!
Bruno.

**Comment by martin1cerny** [comment]
So, this is a geometry issue and has nothing to do with error log from your first screenshot. You are also likely to have different versions in Xplorer because the processing is identical. The best you can do is to isolate the part of geometry causing the exception and opening new issue in XbimGeometry project.

**Comment by bbuzzi** [comment]
What I meant with the first screenshot is that the same IFC that can be opened on Xplorer, can't be converted to wexbim due to some geometry problems, which are handled to still let the user see it on desktop with Xplorer (and other software, like Solibri Viewer and DDS, that I have available on the moment).
I guess that what I was trying to know is if there is a way to convert to wexbim even with geometry errors, cause the same IFC (with errors) can be viewed on desktop.
As for the user's point of view, he's not concerned about technical problems to justify it.
I'm still trying to get his approval to share the model, so I could share here too.
For the moment, I'll try something out with what I have now.

Thanks again,
Bruno.

**Comment by martin1cerny** [comment]
Yes, our strategy is to log errors and process all we can. But geometry processing is a complex task. We are keen to fix issues causing this kind of exception but we need to have the data for that.

**Comment by bbuzzi** [comment]
Hi Martin,

Could I send you an IFC on private?
I could send an e-mail with a downloadable link.
The IFC have 200MB.

Them I could explain again, based on more data, what is happening and what we could do to extract the data as our client need it.

Thanks for your help.
Bruno.

**Comment by CBenghi** [comment]
Hi @bbuzzi,

my preferred alternative  actually to reduce the IFC model isolating a couple of the troublesome elements and then share that part without non-discolosure concerns.
I can show you how to do that using a tool in explorer, if you wish.

Best,
Claudio

**Comment by bbuzzi** [comment]
Hi Claudio,

That would help a lot.
How can I do this? :)

Thanks,
Bruno.

**Comment by CBenghi** [comment]
Send me an email at claudio.benghi@gmail.com, and I'll respond with my
personal contacts.

Cheers,
C

Il Mer 6 Mag 2020, 18:49 Bruno Buzzi <notifications@github.com> ha scritto:

**Comment by bbuzzi** [comment]
I'm a little (too) late on replying here.

Just to close this issue, I've refactored the code, it was opening the model and creating the 3D context on two async tasks, and that was what gave me errors.
