### ISSUE TITLE
[Question] Instances and Interfaces

### ISSUE THREAD

**Issue by nico-planworks** [xBimTeam/XbimEssentials#334]
Im currently working with the XbimEssentials library and im wondering if there is a way extract all IFC types out of a file without having to itertate through all intsances?
Second question, is there an enum or a list of all Interfaces which represent an IFC typ?
Thanks in advance

**Comment by martin1cerny** [comment]
Yes, just iterate over all types:

```cs
foreach (var type in model.Instances.OfType<IIfcTypeObject>())
{
    // do whatever you want
}
```

And no, just use simple reflection:

```cs
var typeInterfaces = typeof(IIfcRoot).Assembly.GetTypes()
    .Where(t => typeof(IIfcTypeObject).IsAssignableFrom(t) && t.IsInterface)
    .ToList();
```

**Comment by nico-planworks** [comment]
Thanks a lot for the fast reply.
