### ISSUE TITLE
ReadShapeTriangulation

### ISSUE THREAD

**Issue by JackMoljerc** [xBimTeam/XbimEssentials#338]
The Unity WebGL can't support the Class BinaryReader. 
Could you please tell me how to get the way to replace the ReadShapeTriangulation?

**Comment by andyward** [comment]
I might be missing something as I'm not a Unity user, but in what way doesn't it support BinaryReader? It seems to be in supported in all .net framework and .netstandard/code implementations.

Ultimately BinaryReader just reads a binary file (a wexbim file in this case), so you could re-implement the same code with another approach for reading binary files.

https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Common/XbimExtensions/BinaryReaderExtensions.cs

**Comment by JackMoljerc** [comment]
Thank you so much. I will try. The Unity WebGL can't support System.IO.I must download the whole file.Maybe I was not found a right way.
