### ISSUE TITLE
SideWall or FrontWall

### ISSUE THREAD

**Issue by tthmartin** [xBimTeam/XbimEssentials#339]
Hello, I'm asking for help once again. Thank you once again for the last time you've helped me. Now I have an issue determining if the selected wall(SelectedEntityChanged) is a side wall or a front wall. I thought I could be able to determine this by it's coordinates, but I've come to a dead end. I don't really know, if a wall has something like a direction vector or some property from which, you can say it's a sidewall or not. Thank you in advance for your help!

**Comment by bekraft** [comment]
Hi. What do you mean by "side" and "front"? A "lateral"/"frontal" wall of another one? In this case you are dealing with spatial relations where you have to define the counter part (lateral of what?). Being in front also implies a view vector (what is front or back since everything is lateral). There's no functionality out of the box. The only (crude) simplification would be to map each component to single point and use a circular compass rule (east is 0, north is pi/2 and so on). But this also assumes small components (otherwise you may have multiple answers and have to deal with "partially"). Hope this answer will help you a bit ...

**Comment by tthmartin** [comment]
Yes, I meant lateral or frontal wall. So when I click on an entity, my program has to decide if its a lateral wall or not, if is a lateral wall do something. I do not know how is that possible, can you explain it to me in more details? Thank you for your help!

**Comment by CBenghi** [comment]
Hello,
Can you show on a drawing what you mean by lateral and frontal wall?
Does it depend on the viewpoint?
Thanks

Il Sab 13 Giu 2020, 08:29 tthmartin <notifications@github.com> ha scritto:

**Comment by tthmartin** [comment]
![image](https://user-images.githubusercontent.com/65157122/84571935-fa0bd300-ad96-11ea-8962-c6c11175b3e3.png)
From the image you can see that the lateral means R or L side(on the viewport cube) and frontal means B. My program has to decide if the selected wall is a lateral or not, but I don't have a clue how.

**Comment by bekraft** [comment]
The most simple solution would be to tag the walls with your own properties for indicating an external frontal or external lateral wall. That‘s completely without geometry. Any other solution depends on geometrical assumptions. Here you have polygonal planar walls only. If you get the normal of the largest face per wall, it would be a indication vector pointing right (R) or back (B).

**Comment by tthmartin** [comment]
This is a great idea, but I want my program to work with any ifc file, not just the one I'm testing it with.

**Comment by CBenghi** [comment]
Another solution could be the projection of the shape onto orthogonal
planes to evaluate the relative size.

That would deal with curved walls too, but of course there are cases where
it breaks down.

I think you need to clarify what the business logic is. At this stage the
purpose of this query totally escapes me.

Best,
Claudio

Il Dom 14 Giu 2020, 07:25 tthmartin <notifications@github.com> ha scritto:

**Comment by bekraft** [comment]
I cannot imagine the purpose this query, too.  Frontal and lateral depends on the orientation of the building; and generic building models will likely produce more than one classification (i.e. partially frontal and partially lateral) as long as you don't have a trusted threshold (for instance 60% wins...). The proposed approach of @CBenghi is great, but with four planes (L/R/B/F) you'll get two completely equal projection. So you'll need 1d-depth sorting - welcome to world of computational geometry. My advice: clarify your goal and then take a deep dive into computational geometry and spatial indexing / reasoning / what ever. More generic isn't possible at this stage.

Cheers,
Bernold

**Comment by andyward** [comment]
Closing as there's no obvious issue or feature here. I suppose we could look to better provide some 'projection' features.
