### ISSUE TITLE
Find all elements with a certain property

### ISSUE THREAD

**Issue by JohnO3535** [xBimTeam/XbimEssentials#340]
How can I use xBim to search an IFC (2x3 in this case) file to return all elements with a certain property or property set?

For example, I have a wall, door and window that all have a property set name "MySpecialData" with a single property "SpecialValue".

How can I get the ids of the wall, door and window so that I can process the contents of "SpecialValue".

Thank you for your help!

**Comment by martin1cerny** [comment]
Have a look at [basic model operations](https://docs.xbim.net/examples/basic-model-operations.html) to see how to retrieve properties for any element. You just need to invert the code.

**Comment by Kilian941** [comment]
There are some good examples to get started with xBIM: https://docs.xbim.net/examples/basic-model-operations.html

A solution for your issue can look like this:

```csharp 
using (var model = IfcStore.Open(fileName))
{
    //get all elements
    var allElements = model.Instances.OfType<IfcBuildingElement>();

    // This should work using Linq:
    IEnumerable<IfcBuildingElement> propElements = from element in allElements 
                                     where element.GetPropertySingleValue("MySpecialData","SpecialValue")!=null) 
                                     select element;
   
}
```

**Comment by JohnO3535** [comment]
Thanks Kilian941  That worked exactly as I needed it to.

> 
> 
> There are some good examples to get started with xBIM: https://docs.xbim.net/examples/basic-model-operations.html
> 
> A solution for your issue can look like this:
> 
> ```cs
> using (var model = IfcStore.Open(fileName))
> {
>     //get all elements
>     var allElements = model.Instances.OfType<IfcBuildingElement>();
> 
>     // This should work using Linq:
>     IEnumerable<IfcBuildingElement> propElements = from element in allElements 
>                                      where element.GetPropertySingleValue("MySpecialData","SpecialValue")!=null) 
>                                      select element;
>    
> }
> ```

**Comment by andyward** [comment]
Just a word of caution that the approach above may not perform brilliantly on larger models. If you think of it like a SQL query you're going to start by enumerating all Building Elements (there could 10's or 100's of thousands?);  then look up the property you want for each one, before finally checking the value to filter down just the elements you want. GetPropertySingleValue() is hiding quite a bit of effort & I/O...

Where the property you're querying is reasonably 'selective' you might want to invert the query, as Martin suggests, so you start looking for the matching pset values, and then list the elements they apply to.  e.g. here's how you could do it

``` csharp
using Xbim.Common;
using Xbim.Ifc;
using Xbim.Ifc4.Interfaces;

// snip

var fileName="your.ifc";
using (var model = IfcStore.Open(fileName))
{

	IEnumerable<int> matchingElements = from i in model.Instances.OfType<IIfcRelDefinesByProperties>()
// Find all properties in Pset called 'Dimensions' with 'Area' > 20.5
		where i.RelatingPropertyDefinition is IIfcPropertySet
		let pset = i.RelatingPropertyDefinition as IIfcPropertySet
		where pset.Name == "Dimensions"
		let property = pset.HasProperties.OfType<IIfcPropertySingleValue>().FirstOrDefault(v => v.Name == "Area")
		where property?.NominalValue is IExpressRealType
		where ((IExpressRealType)property.NominalValue).Value > 20.5d
// Now get the elements
		from element in i.RelatedObjects
		select element.EntityLabel;
}
```
While it looks more complex you've got a lot more control. And it should be a lot easier on I/O, memory etc

**Comment by JohnO3535** [comment]
Thanks!  Right now I am not actually sure how big the files will be that I am dealing with.  I only have the 1 requirement which is to find the specified property and process it for every element that has it.  I just heard about xBim on Monday so any help is a LOT of help!  And what you say makes a lot of sense.  I will definitely implement it this way and let you know if I have any further questions.

> 
> 
> Just a word of caution that the approach above may not perform brilliantly on larger models. If you think of it like a SQL query you're going to start by enumerating all Building Elements (there could 10's or 100's of thousands?); then look up the property you want for each one, before finally checking the value to filter down just the elements you want. GetPropertySingleValue() is hiding quite a bit of effort & I/O...
> 
> Where the property you're querying is reasonably 'selective' you might want to invert the query, as Martin suggests, so you start looking for the matching pset values, and then list the elements they apply to. e.g. here's how you could do it
> 
> ```cs
> using Xbim.Common;
> using Xbim.Ifc;
> using Xbim.Ifc4.Interfaces;
> 
> // snip
> 
> var fileName="your.ifc";
> using (var model = IfcStore.Open(fileName))
> {
> 
> 	IEnumerable<int> matchingElements = from i in model.Instances.OfType<IIfcRelDefinesByProperties>()
> // Find all properties in Pset called 'Dimensions' with 'Area' > 20.5
> 		where i.RelatingPropertyDefinition is IIfcPropertySet
> 		let pset = i.RelatingPropertyDefinition as IIfcPropertySet
> 		where pset.Name == "Dimensions"
> 		let property = pset.HasProperties.OfType<IIfcPropertySingleValue>().FirstOrDefault(v => v.Name == "Area")
> 		where property?.NominalValue is IExpressRealType
> 		where ((IExpressRealType)property.NominalValue).Value > 20.5d
> // Now get the elements
> 		from element in i.RelatedObjects
> 		select element.EntityLabel;
> }
> ```
> 
> While it looks more complex you've got a lot more control. And it should be a lot easier on I/O, memory etc
