### ISSUE TITLE
Adding Ironing to the model

### ISSUE THREAD

**Issue by tthmartin** [xBimTeam/XbimEssentials#342]
Hello, I've been searching the forums and the documentations about XBIM and I couldn't find out how can I add a IfcReinforcingBar to a wall, slab etc... Thank you in advance for your help!

**Comment by martin1cerny** [comment]
What kind of data do you have to create these reinforcing bars?

**Comment by martin1cerny** [comment]
This is an [example showing how to create a wall](https://docs.xbim.net/examples/proper-wall-in-3d.html). You will need to do similar thing to create your reinforcing bars (create the element, create its geometry, create its placement and optionally use relations to define more context).

**Comment by tthmartin** [comment]
Hi. I would like to make an app that can create the Ironing to a model without IfcReinforcingBar. I am using Ifc2x3 Kernel and I saw that only with Ifc4 Kernel I am able to use building.AddElement(). Is there any chance to add a Rebar to a model in Ifc2x3?

**Comment by martin1cerny** [comment]
`AddElement()` is just a very simple extension method. You will be better to implement it yourself anyway to keep the result concise. You just need to create `IfcRelContainedInSpatialStructure`, set `RelatingStructure` to the building (or the floor or the space) and add all your reinforcing bars to `RelatedElements`.
