### ISSUE TITLE
Problem with xBIM write performance

### ISSUE THREAD

**Issue by arunprakash86** [xBimTeam/XbimEssentials#345]
We are using version 5.1.274. In our .net code, we are populating a few thousand property in an IFC file, in the IfcPropertySet. We are doing it for IfcProject, IfcSite, and IfcSpace. The most number of properties are of IfcSpace. What we are observing is, if we write the same amount of data in a smaller IFC file, it is faster, but for a larger IFC file, it is taking a huge amount of time. Is this behaviour expected?

Example: To write in a 63 MB file - Took 13 mins
                To write in a 430 MB file - Took almost 85~95 mins

Can anyone throw some light on this?

**Comment by martin1cerny** [comment]
Hi @arunprakash86, this is certainly not the expected level of performance. For this kind of task you should always be within seconds. There are quite many factors which can have effect on this. Constant search for values using inverse properties is for example very expensive. Can you post a code snippet with the minimal implementation which we could evaluate? 

My test example:
```cs
var editor = new XbimEditorCredentials
{
    ApplicationDevelopersName = "xbim developer",
    ApplicationFullName = "xbim toolkit",
    ApplicationIdentifier = "xbim",
    ApplicationVersion = "4.0",
    EditorsFamilyName = "Santini Aichel",
    EditorsGivenName = "Johann Blasius",
    EditorsOrganisationName = "Independent Architecture"
};

using (var model = IfcStore.Create(editor, Xbim.Common.Step21.XbimSchemaVersion.Ifc4, XbimStoreType.InMemoryModel))
{
    var i = model.Instances;
    using (var txn = model.BeginTransaction("Spaces creation"))
    {
        // create 100 testing spaces
        var spaces = Enumerable.Range(1, 100)
            .Select(n => i.New<IfcSpace>(s => s.Name = $"Space {n:D3}"))
            .ToList();

        var psetNames = Enumerable.Range(0, 100)
            .Select(n => $"XBIM_Automated_Test_{n:D3}")
            .ToList();
        var pNames = Enumerable.Range(0, 100)
            .Select(n => $"Property {n:D3}")
            .ToList();
        var pValues = Enumerable.Range(0, 100)
            .Select(n => $"Value {n:D3}")
            .ToList();

        // start measuring the time
        var w = Stopwatch.StartNew();
        foreach (var space in spaces)
        {
            foreach (var psetName in psetNames)
            {
                var properties = pNames
                    .Zip(pValues, (n, v) => (new { name = n, value = v }))
                    .Select(property => i.New<IfcPropertySingleValue>(p => {
                        p.Name = property.name;
                        p.NominalValue = new IfcLabel(property.value);
                    }))
                    .ToList();
                i.New<IfcRelDefinesByProperties>(r =>
                {
                    r.RelatedObjects.Add(space);
                    r.RelatingPropertyDefinition = i.New<IfcPropertySet>(ps =>
                    {
                        ps.Name = psetName;
                        ps.HasProperties.AddRange(properties);
                    });
                });
            }
        }
        w.Stop();
        Console.WriteLine($"{spaces.Count * psetNames.Count} property sets and {spaces.Count * psetNames.Count * psetNames.Count} properties created in {w.ElapsedMilliseconds}ms");
        txn.Commit();
    }

    var fileName = "spaces_with_properties.ifc";
    var sw = Stopwatch.StartNew();
    model.SaveAs(fileName);
    sw.Stop();

    var info = new FileInfo(fileName);
    Console.WriteLine($"Model saved in {sw.ElapsedMilliseconds}ms. File size {info.Length}B");
}
```

In this example, 10,000 property sets and 1,000,000 properties were created and assigned in 4.4 seconds. Resulting 84MB file was saved in 3 seconds.

```
10000 property sets and 1000000 properties created in 4407ms
Model saved in 3151ms. File size 84497635B
```

In your case, there will be some time needed to open the original file but that is at least 10MB/s which adds 6 seconds for your smaller file. This is about all you can count on xBIM side. The rest is your application logic.

**Comment by arunprakash86** [comment]
> Hi @arunprakash86, this is certainly not the expected level of performance. For this kind of task you should always be within seconds. There are quite many factors which can have effect on this. Constant search for values using inverse properties is for example very expensive. Can you post a code snippet with the minimal implementation which we could evaluate?
> 
> My test example:
> 
> ```cs
> var editor = new XbimEditorCredentials
> {
>     ApplicationDevelopersName = "xbim developer",
>     ApplicationFullName = "xbim toolkit",
>     ApplicationIdentifier = "xbim",
>     ApplicationVersion = "4.0",
>     EditorsFamilyName = "Santini Aichel",
>     EditorsGivenName = "Johann Blasius",
>     EditorsOrganisationName = "Independent Architecture"
> };
> 
> using (var model = IfcStore.Create(editor, Xbim.Common.Step21.XbimSchemaVersion.Ifc4, XbimStoreType.InMemoryModel))
> {
>     var i = model.Instances;
>     using (var txn = model.BeginTransaction("Spaces creation"))
>     {
>         // create 100 testing spaces
>         var spaces = Enumerable.Range(1, 100)
>             .Select(n => i.New<IfcSpace>(s => s.Name = $"Space {n:D3}"))
>             .ToList();
> 
>         var psetNames = Enumerable.Range(0, 100)
>             .Select(n => $"XBIM_Automated_Test_{n:D3}")
>             .ToList();
>         var pNames = Enumerable.Range(0, 100)
>             .Select(n => $"Property {n:D3}")
>             .ToList();
>         var pValues = Enumerable.Range(0, 100)
>             .Select(n => $"Value {n:D3}")
>             .ToList();
> 
>         // start measuring the time
>         var w = Stopwatch.StartNew();
>         foreach (var space in spaces)
>         {
>             foreach (var psetName in psetNames)
>             {
>                 var properties = pNames
>                     .Zip(pValues, (n, v) => (new { name = n, value = v }))
>                     .Select(property => i.New<IfcPropertySingleValue>(p => {
>                         p.Name = property.name;
>                         p.NominalValue = new IfcLabel(property.value);
>                     }))
>                     .ToList();
>                 i.New<IfcRelDefinesByProperties>(r =>
>                 {
>                     r.RelatedObjects.Add(space);
>                     r.RelatingPropertyDefinition = i.New<IfcPropertySet>(ps =>
>                     {
>                         ps.Name = psetName;
>                         ps.HasProperties.AddRange(properties);
>                     });
>                 });
>             }
>         }
>         w.Stop();
>         Console.WriteLine($"{spaces.Count * psetNames.Count} property sets and {spaces.Count * psetNames.Count * psetNames.Count} properties created in {w.ElapsedMilliseconds}ms");
>         txn.Commit();
>     }
> 
>     var fileName = "spaces_with_properties.ifc";
>     var sw = Stopwatch.StartNew();
>     model.SaveAs(fileName);
>     sw.Stop();
> 
>     var info = new FileInfo(fileName);
>     Console.WriteLine($"Model saved in {sw.ElapsedMilliseconds}ms. File size {info.Length}B");
> }
> ```
> 
> In this example, 10,000 property sets and 1,000,000 properties were created and assigned in 4.4 seconds. Resulting 84MB file was saved in 3 seconds.
> 
> ```
> 10000 property sets and 1000000 properties created in 4407ms
> Model saved in 3151ms. File size 84497635B
> ```
> 
> In your case, there will be some time needed to open the original file but that is at least 10MB/s which adds 6 seconds for your smaller file. This is about all you can count on xBIM side. The rest is your application logic.

Hi @martin1cerny ,

Thank you for your response. I appreciate it. As you rightly said, I think I must give some more information on the scenario.

1. We have an already existing IFC of the size 420 MB.
2. We load it into the model
3. From the the database, we get some user specific values pertaining to the IfcSpaces.
4. Our application logic does not create IfcSpaces, we only edit the already existing IfcSpaces in the IFC file/model
5. We have around 400 properties which must be written under various propertyset/headers.
6. We are checking if the property header exists, we write the property under it. Else, create the propertyset and then write the property
6a. If the property under the propertyset is already there, we must update it as creating it again will result in duplicate.
7. The number of IfcSpaces involved are 544.
8. We tried writing all the 544 in parallel for each as well as regular for each. 


The following is our code snippet.
`private void AddOrUpdatePropetyToIfcFile(Xbim.Ifc.IfcStore model, IfcObject ifcObject, IFCPropertyDetails propdetail,
            string paramNameDB, bool isIFCPropertyHeader, string ifcPropertyHeaderName)
        {

            ////lock (ifcObject)
            ////{
            lock (model)
            {
                var txn = model.BeginTransaction($"{ifcObject.Name} modification");
                using (txn)
                {

                    if (!isIFCPropertyHeader)
                    {
                        if (string.Compare(paramNameDB, TranslatorConstants.BuildingName, comparisonType: StringComparison.OrdinalIgnoreCase) == 0)
                        {
                            ifcObject.Name = propdetail.PropertyValue;
                        }
                        else if (string.Compare(paramNameDB, TranslatorConstants.ProjectName, comparisonType: StringComparison.OrdinalIgnoreCase) == 0)
                        {
                            ifcObject.Name = propdetail.PropertyValue;
                        }
                        else if (string.Compare(paramNameDB, TranslatorConstants.ZoneName, comparisonType: StringComparison.OrdinalIgnoreCase) == 0)
                        {
                            IfcSpace ifcSpace = ifcObject as IfcSpace;
                            ifcSpace.LongName = propdetail.PropertyValue;
                            ifcSpace.Name = propdetail.PropertyValue;
                        }
                    }
                    else
                    {
                        var isIFCPropertyHeaderNameExist = ifcObject.PropertySets.Any(x => string.Compare(x.Name, ifcPropertyHeaderName, comparisonType: StringComparison.OrdinalIgnoreCase) == 0);
                        if (isIFCPropertyHeaderNameExist)
                        {
                            var ifcPropertySet = ifcObject.PropertySets.Where(x => x.Name == ifcPropertyHeaderName).FirstOrDefault();
                            //.FirstOrDefault().HasProperties.Where(x => x.Name == translatorParameterMapping.IFCPropertyName).FirstOrDefault();
                            var ifcProperties = ifcPropertySet.HasProperties.Where(x => x.Name == propdetail.PropertyName).FirstOrDefault();

                            if (ifcProperties != null)
                            {

                                var ifcProperty = ifcProperties as IfcPropertySingleValue;
                                ifcProperty.NominalValue = new IfcLabel($"{propdetail.PropertyValue}");

                            }
                            else
                            {
                                ifcPropertySet.HasProperties.Add(model.Instances.New<IfcPropertySingleValue>(p =>
                                {
                                    p.Name = $"{propdetail.PropertyName}";
                                    p.NominalValue = new IfcLabel(propdetail.PropertyValue);
                                }));
                            }


                        }
                        else
                        {

                            //create new property set with two properties
                            var pSetRel = model.Instances.New<IfcRelDefinesByProperties>(r =>
                            {
                                r.GlobalId = IfcGloballyUniqueId.FromGuid(Guid.NewGuid());
                                lock (propdetail)
                                {
                                    r.RelatingPropertyDefinition = model.Instances.New<IfcPropertySet>(pSet =>
                                    {
                                        pSet.Name = ifcPropertyHeaderName;
                                        //all collections are always initialized
                                        pSet.HasProperties.Add(model.Instances.New<IfcPropertySingleValue>(p =>
                                        {
                                            p.Name = $"{propdetail.PropertyName}";
                                            p.NominalValue = new IfcLabel(propdetail.PropertyValue);
                                        }));

                                    });
                                }
                            });

                            pSetRel.RelatedObjects.Add(ifcObject);

                        }
                    }

                    txn.Commit();

                }

            }
            //}
        }
`

**Comment by martin1cerny** [comment]
Parallel writing with locking is definitely a bad idea. Also, while sequential search for property set and property by name is OK for a single call, it is detrimental if you call this frequently, leading to exponential complexity. You should analyse your data sequentially first (that might also be multithreaded) and than change all in one go sequentially in a single thread.

**Comment by arunprakash86** [comment]
Thank you  @martin1cerny . I have the following questions for understanding the xBIM library better,

1. Will the logic to find PropertySet/Property or writing a new property increase with the increase in model/file size? I am thinking that smaller files are quicker than larger files. Does the xBIM library take a longer time to traverse nodes compared to smaller files?

2. You have mentioned exponential complexity in my logic. Is that a factor of the IFC file/model size? Does it depend on it?

I am observing that, given some data and the application logic, the time taken for a larger IFC file is much longer than a smaller file.

Once again, thanks for your responses. Appreciate it.

**Comment by andyward** [comment]
What `IModel` implementation are you using? By default in xbim v5+ it will only use the `MemoryModel` storage, which doesn't have any indexing support, particularly for inverses. As data sets get larger I'd expect the naive memory mode to exhibit O(n2) [or worse] performance on these kinds of looping algorithms. i.e. double the number of records and it gets 4x slower.

On Windows, with larger models, using the `EsentModel` implementation should have much better read performance due to the indexing on 'Inverse' properties. EsentModel is not enabled by default. See https://github.com/xBimTeam/XbimEssentials#updating-from-prior-versions for how to change this.

**Comment by arunprakash86** [comment]
@andyward  Thank you for your reply. We tried to use EsentModel, but as you said, we are using .Net core and the implementation is a part of an API. I guess "UserHeuristicModelProvider" option is not available for .net core APIs.

Also, do you think that increase the RAM or the cores will help in this situation? We are testing this in 8 CPU, 16GB machine.

**Comment by andyward** [comment]
If you're using netcore on Windows I think we should be able to support Esent, as the [latest release](https://github.com/microsoft/ManagedEsent/issues/9) is netstandard compatible. I'll have a quick look at this as it should be low risk. If you're running netcore on Linux, I don't think there's a quick answer.

But that will explain your performance issues.

You'll have to profile your service. But for a 420MB IFC file,16GB should be plenty  - even doing everything in-memory. (If you see memory creeping up after the initial , make sure you're disposing correctly)

Unless you're multi-threading the reads more CPUs won't help - faster CPUs, cache and RAM might but only marginal I'd guess.

I'll get back to you on Esent support in netcore.

**Comment by martin1cerny** [comment]
Even just using MemoryModel, there are ways to improve the performance. For start, you should split your application logic and create a dictionary lookup for all your properties in one go, using built-in mechanism for inverse relation cache like this:

```cs
using (var cache = model.BeginInverseCaching())
{
    // do all analytics and caching to keep fast search indices in dictionaries and hash sets
}
```

This has to run outside of transaction. Then, use these lookups (with string names as keys) in your actual code. That will reduce processing time significantly.

**Comment by arunprakash86** [comment]
@martin1cerny : Thank you for your inputs. I will look at this option of caching. I was actually trying to build my own cache and I didn't know about this built-in mechanism. While I look, if there is a sample code already, I can look into it.

**Comment by martin1cerny** [comment]
No, there is no sample for this. It is specific to your application. What I described earlier are general concepts and principles. Also, you might want to use [performance profiling](https://docs.microsoft.com/en-us/visualstudio/profiling/beginners-guide-to-performance-profiling?view=vs-2019) in Visual Studio.

**Comment by arunprakash86** [comment]
@martin1cerny @andyward Thank you for your kind suggestions.  By accessing the property-set and the corresponding properties, we were able to reduce a lot of time. The key was to access the property-header once and not back and forth.

**Comment by andyward** [comment]
I also put out support for Esent on netcore last week #346 . This is in the Essentials develop branch if you wanted to try out on a Windows machine. This may help - or may not (there's a cost building the Esent index etc), and it sounds like caching has been a big benefit, so I/O may be less of a factor now.

**Comment by mmmggg** [comment]
> Even just using MemoryModel, there are ways to improve the performance. For start, you should split your application logic and create a dictionary lookup for all your properties in one go, using built-in mechanism for inverse relation cache like this:
> 
> ```cs
> using (var cache = model.BeginInverseCaching())
> {
>     // do all analytics and caching to keep fast search indices in dictionaries and hash sets
> }
> ```
> 
> This has to run outside of transaction. Then, use these lookups (with string names as keys) in your actual code. That will reduce processing time significantly.

Can this be used to populate some dictionaries at the time of parsing or context creation (file loading) just to use the same = time?
Can anyone show and small sample of how this mechanism cand be used optimally?

**Comment by martin1cerny** [comment]
IFC has a concept of inverse attributes which is used to access object relations bi-directionally. Common example is [IfcObject.IsDefinedBy](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcobject.htm). When you access this (read-only) property, xbim has to run this query internally: `model.Instances.Where<IfcRelDefinesByProperties>(r => r.RelatedObjects.Contains(this))`. So, this has to go through **all** instances of `IfcRelDefinesByProperties` in the model and compare objects in `RelatedObjects` list with the current entity. This is fine is you do it once, but is computing-expensive if you do it repeatedly. Because you are searching in a list of lists, it is actually exponential. One option is to restructure your code so that it doesn't use inverse attributes at all and is maintaining own lookups for performance. `model.BeginInverseCaching()` is doing this for you. So, once you access `IfcObject.IsDefinedBy` it creates lookup dictionary for all `IfcRelDefinesByProperties`. You pay some cost with the first call, but all subsequent calls on any instance of `IfcObject.IsDefinedBy` are almost instant. You can run a simple test on some large model:

```cs
private static void RunInverseSearch(IModel model)
{

    void usingInverseAttributes()
    {
        var noObjects = 0;
        var noRelations = 0;
        foreach (var obj in model.Instances.OfType<IIfcObject>())
        {
            var relCount = obj.IsDefinedBy.Count();
            if (relCount > 0)
            {
                noObjects++;
                noRelations += relCount;
            }
        }
        Log.Information($"Number of IfcObject instances with properties: {noObjects}");
    }

    void notUsingInverseAttributes()
    {
        var result = new HashSet<int>();
        foreach (var rel in model.Instances.OfType<IIfcRelDefinesByProperties>())
        {
            foreach (var obj in rel.RelatedObjects.OfType<IIfcObject>())
            {
                result.Add(obj.EntityLabel);
            }
        }
        Log.Information($"Number of IfcObject instances with properties: {result.Count}");
    }

    var w = Stopwatch.StartNew();
    using (var cache = model.BeginInverseCaching())
    {
        usingInverseAttributes();
        w.Stop();
        Log.Information($"Task duration WITH inverse caching, using inverse attributes: {w.ElapsedMilliseconds}ms");
    }

    using (var cache = model.BeginInverseCaching())
    {
        w.Restart();
        notUsingInverseAttributes();
        w.Stop();
        Log.Information($"Task duration WITH inverse caching, NOT using inverse attributes: {w.ElapsedMilliseconds}ms");
    }

    w.Restart();
    usingInverseAttributes();
    w.Stop();
    Log.Information($"Task duration WITHOUT caching, using inverse attributes: {w.ElapsedMilliseconds}ms");

    w.Restart();
    notUsingInverseAttributes();
    w.Stop();
    Log.Information($"Task duration WITHOUT caching, NOT using inverse attributes: {w.ElapsedMilliseconds}ms");

}
```

```
[09:19:05 INF] File size: 104.06MB
[09:19:13 INF] Number of IfcObject instances with properties: 968
[09:19:13 INF] Task duration WITH inverse caching, using inverse attributes: 35ms
[09:19:13 INF] Number of IfcObject instances with properties: 968
[09:19:13 INF] Task duration WITH inverse caching, NOT using inverse attributes: 14ms
[09:19:17 INF] Number of IfcObject instances with properties: 968
[09:19:17 INF] Task duration WITHOUT caching, using inverse attributes: 3609ms
[09:19:17 INF] Number of IfcObject instances with properties: 968
[09:19:17 INF] Task duration WITHOUT caching, NOT using inverse attributes: 5ms
```

This kind of caching is obviously mutually exclusive with transactions. And it has a cost on the initial call and consumes memory. If you design your code not to use inverse attributes, you don't need it at all. That is why you have to decide based on your use case and use it explicitly when needed.

**Comment by mmmggg** [comment]
Thank you @martin1cerny for the detailed explanation.
A wonderful and really useful feature. Works great when you mostly work with the Properties of the objects.
Thank you for taking the time to post the sample. It was very helpful to understand the usage of the InverseCache.

**Comment by mmmggg** [comment]
Is there any chance this inverse cache can be applied when retrieving geometry representations?
I am doing a select all for ~3000 entities and the method selecting them takes quite long:

DwingControl:> <GetSelectionGeometry()>: newVal: 203. Calling method: HighlighSelected. (1)
DrawingControl:> Getting geometry for Selection: Selection count: 3125. (1)
DrawingControl:> </GetSelectionGeometry()>. Elapsed: **20867ms**. (1)

**Comment by martin1cerny** [comment]
Inspect the code and check if it uses inverse relations. If it does, inverse cache will help. If it doesn't, the bottleneck is somewhere else. You can use performance profiling in VS to see where is the bottleneck. Or, you can try to use inverse cache if it makes any difference.

**Comment by mmmggg** [comment]
Thank you for your answer.
I tried using the inverse cache but it did not help.
I am now profiling the app and try to locate the bottleneck.
Thank you again for your help.

Below a PrintScreen from dotTrace.
![image](https://user-images.githubusercontent.com/230109/104586697-7983bc80-566e-11eb-801b-b992b98d0799.png)

**Comment by mmmggg** [comment]
Just dropping this info here.
For implementing a SelectAll entities functionality, I used the **GetSelectionGeometry** method of the **DrawingControl3D**.
This method is used by the **HighlighSelected** to show the current selection.

The **GetSelectionGeometry** returns a **WpfMeshGeometry3D** that works fine for small numbers of entities (in my specific case, lower than 400). However, when selecting thousands, the mesh gets really big and the performance drops with the increase in the size of the if **PositionCount** and **TriangleIndexCount** collections.

The **BuildScene** method of the **SurfaceLayerStyler** uses an optimization when getting all geometries to render:
```
// replace target mesh beyond suggested size
// https://docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/maximize-wpf-3d-performance 
                                if (targetMergeMeshByStyle.PositionCount > 20000
                                    ||
                                    targetMergeMeshByStyle.TriangleIndexCount > 60000
                                )
```

So, it seems, that one way to implement SelectAll and take advantage of this optimization would be to modify the **GetSelectionGeometry** to return the meshes in a **Model3DGroup** instead of a single really large mesh.

When selecting about 3000 entities I was getting the following item count in the **WpfMeshGeometry3D** collections:
```
_unfrozenPositions: 263896, 
_unfrozenNormals: 263896, 
_unfrozenIndices: 629484
```

Related issue: https://github.com/xBimTeam/XbimWindowsUI/issues/116

**Comment by martin1cerny** [comment]
Dear @mmmggg, this is completely unrelated to this issue topic. Consider other place to post this please.
