### ISSUE TITLE
[Question] Stackoverflow exception while using InserCopy approach

### ISSUE THREAD

**Issue by bekraft** [xBimTeam/XbimEssentials#349]
I'm getting into trouble while transforming an IFC4 file into a new one by using the Model.InsertCopy approach. It exclusively uses recursion. In a test model with lots of property sets and properties which are spread throughout the model's objects and and reused in different sets, the process hit the stack threshold. 

Turning off inverse relations while copying might solve things, but I guess it only shifts the issue into future ... Models are getting bigger and bigger ;-)

Is there anything planned to turn the recursion into a non-recursive algorithm using stacks, queues whatever ?

**Comment by martin1cerny** [comment]
Do you use a single instance of the `XbimInstanceHandleMap`?

**Comment by bekraft** [comment]
Yes, I do. Does this have an impact?

**Comment by martin1cerny** [comment]
It makes sure that one object doesn't expand into many (one per use). But single instance is OK. You are right that the best would be to refactor the code to be non-recursive using processing queue or stack. Feel free to create a pull request. The function you will want to refactor is [here](https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Common/ModelHelper.cs#L365).

**Comment by bekraft** [comment]
Many thanks! For now I could fix the issue by terminating the recursion. I skip the inverse relationships since I have to scan the whole model anyway. So it's done by setting the direct relations. I'll will do a try to refactor the algorithm and let you know, if there's any success. 
Cheers,
Bernold

**Comment by andyward** [comment]
Worth noting there's a separate implementation of `InsertCopy` at https://github.com/xBimTeam/XbimEssentials/blob/8555eb3be90f9fb06711e6347c546a67ce9a36a7/Xbim.Ifc/Extensions/IfcStoreCopyItemsExtensions.cs#L29

... which is a bit simpler and may be easier to refactor that the ModelHelper version.

**Comment by martin1cerny** [comment]
This is a higher order implementation specialised for `IfcProduct`s, which uses `ModelHelper` internally anyway.

**Comment by youshengCode** [comment]
Hi everyone, is there any update about this?

I ran into the same problem recently. For a file of about 400MB, InsertCopy caused StackOverFlow each time.
