### ISSUE TITLE
IfcInputStream not found, Reading + Editing existing IFC

### ISSUE THREAD

**Issue by mrca** [xBimTeam/XbimEssentials#35]
Hello, 

Im trying out the toolkit. I have a presumably an older example **SimpleOpenAndSaveIfcFile** where an existing IFC file is read that uses the IfcInputStream:

`IfcInputStream input = new IfcInputStream(new FileStream(ifcFileName, FileMode.Open, FileAccess.Read));`

I also have a the **HelloWallExample** but apparently the Xbim.IO referenced to this project does not contain anymore the IfcInputStream.

Could you please point me out where to look for the IfcInputStream? Has it been renamed or deprecated? Or is there a an example for reading + editing an existing IFC file in another way? I have tried using the XbimModel.CreateFrom() function but it gives me an error.

Thanks in advance for the feedback.

PS: Sorry for using the tracker but the discussion forum link is dead.

**Comment by martin1cerny** [comment]
Hi @mrca , the sample you are using is extremely old and obsolete. To get the best performance and features I would recommend to use our `develop` branch now. It has very simple `IfcStore.Open(string filePath)` to open model and get you up to speed quickly. This also handles IFC2x3 as well as IFC4 in both Step21 and XML form.

**Comment by mrca** [comment]
Hi @martin1cerny, super. It works very nicely. One question, does the IfcStore replace the XbimModel? What is the difference? Also It would be cool to know what the plan for the project in the long term is. Is there some agenda somewhere? Thanks.

**Comment by martin1cerny** [comment]
Yes, IfcStore is replacement for XbimModel. XbimModel uses Esent database as a back-end storage whereas IfcStore uses in-memory model for small models and Esent for big ones. You can control this explicitly, by threshold or you don't have to care and let defaults to choose. Also IfcStore has some new features. It is for example agnostic about IFC version. XbimModel can only work with IFC2x3. I'd recommand to use IfcStore for any current and future development.

We work on a long-term planning but it is not finished yet. However, there are enterprises using xBIM as their BIM back-end engine so there is very clear plan to sustain the toolkit. Also GeometryEngine is being continuously improved as we see new kinds of IFC files coming. Serious part of these fixes is down to wrongly structured IFC data from authoring tools.
