### ISSUE TITLE
Merging IfcBuildings from multiple Files

### ISSUE THREAD

**Issue by Kilian941** [xBimTeam/XbimEssentials#352]
Hello,

I am looking for a solution to merge multiple diciplines into one file. My idea was to federate the models either by IfcSite or IfcBuilding. So basically,  I want to query all data from one model and add it to another. In the end I want one file that contains multiple disciplines. 

Federating the models using IfcStore.AddModelReference() does not help as I want to export an Ifc file supported by other software.

#### Steps (or code) to reproduce the issue:

* Model A comprises a building with multiple storeys and elements
* Model B contains the HVAC

```csharp
IfcStore modelA = IfcStore.Open("modelA.ifc");
IfcStore modelB = IfcStore.Open("modelB.ifc");

using (var txn = model.BeginTransaction("Merge"))
{
     // Here I need to do some merging such as:
     model.Instances.New(modelB.Instances);

     txn.Commit();
}
```

#### Expected behavior:

I would expect to create an IFC file that keeps the same structure of both. For example I generate an IfcFile that contains an IfcSite or IfcBuilding for each of the previously merged files.
From there the structure should be the original.

#### Additional Details

This feature could support model coordination. There are many software solutions that allows for importing several IFC files. However, I want to generate a coordinated model in ifc and share this.

Thanks,
Kilian

**Comment by martin1cerny** [comment]
Hi @Kilian941, you should use the `model.InsertCopy()` function for this task. We have this available at two levels. One override is taking any IFC entity and you can pass in a filtering delegate function to drive how it is copied (select attributes or even transform data on the fly). Second override is higher level and takes any `IfcProduct`. This is our attempt to copy over entities with their context, properties etc. Your task will be rather complex so you might want to check our implementation which takes IfcProduct and develop your own logic to insert copies from multiple files. Just be aware, that you have to end up with maximum of one `IfcProject` root object in the resulting file and have to use one length unit for all the geometry.
