### ISSUE TITLE
Handeling multiple IFCUNITASSIGNMENT's of possibly different units

### ISSUE THREAD

**Issue by dirkzwager** [xBimTeam/XbimEssentials#356]
*Summary: when multiple IFCUNITASSIGNMENT statements are issued in an IFC file, only the first assignment is applied causing the unit of measurement in the model to be incorrect*

#### Assemblies and versions affected:

*Xbim.Essentials 5.1.274*

#### Steps (or code) to reproduce the issue:

Consider (a section) of the following IFC file:

```
#8=IFCUNITASSIGNMENT((#9,#10,#11,#12,#13,#14,#15,#16,#17));
#9=IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.);
#10=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#11=IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
#12=IFCSIUNIT(*,.SOLIDANGLEUNIT.,$,.STERADIAN.);
#13=IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.);
#14=IFCSIUNIT(*,.MASSUNIT.,$,.GRAM.);
#15=IFCSIUNIT(*,.TIMEUNIT.,$,.SECOND.);
#16=IFCSIUNIT(*,.THERMODYNAMICTEMPERATUREUNIT.,$,.DEGREE_CELSIUS.);
#17=IFCSIUNIT(*,.LUMINOUSINTENSITYUNIT.,$,.LUMEN.);
#18=IFCCARTESIANPOINT((0.,0.,0.));
#19=IFCAXIS2PLACEMENT3D(#18,$,$);
#20=IFCGEOMETRICREPRESENTATIONCONTEXT('Building Model','Model',3,1.E-05,#19,$);
#21=IFCCARTESIANPOINT((0.,0.));
#22=IFCAXIS2PLACEMENT2D(#21,$);
#23=IFCGEOMETRICREPRESENTATIONCONTEXT('Building Plan View','Plan',2,1.E-05,#22,$);
#24=IFCUNITASSIGNMENT((#25));
#25=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
```
Particularly consider:
```
#8=IFCUNITASSIGNMENT((#9,#10,#11,#12,#13,#14,#15,#16,#17));
```
and
```
#24=IFCUNITASSIGNMENT((#25));
```

As the following code in MemoryModel.cs shows instOfType.FirstOrDefault() only causes the following assignment to be applied
```
#8=IFCUNITASSIGNMENT((#9,#10,#11,#12,#13,#14,#15,#16,#17));
```
```csharp
public static void CalculateModelFactors(IModel model)
{
	bool planeAngleSpecified = false;
	double angleToRadiansConversionFactor = 1; //assume radians
	double lengthToMetresConversionFactor = 1; //assume metres
	var instOfType = model.Instances.OfType<IIfcUnitAssignment>();
	var ua = instOfType.FirstOrDefault();
	if (ua != null)
	{
		foreach (var unit in ua.Units)
		{
		   ....
		}
	}
}
```

We can produce the desired behaviour in this model by changing

```csharp
foreach (var unit in ua.Units)
{
 ...
}
```

with:
```csharp
foreach (var unit in instOfType.SelectMany(u => u.Units)) 
{
  ...
}
```

Which does result in the correct model.ModelFactor.OneMeter (should be 1  instead of 1000 for the supplied IFC file).

*A simple set of steps to reproduce the issue. 
```csharp
[TestMethod]
public void OpenMemoryModelWithMultipleIfcUnitAssignments()
{
	using (FileStream inputStream = new FileStream("TestSourceFiles\\file

.ifc", FileMode.Open, FileAccess.Read)) {
		var model = Ifc.IfcStore.Open(inputStream, StorageType.Ifc, Common.Step21.XbimSchemaVersion.Ifc2X3, XbimModelType.MemoryModel);                
		Assert.IsTrue(model.ModelFactors.OneMeter == 1);
	}                
}
```
#### Minimal file to reproduce the issue:

[file.zip](https://github.com/xBimTeam/XbimEssentials/files/5292494/file.zip)

#### Expected behavior:

I would expect the ModelFactors.OneMeter to be 1 for this ifc file

#### Actual behavior or exception details:

The ModelFactors.OneMeter is 1000

#### Additional Details
Happy to supply a pull request with unit tests.

**Comment by bekraft** [comment]
I wonder where ```#24``` is reused? Or is it meant as singleton unit assignment? In this case you might get into trouble since the IFC does not state anything concerning the order of instances.

**Comment by dirkzwager** [comment]
Hi, thanks for your response.

Your suggestion about the order is interesting and prompted me to try the following:

Opening the file.zip in for example BimVision does shows the correct unit:

![image](https://user-images.githubusercontent.com/10120573/94464561-e86fff00-01be-11eb-84c7-cc143fa1fb76.png)

However, changing the order of the IFC declarations in the file to this:

```
#8=IFCUNITASSIGNMENT((#25));
#9=IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.);
#10=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#11=IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
#12=IFCSIUNIT(*,.SOLIDANGLEUNIT.,$,.STERADIAN.);
#13=IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.);
#14=IFCSIUNIT(*,.MASSUNIT.,$,.GRAM.);
#15=IFCSIUNIT(*,.TIMEUNIT.,$,.SECOND.);
#16=IFCSIUNIT(*,.THERMODYNAMICTEMPERATUREUNIT.,$,.DEGREE_CELSIUS.);
#17=IFCSIUNIT(*,.LUMINOUSINTENSITYUNIT.,$,.LUMEN.);
#18=IFCCARTESIANPOINT((0.,0.,0.));
#19=IFCAXIS2PLACEMENT3D(#18,$,$);
#20=IFCGEOMETRICREPRESENTATIONCONTEXT('Building Model','Model',3,1.E-05,#19,$);
#21=IFCCARTESIANPOINT((0.,0.));
#22=IFCAXIS2PLACEMENT2D(#21,$);
#23=IFCGEOMETRICREPRESENTATIONCONTEXT('Building Plan View','Plan',2,1.E-05,#22,$);
#24=IFCUNITASSIGNMENT((#9,#10,#11,#12,#13,#14,#15,#16,#17));
#25=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
```

Results in the following in BimVision:

![image](https://user-images.githubusercontent.com/10120573/94465388-1f92e000-01c0-11eb-838d-dd7d0a0442a5.png)

which is incorrect.

The file is produced by an extension for autodesk software. I might address the issue there as a single line of:

```
#8=IFCUNITASSIGNMENT((#9,#10,#11,#12,#13,#14,#15,#16,#17,#25));
```
would suffice.

**Comment by bekraft** [comment]
If BIM Vision deals with the modified file in a different way, both, your extension for autodesk and BIM vision are wrong. The unit assignment is referenced once by an IfcContext (IfcProject). Any standalone assignment is an incorrectly given assignment. So, the extension should reference the the correct unit by an unit assignment once. Otherwise the coordinates of geometrical bodies would depend on the order of transmittal.

**Comment by martin1cerny** [comment]
```
#8=IFCUNITASSIGNMENT((#9,#10,#11,#12,#13,#14,#15,#16,#17,#25));
```
is invalid as any measure type can only be assigned once to create unambiguous definition for the context. Both `#9` and `#25` are defining length units so it is unclear which one should be used and it is actually [violating schema constraints](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifccorrectunitassignment.htm). 

Also, you need to be very careful with this kind of modification as it will have impact on the scale of all geometries in the context as well as any properties (`IfcProperty`) with length measures (`IfcLengthMeasure`, `IfcPositiveLengthMeasure`, `IfcNonNegativeLengthMeasure`).

**Comment by dirkzwager** [comment]
I think BimVision handles it something like this:

```
foreach (var unit in instOfType.SelectMany(u => u.Units)) 
{
  ..
}
```

as

```
#8=IFCUNITASSIGNMENT((#9,#10,#11,#12,#13,#14,#15,#16,#17));
#9=IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.);
#10=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#11=IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
#12=IFCSIUNIT(*,.SOLIDANGLEUNIT.,$,.STERADIAN.);
#13=IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.);
#14=IFCSIUNIT(*,.MASSUNIT.,$,.GRAM.);
#15=IFCSIUNIT(*,.TIMEUNIT.,$,.SECOND.);
#16=IFCSIUNIT(*,.THERMODYNAMICTEMPERATUREUNIT.,$,.DEGREE_CELSIUS.);
#17=IFCSIUNIT(*,.LUMINOUSINTENSITYUNIT.,$,.LUMEN.);
#18=IFCCARTESIANPOINT((0.,0.,0.));
#19=IFCAXIS2PLACEMENT3D(#18,$,$);
#20=IFCGEOMETRICREPRESENTATIONCONTEXT('Building Model','Model',3,1.E-05,#19,$);
#21=IFCCARTESIANPOINT((0.,0.));
#22=IFCAXIS2PLACEMENT2D(#21,$);
#23=IFCGEOMETRICREPRESENTATIONCONTEXT('Building Plan View','Plan',2,1.E-05,#22,$);
#24=IFCUNITASSIGNMENT((#25));
#25=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
```

results in Meters and this:

```
#8=IFCUNITASSIGNMENT((#25));
#9=IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);
#10=IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.);
#11=IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.);
#12=IFCSIUNIT(*,.SOLIDANGLEUNIT.,$,.STERADIAN.);
#13=IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.);
#14=IFCSIUNIT(*,.MASSUNIT.,$,.GRAM.);
#15=IFCSIUNIT(*,.TIMEUNIT.,$,.SECOND.);
#16=IFCSIUNIT(*,.THERMODYNAMICTEMPERATUREUNIT.,$,.DEGREE_CELSIUS.);
#17=IFCSIUNIT(*,.LUMINOUSINTENSITYUNIT.,$,.LUMEN.);
#18=IFCCARTESIANPOINT((0.,0.,0.));
#19=IFCAXIS2PLACEMENT3D(#18,$,$);
#20=IFCGEOMETRICREPRESENTATIONCONTEXT('Building Model','Model',3,1.E-05,#19,$);
#21=IFCCARTESIANPOINT((0.,0.));
#22=IFCAXIS2PLACEMENT2D(#21,$);
#23=IFCGEOMETRICREPRESENTATIONCONTEXT('Building Plan View','Plan',2,1.E-05,#22,$);
#24=IFCUNITASSIGNMENT((#9,#10,#11,#12,#13,#14,#15,#16,#17));
#25=IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.);
```

In mm (note the order of IFCUNITASSIGNMENT). 

In anyway, its not deterministic and a matter of luck the model turned out in m

**Comment by martin1cerny** [comment]
As I say, it is an [invalid IFC model](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifccorrectunitassignment.htm).

**Comment by dirkzwager** [comment]
Thanks Martin, 

To conclude there seems to be an issue with the supplied IFC file. A valid IFC file in this case should define the IFCUNITASSIGNMENT like:
```
#8=IFCUNITASSIGNMENT((#25,#10,#11,#12,#13,#14,#15,#16,#17));
```
There will be no:
```
#9=IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.);
```
Is this correct?

**Comment by martin1cerny** [comment]
Yes, just be aware that it changes the meaning of all length based properties and other parts of data. Also, it has a direct impact on the declared geometry precision which is important for geometry processing.
