### ISSUE TITLE
does this repo support convert geometry data(like occt brep) to ifc file? 

### ISSUE THREAD

**Issue by Elliotloststh** [xBimTeam/XbimEssentials#358]

**Comment by martin1cerny** [comment]
It does support it. See our example [here](https://docs.xbim.net/examples/proper-wall-in-3d.html) to see how to create an IFC model. IFC standard has [large number of data types for geometry](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcgeometricmodelresource.htm), so you just need to find the right mapping to express your geometry as IFC. For BRep you would start [here](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcmanifoldsolidbrep.htm). Xbim implements 100% of the standard, so you can use it to create any IFC data you like and save it as any physical representation (*.ifc, *.ifcXML, *.ifcZIP).

**Comment by andyward** [comment]
Closing
