### ISSUE TITLE
Can't compile Xbim.ModelGeometry.Converter project!

### ISSUE THREAD

**Issue by michealChin** [xBimTeam/XbimEssentials#36]
Hi,

It seems like all the native dlls TKBO.dll, TKBool.dll TKBRep.dll and etc didn't come along with the downloaded project. May I know where can I get all these dlls in order to compile Xbim.ModelGeometry.Converter successfully? 

Thanks in Advance!

**Comment by LloydPickering** [comment]
I'm pretty sure that project was removed a significant while ago. Where did you get the project code from?

There are new ways to generate and convert files, and the project has been split up into nuget packages for convenience of end users.

**Comment by michealChin** [comment]
Hi LloydPickering,

I downloaded this version (xBIM2.4.1.zip). All the c# project can be compiled without problem, only the c++ project and Xbim.ModelGeometry.Converter that require native dlls TKBO.dll, TKBool.dll TKBRep.dll cannot be compiled.

**Comment by LloydPickering** [comment]
Hi,

That code is really really out of date.

The latest code is split up into a repository per Nuget package, and they can all be found at https://github.com/xBimTeam

The packages are also published to Nuget.org and can be found at https://www.nuget.org/packages?q=xbim 

You shouldn't need the xbim code itself unless you want to alter xbim itself. If you are just consuming it, then use the nuuget packages.

If you want an example of how to interact with the packages using a Windows UI, you can have a look at the code in https://github.com/xBimTeam/XbimWindowsUI (there is also a web one, too)

**Comment by michealChin** [comment]
Thanks man! Will give it a try tomorrow!

**Comment by michealChin** [comment]
Hi I have downloaded https://github.com/xBimTeam/XbimWindowsUI, I open it with Visual Studio Community 2015 version  but I am not able to compile the code. Below is the error message
![bimcompileerror](https://cloud.githubusercontent.com/assets/12890191/15389363/124e46ec-1de9-11e6-9b93-063a1ed13e62.png)

What should I do to compile it correctly?

**Comment by martin1cerny** [comment]
You need to add https://www.myget.org/F/xbim-master/api/v2 to your NuGet feeds (in your NuGet settings). You can also add https://www.myget.org/F/xbim-develop/api/v2 if you wanted to use our development packages.

**Comment by michealChin** [comment]
Hi Martin,

Thank you so much it works!
