### ISSUE TITLE
Unable to use products parameter in model.SaveAsWexBim

### ISSUE THREAD

**Issue by Abhicode5** [xBimTeam/XbimEssentials#364]
`// using Microsoft.Extensions.Logging;
// using Serilog;
using System.IO;
// using Xbim.Common;
using System;
using Xbim.Ifc;
using Xbim.ModelGeometry.Scene;
using System.Diagnostics;

using System.Collections;
// using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.Common.Geometry;
using Xbim.Common.Step21;
using Xbim.Common.XbimExtensions;
using Xbim.Ifc4.Interfaces;
namespace CreateWexBIM
{
    class Program
    {
        public static void Main()
        {
            // Log.Logger = new LoggerConfiguration()
            //    .Enrich.FromLogContext()
            //    .WriteTo.ColoredConsole()
            //    .CreateLogger();

            // var lf = new LoggerFactory().AddSerilog();
            // var log = lf.CreateLogger("WexbimCreation");
            // log.LogInformation("Creating wexBIM file from IFC model.");

            // // set up xBIM logging. It will use your providers.
            // XbimLogging.LoggerFactory = lf;

            const string fileName = @"test.ifc";
            // log.LogInformation("File size: {new FileInfo(fileName).Length / 1e6}MB");

            using (var model = IfcStore.Open(fileName, null, -1))
            {
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                var wexBimFilename = Path.ChangeExtension(fileName, "wexbim");
                using (var wexBimFile = File.Create(wexBimFilename))
                {
                    using (var wexBimBinaryWriter = new BinaryWriter(wexBimFile))
                    {
                        model.SaveAsWexBim(wexBimBinaryWriter,IEnumerable<IIfcProduct> products = null);
                        wexBimBinaryWriter.Close();
                    }
                    wexBimFile.Close();
                      Console.WriteLine(fileName+" has been successfully written");

                }
            }
        }
    }
}

`

I am Successfully able to convert ifc to wexbim.  using model.SaveAsWexBim(wexBimBinaryWriter).

Now i want to save multiple ifc files of same model - - say a model contains walls only
so i used the code  which is supposed to save everything   `model.SaveAsWexBim(wexBimBinaryWriter,IEnumerable<IIfcProduct> products = null);`

or to save walls only model
`model.SaveAsWexBim(wexBimBinaryWriter,IEnumerable<IIfcProduct> products = IIfcWall);`

But i am getting the error as follows

Program.cs(52,63): error CS0119: 'IEnumerable' is a type, which is not valid in the given context [C:\Users\EliteBook\Downloads\ifc_to_wexbim_convert\CreateWexBIM\CreateWexBIM.csproj]
Program.cs(52,75): error CS0119: 'IIfcProduct' is a type, which is not valid in the given context [C:\Users\EliteBook\Downloads\ifc_to_wexbim_convert\CreateWexBIM\CreateWexBIM.csproj]
Program.cs(52,88): error CS0103: The name 'products' does not exist in the current context [C:\Users\EliteBook\Downloads\ifc_to_wexbim_convert\CreateWexBIM\CreateWexBIM.csproj]
Program.cs(52,99): error CS0119: 'IIfcWall' is a type, which is not valid in the given context [C:\Users\EliteBook\Downloads\ifc_to_wexbim_convert\CreateWexBIM\CreateWexBIM.csproj]

The build failed. Fix the build errors and run again.

@martin1cerny could you please help .

**Comment by Abhicode5** [comment]
``

**Comment by andyward** [comment]
The 2nd parameter expects a list of IIfcProducts but you're providing a Type

For reference you'd use something like:

```csharp
    model.SaveAsWexBim(wexBimBinaryWriter, store.Instances.OfType<IIfcWall>());
```

**Comment by Abhicode5** [comment]
Thanks @andyward  i achieved the same using `        model.SaveAsWexBim(wexBimBinaryWriter,model.Instances.OfType<IIfcBeam>(), null);`. 

Is there any way to save say 3  wexbim files   
1. type <IIcBeam>
2.  type<iifcWall>
3.  type<everything except 1 &2>

**Comment by andyward** [comment]
Yes, that's basically the same code. The 3rd parameter is an optional transform vector. https://github.com/xBimTeam/XbimEssentials/blob/5ed57d0281d1cad35a4a502ddf06bc8b32866537/Xbim.Ifc/Extensions/IfcStoreGeometryExtensions.cs#L25

I would create a method:

```csharp
void CreateWexbimFile(IModel model, string wexBimFilename, IEnumerable<IIfcProduct> products = null)
{
           // Parameterised implementation from above
            using (var wexBimFile = File.Create(wexBimFilename))
            {
                using (var wexBimBinaryWriter = new BinaryWriter(wexBimFile))
                {
                    model.SaveAsWexBim(wexBimBinaryWriter, products);
                    wexBimBinaryWriter.Close();
                }
                wexBimFile.Close();
                  Console.WriteLine(wexBimFilename+" has been successfully written");

            }
}

void CreateSplitWexbims()
{
        using (var model = IfcStore.Open(fileName, null, -1))
        {
            var context = new Xbim3DModelContext(model);
            context.CreateContext();

            var beams = model.Instances.OfType<IIfcBeam>();
            var walls= model.Instances.OfType<IIfcWall>();
            var toExclude= beams.Concat(walls);

// This is just standard LINQ. There are otherways of achieving the same thing, e.g. https://stackoverflow.com/questions/4559257/how-can-i-implement-notoftypet-in-linq-that-has-a-nice-calling-syntax
            var theRest= model.Instances.OfType<IIfcProduct>().Except(toExclude);

            CreateWexbimFile(model, "beams.wexbim", beams);
            CreateWexbimFile(model, "walls.wexbim", walls);
            CreateWexbimFile(model, "therest.wexbim", theRest);


        }
   
}
```

**Comment by Abhicode5** [comment]
@andyward  Thank you so much .

**Comment by Abhicode5** [comment]
`// using Microsoft.Extensions.Logging;
// using Serilog;
using System.IO;
// using Xbim.Common;
using System;
using Xbim.Ifc;
using Xbim.ModelGeometry.Scene;
using System.Diagnostics;



using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Xbim.Common;
using Xbim.Common.Exceptions;
using Xbim.Common.Geometry;
using Xbim.Common.Step21;
using Xbim.Common.XbimExtensions;
using Xbim.Ifc4.Interfaces;
namespace CreateWexBIM
{
    class Program
    {

        void CreateWexbimFile(IModel model, string wexBimFilename, IEnumerable<IIfcProduct> products = null)
{
           // Parameterised implementation from above
            using (var wexBimFile = File.Create(wexBimFilename))
            {
                using (var wexBimBinaryWriter = new BinaryWriter(wexBimFile))
                {
                    model.SaveAsWexBim(wexBimBinaryWriter, products);
                    wexBimBinaryWriter.Close();
                }
                wexBimFile.Close();
                  Console.WriteLine(wexBimFilename+" has been successfully written");

            }
}

void CreateSplitWexbims(string fileName)
{
        using (var model = IfcStore.Open(fileName, null, -1))
        {
            var context = new Xbim3DModelContext(model);
            context.CreateContext();

            var beams = model.Instances.OfType<IIfcBeam>();
            var walls= model.Instances.OfType<IIfcWall>();
            var toExclude= beams.Concat(walls);

// This is just standard LINQ. There are otherways of achieving the same thing, e.g. https://stackoverflow.com/questions/4559257/how-can-i-implement-notoftypet-in-linq-that-has-a-nice-calling-syntax
            var theRest= model.Instances.OfType<IIfcProduct>().Except(toExclude);

            CreateWexbimFile(model, "beams.wexbim", beams);
            CreateWexbimFile(model, "walls.wexbim", walls);
            CreateWexbimFile(model, "therest.wexbim", theRest);


        }

   
}

        public static void Main()
        {
            
        Program obj = new Program();
        obj.CreateSplitWexbims("test.ifc");
    
    }

    }
}

`

Sorry i dont know much c#.  i am getting the error on line beams.concat(). Not able to concat two instances. also it was showing some warnings on storing instances enumerate type in var
Program.cs(51,28): error CS1929: 'IEnumerable<IIfcBeam>' does not contain a definition for 'Concat' and the best extension method overload 'Queryable.Concat<IIfcWall>(IQueryable<IIfcWall>, IEnumerable<IIfcWall>)' requires a receiver of type 'IQueryable<IIfcWall>' [C:\Users\EliteBook\Downloads\ifc_to_wexbim_convert\CreateWexBIM\CreateWexBIM.csproj]

The build failed. Fix the build errors and run again.

**Comment by martin1cerny** [comment]
> The build failed. Fix the build errors and run again.

This is not xbim specific. You need to fix your references and `using` statements. You probably miss `using System.Linq;`

**Comment by Abhicode5** [comment]
@martin1cerny  sorry but i have included using system.Linq

**Comment by andyward** [comment]
Sorry, I was editing that code outside of an IDE. You need to have 'walls' and 'beams' typed `IEnumerable<IIfcProduct>` in order to concatenate them in Linq. (the two types need to be the same for Contat to work, which is what the error is trying to say

Changing it as follows to replace the var with the 'base' list should fix

```csharp
        IEnumerable<IIfcProduct> beams = model.Instances.OfType<IIfcBeam>();
        IEnumerable<IIfcProduct> walls= model.Instances.OfType<IIfcWall>();
        var toExclude= beams.Concat(walls);
```

**Comment by Abhicode5** [comment]
Perfect. 
@andyward  Thanks for such a quick reply.
