### ISSUE TITLE
Render issues

### ISSUE THREAD

**Issue by Abhicode5** [xBimTeam/XbimEssentials#366]
I converted the ifc model to wexbim . and loaded it in XbimWebui . and also in autodesk. Clearly i can see some elements are not  loaded .

Xbim Webui
![image](https://user-images.githubusercontent.com/74701785/107482828-3a318880-6ba6-11eb-8d1d-1c5a1fbb7be1.png)

Autodesk

![image](https://user-images.githubusercontent.com/74701785/107483107-9694a800-6ba6-11eb-9a91-1bc4ea5b20d3.png)

**Comment by martin1cerny** [comment]
You should check the log when you are converting IFC to wexBIM. There might be warnings or errors which would indicate invalid geometry definitions in IFC.

**Comment by Abhicode5** [comment]
C:\Program Files\dotnet\sdk\3.1.404\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3088: Could not read state file "obj\Debug\net47\CreateWexBIM.csprojAssemblyReference.cache". The process cannot access the file 'C:\Users\EliteBook\Desktop\XbimSamples\CreateWexBIM\obj\Debug\net47\CreateWexBIM.csprojAssemblyReference.cache' because it is being used by another process. [C:\Users\EliteBook\Desktop\XbimSamples\CreateWexBIM\CreateWexBIM.csproj]
C:\Program Files\dotnet\sdk\3.1.404\Microsoft.Common.CurrentVersion.targets(2084,5): warning MSB3101: Could not write state file "obj\Debug\net47\CreateWexBIM.csprojAssemblyReference.cache". The process cannot access the file 'C:\Users\EliteBook\Desktop\XbimSamples\CreateWexBIM\obj\Debug\net47\CreateWexBIM.csprojAssemblyReference.cache' because it is being used by another process. [C:\Users\EliteBook\Desktop\XbimSamples\CreateWexBIM\CreateWexBIM.csproj]
2021-02-10 15:36:53 INF Creating wexBIM file from IFC model.
2021-02-10 15:36:53 INF File size: {new FileInfo(fileName).Length / 1e6}MB
2021-02-10 15:36:53 WRN Defaulting to MemoryModelProvider. Working with large models could be sub-optimal.
To fix this warning, consider calling 'IfcStore.ModelProviderFactory.UseHeuristicModelProvider();' at application startup'
2021-02-10 15:37:14 INF Starting creation of model scene
2021-02-10 15:37:24 INF Finished creation of model scene
test.ifc has been successfully written

**Comment by Abhicode5** [comment]
```
using Microsoft.Extensions.Logging;
using Serilog;
using System.IO;
using Xbim.Common;
using System;
using Xbim.Ifc;
using Xbim.ModelGeometry.Scene;
using System.Diagnostics;
namespace CreateWexBIM
{

    class Program
    {
        public static void Main()
        {
            Log.Logger = new LoggerConfiguration()
               .Enrich.FromLogContext()
               .WriteTo.ColoredConsole()
               .CreateLogger();
            
            var lf = new LoggerFactory().AddSerilog();
            var log = lf.CreateLogger("WexbimCreation");
            log.LogInformation("Creating wexBIM file from IFC model.");

            // set up xBIM logging. It will use your providers.
            XbimLogging.LoggerFactory = lf;

            const string fileName = @"test.ifc";
            log.LogInformation("File size: {new FileInfo(fileName).Length / 1e6}MB");
            IfcStore.ModelProviderFactory.UseHeuristicModelProvider();
            using (var model = IfcStore.Open(fileName, null, -1))
            {
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                var wexBimFilename = Path.ChangeExtension(fileName, "wexbim");
                using (var wexBimFile = File.Create(wexBimFilename))
                {
                    using (var wexBimBinaryWriter = new BinaryWriter(wexBimFile))
                    {
                        model.SaveAsWexBim(wexBimBinaryWriter);
                        wexBimBinaryWriter.Close();
                    }
                    wexBimFile.Close();
                      Console.WriteLine(fileName+" has been successfully written");

                }
            }
        }
    }
}

```

I have added **  IfcStore.ModelProviderFactory.UseHeuristicModelProvider();**
Now warnings are removed but model is rendered as before. 

2021-02-10 15:52:14 INF Creating wexBIM file from IFC model.
2021-02-10 15:52:14 INF File size: {new FileInfo(fileName).Length / 1e6}MB
2021-02-10 15:52:40 INF Starting creation of model scene
2021-02-10 15:52:53 INF Finished creation of model scene
test.ifc has been successfully written

**Comment by martin1cerny** [comment]
Can you share the IFC model?

**Comment by Abhicode5** [comment]
@martin1cerny  please check.

https://drive.google.com/file/d/16JAGgJv98A4rRKZ5jaiJmeWbfLPoKbb6/view?usp=sharing

**Comment by martin1cerny** [comment]
Everything is processed fine, but some element are completely transparent in your model. Therefore they are invisible.

**Comment by Abhicode5** [comment]
Ok so should i change colors in my model ,make it darker ? . Could you please guide me how to do it ? which method, or parameter do i need to change


Thanks for such a quick response

**Comment by martin1cerny** [comment]
It is not about the colour, but about the transparency. `#173=IFCSURFACESTYLERENDERING(#174,1.,IFCNORMALISEDRATIOMEASURE(1.),$,$` has transparency 1.0 which makes it invisible

From [IFC documentation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcsurfacestyleshading.htm):

>The transparency field specifies how "clear" an object is, with **1.0 being completely transparent**, and 0.0 completely opaque. If not given, the value 0.0 (opaque) is assumed.
>    NOTE  The definition of 1 being transparent and 0 being opaque is the opposite of the definition in alpha channels, where 0.0 is completely transparent and 1.0 is completely opaque. This definition is due to upward compatibility to previous versions of this standard in different to the definition in IfcIndexedColourMap.

So, you should make sure that all styles have at least *some* visibility.

**Comment by Abhicode5** [comment]
@martin1cerny  , got your point . Thanks
