### ISSUE TITLE
[Question] Creation of IfcRightCircularCylinder

### ISSUE THREAD

**Issue by mis-nca** [xBimTeam/XbimEssentials#367]
I've been unsuccessfully trying to programmatically create an [IfcRightCircularCylinder](https://standards.buildingsmart.org/IFC/RELEASE/IFC2x3/TC1/HTML/ifcgeometricmodelresource/lexical/ifcrightcircularcylinder.htm) using Ifc2x3 (see code below).

Can somebody tell me what I need to do so that the generated IFC file shows the cylinder in 3D when opened in e.g. [OpenIFCViewer](https://openifcviewer.com/)? What am I missing?

#### Assemblies and versions used:

Xbim.Essentials 5.1.323

#### Code:

```csharp
using Xbim.Common;
using Xbim.Common.Step21;
using Xbim.Ifc;
using Xbim.IO;
using Xbim.Ifc2x3.GeometricModelResource;
using Xbim.Ifc2x3.GeometryResource;
using Xbim.Ifc2x3.Kernel;


namespace HelloCylinder
{
    class Program
    {

        static int Main()
        {

            using (var model = CreateandInitModel("My Project"))
            {
                using (var txn = model.BeginTransaction("Create IfcObject"))
                {
                    CreateCylinder(model);
                    txn.Commit();
                }

                model.SaveAs("BasicCylinder.ifc");
            }
            return 0;
        }

        private static IfcStore CreateandInitModel(string projectName)
        {
            var credentials = new XbimEditorCredentials
            {
...
            };

            var model = IfcStore.Create(credentials, XbimSchemaVersion.Ifc2X3, XbimStoreType.InMemoryModel);

            using (var txn = model.BeginTransaction("Initialise Model"))
            {
                var project = model.Instances.New<IfcProject>();
                project.Initialize(ProjectUnits.SIUnitsUK);
                project.Name = projectName;
                txn.Commit();
            }
            return model;

        }

        private static IfcRightCircularCylinder CreateCylinder(IfcStore model)
        {
            var origin = model.Instances.New<IfcCartesianPoint>();
            origin.SetXYZ(0.0, 0.0, 0.0);

            var xAxis = model.Instances.New<IfcDirection>();
            xAxis.SetXYZ(1.0, 0.0, 0.0);

            var yAxis = model.Instances.New<IfcDirection>();
            yAxis.SetXYZ(0.0, 1.0, 0.0);

            var zAxis = model.Instances.New<IfcDirection>();
            zAxis.SetXYZ(0.0, 0.0, 1.0);

            var cartesionCoordinateSystem = model.Instances.New<IfcAxis2Placement3D>();
            cartesionCoordinateSystem.Location = origin;
            cartesionCoordinateSystem.Axis = zAxis;
            cartesionCoordinateSystem.RefDirection = xAxis;


            var cylinder = model.Instances.New<IfcRightCircularCylinder>();
            cylinder.Height = 2.0;
            cylinder.Radius = 5.0;
            cylinder.Position = cartesionCoordinateSystem;


            return cylinder;
        }


    }
}
```

#### Expected behavior:

A valid IFC2x3 file gets generated an shows a cylinder in 3D when opened in a viewer.

#### Actual behavior or exception details:

The file gets generated by the cylinder is not shown when opened in a viewer.

**Comment by martin1cerny** [comment]
You need to create more context around the geometry for the model viewers to present your data. Have a look at our example: https://docs.xbim.net/examples/proper-wall-in-3d.html

**Comment by mis-nca** [comment]
Thanks for your answer.

I already looked at the example. Would you mind to elaborate a bit more about what you mean with "context around the geometry"? When I look at the provided example, it's not clear for me what is absolutely necessary and what's not and how to adapt it for the IfcRightCircularCylinder to be shown.

**Comment by martin1cerny** [comment]
The example is almost bare-bone. You need to have IfcProject -> IfcBuilding -> IfcElement at least for most viewers to show the structure. You need to define the IfcGeometryContext with the right identifiers for 3D geometry. You must provide length and angular units at least through IfcUnitAssignment. You should assign some representation (colour) to the shape using IfcStyledItem.

I stripped it down to absolute minimum here: https://github.com/xBimTeam/XbimSamples/blob/master/BasicCreate/CubeWithColourExample.cs

The result is a simple orange cube:

![image](https://user-images.githubusercontent.com/773078/107757452-dc2baf00-6d25-11eb-8f5b-3017e5244f26.png)

**Comment by mis-nca** [comment]
Thanks again for your help and your “simpler” example, I really appreciate your time.

Unfortunately, I am still unable to take your cube example and adapt it for the `IfcRightCircularCylinder`.

As I understand now, you need to have an `IfcProject` first then an `IfcBuilding` and eventually you can add an `IfcProduct` to the building. However, `IfcRightCircularCylinder` is not an `IfcProduct` so I probably need to make it somehow a `IfcProduct`… But for me it’s not clear how I do that.

Sorry for my lack of understanding.

**Comment by martin1cerny** [comment]
IFC is a product model, so you need to give some semantics to the data. Pure geometry is not enough. In my example, you would use your `IfcRightCircularCylinder` [here](https://github.com/xBimTeam/XbimSamples/blob/master/BasicCreate/CubeWithColourExample.cs#L145). And yes, you should say what kind of product your geometry represents.

**Comment by mis-nca** [comment]
Because of your help, I was able to adapt the given example so that it shows my cylinder.

I have one additional question regarding the orientation of the objects: How can I rotate them in a simple way? I know that I can change `IfcAxis2Placement3D`'s RefDirection, Location and Axis by defining a new coordinate system relative to the main one... However, isn't there a way to e.g. simply say rotate 90° along the Z axis or something similar?

**Comment by martin1cerny** [comment]
No, you have to express any transformations using `IfcAxis2Placement3D`.
