### ISSUE TITLE
Missing public constructor of cartesian point list, prevents programmatically creation of triangulated face set

### ISSUE THREAD

**Issue by Noranius** [xBimTeam/XbimEssentials#368]
In order to create a new instance of a product with an `IfcTriangulatedFaceSet` as representation, it is necessary to create and fill an `IfcCartesianPointList3D`. The `IfcCartesianPointList3D` stores all coordinates as `ItemSet<ItemSet<IfcLengthMeasure>>` in the field `CoordList`. The outer item set is properly initialized. However, all inner item sets have to be initialized. The problem arises now from the fact that the constructor for the `Ifc4.ItemSet` respectively `Ifc2x3.ItemSet` has only `internal` accessibility. How can I create a cartesian point list by code?

#### Steps (or code) to reproduce the issue:
````
Type verticesClass = typeof(Xbim.Ifc4.GeometricModelResource.IfcCartesianPointList3D);
Xbim.Ifc4.GeometricModelResource.IfcCartesianPointList3D vertices =
    (Xbim.Ifc4.GeometricModelResource.IfcCartesianPointList3D) model.Instances.New(verticesClass); 
vertices.CoordList.Add(???);
````

#### Question:
How to create a triangulated face set by code?

#### Problem:
The constructor for the necessary ÌtemSet<T>` has only `internal `accessibility.

**Comment by martin1cerny** [comment]
It doesn't have a public constructor because we need to maintain internal data integrity and change detection. See #70 to see how to use it.

**Comment by Noranius** [comment]
Thank you. Works perfectly 👍
