### ISSUE TITLE
GetMaterials from walls

### ISSUE THREAD

**Issue by pierrenavarra** [xBimTeam/XbimEssentials#369]
Hi,
I'd like to get the list of materials of each standardWall in my collection. Is it possible?
I've tried with IfcRelAssociatesMaterial but no way...
Could you help me please?
Thx

`string filename = "R:\\RECHERCHE\\PLAY-TOWN\\IFC\\GABARIT-TO-UNREAL.ifc";
            
            using (var model = IfcStore.Open(filename))
            {
                // get all walls in the model
                var allWallsSC = model.Instances.OfType<IIfcWallStandardCase>();
                
                foreach (IIfcWallStandardCase wallSC in allWallsSC)
                {

                }
            }
            Console.WriteLine(filename);`

**Comment by martin1cerny** [comment]
```cs
var materials = wall.HasAssociations
    .OfType<IIfcRelAssociatesMaterial>()
    .Select(r => r.RelatingMaterial);
```

**Comment by pierrenavarra** [comment]
> 
> 
> ```cs
> var materials = wall.HasAssociations
>     .OfType<IIfcRelAssociatesMaterial>()
>     .Select(r => r.RelatingMaterial);
> ```

Hi martin, thx for answering me. 
That's great , I got now an IFCMATERALLLAYERSETUSAGE, but how to get the material name?
Is it possible to get the IFCMATERIALLAYERSET with a list of IFCMATERIALLAYER and IFCMATERIAL to get each material name?

**Comment by martin1cerny** [comment]
Yes, you just need to traverse the [data structures](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcmateriallayersetusage.htm).

**Comment by pierrenavarra** [comment]
You mean?

Something like that?
`foreach (IfcMaterialLayerSetUsage materialLSU in materials)
                    {
                        //do something..                                    
                    }`

Sorry I'm lost martin...

**Comment by pierrenavarra** [comment]
I've done it! Thx MArtin!
`foreach (IIfcWallStandardCase wallSC in allWallsSC)
                {
                    Console.WriteLine(wallSC.Name.ToString());
                    
                    var materials = wallSC.HasAssociations.OfType<IIfcRelAssociatesMaterial>().Select(r => r.RelatingMaterial);
                    
                    foreach (IfcMaterialLayerSetUsage materialLSU in materials)
                    {
                        IfcMaterialLayerSet matLS = materialLSU.ForLayerSet;
                        
                        foreach (IfcMaterialLayer matLayer in matLS.MaterialLayers)
                        {
                            Console.WriteLine(matLayer.Material.Name);
                        }
                        
                                    
                    }                    
                }`

**Comment by martin1cerny** [comment]
You are welcome.
