### ISSUE TITLE
How to collect the geometry data from IFC file?

### ISSUE THREAD

**Issue by michealChin** [xBimTeam/XbimEssentials#37]
Hi,

This open source project is a great job! I spend a few days to study it but it is too huge for me. Actually what I need is to open an IFC file, import the structural element such as Beam, Wall, Slab, Column and its 3D geometry data. Can anyone give me some hints to do that? Thanks in advance.

**Comment by martin1cerny** [comment]
Hi @michealChin , thanks for your appreciation. It is not very clear from your question in which direction you need the data to flow. Do you need to save data from external source into the IFC model or do you need to extract data from IFC and import them into other environment? What kind of geometry do you need? Native IFC geometry, B-Rep, triangulated mesh or other?

**Comment by michealChin** [comment]
Hi Martin,

Thanks for your kindly reply, I actually would like to extract data from IFC and import them into other environment and I need the native IFC geometry with the final orientation and position (world matrix).

**Comment by martin1cerny** [comment]
Native geometry in IFC is a very complex part of the standard and it follows ISO 10303. Absolute most of the geometry is positioned relative to its parent in the structure (table is relative to space, that is relative to storey, that is relative to building, that is relative to site). You can use xBIM to get complete IFC data of geometry which can either be directly represented as `IfcProduct.Representation` and all further references plus chain of `IfcProduct.ObjectPlacement` which can be absolute or relative as described above. Representation can also be mapped (for products which have the same representation but have multiple instances placed in different locations). For detailed information about the structure see [IFC documentation](http://www.buildingsmart-tech.org/ifc/IFC4/Add1/html/).

**Comment by michealChin** [comment]
Ya, I know it is relative to its parent. Previously I tried the old xbim version (2.4.1), there is a class call TransformGraph which able to return the final orientation and position of the element.

            TransformGraph graph = new TransformGraph(refModel);
            graph.AddProducts(toDraw); //load the products as we will be accessing their geometry

  if (t is IfcColumn)
 {
    XbimMatrix3D matrix = graph[t].WorldMatrix();
    .....
 }
else   if (t is IfcWall)
 {
    XbimMatrix3D matrix = graph[t].WorldMatrix();
    .....   
 }

I can get all the orientation and position correctly for IfcBeam, IfcColumn and IfcWall except for IfcSlab which always return me wrong orientation.

**Comment by martin1cerny** [comment]
This kind of functionality is implemented in [Xbim.ModelGeometry.Scene](https://github.com/xBimTeam/XbimGeometry/tree/develop/Xbim.ModelGeometry.Scene). For related questions you are better to ask in [XbimGeometry](https://github.com/xBimTeam/XbimGeometry) as XbimEssentials only deal with semantics of IFC.

**Comment by michealChin** [comment]
Hi,

Thanks Martin.

**Comment by dinesh14persaud** [comment]
Hi, sorry if i am off topic. Have you guys implement a mobile version of BIM Viewer, for iOS maybe?

**Comment by martin1cerny** [comment]
Yes we did in past but it was part of a project with a company where the results are not public/open-source.

**Comment by LloydPickering** [comment]
Just to add to what Martin said, iOS uses OpenGL ES for it's graphics API (https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/Introduction/Introduction.html), as does Android. The Xbim.WebViewer uses WebGL, which in turn is based on OpenGL ES, and is therefore VERY similar.

You should be able to use the 3D graphics side of the web viewer as the basis of how to build the 3D side of an iOS app. Obviously there is far more to it than just the 3D side, but that's probably the most tricky part for most people as graphics programming is a little out of the norm for most devs.

**Comment by Pyogisha** [comment]
Hi,

I am developing test app for IFC viewer for iOS platform. But stuck in finding solution and open source as well. I saw some post here w.r.t IFC in iOS. Guys plz help me to implement it. Any suggestions or example app available for learning would be greatly appreciable.

**Comment by MGVisschers** [comment]
You may want to check my graduation thesis. In short: I used Python scripting to extract information from IFC files. For example, i extracted building elements with its geometry and material properties, hereafter I translated this information into a XML structure.

**Comment by martin1cerny** [comment]
Using the latest multiplatform developments from Microsoft it should be possible to compile and run most of xBIM on iOS. However, we haven't tried this yet. If your application is server based we worked on a project in past where IFC was processed on a Windows server to the form which could than be rendered and visualized on any iOS device.

**Comment by mjuusela** [comment]
MGVisschers, your thesis sounds very interesting. Could we have a look at it? And the code?

**Comment by MGVisschers** [comment]
Thank you for reaching out to me.

Of course you can have a look at my thesis and the code I wrote is open source / free accessible for everyone interested.

Correct me if i'm wrong but you can download my thesis and code directly from Github!
Then from curiosity, what kind of code / tool are you planning to make?

I'm happy to answer any question regarding my work.

Kind regards,
Maarten Visschers

________________________________
Van: mjuusela <notifications@github.com>
Verzonden: vrijdag 11 augustus 2017 11:08
Aan: xBimTeam/XbimEssentials
CC: Maarten Visschers; Comment
Onderwerp: Re: [xBimTeam/XbimEssentials] How to collect the geometry data from IFC file? (#37)


MGVisschers, your thesis sounds very interesting. Could we have a look at it? And the code?

**Comment by stonecompass** [comment]
@martin1cerny How did you implement the windows server application? Did you display a webpage on the iOS devices?
