### ISSUE TITLE
Find plane equation to compute distances

### ISSUE THREAD

**Issue by taismag** [xBimTeam/XbimEssentials#371]
Hello! i'm new in Xbim and i'm trying to find longest distances between walls. I think it is easier to do that by finding the distances between the vertices of each wall and the planes (faces) of each wall. The problem is I don't know if it is possible to find the plane equation (to calculate the distance from point to plane). I could do it by picking 3 points on the face of the wall, but I don't know how to do that. I could find the triangles on each face and the indices, but I don't know if there is a way to find the vertices of these triangles from that.

Another (and easier) way to do this would be to calculate the distances from the edges of the walls to the vertices of the walls (distance from point to line), but I was unable to get the edges of the walls.

Maybe there is a simpler way to find the distances in xbim too, but I have no idea from what I've studied so far.

The code I have so far is:

```cs
using (var model = IfcStore.Open(fileName))
            {
                Xbim3DModelContext context = new Xbim3DModelContext(model);
                context.CreateContext();

                IEnumerable<IIfcProduct> walls = model.Instances.OfType<IIfcWall>();
                count = walls.Count(); 
                Console.WriteLine(count);

                foreach (var wall in walls)
                {
                    Console.WriteLine("\nID: " + wall.GlobalId + "; Nome do Elemento: " + wall.Name); 

                    var productShape = context.ShapeInstancesOf(wall);

                    var todas_faces = new List<XbimFaceTriangulation>();

                    foreach (var shape in productShape)
                    {
                        var transform = shape.Transformation;
                        var geometry = context.ShapeGeometry(shape);
                        var data = ((IXbimShapeGeometryData)geometry).ShapeData;

                        using (var stream = new MemoryStream(data))
                        {
                            using (var reader = new BinaryReader(stream))
                            {
                                var mesh = reader.ReadShapeTriangulation();
                                mesh = mesh.Transform(transform);

                                var faces = mesh.Faces;

                                Console.WriteLine("Number of faces " + faces.Count());

                                foreach (XbimFaceTriangulation face in faces)
                                {
                                    todas_faces.Add(face);

                                    var normal = face.Normals;

                                    var triangleCount = face.TriangleCount; //number of triangles

                                    var indices = face.Indices;

                                }
                            }
                        }
                    } 
                }       
            }
```

If anyone knows, please give me a hint.

Thank you!

**Comment by martin1cerny** [comment]
You have already found how to get the triangles. The rest is a generic mathematical exercise. You would be best to compute distance between triangles. 

Here is one of many links you can find:
https://stackoverflow.com/questions/53602907/algorithm-to-find-minimum-distance-between-two-triangles

**Comment by taismag** [comment]
Thank you for your answer!

But actually I haven't found the triangles yet. I found the number of triangles on each face (which is an int), but I don't know how to access their vertex and edges. From what I saw in your post, I would need toget them anyway to do that calculation, right?

**Comment by martin1cerny** [comment]
You just need to use indices to access vertices:

```cs
var mesh = reader.ReadShapeTriangulation();
mesh = mesh.Transform(transform);

foreach (XbimFaceTriangulation face in mesh.Faces)
{
    // iterate over triangles
    for (int i = 0; i < face.TriangleCount; i++)
    {
        // get indices pointing to list of vertices
        var idx1 = face.Indices[i * 3];
        var idx2 = face.Indices[i * 3 + 1];
        var idx3 = face.Indices[i * 3 + 2];

        // get vertices for the triangle
        var p1 = mesh.Vertices[idx1];
        var p2 = mesh.Vertices[idx2];
        var p3 = mesh.Vertices[idx3];

        // here is a single triangle
        var triangle = new[] { p1, p2, p3 };
    }

}
```

**Comment by taismag** [comment]
Thank you very much, Martin! :)
