### ISSUE TITLE
List of all different IfcEntities in IfcFile

### ISSUE THREAD

**Issue by VahdetC** [xBimTeam/XbimEssentials#374]
*Summary*
- i have an ifc file with different IfcEntities like IfcWall, IfcBeam, IfcColumn etc.
- i'm struggling to find a way to list all different entities in this ifc file
- the list should contain every ifcentity occurence just once {"IfcWall", "IfcColumn", "IfcBeam", ...}
- debugged also the code to see if there was any property which held the value i was searching for

#### My Code:
- i've used the xbim Essential quick start guide
- googled also
- looked through the issues here on github

```csharp
using (var model = IfcStore.Open(_FilePath))
{
    var allInstances = model.Instances;
    var testList = model.Instances.OfType<IIfcBuildingElement>();

    var nameList = new List<string>();
    var objTypeList = new List<string>();
    foreach (var item in testList)
    {
        var objType = item.IsTypedBy;
        var firstObjType = objType.ElementAt(0);
        var relType = firstObjType.RelatingType;

        var name = item.Name;
        nameList.Add(name);
    }
}
```

Would appreciate any help

**Comment by martin1cerny** [comment]
is this what you want?

```cs
var testList = model.Instances.OfType<IIfcBuildingElement>().GroupBy(e => e.GetType());
```

**Comment by VahdetC** [comment]
Yes thank you so much!

**Comment by UVinfotech** [comment]
I have .ifc file and in this many proprties for each element. I load the .ifc file in my project and show properties. But I would like to update property values. I have tried a lot but nothing is helpful.

This is my .ifc file here i update value of property.

`#218=IFCWALLSTANDARDCASE('1pDQMJdjH6bhX$cSYxDgoS',#42,'Basiswand:Wandtyp 1:7596179',$,'Basiswand:Wandtyp 1',#190,#212,'7596179');
#259=IFCPROPERTYSINGLEVALUE('5dmep 720 Druckverlust Abluft',$,IFCPRESSUREMEASURE(1000.),$);
#260=IFCPROPERTYSINGLEVALUE('5dmep 720 Druckverlust Aussenluft',$,IFCPRESSUREMEASURE(1000.),$);
#261=IFCPROPERTYSINGLEVALUE('5dmep 720 Druckverlust Fortluft',$,IFCPRESSUREMEASURE(1000.),$);
#262=IFCPROPERTYSINGLEVALUE('5dmep 720 Druckverlust Zuluft',$,IFCPRESSUREMEASURE(1000.),$);
#263=IFCPROPERTYSINGLEVALUE('5dmep 720 Geschwindigkeit Abluft',$,IFCLINEARVELOCITYMEASURE(1000.),$);
#264=IFCPROPERTYSINGLEVALUE('5dmep 720 Geschwindigkeit Aussenluft',$,IFCLINEARVELOCITYMEASURE(1000.),$);
#265=IFCPROPERTYSINGLEVALUE('5dmep 720 Geschwindigkeit Fortluft',$,IFCLINEARVELOCITYMEASURE(1000.),$);
#266=IFCPROPERTYSINGLEVALUE('5dmep 720 Geschwindigkeit Zuluft',$,IFCLINEARVELOCITYMEASURE(1000.),$);
#267=IFCPROPERTYSINGLEVALUE('5dmep 720 Volumenstrom Abluft',$,IFCVOLUMETRICFLOWRATEMEASURE(0.277777777777778),$);
#268=IFCPROPERTYSINGLEVALUE('5dmep 720 Volumenstrom Aussenluft',$,IFCVOLUMETRICFLOWRATEMEASURE(0.277777777777778),$);
#269=IFCPROPERTYSINGLEVALUE('5dmep 720 Volumenstrom Fortluft',$,IFCVOLUMETRICFLOWRATEMEASURE(0.277777777777778),$);
#270=IFCPROPERTYSINGLEVALUE('5dmep 720 Volumenstrom Zuluft',$,IFCVOLUMETRICFLOWRATEMEASURE(0.277777777777778),$);`

@martin1cerny Can you please help me?

**Comment by martin1cerny** [comment]
What did you try @UVinfotech? [This example](https://docs.xbim.net/examples/basic-model-operations.html) shows how to change properties in the model (scroll down to the "Update" section).
