### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by paireks** [xBimTeam/XbimEssentials#376]
Hello guys!

I have a more formal question: if I'm using your libraries in my open source project (that is on MIT License), and I will include your dlls in my project:

- Do I need to change my license from MIT to CDDL?
- How to correctly add you to the credits: is including your CDDL license with your dlls will be enough?

Looking forward to hear from you :)

**Comment by martin1cerny** [comment]
Hi @paireks, thanks for asking. You don't have to change your license from MIT to CDDL. Adding license is OK, but if you give us some credit in the product documentation, it will make us excited. I assume it is your [T-Rex](https://github.com/paireks/T-Rex) project?

**Comment by paireks** [comment]
Hello, OK. 

Yes, I left the information about xbim wherever I could: Github, manual (https://code-structures.com/T_Rex_Manual/Manual%20for%20T-Rex.html), and inside download page (https://www.food4rhino.com/app/t-rex).

Thank you for help ;)
