### ISSUE TITLE
EsentSessionSharingViolationException with Parallel.ForEach

### ISSUE THREAD

**Issue by XYCaptain** [xBimTeam/XbimEssentials#378]
*Short summary describing the issue. (3-5 sentences)*
EsentSessionSharingViolationException: Multiple threads are using the same session.

#### Assemblies and versions affected:

*Which assemblies/packages and their versions are known to be affected. E.g. __Xbim.Essentials 5.1.323__*

#### Steps (or code) to reproduce the issue:

```csharp
 var psetsrels = model.Instances.OfType<IfcRelDefinesByProperties>();
 Parallel.ForEach(psetsrels, rel =>
{
}
```
#### Expected behavior:
using Parallel.ForEach() to read all IfcPropertySet

#### Actual behavior or exception details:

*What actually is happening*

#### Additional Details
IfcStore.ModelProviderFactory.UseHeuristicModelProvider();

**Comment by martin1cerny** [comment]
Esent model doesn't support parallel reading from the database.

**Comment by XYCaptain** [comment]
> Esent model doesn't support parallel reading from the database.
Your help is greatly appreciated.I have a few more questions.
Is it possible to open large files and process them in parallel？Can Toolkit build only a subset of graphical features？

**Comment by martin1cerny** [comment]
You should be able to process several Esent models in parallel, but not their internal data. So, this should work fine:

```cs
var models = new IModel[]{ modelA, modelB, modelC };
Parallel.ForEach(models, model => {
   // process the model ...
});
```

If you use `MemoryModel`, you can access the data in parallel as well, but that is not scalable if you want to process several large models at the same time. 

We currently work on a (commercial) cloud service which uses distributed processing of models for custom workflows. Let me know if you were interested to hear more.
