### ISSUE TITLE
Quick geometry units conversion

### ISSUE THREAD

**Issue by paireks** [xBimTeam/XbimEssentials#379]
Hello!

Just a quick question: is there an easy built-in way to convert geometries into different units? (Different than millimeters).

The thing is I have a geometry that is unit-less. When I convert it with xbim to Ifc geometry and later export it, it assumes by default that it is in millimeters.

If there is a way to simply switch it with code into inches, meters, centimeters and so on: that would be cool. If there is no option for that then I assume the way to do this is to scale it by myself before the conversion, and only then convert it with xbim to Ifc geometry.

Looking forward to hearing from you :)

**Comment by martin1cerny** [comment]
It depends on what you actually want to do. If you only want to change the declared units of the model, than it is very simple. To make it meters, just do this:

```cs
var project = model.Instances.FirstOrDefault<IfcProject>();
var lengthUnit = project.UnitsInContext.OfType<IfcSIUnit>().Where(u => u.UnitType == IfcUnitEnum.LENGTHUNIT);
lengthUnit.Prefix = null;
lengthUnit.Name = IfcSIUnitName.METRE;
```

If you actually want to scale the geometry, than you have to scale all the definitions which is non-trivial as a generic task. But if you only deal with triangulated geometry, it is quite easy as well.

**Comment by paireks** [comment]
Thank you! I think this is exactly what I needed!

The only thing I had to change is to insert ".Units" between before OfType ;)
