### ISSUE TITLE
ManagedEsent 1.9.3.3 problem

### ISSUE THREAD

**Issue by kozintsev** [xBimTeam/XbimEssentials#38]
I use xBim develop (Xbim.Essentials.4.0.0-V198) and found problem if update ManagedEsent from 1.9.2.0 to 1.9.3.3 (in my project).
Please test it.

The problem occurs if to call the xBim library from another library( which uses a standard mechanism for application extensions in .NET - Managed Extensibility Framework (MEF)). 
In my case ...

**Comment by martin1cerny** [comment]
You will need to be more specific about the problem @kozintsev.

**Comment by kozintsev** [comment]
Xbim.Essentials.4.0.0-V198 use ManagedEsent 1.9.2.0 version.
If use Xbim.Essentials.4.0.0-V198 and update ManagedEsent to 1.9.3.3. in project then we have a problem.
There are two ways to fix the problem:
- Rolling back to a previous ManagedEsent version
- Compile the xBim with a new version of the ManagedEsent

**Comment by martin1cerny** [comment]
We will eventually upgrade to the latest ManagedEssent but we are not planning that for now.

**Comment by kozintsev** [comment]
Issue created for information. Thanks for the info!
