### ISSUE TITLE
Problem saving ifc in Hololens application

### ISSUE THREAD

**Issue by EpaN-netizen** [xBimTeam/XbimEssentials#380]
Hello, 

I am working on an application that edits an ifc file in Hololens. I can successfully open the ifc file using the IfcStore.Open function. But, when I try to save the ifc file in a folder in Hololens (persistentDataPath) using the IfcStore.SaveAs function, I am facing problems regarding the IfcOwnerHistory. More specifically, the error is:

`System.ArgumentException: Get Method not found for 'OwningUser'`

The writing of the ifc starts, but is terminated in the line:
`#2=IFCOWNERHISTORY(`

It seems that I cannot save the original ifc, even without any editing. I run the following code:

    using (var model = IfcStore.Open(Path.Combine(Application.streamingAssetsPath, "MyIfc.ifc")))
    {
             model.SaveAs(Path.Combine(Application.persistentDataPath, "MyExportedIfc.ifc"));
    }

I am struggling to find what is the problem, something about the editor credentials and the IfcRoot, maybe? I tried inserting XbimEditorCredentials, but with no success. The above code works fine in Unity for reading and saving the ifc.

Does anybody has any experience saving ifc in Hololens? Could anyone please help me understand what is the problem? 

Thank you in advance.

**Comment by martin1cerny** [comment]
I have no experience with Hololens but this seems like a problem with Reflection. We use reflection to go through properties to serialise them. And this exception looks like it doesn't work properly on your platform. Can you try simple test like this?

```cs
public class TestClass
{
    public int TestProperty { get; set; }
}

class Program
{
    public static void Main(string[] args)
    {
        var instance = new TestClass { TestProperty = 5 };
        var info = typeof(TestClass).GetProperty(nameof(TestClass.TestProperty));
        var value = info.GetValue(instance);

        if (value == null || !(value is int testValue) || testValue != 5)
            throw new System.Exception("Reflection not working!");
    }
}
```

**Comment by EpaN-netizen** [comment]
Martin, thank you very much for your quick response. It works now on Hololens, I wasn't getting the fields of entities correctly. Now, I can open and save the ifc on Hololens using the following code to get the values for entity IfcOwnerHistory (and for IfcOrganization, IfcApplication, and IfcPerson, accordingly):


```
using (var model = IfcStore.Open(Path.Combine(Application.streamingAssetsPath, "MyIfc.ifc")))
{
	using (var txn = model.BeginTransaction())
	{
		var instanceOwnerHistory = model.Instances.FirstOrDefault<IfcOwnerHistory>();
		var ifcOwnerHistoryProperties = typeof(IfcOwnerHistory).GetProperties();
		var result = new object[ifcOwnerHistoryProperties.Length];
		for (int i = 0; i < ifcOwnerHistoryProperties.Length; i++)
		{
			result[i] = ifcOwnerHistoryProperties[i].GetValue(instanceOwnerHistory);
		}
		txn.Commit();
	}
	model.SaveAs(Path.Combine(Application.persistentDataPath, "MyExportedIfc.ifc"));
}
```

Can't thank you enough for your help!

**Comment by martin1cerny** [comment]
I§m not quite sure why you need to use reflection to do this, but I'm glad that it works for you.
