### ISSUE TITLE
XbimSolid not in the right place

### ISSUE THREAD

**Issue by gelsonbieber** [xBimTeam/XbimEssentials#39]
I am using the following code to get XbimSolid and build a solid with the faces coordinates, but when finished, the solids get far away from each other, like if some are on the right place and others on the origin. Can someone help me? Also, how can I find the IfcProduct of the XbimSolid? So I can try to get the transformation and also the attributes.
Thanks!

            List<Xbim.Ifc2x3.GeometryResource.IfcGeometricRepresentationItem> items = model.Instances.OfType<Xbim.Ifc2x3.GeometricModelResource.IfcExtrudedAreaSolid>().ToList<Xbim.Ifc2x3.GeometryResource.IfcGeometricRepresentationItem>();
            MessageBox.Show("Geometric - " + items.Count().ToString());

            for (int i = 0; i < items.Count(); i++)
            {
               
      
                if (items[i] is Xbim.Ifc2x3.GeometricModelResource.IfcExtrudedAreaSolid)
                {
             
                    
                    XbimGeometry.Interfaces.IXbimSolid solidotemp = _xbimGeometryCreator.Create(items[i]) as XbimGeometry.Interfaces.IXbimSolid;
 		    XbimGeometry.Interfaces.IXbimFaceSet faces = solidotemp.Faces;

		}
	    }

![capturar](https://cloud.githubusercontent.com/assets/19961326/16097298/8f0b8682-3323-11e6-84f4-998da8bf6a23.PNG)

**Comment by martin1cerny** [comment]
@gelsonbieber, you are using very low level API to handle geometry. Please have a look at [Xbim.ModelGeometry.Scene](https://github.com/xBimTeam/XbimGeometry/tree/develop/Xbim.ModelGeometry.Scene) for API to get products and their representation. Product is defining geometry placement.

**Comment by gelsonbieber** [comment]
@martin1cerny I Really Appreciate your answer, but I am not able to get the Representation.
I am going thru the Model.IfcProducts
In each there is a Representation
But I cant get the geometry.
Can you give me a little example?
Thank you very much!

**Comment by martin1cerny** [comment]
The best place is to have a look on tests in [XbimGeometry](https://github.com/xBimTeam/XbimGeometry/tree/develop).

**Comment by gelsonbieber** [comment]
I got it. Thanks!
