### ISSUE TITLE
Defining Model View Definitions (MVDs)

### ISSUE THREAD

**Issue by kudav** [xBimTeam/XbimEssentials#390]
Hello everyone!

I was wondering if Xbim allows to define Model View Definitions (MVDs) when creating a model from scratch. Or if, in your opinion, it would even make sense to do so.

Thank you!

**Comment by martin1cerny** [comment]
We have MVD library as part of the xbim Toolkit. So, you can create both MVDs and IFCs with xbim. Based on your question, I'm not quite sure what you want to achieve. Would you like to share more about what you want to do?

**Comment by kudav** [comment]
I am creating an IFC file from scratch with Xbim with all the detailing for a wood building (for my master thesis) and the goal is to guarantee a certain IFC quality. In the literature, the correct implementation of MVDs is part of this quality definition. That’s why I wondered if I should make sure my file complies to e.g. the Design View (IFC4) and if this step is already implemented in Xbim. So my goal is not to create a MVD, but to check if my IFC file complies with the existing MVDs of building smart.

**Comment by martin1cerny** [comment]
Yes, you can use for example Design View MVD defined in MVDXML format and you can use [XbimMvdXML](https://github.com/xBimTeam/XbimMvdXML) project (and respective NuGet package) to run validation of the file. And yes, it is a good indicator for the quality of the resulting model.

**Comment by kudav** [comment]
Thank you, I'll try using that!

**Comment by kudav** [comment]
Hello again,
I couldn't find the nuget package and on the github site it also says that it is not found. 
Will it be accessible in the future?
Thank you!

**Comment by martin1cerny** [comment]
You may need to use our **MyGet feeds**:

    https://www.myget.org/F/xbim-develop/api/v3/index.json
    https://www.myget.org/F/xbim-master/api/v3/index.json
