### ISSUE TITLE
Property set names are not unique

### ISSUE THREAD

**Issue by kudav** [xBimTeam/XbimEssentials#391]
Hello everyone!

In the Xbim.Xplorer IFC Validation, I get the issue that my property set names are not unique. This is certainly true, but I wondered why this is an issue. In my understanding property sets can be used to assign the same (e.g. physical) quantities to objects. Is this wrong? Or should I use a different entity instead of IfcPropertySet?

#### Validation messages:
```
Entity #33 (IfcPropertySet) has validation failures.

                Issue of type EntityWhereClauses on IfcPropertySet.UniquePropertyNames.

Entity #58 (IfcPropertySet) has validation failures.

                Issue of type EntityWhereClauses on IfcPropertySet.UniquePropertyNames.

Entity #86 (IfcPropertySet) has validation failures.

                Issue of type EntityWhereClauses on IfcPropertySet.UniquePropertyNames.
```

#### Respective lines of the IFC file:

```
#33=IFCPROPERTYSET('3mP5G7x6fBQwzZX04tDRw3',#2,'ISO717_SoundTransmission',$,(#34,#35,#36,#37,#38,#39));

#58=IFCPROPERTYSET('2JmajOlJfEQPpx6glItUlG',#2,'ISO717_SoundTransmission',$,(#59,#60,#61,#62,#63,#64,#65,#66));

#86=IFCPROPERTYSET('2Jiz2CtinFcgHDClnQiCG1',#2,'ISO717_SoundTransmission',$,(#87,#88,#89,#90,#91,#92));
```

Thank you!

**Comment by martin1cerny** [comment]
There is an explicit rule in IFC standard which says: 
> UniquePropertyNames | Every individual subtype of IfcProperty within the property set shall have a unique Name attribute value.

So, the problem is in your set of properties, not in the property sets themselves. This list of properties will contain one or more properties with the same name: `#34,#35,#36,#37,#38,#39`

**Comment by kudav** [comment]
Sorry, my bad! This solves the issue :)
Thank you!
