### ISSUE TITLE
Find ending location of a IfcBeam in 3D (x-y-z)

### ISSUE THREAD

**Issue by epsi1on** [xBimTeam/XbimEssentials#392]
Hi all,
I need to find the start and end location of `IfcBeam` in 3d (i need x-y-z of start and end). this is what i do so far:

```
var pl = beam.ObjectPlacement as IfcLocalPlacement;
var pl2 = pl.RelativePlacement as IfcAxis2Placement3D;
var pl2 = t2.Location; // this is the start point (x,y,z) but how to find the ending node?
```

I can find the start node, but not the ending node. I think the `IfcAxis2Placement3D.Axis` and `IfcAxis2Placement3D.RefDirection`  or even `IfcAxis2Placement3D.ToMatrix3D()` should be used for this purpose, but i do not know how to use them. Can anyone please suggest something?

Thanks

**Comment by martin1cerny** [comment]
If the geometry of the beam is an extruded shape, you will need to inspect the extrusion direction and depth: https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcextrudedareasolid.htm

**Comment by epsi1on** [comment]
Thanks.
For example consider IFC beam named `beam1`. With above method i can find ending point of extruded beam. I also need to determine which other beam/columns are connected to this beam, one method is to check the end point and se if it is common with other beams, but rounding problem can cause errors. 
Is there any other Properties, method etc which i can find other elements connected to this `beam1`?

Thanks again

**Comment by epsi1on** [comment]
> 
> 
> If the geometry of the beam is an extruded shape, you will need to inspect the extrusion direction and depth: https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcextrudedareasolid.htm

How can i find `IfcExtrudedAreaSolid` object related to the `IfcBeam` object?
I'm not familiar with IFC entity model...
Thanks

**Comment by martin1cerny** [comment]
You will need to get more familiar with [IFC schema](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/) to be able to use IFC data on this level. You can have a look at our [example](https://docs.xbim.net/examples/proper-wall-in-3d.html) where we create extruded shape for a wall. You just need to read it instead.

**Comment by rnilay81** [comment]
@epsi1on  -  Were you able to resolve this issue ? I was also looking something similar to this. Let me know please.

**Comment by epsi1on** [comment]
> @epsi1on - Were you able to resolve this issue ? I was also looking something similar to this. Let me know please.

yes, the object's geometry is inside the property `Representation`. this code does the work partially for me:


```
                 var cols = model.Instances.OfType<IfcBuildingElement>().ToList();//list of columns

                foreach(var bm in cols)
                {
                    var ext = bm.Representation.Representations.FirstOrDefault(i => i.RepresentationType == "SweptSolid") ;

                    
                    var cl = ext.Items.FirstOrDefault() as IfcExtrudedAreaSolid;

                    var pl0 = (bm.ObjectPlacement as IfcLocalPlacement);
                    var m0 = pl0.ToMatrix3D();

                    var pl = pl0.RelativePlacement as IfcAxis2Placement3D;
                    
                    var start = pl;
                    var dirc = cl.ExtrudedDirection.XbimVector3D();

                    var m1 = cl.Position.ToMatrix3D();


                    var d2 = dirc;// new XbimVector3D(dirc.X,dirc.Y,dirc.Z); 

                    var l = Convert.ToDouble(cl.Depth.Value);

                    var p0c = start.Location.XbimPoint3D();//m0.Transform(m1.Transform(start.Location.XbimPoint3D()));

                    var p0 = new Point(p0c.X, p0c.Y, p0c.Z);

                    Point p2;

                    {
                        var m = pl.ToMatrix3D();
                        //m.Invert();
                        d2 = m0.Transform(m1.Transform(d2)) ;

                        var dir = new Vector(d2.X, d2.Y, d2.Z);
                        
                        p2 = p0 + dir * l;
                    }


                    var n1 = new Node(p0);//p0 start location
                    var n2 = new Node(p2);//p1 end location

                }
```

**Comment by martin1cerny** [comment]
Thanks @epsi1on for a working example. @rnilay81 , you will probably need to put in more type checking because the geometry might be other than `IfcExtrudedAreaSolid`. Also, if the profile (`cl.SweptArea`) is one of `IfcParametrizedProfileDef`, it might have additional offset in `IfcParametrizedProfileDef.Position`. Also, id the profile is an arbitrary profile, the question what is the definition point of the profile. Is it [0,0], or is it centroid of the profile shape? Or something else? You may need to consider these based on your usecase.

From the [documentation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcprofiledef.htm):
![IfcParametrizedProfileDef](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/figures/ifcprofiledef-layout1.gif)

**Comment by rnilay81** [comment]
> > @epsi1on - Were you able to resolve this issue ? I was also looking something similar to this. Let me know please.
> 
> yes, the object's geometry is inside the property `Representation`. this code does the work partially for me:
> 
> ```
>                  var cols = model.Instances.OfType<IfcBuildingElement>().ToList();//list of columns
> 
>                 foreach(var bm in cols)
>                 {
>                     var ext = bm.Representation.Representations.FirstOrDefault(i => i.RepresentationType == "SweptSolid") ;
> 
>                     
>                     var cl = ext.Items.FirstOrDefault() as IfcExtrudedAreaSolid;
> 
>                     var pl0 = (bm.ObjectPlacement as IfcLocalPlacement);
>                     var m0 = pl0.ToMatrix3D();
> 
>                     var pl = pl0.RelativePlacement as IfcAxis2Placement3D;
>                     
>                     var start = pl;
>                     var dirc = cl.ExtrudedDirection.XbimVector3D();
> 
>                     var m1 = cl.Position.ToMatrix3D();
> 
> 
>                     var d2 = dirc;// new XbimVector3D(dirc.X,dirc.Y,dirc.Z); 
> 
>                     var l = Convert.ToDouble(cl.Depth.Value);
> 
>                     var p0c = start.Location.XbimPoint3D();//m0.Transform(m1.Transform(start.Location.XbimPoint3D()));
> 
>                     var p0 = new Point(p0c.X, p0c.Y, p0c.Z);
> 
>                     Point p2;
> 
>                     {
>                         var m = pl.ToMatrix3D();
>                         //m.Invert();
>                         d2 = m0.Transform(m1.Transform(d2)) ;
> 
>                         var dir = new Vector(d2.X, d2.Y, d2.Z);
>                         
>                         p2 = p0 + dir * l;
>                     }
> 
> 
>                     var n1 = new Node(p0);//p0 start location
>                     var n2 = new Node(p2);//p1 end location
> 
>                 }
> ```

Thanks @epsi1on . Will try this out and update you .

**Comment by rnilay81** [comment]
> Thanks @epsi1on for a working example. @rnilay81 , you will probably need to put in more type checking because the geometry might be other than `IfcExtrudedAreaSolid`. Also, if the profile (`cl.SweptArea`) is one of `IfcParametrizedProfileDef`, it might have additional offset in `IfcParametrizedProfileDef.Position`. Also, id the profile is an arbitrary profile, the question what is the definition point of the profile. Is it [0,0], or is it centroid of the profile shape? Or something else? You may need to consider these based on your usecase.
> 
> From the [documentation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcprofiledef.htm):
> ![IfcParametrizedProfileDef](https://camo.githubusercontent.com/f386d2084887a75cc323f2e550f5b1e9a0d2408e07c65a20abc0ad4da733dbb5/68747470733a2f2f7374616e64617264732e6275696c64696e67736d6172742e6f72672f4946432f52454c454153452f494643342f414444325f5443312f48544d4c2f666967757265732f69666370726f66696c656465662d6c61796f7574312e676966)

Thanks @martin1cerny . Will keep these things in mind while implementing.

**Comment by martin1cerny** [comment]
Here is how the simple implementation may look like:

```cs
foreach (var beam in model.Instances.OfType<IIfcBeam>())
{
    var representation = beam.Representation?.Representations?
        .FirstOrDefault(r => 
        string.Equals(r.RepresentationIdentifier, "body", StringComparison.OrdinalIgnoreCase));

    // no 3D geometry
    if (representation == null || representation.Items.Count == 0)
    {
        model.Logger.LogWarning($"Skipped beam #{beam.EntityLabel}. No 3D representation.");
        continue;
    }

    // more than one item. This would require further handling to identify the points
    if (representation.Items.Count > 1)
    {
        model.Logger.LogWarning($"Skipped beam #{beam.EntityLabel}. More than 1 representation items.");
        continue;
    }

    var item = representation.Items[0];
    if (!(item is IIfcExtrudedAreaSolid extrusion))
    {
        // other representation item types would require different handling. 
        // It might be triangulated geometry, or sweep or something els
        model.Logger
            .LogWarning($"Skipped beam #{beam.EntityLabel}. Representation item is {item.GetType().Name}");
        continue;
    }

    // transformation matrix computed from the placement hierarchy
    var transformation = beam.ObjectPlacement.ToMatrix3D();

    // swept area is the most common 3D representation of beams
    var profileDef = extrusion.SweptArea;
    if (!(profileDef is IIfcParameterizedProfileDef paramProfile) || paramProfile.Position == null)
    {
        // other representation types would require other processing
        continue;
    }

    var point = paramProfile.Position.Location;
    var xpoint = new XbimPoint3D(point.X, point.Y, point.Z);
    var start = transformation.Transform(xpoint);

    model.Logger.LogInformation($"Beam starts at [{start.X}, {start.Y}, {start.Z}]");

    var direction = extrusion.ExtrudedDirection;
    var xdirection = new XbimVector3D(direction.X, direction.Y, direction.Z);
    var translation = xdirection.Normalized() * extrusion.Depth;
    var end = start + translation;

    model.Logger.LogInformation($"Beam ends at [{end.X}, {end.Y}, {end.Z}]");
}

```
