### ISSUE TITLE
Using this project as part of my own project.

### ISSUE THREAD

**Issue by levenherz** [xBimTeam/XbimEssentials#394]
Dear colleagues.
Sorry to write you a message here.
I have recently found your software and I am wondering if I may use it in my paid app?

I read the license and I am ready to add any links to your software but I want to have my part of the code hidden. I will not modify your code, just use your classes.

Is it possible? If not then can I buy the license to use it as described above? I would like to create a project for AV in BIM models

Sincerely Yours, Denis.

**Comment by levenherz** [comment]
Sorry. Found your email

**Comment by martin1cerny** [comment]
An answer for anybody else wondering: The CDDL license allows to combine the Toolkit with any proprietary code. It is not a "viral" type of license. That means that it doesn't constrain or enforce any specific licensing or behaviour when used in other projects. It is being used in hundreds of commercial projects worldwide already.
