### ISSUE TITLE
How can i get the relation between the  Property Values and the IFC Units?

### ISSUE THREAD

**Issue by struckl** [xBimTeam/XbimEssentials#396]
I can not find a way to get the corresponding Unit to a Property Value or a Quantity Value

File for this example: "Sample House.ifc" [SampleHouse.zip](https://github.com/xBimTeam/XbimEssentials/files/7176589/SampleHouse.zip)

The IFC File has IFCSIUNITs which are refered to in the IFCUNITASSIGNMENT.
And the a IFCPROPERTYSINGLEVALUE for example has IFCLENGTHMEASURE(_*value*_).

I am reading the file into C# and i can not find a way to tell which Unit has been assigned to the Value of the Property or Quantity .
For example :
#4898= IFCPROPERTYSINGLEVALUE('Length',$,IFCLENGTHMEASURE(4645.),$);
Is 4645 given in m or mm?

Also following Output of the Code is always empty, because i think .Unit is only filled if it is different of the IFCUNITASSIGNMENT.  (Same with Properties)
```csharp
  foreach (IIfcPhysicalQuantity quantity in (propertySet as IIfcElementQuantity).Quantities)
  {
    switch (quantity)
    {
            case IIfcQuantityLength ifcLength:
                    Console.WriteLine(ifcLength.Unit.toString());
                    break;
    }  
  }
```

I sadly could not find any solution online related to my problem.
Thank you in advance!

**Comment by jomijomi** [comment]
Yes, regarding "unit" being empty in the IFCPROPERTYSINGLEVALUE the specification states:

"Unit for the nominal value, if not given, the default value for the measure type (given by the TYPE of nominal value) is used as defined by the global unit assignment at IfcProject"

So, when not given, we have to look at IFCPROJECT and get "UnitsInContext", and then find the units used for length, i.e. .LENGTHUNIT. (and we then see that it´s in mm)

excerpt from file below to show the relevant parts:
```
#43= IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.);
#90= IFCUNITASSIGNMENT((#43,#45,#46,#50,#52,#53,#54,#56,#60,#65,#67,#68,#69,#70,#71,#72,#73,#78,#82,#84,#88));
#103= IFCPROJECT('1o0c33arXF9AEePDXPKItb',#42,'Project Number',$,$,'Project Name','Project Status',(#95),#90);
```

/Mikael

**Comment by martin1cerny** [comment]
As Michael said, when there is no unit explicitly defined for the property, it defaults to project-wide units. You can find the map between value types and unit types in [this table](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcmeasureresource.htm).
