### ISSUE TITLE
CP:1871 IfcProject.UnitsInContext.Units always lists units as AMPERE

### ISSUE THREAD

**Issue by andyward** [xBimTeam/XbimEssentials#4]
https://xbim.codeplex.com/workitem/1871 

I hit this the other day. You end up with all units appearing to be Ampers in the debugger. It looks like:

`IfcSIUnit.ToString()`

is not implemented correctly

![image](https://cloud.githubusercontent.com/assets/923699/8308417/7d4483b2-19bc-11e5-9a92-9ebc50e518a6.png)

**Comment by martin1cerny** [comment]
Shall we close this issue @andyward ?

**Comment by andyward** [comment]
I'd guess events have overtaken this since we're code-gen'ing the schema classes. The PR referenced above was not actually merged to master so it's still broken there, but the IFC4 changes will have fixed it independently I'd guess. The issue was using a member in ToString before Activate had been called.

**Comment by martin1cerny** [comment]
Yes, that shouldn't be an issue any more.
