### ISSUE TITLE
Contractualise reading data from a persistant data source to the IModel class with implementations in 'MemoryModel', 'EsentModel' etc

### ISSUE THREAD

**Issue by RichardWhitfield** [xBimTeam/XbimEssentials#403]
The methods for opening the data from a Step21 file (`OpenReadStep21()`) are coupled to the `MemoryModel` class, while the methods for opening the data from an EsentDb are coupled to the `EsentModelClass`.  This gives 2 issues:
1. Extending the model types for data persistance will be more difficult and will require larger code changes to implement
2. It is not possible to mock the behaviour of the file read command when unit testing 
3. Programming to an interface supports IoC making testing in general easier

#### Assemblies and versions affected:
Xbim.IO.Esent
Xbim.IO.MemoryModel

*Which assemblies/packages and their versions are known to be affected. E.g. __Xbim.Essentials 4.0.29__*
Xbim.Essentials (5.1.323)

#### Steps (or code) to reproduce the issue:

Reproduction of potential unit test code below for testing an API endpoint which received a Step21 file and opens this.  Note unit test is testing *only* the controller method.  For simplicity I have removed auth, logging etc.
The issue can be found in the `Assert` section of the unit test:

```csharp
        [Fact]
        public async Task CreateModelAsync_ShouldReturnOkResult_WhenValidIfcFileIsPassed()
        {
            //Arrange

            //Create sample model data to be returned
            IModel modelSample;
            using (var store = IfcStore.Create(Xbim.Common.Step21.XbimSchemaVersion.Ifc4, Xbim.IO.XbimStoreType.InMemoryModel))
            {
                using (var transaction = store.BeginTransaction("Create Elements"))
                {
                    var element = store.Instances.New<IfcColumn>();
                    transaction.Commit();
                }
                modelSample = store.Model;
            }
            //Mock required entities
            var factoryMock = new Mock<IEntityFactory>();
            var fileMock = new Mock<IFormFile>();
            var modelMock = new Mock<IModel>();
            
            //Act

            //Mock behaviour from 'OpenReadStep21' method call
            //*This is where the issue lies.*  Because the method OpenReadStep21 is coupled to the MemoryModel class it cannot                         
            //be mocked in testing.
            modelMock.Setup(m => m.OpenReadStep21(fileMock.Object.OpenReadStream()))
                .ReturnsAsync(modelSample);

            //Test controller method
            var result = await _sut.CreateModelAsync(factoryMock.Object, fileMock.Object);
            
            //Assert

            //Unit testing of IResult is currently difficult due to internal classes implmenting IResult. 
            //Known issue logged here: https://github.com/dotnet/aspnetcore/issues/37502
            //TODO: Update test when MS fix issue with IResult
            result.ToString().Should().Be(Results.Ok().ToString());
        }
```

#### Minimal file to reproduce the issue:

N/A

#### Expected behavior:

The persistent models (`Step21` files, `EsentModels` and any other implemented) should be responsible for thier own 'reading'.

#### Actual behavior or exception details:

The `MemoryModel` is actually a 'File Reader' responsible for loading the Step21 file but the `EsentModel` is responsible for reading it's own data.

#### Additional Details

Suggest passing the responsibility for readong from the files to the storage medium used (in this case Step21 files and the EsentModel).
Both of the persistent models mentioned could implement the IModel interface which could stipulate a `Read()` method implemented by each of the concrete classes.

There is also duplication of functionality with `MemoryModel` exposing a method `OpenReadStep21()` and the inherited class `StepModel` exposing a method `LoadStep21()` which appear to do the same thing

I think this change should be possible without breaking the existing code.  We can keep the `OpenReadStep21()` and 'LoadStep21()' methods for example and create a new `Open()` or `Load()` method which they can call to support backward compatibility.

**Comment by martin1cerny** [comment]
Yes, `IModel` interface doesn't assume any specific presistance. If your main concern is to mock the opening operation then it sounds like a good candidate for the provider design pattern. Your `IModelProvider` would expose methods needed to open the model from file/stream/DB Blob/string/.... And you could easily mock the behaviour to return any `IModel` you need for your tests.

**Comment by RichardWhitfield** [comment]
Thanks @martin1cerny , sorry for the very slow reply on this.  
The IModelProvider certainly does meet these requirements.  Will close this issue.
