### ISSUE TITLE
Using of IfcIndexedColourMap

### ISSUE THREAD

**Issue by GVladislavG** [xBimTeam/XbimEssentials#404]
Hello, team!
I try to use IfcIndexedColourMap to set diffrent colors to IfcTriangulatedFaceSet.
I get the result IFC-file. But it has some errors.
Please help to understand, what I'm doing wrong.
Thanks!
[test.zip](https://github.com/xBimTeam/XbimEssentials/files/7433701/test.zip)

**Comment by martin1cerny** [comment]
You will need to be more specific about *some errors*.

**Comment by GVladislavG** [comment]
The result IFC-file is in attached archive. If Itry to open it with BimVision, software crashes
with Unknown_Eception

**Comment by martin1cerny** [comment]
I'm sorry, but I can't debug BimVision to find why it is crashing. But first thing to do is to run the schema validation which we have implemented:

```cs
var v = new Validator
{
    ValidateLevel = ValidationFlags.All,
    CreateEntityHierarchy = true
};
var schemaErrors = v.Validate(model.Instances).;
```
Also, don't forget that **IFC indices are 1 based**. Your indices seem to be 0 based:

```
#85=IFCINDEXEDCOLOURMAP(#87,0.3,#86,(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0...
```

**Comment by GVladislavG** [comment]
Thanks! It works! 
But how can I add an opacity to windows?
I set the Opacity of IfcIndexedColourMap to 0.8. 
But window is not transparent.
[test.zip](https://github.com/xBimTeam/XbimEssentials/files/7469573/test.zip)

**Comment by martin1cerny** [comment]
It may not be supported by the viewer?

**Comment by GVladislavG** [comment]
Maybe. Let's see in future versions of BimVision. Or in other viewers...

**Comment by martin1cerny** [comment]
I'm closing for now. Reopen if needed.
