### ISSUE TITLE
Question - writing e2e test for xbim part

### ISSUE THREAD

**Issue by paireks** [xBimTeam/XbimEssentials#405]
Hello!

Next to the unit tests I wanted to write small number of end2end tests, that will simply compare the resultant IFC file created with xbim with the expected IFC file. Issue is that obviously comparing two IFCs line by line won't work, because of time stamps / guids and maybe few other things. How can I automatically test if the IFC file created is the same as expected then?

Best regards ;)

**Comment by martin1cerny** [comment]
You will need to define what **the same** means to you. We auto-generate UUIDs but you can specify your own IDs for all objects. That way, your model creation should be completely deterministic. If you want to get more complicated you can have a look at our code to  insert a copy of  IPersistEntity from one model to another and use the same logic to traverse certain sub-graphs and compare them.

**Comment by paireks** [comment]
Thank you for suggestions :)

At the end I test function that creates an IFC by later opening it also with xBim, and analyzing specific instances, that I want to check one by one.

Best regards :)
