### ISSUE TITLE
Question - IfcOwnerHistory

### ISSUE THREAD

**Issue by paireks** [xBimTeam/XbimEssentials#406]
Hi,

if I understand correctly IfcOwnerHistory is created in xbim automatically once we Initialize an IfcProject.
My question is if is there is a simple way to not initialize IfcOwnerHistory at all?

Looking at the Tekla or BlenderBIM export of IFC4, I see that they don't even bother to attach IfcOwnerHistory. Thing is that different applications use this data in a different way, so if it's not necessary to attach it - maybe an option to not attach it at all would be even better than trying to understand different approaches.

Best regards ;)

**Comment by martin1cerny** [comment]
Hi @paireks . `IfcOwnerHistory` is mandatory in IFC2x3 and we keep the implementation for IFC4. But you are right, it is not mandatory in IFC4 so it should be optional. We only set it automatically when you use `IfcStore` where we try to automate as much as possible for convenient data retrieval and creation. Feel free to submit a PR which will make the owner history optional for IFC4.
