### ISSUE TITLE
Looking for source code for a specific build of Xbim.Essentials

### ISSUE THREAD

**Issue by lustenbc** [xBimTeam/XbimEssentials#411]
I had problems opening certain ifc files (the program was somehow stuck in an eternal loop).
I found a build of Xbim.Essentials (and also Xbim.Geometry) which fixed the problem.
The build numbers are:
4.0.1902.12444 Xbim.Essentials
4.0.1902.12484 Xbim.Geometry

Now I need the corresponding sources, because the CDDL license requires availability of source code when distributing the binaries.

Questions:
Does anybody know where/how the source code for these builds can be obtained?
Does anybody face the same/similar ifc opening problems, and is there a solution for this issue in an official release?

Many thanks.

**Comment by CBenghi** [comment]
Hi, 

for xbim4 the build number encapsulates the date of the build.
That would be 2019 February 12th - 444 an 484 point to the time of day (minutes from midnight divided by two to fit in the available length of the field).

I think you are looking for 
Essentials: 2abf8acec9cf47ad7b20621a2466917f47776461
Geometry: 3516fd07d72b365ce6eb51486ee325b1106f9374

For any future readers this has changed for version 5 and no longer applies.
