### ISSUE TITLE
Can we get rid of Microsoft.Extensions.Logging dependency?

### ISSUE THREAD

**Issue by ChernyshevDS** [xBimTeam/XbimEssentials#415]
Hello. I've recently tried to use Xbim library in Unity project and I've noticed that I need to include dependent libraries that are totally useless in my case.

Xbim uses `Microsoft.Extensions.Logging.Abstractions` to avoid dependency on specific logging framework and this is nice, but it depends also on `Microsoft.Extensions.Logging` implementation that depends on 6 other assemblies:

Microsoft.Extensions.Configuration.Abstractions.dll
Microsoft.Extensions.Configuration.Binder.dll
Microsoft.Extensions.Configuration.dll
Microsoft.Extensions.DependencyInjection.Abstractions.dll
Microsoft.Extensions.Options.dll
Microsoft.Extensions.Primitives.dll

All this stuff is needed only to provide default implementation of `LoggingFactory` in `XbimCommon.XbimLogging`:

```csharp
public static ILoggerFactory LoggerFactory {
    get
    {
        if (_loggerFactory == null)
        {
            _loggerFactory = new LoggerFactory();
        }
        return _loggerFactory;
    }
    set
    {
        _loggerFactory = value;
    }
}
```

To get rid of dependencies we can use `NullLoggerFactory` from `Abstractions` package. Of course, it has a drawback that we can not just add custom `ILoggerProvider` to existing `LoggerFactory` anymore, so the API has to be changed to prevent its misuse:

```csharp
private static ILoggerFactory _loggerFactory = Microsoft.Extensions.Logging.Abstractions.NullLoggerFactory.Instance;

public static void SetLoggerFactory(ILoggerFactory factory)
{
    _loggerFactory = factory;
}
```

Otherwise the user may call `XbimLogging.LoggerFactory.AddProvider(myProvider)` and be unpleasantly surprised that nothing happens.

That is a breaking API change, so I'm not sure if it worths the hassle. But reducing the number of dependencies also reduces the risk of potential versions mismatches. May be in next major release?

**Comment by martin1cerny** [comment]
Hi @ChernyshevDS , we had an internal discussion before we introduced this. In previous versions we were just using `Log4Net`. Using `Microsoft.Extensions.Logging.Abstractions` was a step towards less specific dependencies already. But you are right, it is still not great. My intention is to use ` Microsoft.Extensions.DependencyInjection` for this kind of dependencies as well as configuration of other aspects of the xbim set-up. As part of this, I'd like to get rid of this static member which will make it a non-confusing change with compile time check. But yes, that would be for the next major release.

**Comment by ChernyshevDS** [comment]
Thank you for the answer.

**Comment by Thaina** [comment]
Are there any progress on this? I wish I could use this library in unity android/ios and webgl

**Comment by martin1cerny** [comment]
In a couple of weeks.

**Comment by martin1cerny** [comment]
#455
