### ISSUE TITLE
Missing single-value properties of cable trays

### ISSUE THREAD

**Issue by ameliajiang321** [xBimTeam/XbimEssentials#417]
*Hi! I'm trying to read the properties of a cable tray segment. I used the following code and it returned only 2 properties (Manufacturer and Reference). But when I checked in Dynamo, 25 properties were found in the same element. I wonder if anyone has met a similar issue of (possibly) missing single value properties?*

*I'm using Xbim.Essentials 5.1.297, Visual Studio 2019, windows 10.*

*The following code works when the element is a structural one, e.g. a column.*

```csharp
using (var model = IfcStore.Open("file.ifc"))
{
    var id = "3cLbQZoCX4HQwCo0a9J232";   // IfcCableCarrierSegment        
    var theCable = model.Instances.FirstOrDefault<IIfcElement>(d => d.GlobalId == id);
    Console.WriteLine($"ID: {theCable.GlobalId}, Name: {theCable.Name}");
    // ...
    // Find all single value properties
    var properties = theCable.IsDefinedBy
           .Where(r => r.RelatingPropertyDefinition is IIfcPropertySet)
           .SelectMany(r => ((IIfcPropertySet)r.RelatingPropertyDefinition).HasProperties)
           .OfType<IIfcPropertySingleValue>();
     foreach (var property in properties)
           Console.WriteLine($"Property: {property.Name}, Value: {property.NominalValue}");
}
```
*The result produced by the code above:*
![console](https://user-images.githubusercontent.com/68220328/160016763-88a4ce22-b429-4e84-b85c-4bb431482360.PNG)

*Screenshot of Dynamo showing 25 properties of the element:*
![dynamo](https://user-images.githubusercontent.com/68220328/160014431-6bdec381-c949-4af7-a852-0bd671184a6d.PNG)

*The ifc file:*

[cable tray file.zip](https://github.com/xBimTeam/XbimEssentials/files/8346014/cable.tray.file.zip)

**Comment by dumitrugrl** [comment]
Depending on the way the export handles elements, some property sets might be attached via the _typedby_ relation.
Maybe you could check it like this:

```
 var typeBy = el.IsTypedBy.ToList();
foreach (var tb in typeBy)

var relType = tb.RelatingType;
if (relType != null)

var psvList = relType.HasPropertySets.OfType<IIfcPropertySet>().SelectMany(r => r.HasProperties).OfType<IIfcPropertySingleValue>().ToList();

foreach (var psv in psvList){}
}
```

**Comment by martin1cerny** [comment]
Hi @ameliajiang321, thanks for using the Toolkit. As @dumitrugrl suggested, it is usually necessary to inspect type properties as well to get a complete list of properties. But in this case, the issue is with your IFC export configuration. I had a look at your file and **there are no more properties in the IFC file**. I assume you access the native file with Dynamo. Make sure you export **all* properties from Revit to IFC in this case. Or even better, make sure you configure the exporter to export **the properties you actually need and want**.

**Comment by ameliajiang321** [comment]
Many thanks to @dumitrugrl and @martin1cerny ! Your advice is super helpful. The issue is indeed as @martin1cerny pointed out, and it is resolved by checking "Export Revit property sets" when exporting the ifc file from Revit.
