### ISSUE TITLE
Resize Object

### ISSUE THREAD

**Issue by VuGiaHuy-0808** [xBimTeam/XbimEssentials#418]
Hello xBim team.
I have a random object like a picture. I want to add that object into my model but I have problem with it's size.
I wonder is it possible to resize object using xBimEssentials.
Thanks for the answers.
![Screenshot 2022-03-28 170050](https://user-images.githubusercontent.com/66827155/160375505-a9279ea6-d604-4603-b8f3-374b7f3e6127.png)

**Comment by martin1cerny** [comment]
Yes, this is possible in principle. I assume your object uses different units than the main model?

**Comment by VuGiaHuy-0808** [comment]
In fact, my object has different units than the main model. Can you show how can I do that?
Thanks in advance.

**Comment by CBenghi** [comment]
Hello, it would be helpful if you could share the model to look at the units used there.
It might be just a matter of setting the units correctly in the `IFCUNITASSIGNMENT` of a project.

You probably have some unit similar to the following: `IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.);`

and the dollar sign should be replaced with a factor (e.g. .MILLI.), but it difficult to provide correct instructions without a look at the models.
You could start reading up something about units here: https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/schema/ifcmeasureresource/lexical/ifcunitassignment.htm

**Comment by VuGiaHuy-0808** [comment]
I have some mistakes, my object and main model uses the same units.
This is my issue, when I add object into the main model using insertCopy(), seems like object size is quite small and I want it bigger than that. Here is the main model and object.
[IFCFile.zip](https://github.com/xBimTeam/XbimEssentials/files/8376955/IFCFile.zip)

**Comment by martin1cerny** [comment]
You can apply scale for the mapped item:
https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifccartesiantransformationoperator3d.htm
