### ISSUE TITLE
How to write and save ifc files now? (seems that xBimDocument has been deleted.)

### ISSUE THREAD

**Issue by WangYini** [xBimTeam/XbimEssentials#42]
In the given example in https://xbim.codeplex.com/  the ifc file can be written and saved through xBimDocument class. But I can't find this class in xBimToolkit now. Is this writing function still available in xbim toolkit? 
Thank you very much!

**Comment by martin1cerny** [comment]
Hi @WangYini , thanks for your interest in xBIM. It is indeed possible to create and save IFC files with xBIM. The whole toolkit has gone quite a journey since we moved from Codeplex to GitHub. The best from xBIM is now in `develop` branch which is pretty stable by now. Preferred document level object is `IfcStore` which can handle both IFC2x3 and IFC4. The easiest way to use it is to add our development NuGet stream https://www.myget.org/F/xbim-develop/api/v2.

Basic code would look like this:
```cs
var credentials = new XbimEditorCredentials
{
    ApplicationDevelopersName = "Martin",
    ApplicationFullName = "xBIM Sample Application",
    ApplicationIdentifier = "xBIM SA",
    ApplicationVersion = "0.1",
    EditorsFamilyName = "Cerny",
    EditorsGivenName = "Martin",
    EditorsOrganisationName = "xBIM Team"
};
using (var model = IfcStore.Create(credentials, IfcSchemaVersion.Ifc2X3, XbimStoreType.InMemoryModel))
{
    using (var txn = model.BeginTransaction("Data creation"))
    {
        var wall = model.Instances.New<IfcWall>(w => w.Name = "Brand new wall");
        var prop = model.Instances.New<IfcPropertySingleValue>(p =>
        {
            p.Name = "InternalID";
            p.NominalValue = new IfcIdentifier("9A17A7FF-F4ED-458B-A69B-9C3F72D7EFB4");
        });
        var pSet = model.Instances.New<IfcPropertySet>(ps =>
        {
            ps.Name = "Internal Properties";
            ps.HasProperties.Add(prop);
        });
        model.Instances.New<IfcRelDefinesByProperties>(r =>
        {
            r.RelatingPropertyDefinition = pSet;
            r.RelatedObjects.Add(wall);
        });

        txn.Commit();
    }
    model.SaveAs("model.ifc");
}

```

**Comment by ToxaDev** [comment]
Hi @martin1cerny!
Show please how to create wall with width and height and in specified location.
And add to this wall one opening.

Thank You!

**Comment by martin1cerny** [comment]
Please, refer to a documentation of IFC schema to see how the data should
be structured. xBIM will allow you to create such a data easily by using
`model.Instances.Create<IInstantiableEntity>()`.

**Comment by refac2019** [comment]
Hi @martin1cerny 

How I can to convert WPF Model3D/GeometryModel3D to Xbim object for after save it to IFC file format?

Please, help me!!!

**Comment by martin1cerny** [comment]
You would be better to open a new issue for this @refac2019 .

**Comment by refac2019** [comment]
> You would be better to open a new issue for this @refac2019 .

Hi Martin, I had already opened a new issue. 

Please follow the link: https://github.com/xBimTeam/XbimEssentials/issues/308


Thank you very much!
