### ISSUE TITLE
Xbeam.Essentials + Xbeam.Geometry version 4 vs version 5

### ISSUE THREAD

**Issue by LubomirBucek** [xBimTeam/XbimEssentials#421]
Hello
I am very sorry to trouble you.

I created a small simple project "HelloWall".
(It is nested in a basic ASP.NET Web Application (.NET Framework)).
Target Framework 4.8
Windows 10/64 21H1 19043.1586
Visual Studio Pro 2019 ver. 16.11.11

Until I use NuGet Packages ver. 4
Xbeam.Essentials 4.0.32
Xbeam.Geometry 4.0.19
All is runnig perfectly, no problem.

But after update NuGet Packages on ver.  5 (where I expect ifc format compatibility for Autodesk Revit 2023)
Xbeam.Essentials 5.1.323
Xbeam.Geometry 5.1.403
Program does not start, browser shows error message:
"Could not load file or assembly 'Xbim.Geometry.Engine64' or one of its dependencies. An attempt was made to load a program with an incorrect format."

I found out more questions on web with the exactly same problem.
But I did not find out solution.
Can I ask you please, where I should start investigation.
May be information: ver 4 loads, but ver. 5 no can a litle help for an advices.

Thank you very much for your help.
Kind regards.
Lubomir

**Comment by martin1cerny** [comment]
This message usually means there is an issue with x86/x64 versions. We have changed the way geometry engine is added to the projects to follow recent developments. Is your application x86? Make sure there is only the right native geometry engine file deployed as IIS is pre-loading all assemblies in the folder, including those not needed (and not compatible).

**Comment by LubomirBucek** [comment]
Thank you for your answer and advices.
Fortunately I found, I dont need Xbim.Geometry.Engine at all.
I only construct ifc model an write it into a file.
For watching the result I use XbimXplorer or Trimble Connect viewer.
My program is running without nuget package Xbim.Geometry.
So, even if problem is not solved, I can close this issue.
Thank you again.
Kind regards.
Lubomir
