### ISSUE TITLE
Can't Modify Existing Properties Individually

### ISSUE THREAD

**Issue by RyanDaley** [xBimTeam/XbimEssentials#427]
I've been trying to learn how to change the values of existing Properties within existing Psets in my Ifc File.
Martin posted a pretty good answer [here  ](https://github.com/xBimTeam/XbimEssentials/issues/122#issuecomment-346760420).  

```csharp
var property = model.Instances
    .Where<IfcPropertySingleValue>(p => p.Name == "I_want_to_change").ToList()
    .ForEach(p => p.Value = new IfcLabel("I'm changed now!"));
````
This works brilliantly.  However, I can't assign a different value for each object.  
Whenever, I try to iterate through all the model objects, they all end up with the same value.  

```csharp
               foreach(EntityConcept concept in ConceptList)
               {
                    var xbimConcepts = AllBuildingElementsOfType(concept.ifcEntity, model);
                    if (xbimConcepts != null)
                    {
                        concept.Guids = GuidsListFromIfcEntities(xbimConcepts);
                        for (int i = 0; i < concept.Guids.Count(); i++)
                        {
    IfcPropertySet propSet = xbimConcepts.ElementAt(i).GetPropertySet(myPropSet);
    var prop = propSet.HasProperties.OfType<IfcPropertySingleValue>().FirstOrDefault((IfcPropertySingleValue p) => p.Name == myProperty);

    prop.NominalValue = new IfcLabel(i.ToString());

txn.Commit();
                            }
                        }
                    }    
```

In this instance, all the objects receive the same value.  

I guess it just finds the "FirstOrDefault" Property in the IFC file, instead of the "FirstOrDefault" that is associated with this IFC object.

How can I set the nominal value differently for each object?

I guess I need to access the "IfcRelDefinesByProperties."  Im not entirely sure what this entity is, but I guess this is what I\m missing when comparing with the [standard Update example. ](https://docs.xbim.net/examples/basic-model-operations.html).

**Comment by martin1cerny** [comment]
Modifying property values might be tricky, especially if the IFC file has been optimised as part of the post-processing. It is possible that multiple entities and property sets actually share a single instance of the property. In that case, changing one value at one place changes the value for everything referencing that property in the object graph. Or, multiple entities might be pointing to a single instance of property set which will have the same effect.

The best you can do in that case is to build a lookup of all property set and property references upfront and clone the instance if you want to change it but it is shared across multiple entities.

**Comment by RyanDaley** [comment]
> Modifying property values might be tricky, especially if the IFC file has been optimised as part of the post-processing. It is possible that multiple entities and property sets actually share a single instance of the property. In that case, changing one value at one place changes the value for everything referencing that property in the object graph. Or, multiple entities might be pointing to a single instance of property set which will have the same effect.
> 
> The best you can do in that case is to build a lookup of all property set and property references upfront and clone the instance if you want to change it but it is shared across multiple entities.


Martin,

Is there any way I can assign a unique property to each model instance, and still have the names be the same?
What I find strange is that all of my "FireRating" properties get the same value, even if they exist within different psets such as  Pset_ColumnCommon.FireRating and Pset_BeamCommon.FireRating.  Its painfully obvious that I am not accessing the property for specific objects, or even specific Pset, but that the property exists in only one place within the IFC file.  

![image](https://user-images.githubusercontent.com/65096230/176613083-411c906a-1628-4f02-9253-7b1711adb95a.png)

But, at least it does end up in the correct place in the IFC schema:
![image](https://user-images.githubusercontent.com/65096230/176614055-5c42541d-a09b-4c06-9370-e4fca47f17e1.png)






Martin, you are well aware of this, but this is for anyone else interested.  If I [create new properties and psets as is shown in the examples](https://docs.xbim.net/examples/basic-model-operations.html), it does create a unique value for each model object, but it also creates a duplicate Pset in the schema.  Here, we can see that each model object has a unique property definition in my IFC file:    
![image](https://user-images.githubusercontent.com/65096230/176611286-3eb80f7a-e577-47d0-9a28-5bb5b969a399.png)

This is not ideal because now my property is not in the correct place in the IFC Schema.  You can see that now there are two Pset_BeamCommon property sets.  
![image](https://user-images.githubusercontent.com/65096230/176612388-b4f566d5-b150-471b-8927-9b4e0b7ffa97.png)

**Comment by RyanDaley** [comment]
@martin1cerny ,

I assume that I need to access the existing [IfcRelDefinesByProperties. ](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/schema/ifckernel/lexical/ifcreldefinesbyproperties.htm) 
Because this is what defines the relationship between an object and its Psets.  

I wrote a Linq query that finds the IfcRelDefinesByProperties for each relevant object and Pset.
I then try to get the relevant Pset and Property from that IfcRelDefinesByProperties.
However, this did not now.

```csharp
    IfcRelDefinesByProperties relDefinesByProperties = model.Instances.Where<IfcRelDefinesByProperties>(r =>
        r.RelatingPropertyDefinition == model.Instances.Where<IfcPropertySet>(pSet => pSet.Name == myPropSet)
            && r.RelatedObjects.Contains(xbimConcepts.ElementAt(i))).FirstOrDefault();
    if (relDefinesByProperties != null)
    {
        IfcPropertySet mySet = relDefinesByProperties.RelatingPropertyDefinition as IfcPropertySet;
        if (mySet != null)
        {
            IfcPropertySingleValue myProp = mySet.HasProperties.Where<IfcPropertySingleValue>(p => p.Name == myProperty).FirstOrDefault();
            myProp.NominalValue = new IfcLabel(teklaUda);
        }
    }
```

**Comment by RyanDaley** [comment]
> Modifying property values might be tricky, especially if the IFC file has been optimised as part of the post-processing. It is possible that multiple entities and property sets actually share a single instance of the property. In that case, changing one value at one place changes the value for everything referencing that property in the object graph. Or, multiple entities might be pointing to a single instance of property set which will have the same effect.
> 
> The best you can do in that case is to build a lookup of all property set and property references upfront and clone the instance if you want to change it but it is shared across multiple entities.

How would you clone property and property references?  Wouldnt one have to then change all the references from the IfcRelDefines and the IfcPropertySets?  Is xBim capable of doing this?  Or is this something I would have to do without the xBim API?

**Comment by martin1cerny** [comment]
Yes, you would need to change references and make copies. And yes, you can use the Toolkit to do this. Following code is taken and enhanced from `Xbim.Common.ModelHelper`. It is actually very interesting topic. I'll cover this in the next issue of the Toolkit Newsletter.

```cs
public static void Expand<IParentEntity, IUniqueEntity>(
    IModel model, 
    Expression<Func<IParentEntity, ICollection<IUniqueEntity>>> accessor,
    Func<IParentEntity, bool> parentFilter,
    Func<IUniqueEntity, bool> childFilter
    ) where IParentEntity : IPersistEntity where IUniqueEntity : IPersistEntity
{
    var pInfo = GetPropertyInfo(accessor);
    //get duplicates in one go to avoid exponential search
    var candidates = new Dictionary<IUniqueEntity, List<IParentEntity>>();
    foreach (var entity in model.Instances.OfType<IParentEntity>().Where(parentFilter))
    {
        var children = pInfo.GetValue(entity) as ICollection<IUniqueEntity>;
        foreach (var val in children.Where(childFilter))
        {
            if (!candidates.TryGetValue(val, out var parents))
            {
                parents = new List<IParentEntity>();
                candidates.Add(val, parents);
            }
            parents.Add(entity);
        }
    }

    var multi = candidates.Where(a => a.Value.Count > 1);
    var map = new XbimInstanceHandleMap(model, model);

    foreach (var kvp in multi)
    {
        var value = kvp.Key;
        var entities = kvp.Value;

        //skip the first
        for (int i = 1; i < entities.Count; i++)
        {
            //clear map to create complete copy every time
            map.Clear();
            var copy = model.InsertCopy(value, map, null, false, false);

            //remove original and add fresh copy
            var entity = entities[i];
            var collection = pInfo.GetValue(entity) as ICollection<IUniqueEntity>;
            collection.Remove(value);
            collection.Add(copy);
        }
    }
}

public static void Expand<IParentEntity, IUniqueEntity>(
    IModel model,
    Expression<Func<IParentEntity, IUniqueEntity>> accessor,
    Func<IParentEntity, bool> parentFilter,
    Func<IUniqueEntity, bool> childFilter
    ) where IParentEntity : IPersistEntity where IUniqueEntity : IPersistEntity
{
    var pInfo = GetPropertyInfo(accessor);
    //get duplicates in one go to avoid exponential search
    var candidates = new Dictionary<IUniqueEntity, List<IParentEntity>>();
    foreach (var entity in model.Instances.OfType<IParentEntity>().Where(parentFilter))
    {
        var child = (IUniqueEntity)pInfo.GetValue(entity);
        if (childFilter(child))
        {
            if (!candidates.TryGetValue(child, out var parents))
            {
                parents = new List<IParentEntity>();
                candidates.Add(child, parents);
            }
            parents.Add(entity);
        }
    }

    var multi = candidates.Where(a => a.Value.Count > 1);
    var map = new XbimInstanceHandleMap(model, model);

    foreach (var kvp in multi)
    {
        var value = kvp.Key;
        var entities = kvp.Value;

        //skip the first
        for (int i = 1; i < entities.Count; i++)
        {
            //clear map to create complete copy every time
            map.Clear();
            var copy = model.InsertCopy(value, map, null, false, false);

            //remove original and add fresh copy
            var entity = entities[i];
            pInfo.SetValue(entity, copy);
        }
    }
}

private static PropertyInfo GetPropertyInfo<IParentEntity, IUniqueEntity>(Expression<Func<IParentEntity, ICollection<IUniqueEntity>>> accessor)
{
    if (!(accessor.Body is MemberExpression memacc))
        throw new ArgumentException("Invalid expression type supplied.",nameof(accessor));
    if (!(memacc.Member is PropertyInfo pInfo))
        throw new ArgumentException("Invalid expression return type.", nameof(accessor));
    return pInfo;
}

private static PropertyInfo GetPropertyInfo<IParentEntity, IUniqueEntity>(Expression<Func<IParentEntity, IUniqueEntity>> accessor)
{
    if (!(accessor.Body is MemberExpression memacc))
        throw new ArgumentException("Invalid expression type supplied.", nameof(accessor));
    if (!(memacc.Member is PropertyInfo pInfo))
        throw new ArgumentException("Invalid expression return type.", nameof(accessor));
    if (pInfo.SetMethod == null)
        throw new ArgumentException("Accessor has to have a setter", nameof(accessor));
    return pInfo;
}

```
