### ISSUE TITLE
Get properties for single IFC GUID

### ISSUE THREAD

**Issue by krosoftware** [xBimTeam/XbimEssentials#430]
Hello
I found this: https://docs.xbim.net/examples/basic-model-operations.html
and my question is - how to retrieve all properties for IFC GUID, even if I don't know it is Door??
With other words, I know only IFC GUID and I need all properties for it.
Thank you.

**Comment by krosoftware** [comment]
Is there any way to get properties faster? 
Here is code I use:

> const string fileName = "SampleHouse.ifc";
using (var model = IfcStore.Open(fileName))
{
  //get single element
  var id = "19Cb8kK7HC_RFESV1gaRKO";
  var theElem = model.Instances.FirstOrDefault<IIfcFooting>(d => d.GlobalId == id);
  //get all single-value properties of the door
  var properties = theElem.IsDefinedBy
      .Where(r => r.RelatingPropertyDefinition is IIfcPropertySet)
      .SelectMany(r => ((IIfcPropertySet)r.RelatingPropertyDefinition).HasProperties)
      .OfType<IIfcPropertySingleValue>();
  foreach (var property in properties)
    Console.WriteLine($"Property: {property.Name}, Value: {property.NominalValue}");
}

but it take 2-3 seconds to get results.
Thank you.

**Comment by SteveLockley** [comment]
Have a look in the XbimSamples project BasicCreate/InverseSearchExample.cs

**Comment by krosoftware** [comment]
OK thank you.

**Comment by krosoftware** [comment]
Hello
as I do not work with C# at all, I'm not able to use your sample.
I just try but it does not work :(
Is there anybody who can help (not for free) to create console application which do this:
- take IFC filename as parameter1
- take productID as parameter 2
- send all properties (for productID) to text file
This is what I need: https://i.postimg.cc/8z33XKHX/image-2022-07-14-154501733.png
and this is productID
https://i.postimg.cc/RhLNCpGv/image-2022-07-14-154840559.png
If anyone want to do this, please send your offer to krosoftware_REMOVE_@gmail.com
Thank you.

**Comment by SteveLockley** [comment]
I have tried to send you an email but the address above is invalid, could you contact me please (steve.lockley@xbim.net)

**Comment by krosoftware** [comment]
I did, thanks.

**Comment by krosoftware** [comment]
@SteveLockley , did you received my answer?

**Comment by krosoftware** [comment]
Closed
