### ISSUE TITLE
Is It Possible to remove a Pset's reference to a specific Property?

### ISSUE THREAD

**Issue by RyanDaley** [xBimTeam/XbimEssentials#433]
Is It possible to remove a property from a Pset using xBim?

There are certain instances, where an IfcPropertySingleValue is being referenced by multiple Psets.  However, I just want to remove the reference to this property from one Pset.

It would be the equivalent of removing this line reference from the Pset:

![image](https://user-images.githubusercontent.com/65096230/179764785-dbdcbd27-dfd4-4e5a-92fd-d2c390f1f1c9.png)

If I were to simply delete the property, then it is removed from all the other Psets as well.

Essentially, I wish it was possible to do this:
```csharp
IIfcPropertySet propertySet = model.Instances.FirstOrDefault<IIfcPropertySet>(s => s.Name == pItem.Pset);
propertySet.RemoveProperty("myPropertyName");
```

**Comment by martin1cerny** [comment]
Just use `propertySet.HasProperties.Remove(property)`.

**Comment by RyanDaley** [comment]
@martin1cerny , thanks!
