### ISSUE TITLE
How to add new property?

### ISSUE THREAD

**Issue by krosoftware** [xBimTeam/XbimEssentials#438]
I try to add new property and it does not work - no any message, but properties are not added.
Here is the code:

```
using System;
using System.Linq;
using Xbim.Ifc;
using Xbim.Ifc4.Interfaces;
using Xbim.Ifc4.Kernel;
using Xbim.Ifc4.MeasureResource;
using Xbim.Ifc4.PropertyResource;
using Xbim.Ifc4.SharedBldgElements;

const string fileName = "my.ifc";
var editor = new XbimEditorCredentials
{
    ApplicationDevelopersName = "xbim developer",
    ApplicationFullName = "xbim toolkit",
    ApplicationIdentifier = "xbim",
    ApplicationVersion = "4.0",
    EditorsFamilyName = "Santini Aichel",
    EditorsGivenName = "Johann Blasius",
    EditorsOrganisationName = "Independent Architecture"
};

using (var model = IfcStore.Open(fileName))
{
    //get existing door from the model
    var id = "1xG$tJQVXD_8yHVezENHE5";
    var theDoor = model.Instances.FirstOrDefault<IfcWall>(d => d.GlobalId == id);

    //open transaction for changes
    using (var txn = model.BeginTransaction("Modification"))
    {
        //create new property set with two properties
        var pSetRel = model.Instances.New<IfcRelDefinesByProperties>(r =>
        {
            r.GlobalId = Guid.NewGuid();
            r.RelatingPropertyDefinition = model.Instances.New<IfcPropertySet>(pSet =>
            {
                pSet.Name = "New property set";
                //all collections are always initialized
                pSet.HasProperties.Add(model.Instances.New<IfcPropertySingleValue>(p =>
                {
                    p.Name = "First property";
                    p.NominalValue = new IfcLabel("First value");
                }));
                pSet.HasProperties.Add(model.Instances.New<IfcPropertySingleValue>(p =>
                {
                    p.Name = "Second property";
                    p.NominalValue = new IfcLengthMeasure(156.5);
                }));
            });
        });

        //change the name of the door
        theDoor.Name += "_checked";
        //add properties to the door
        pSetRel.RelatedObjects.Add(theDoor);

        //commit changes
        txn.Commit();
    }

}
```
Also, how to use any type instead of "IfcWall" here:
```
var theDoor = model.Instances.FirstOrDefault<IfcWall>(d => d.GlobalId == id);
```

Thanks.

**Comment by martin1cerny** [comment]
Because this opens the model in memory, you will also need to save it to persist the changes.

**Comment by martin1cerny** [comment]
You can use `model.Instances.FirstOrDefault<IIfcObjectDefinition>(o => o.GlobalId == id)`

**Comment by krosoftware** [comment]
Thanks, but I'm not sure how to do that.
After 
``
tx.commit();
``
I added this:
``
        string memString = txn.ToString(); // or theDoor.ToString();
        // convert string to stream
        byte[] buffer = Encoding.ASCII.GetBytes(memString);
        MemoryStream ms = new MemoryStream(buffer);
        //write to file
        FileStream file = new FileStream("x:\\NEWfile.ifc", FileMode.Create, FileAccess.Write);
        ms.WriteTo(file);
        file.Close();
        ms.Close();
``
But it does not save new IFC file. With other words, how to save model from memory to a new file?
Thanks.

**Comment by martin1cerny** [comment]
Just call `model.SaveAsIfc(model)`. It is an extension method living in `Xbim.Ifc` namespace.

**Comment by krosoftware** [comment]
Awesome, but in the meantime, I found model.SaveAs("FileName.ifc"); as better option :)
Thank you very much

**Comment by krosoftware** [comment]
If you take a look to code above - how to avoid adding new PropertySet if it exists?
With other words - Is it possible to search for property set and reuse it (if it exists)?
I mean on this line:
```
r.RelatingPropertyDefinition = model.Instances.New<IfcPropertySet>(pSet =>
```
If it is possible, how to do that, please?

**Comment by martin1cerny** [comment]
Yes, just use the standard get-or-create approach with caching for improved performance. Bear in mind you can only reuse the property set if you intend to reuse **all the properties** inside.

```cs
var pset = model.Instances
    .FirstOrDefault<IfcPropertySet>(ps => ps.Name == "PSet_XXX" && ps.HasProperties.Any(p => ...))
```

**Comment by krosoftware** [comment]
Thank you but it is above my C# knowledge :(
Maybe you can check simple code below and put your code inside?
The idea is to not to add new PropertySet but to use existing (if  propertySet with name "New property set" already exist).

```
using Xbim.Ifc;
using Xbim.Ifc4.Interfaces;
using Xbim.Ifc4.Kernel;
using Xbim.Ifc4.MeasureResource;
using Xbim.Ifc4.PropertyResource;

const string fileName = "s.ifc";
using (var model = IfcStore.Open(fileName))
{
    //get existing door from the model
    var id = "1xG$tJQVXD_8yHVezENHE5";
    var theElem = model.Instances.FirstOrDefault<IIfcObjectDefinition>(o => o.GlobalId == id);

    //open transaction for changes
    using (var txn = model.BeginTransaction("Modification"))
    {
        //create new property set with two properties
        var pSetRel = model.Instances.New<IfcRelDefinesByProperties>(r =>
        {
            r.GlobalId = Guid.NewGuid();
            r.RelatingPropertyDefinition = model.Instances.New<IfcPropertySet>(pSet =>
            {
                pSet.Name = "New property set";
                //all collections are always initialized
                pSet.HasProperties.Add(model.Instances.New<IfcPropertySingleValue>(p =>
                {
                    p.Name = "First property";
                    p.NominalValue = new IfcLabel("First value");
                }));
;
            });
        });

        //change the name of the door
        theElem.Name += "_checked";
        //add properties to the door
        pSetRel.RelatedObjects.Add((IfcObjectDefinition)theElem);

        //commit changes
        txn.Commit();
    }
    model.SaveAs("BasicWall.ifc");
    model.Dispose();
}
```
Thank you

**Comment by martin1cerny** [comment]
Just call `pSetRel.RelatedObjects.Add((IfcObjectDefinition)theElem);` for all elements where you want to add this property set with this value.

**Comment by krosoftware** [comment]
OK I give up, I don't know how you mean :(
From example above, I want to add only one PropertySingleValue for PropertySet and it works fine.
Problem is - I want to add new propertySet only if it does not exists for current GUID.
Otherwise (if propertySet exist for current GUID), I want to add PropertySet under existing PropertySet (and not to add new one, otherwise I have 2 propertSets with same name, like you can see here:
https://i.postimg.cc/wM0jNTCB/image-2022-08-25-153717061.png
Can you please be so kind and show me (inside code above)?
Thank you.

**Comment by martin1cerny** [comment]
I'm sorry, but this is beyond the level of support I can provide here. Just get all the objects and all their existing property sets first (there are plenty examples of how to do that) and then use it or create a new one.
