### ISSUE TITLE
How to capture propertySets for each geometry?

### ISSUE THREAD

**Issue by PierreAlexandreADAMSKI** [xBimTeam/XbimEssentials#44]
Hi @LloydPickering , @martin1cerny , @andyward , @benjymous, @CBenghi  

I've been trying to get the Properties of each shape this way : 

`

    using (var geomStore = Model.GeometryStore)
    {

        using (var geomReader = geomStore.BeginRead())
        {

            var shapeInstances = geomReader.ShapeInstance.Where(s => s.RepresentationType == XbimGeometryRepresentationType.OpeningsAndAdditionsIncluded && !excludedTypes.Contains(s.IfcTypeId));

            foreach (var shapeInstance in shapeInstances)
            {
                var ifcObjs = Model.Instances[shapeInstance.InstanceLabel] as IIfcObject;
                // then access the properties from ifcObjs
            }

        }

    }
`

but shapeInstance.InstanceLabel is always equal to -1

Can anybody please help me with that?

**Comment by SteveLockley** [comment]
You need to create the geometry context before you can access geometry, see the Issues on the Geometry project for details. In reality though you are doing the wrong thing, IFC does not support adding properties to IFC geometry objects, you can only add them to IfcObjects, geometries do not inherit from this. I am closing this as it is a problem which is not really related to Xbim. If you want to add properties to Xbim Geometry objects you can use the Tag property, but this is transient you will need to persist them yourself. This is in the develop branch only
