### ISSUE TITLE
How to get the center point of the bounding box of all elements?

### ISSUE THREAD

**Issue by GalensGan** [xBimTeam/XbimEssentials#441]
Hello，xBIM team!
  Is there a way to calculate the bounding box of all elements and get the center point of them?

**Comment by martin1cerny** [comment]
Yes, this is possible. You need to use our geometry engine (Xbim.Geometry nuget package) to process all the geometry. They you will be able to get all the bounding boxes of all elements.

**Comment by GalensGan** [comment]
@martin1cerny Thanks! I have isntalled the package but I can't find a document to Introduce how to use，could you show me example code?

**Comment by martin1cerny** [comment]
You can start with this code:

```cs
Xbim3DModelContext context = new Xbim3DModelContext(model);
context.CreateContext();

var elements = model.Instances.OfType<IIfcElement>();
foreach (var element in elements)
{
    var productShapes = context.ShapeInstancesOf(element);
    var bBox = productShapes
        .Select(s => XbimRect3D.TransformBy(s.BoundingBox, s.Transformation))
        .Aggregate(XbimRect3D.Empty, (last, current) => { 
            last.Union(current); 
            return last; 
        });
}
```

**Comment by GalensGan** [comment]
@martin1cerny Wow, it works! Thanks very much!
The type of `BoundingBox`  is `XbimRect3D` , and the method `Centroid()` in `XbimRect3D` is just what I need.
