### ISSUE TITLE
Same code for writing IFC2x3 and IFC4

### ISSUE THREAD

**Issue by johnnyontheweb** [xBimTeam/XbimEssentials#442]
Hello,
I wrote a code that writes correctly IFC4 using XbimEssentials. I'm trying to use the same code for writing IFC2x3.

#### Assemblies and versions affected:

Xbim.Essentials 5.1.259.0

#### Steps (or code) to reproduce the issue:
I'm currently using these import directives:
```
' import lib
Imports Xbim.Ifc
Imports Xbim.Common
' for IFC4
Imports Xbim.Ifc4.Interfaces
Imports Xbim.Ifc4.Kernel
Imports Xbim.Ifc4.SharedBldgElements
Imports Xbim.Ifc4.GeometryResource
Imports Xbim.Ifc4.GeometricConstraintResource
Imports Xbim.Ifc4.ProductExtension
Imports Xbim.Ifc4.ProfileResource
Imports Xbim.Ifc4.MeasureResource
Imports Xbim.Ifc4.RepresentationResource
Imports Xbim.Ifc4.GeometricModelResource
Imports Xbim.Ifc4.MaterialResource
Imports Xbim.Ifc4.StructuralElementsDomain
Imports Xbim.Ifc4.PresentationAppearanceResource
Imports Xbim.ModelGeometry.Scene.Extensions
...
Dim imodel = IfcStore.Create(editor, Step21.XbimSchemaVersion.Ifc2X3,Xbim.IO.XbimStoreType.InMemoryModel)
```

#### Expected behavior:

By using IFC4 interfaces, the code should be the same also for writing IFC2x3. It should expected that by changing the flag in Create function, output would be of the desired schema version (e.g. IFC2x3).

#### Actual behavior or exception details:

**The resulting IFC is still IFC4**, despite the requested schema version in IfcStore.Create was IFC2x3.

**Comment by andyward** [comment]
Yes this won't work. Take a look at https://github.com/xBimTeam/XbimEssentials/issues/360 for how to do this. There's a special [factory](https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Ifc2x3/Interfaces/IFC4/Create.cs) in the IFC2x3 schema that will give you the correct instance depending on the model schema.
