### ISSUE TITLE
Can I change the units of a project?

### ISSUE THREAD

**Issue by ido-cu** [xBimTeam/XbimEssentials#445]
Hi,
I'd like to change the units of my IFC project, in a way that will also affect the coordinates, lengths and volumes of my elements.
For example:
I have a wall that is located at (100, 100, 100)
and my project is in meters.

I'd like to change the units to millimeters and have my wall located at (100,000, 100,000, 100,000).

Is it possible?
Is there an easy way to do it?

**Comment by andyward** [comment]
Yes, you can see how in this issue: https://github.com/xBimTeam/XbimEssentials/issues/379#issuecomment-824619982

**Comment by ido-cu** [comment]
ok, does that answer say that it's enough to change the unit of project.UnitsInContext to make my wall located at  (100,000, 100,000, 100,000)
or do I need to manually change the values of each point in the geometry?

**Comment by andyward** [comment]
No you'd need to refactor the quantities across the model. With complex parametric geometry this could get "gnarly".

Make sure you understand **why** you're doing this. For 3D accuracy purposes _Meters_ might actually be a better unit than _mm_ at world scale. These are floating point numbers so precision can can be un-intuitive.

If you just wanted to present measurements in a different unit for the user, I'd probably convert it further up the stack.

**Comment by ido-cu** [comment]
ok, thanks!
