### ISSUE TITLE
IfcExtrudedAreaSolid holes information?

### ISSUE THREAD

**Issue by michealChin** [xBimTeam/XbimEssentials#45]
Hi,

I have an Ifc file exported from Revit. If open with Xbim Xplorer you will see 4 holes within a IfcSlab. When I try to retrieve the IfcSlab info programmatically, the IfcSlab is actually represented by  IfcExtrudedAreaSolid, I check the IfcExtrudedAreaSolid.SweptArea and it is actually a IfcArbitraryClosedProfileDef and the outerCurve is a IfcPolyline type. My question is where do they store the holes information ? Thanks in advance.

**Comment by martin1cerny** [comment]
It must be a Boolean clipping result.

**Comment by michealChin** [comment]
Ya, I guess so but it is indeed IfcExtrudedAreaSolid type for that slab.

**Comment by martin1cerny** [comment]
Can you share the file and point out an entity label of the slab?

**Comment by michealChin** [comment]
Hi,

Not sure why I can't attach the ifc file directly, I have to copy it to a text file and upload as New Text document.txt.

This file only contain one IFCSlab entity. Only check this IFCslab and ignore the rest of the entity. If you open with Xbim Xplorer sure you will see 4 holes in the slab. Thanks!

[New Text Document.txt](https://github.com/xBimTeam/XbimEssentials/files/347197/New.Text.Document.txt)

**Comment by martin1cerny** [comment]
These are openings which are cut out from the slab:
```
Line 20497: #38973= IFCRELVOIDSELEMENT('16IOGD3YXFov6GZPlweyzW',#41,$,$,#38947,#38968);
Line 20510: #38996= IFCRELVOIDSELEMENT('1mRkPGB0L5GP8wwip$iVnP',#41,$,$,#38947,#38993);
Line 20523: #39018= IFCRELVOIDSELEMENT('39kgYgJ0r3XAbLl4QfJq4N',#41,$,$,#38947,#39015);
Line 20536: #39040= IFCRELVOIDSELEMENT('2M4OdNlrf3sx6mU0lq3Asv',#41,$,$,#38947,#39037);
```

**Comment by michealChin** [comment]
Thanks a lot martin! I will try to study this element type.

**Comment by michealChin** [comment]
Hi Martin

I have successfully extract the information of the opening but I am confused about how to know its position relative to the IfcExtrudedAreaSolid? I try to use IfcRelVoidsElement.RelatedOpeningElement.ObjectPlacement.ToMatrix3D（） to get its position but the position is wrong.

I also found out that, the same project file for the same IfcSlab. When I simplify the project to only one IfcSlab with the openings by deleting others elements(for easy inspection) the IfcRelVoidsElement.RelatedOpeningElement.ObjectPlacement.ToMatrix3D（) return  different value than in the original project file(without delete any elements). Why are they return different value while they are both the same element?

**Comment by martin1cerny** [comment]
Because placement of the opening is relative to the element it voids. See the IFC documentation.

**Comment by michealChin** [comment]
Hi martin,

I have go through the IFC documentation a bit but it is quite difficult to understand. Can you suggest any method to get the World coordinate system of the opening?

**Comment by martin1cerny** [comment]
You need to aggregate all the placements of products.

**Comment by SteveLockley** [comment]
See the Geometry Issues discussion for how to use this using the XbimPlacementTree
