### ISSUE TITLE
IFC4 `IfcLocalPlacement.PlacementRelTo` does not show as `Nullable`

### ISSUE THREAD

**Issue by tymokvo** [xBimTeam/XbimEssentials#458]
Hello,

I noticed today while using Xbim in an FSharp project and editing with VSCode, that the property `PlacementRelTo` does not show as a nullable value:

![image](https://user-images.githubusercontent.com/12144028/197267504-ea989baa-6d9e-477b-bfcb-70cb819d9905.png)

even though it seems to have an annotation as such here:

https://github.com/xBimTeam/XbimEssentials/blob/96f190530d02ba8aef387bb19fc25a9a1c04045f/Xbim.Ifc4/GeometricConstraintResource/IfcLocalPlacement.cs#L70

And is marked as optional in the [express schema][ifc4].

Is this intentional?

[ifc4]: https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2/HTML/link/ifclocalplacement.htm

**Comment by andyward** [comment]
This schema code is generated, so it's possible we need to look at the tooling. We're doing a schema regen for 4.3 so can maybe pick up when doing that.

**Comment by tymokvo** [comment]
Got it! Thanks. Let me know if you can use any other information.

**Comment by martin1cerny** [comment]
Hi @tymokvo, `IfcObjectPlacement` is a class which is a reference type, therefore it is always nullable. The annotation is there for validation purposes. Do you propose to use different mapping between EXPRESS and C#?

**Comment by martin1cerny** [comment]
Hi @tymokvo, `IfcObjectPlacement` is a class which is a reference type, therefore it is always nullable. The annotation is there for validation purposes. Do you propose to use different mapping between EXPRESS and C#?

**Comment by tymokvo** [comment]
Yes, I was going to link to the same article. It does seem to be a default for net6.0 projects. Not sure if there's a recommended runtime version for Xbim, though. 

I think part of the issue for my use case is the interface with F# where `null` is a no-no. The compiler doesn't warn on reference types that may be null, but does for `Nullable<T>` value types. This can lead to unexpected null errors at runtime.

**Comment by martin1cerny** [comment]
It is a language, not a platform/runtime feature, so it should be OK. This will require a minor enhancement in our code generation utility, but is doable and I can see the benefit. As mentioned above, I have created the work item in the project for that. So, I'm closing this issue. You can watch #459 for updates.
