### ISSUE TITLE
Possible bug: XbimEditorCredentials ApplicationDevelopersName not mapped to the IFC entity

### ISSUE THREAD

**Issue by janbrouwer** [xBimTeam/XbimEssentials#465]
When using XbimEditorCredentials in the IfcStore constructor both "IfcApplication->ApplicationDeveloper" and "OwningUser->TheOrganization" for the "IfcOwnerHistory" point to the same "IfcOrganization" created from "EditorsOrganisationName".
I believe "IfcApplication->ApplicationDeveloper" should reference "ApplicationDevelopersName" instead.

So I think, these lines:
https://github.com/xBimTeam/XbimEssentials/blob/044c82b9d7c8bee7e60d3e29200540e0f780a617/Xbim.Ifc/IfcStore.cs#L517
https://github.com/xBimTeam/XbimEssentials/blob/044c82b9d7c8bee7e60d3e29200540e0f780a617/Xbim.Ifc/IfcStore.cs#L518
should be:
```
a.ApplicationDeveloper = Instances.OfType<Ifc4.ActorResource.IfcOrganization>().FirstOrDefault(o => o.Name == EditorDetails.ApplicationDevelopersName)
?? Instances.New<Ifc4.ActorResource.IfcOrganization>(o => o.Name = EditorDetails.ApplicationDevelopersName);
```
and these lines:
https://github.com/xBimTeam/XbimEssentials/blob/044c82b9d7c8bee7e60d3e29200540e0f780a617/Xbim.Ifc/IfcStore.cs#L528
https://github.com/xBimTeam/XbimEssentials/blob/044c82b9d7c8bee7e60d3e29200540e0f780a617/Xbim.Ifc/IfcStore.cs#L529
should be:
```
a.ApplicationDeveloper = Instances.OfType<Ifc2x3.ActorResource.IfcOrganization>().FirstOrDefault(o => o.Name == EditorDetails.ApplicationDevelopersName)
?? Instances.New<Ifc2x3.ActorResource.IfcOrganization>(o => o.Name = EditorDetails.ApplicationDevelopersName);
```

**Comment by andyward** [comment]
Good spot - looks like it is cross wired... If it's a priority and you feel like putting in a PR we'll get it fixed quickly.

**Comment by andyward** [comment]
Fixed, thanks @janbrouwer !
