### ISSUE TITLE
IfcStore Open Fails with MemoryStream

### ISSUE THREAD

**Issue by Chandra123539** [xBimTeam/XbimEssentials#470]
*Short summary describing the issue. (3-5 sentences)*

#### Assemblies and versions affected:

Xbim.Essentials 5.1.0.0

#### Steps (or code) to reproduce the issue:

IfcStore Open file fails on Memory Stream as input. It Works with file stream. When FileStream is copied to MemoryStream and Open is called, null is returned as output. 

using (FileStream Stream = new FileStream(filepath, FileMode.Open, FileAccess.Read, FileShare.Read))
                {
                    MemoryStream memoryStream = new MemoryStream();
                    Stream.CopyTo(memoryStream);
                    _store = IfcStore.Open(memoryStream, Xbim.IO.StorageType.Ifc,XbimSchemaVersion.Ifc2X3, XbimModelType.MemoryModel, null);
                }

#### Minimal file to reproduce the issue:

Any ifc File can be used 

#### Expected behavior:

MemoryStream also need to be supported.

#### Actual behavior or exception details:

IfcStore Open fails.

#### Additional Details

Please let us know on why failure occurs or let us know if we are missing anything here while giving the input.

**Comment by martin1cerny** [comment]
Make sure the `MemoryStream` is set to beginning before you try to open it.

```cs
memoryStream.Seek(0, SeekOrigin.Begin);
```

**Comment by Chandra123539** [comment]
Thanks Martin. When Stream is copied , position is set to last. Setting it to begin works fine.
Please close the issue.

**Comment by namkhang2603** [comment]
> Make sure the `MemoryStream` is set to beginning before you try to open it.
> 
> ```cs
> memoryStream.Seek(0, SeekOrigin.Begin);
> ```
I do this with a broken ifc 4 file exported from Revit
[2BoxIfc4.zip](https://github.com/xBimTeam/XbimEssentials/files/12354520/2BoxIfc4.zip)

**Comment by andyward** [comment]
@namkhang2603  Can you raise in a new issue please. Make sure you specify what version of xbim, steps to recreate and what the issue is
