### ISSUE TITLE
Rotation in IfcAxis2Placement3D

### ISSUE THREAD

**Issue by OzKitsune** [xBimTeam/XbimEssentials#479]
Hello!

Please help me figure out how to set the rotation of an object when creating of IFC.

I have a rotation given by a quaternion and I am using this code from the example:

```csharp
parent.ObjectPlacement = i.New<IfcLocalPlacement>(p => p.RelativePlacement = i.New<IfcAxis2Placement3D>(a =>
{
    a.Location = i.New<IfcCartesianPoint>(cp => cp.SetXYZ(0, 0, 0));
    a.RefDirection = i.New<IfcDirection>();
    a.RefDirection.SetXYZ(1, 0, 0);
    a.Axis = i.New<IfcDirection>();
    a.Axis.SetXYZ(0, 0, 1);
}));
```

As I understood, I need to set the value in RefDirection, but I do not understand how exactly this should be done.

**Comment by martin1cerny** [comment]
You need to use quaternion to compute directions of the X (`RefDirection`) and Z (`Axis`) axes. These define the local coordination system.

**Comment by OzKitsune** [comment]
Thanks for help, I think I figured it out.
