### ISSUE TITLE
Delete PropertySet

### ISSUE THREAD

**Issue by ivanstef** [xBimTeam/XbimEssentials#48]
Hi,

I am looking for a way to remove the property set itself after removing all its properties. I see AddPropertySet(), GetPropertySet but no RemoveProperyStet. Is there any way I can do this?

Best regards

**Comment by martin1cerny** [comment]
Deletion of objects in a complex object model such as IFC isn't easy task.
IModel has a function `Delete (IPersistEntity entity)` which makes sure
that all references to the entity are removed as well. This is a low level
function which won't remove entity members. It is also only implemented in
MemoryModel. If you try to use it with EsentModel it will throw an
exception.
