### ISSUE TITLE
Position of insertCopy object

### ISSUE THREAD

**Issue by VuGiaHuy-0808** [xBimTeam/XbimEssentials#499]
Hi Xbim team.
Currently, I create a model in a picture below. A cylinder is created by start point and end point using IfcExtrudedAreaSolid. Two other objects is copied to main model by InsertCopy function and changed z coordinate of LocalPlacement to z value of start point and end point. My expectation is 2 objects have a position equal to start point & end point but it doesn't. Moreover, a distance between 2 objects is greater than the cylinder's height.
Main model and object model is the same unit (mm).
Could u give me some clues, thanks.
![Screenshot 2023-03-20 102629](https://user-images.githubusercontent.com/66827155/226239626-355fdd14-8f21-46c1-aa49-6c67aff0ebd0.jpg)

**Comment by QuangHieu1704** [comment]
Yes, I face the same issue as yours. I think the problem may comes from local/global location or ratio between 2 objects. Can anyone solve this?

**Comment by martin1cerny** [comment]
Placement and orientation of geometric representations in IFC is a complex domain. You need ton consider the entire placement hierarchy structure of the product + transformations applied to mapped representations (potentially non-uniform) + extruded shape position.
