### ISSUE TITLE
Where methods moved from version 3?

### ISSUE THREAD

**Issue by kozintsev** [xBimTeam/XbimEssentials#50]
Hello!

Where are the methods:
buildingStorey.AddElement ?
project.AddSite(site) ?
project.AddBuilding(building) ?

etc.

Maybe there are common methods for IFC2x3 и IFC4 ?
Do you have an example?

Thank you for attention.

**Comment by theebow** [comment]
Hi Oleg
this was good questions
why did you closed ? have you found answer ?
some times ago have been testing (add/modify the IfcModel) using IfcModel.Instances.New<IfcRelAggregates>(........) seems to be working for add storey to building, wall to storey..Ect...

**Comment by martin1cerny** [comment]
These are extension methods which are only implemented for IFC2x3. Some methods might make it to IFC4 interfaces but there is no plan to implement all of them. Feel free to grab the code from source and use it in your project. To be able to use it with IFC4 you will need to do some refactoring.

**Comment by CBenghi** [comment]
Hello Kozintsev,
can I ask why you reopened the issue? 
We do not consider it an issue, but a change in the APIs with the new version.
If you think that this is a mistake, please mabke your point. Martin, however suggested that you implemented the same code in an extension method (taking it from the 3.x branch) if needed for your projects.
Best,
Claudio
