### ISSUE TITLE
[QUESTION] Classes in this library for getting Mesh of entity

### ISSUE THREAD

**Issue by Blogbotana** [xBimTeam/XbimEssentials#506]
Hi everyone, can you help me with my problem? 
I have an IFC file and I need to get bynary data of geometry (Vertices, Triangles, Nornals). Usually I have ["Swept Solid"](https://i.imgur.com/AgFrK2A.png) representation.

I tried to use Xbim.Tessellator.XbimTessellator, but it doesn't work with IfcExtrudedAreaSolid. 
Also I tried to use Xbim.Geometry.Engine.Interop.XbimGeometryEngine but I didn't understand how it works properly. 
How I can get data of Vertices, Triangles and Normals? 

Thank you

**Comment by GVladislavG** [comment]
Hi, @Blogbotana. You can try and develop this code sample
```
var m_3DMdlContext = new Xbim3DModelContext(m_model);
                    m_3DMdlContext.MaxThreads = 1;
                    m_3DMdlContext.CreateContext();

var m_ShapeInsts = m_3DMdlContext.ShapeInstances().ToList();
```

```
if (shapeInsts == null || shapeInsts.Count == 0)
                shapeInsts = (from inst in m_ShapeInsts
                              where inst.IfcProductLabel == EntLabel select inst).ToList();

foreach (var instance in shapeInsts)
{  
    using (var stream = new MemoryStream(data))
                {
                    using (var reader = new BinaryReader(stream))
                    {
                        var mesh = reader.ReadShapeTriangulation();                        

                        List<XbimFaceTriangulation> faces = mesh.Faces as List<XbimFaceTriangulation>;
                        List<XbimPoint3D> vertices = mesh.Vertices as List<XbimPoint3D>;
                     }
                 }
}
```

**Comment by Blogbotana** [comment]
Thank you for your feedback. Ш was very helpfull. I tried to use it, but this lose part of geometry. What to do this that? [Original](https://i.imgur.com/picfl1s.png) and [Result](https://i.imgur.com/3gGqwRa.png)

**Comment by martin1cerny** [comment]
You may need to change deflection angle when you create `Xbim3DModelContext` That defines how smooth curves are tesselated.

**Comment by Blogbotana** [comment]
@martin1cerny  There's no any deflection [angle ](https://i.imgur.com/PTkFdbH.png) and I didn't find any property or field

**Comment by Blogbotana** [comment]
I found `CustomMeshingBehaviour `delegate, but don't understand how it works

**Comment by Blogbotana** [comment]
I tried to change [deflcetion](https://i.imgur.com/9wJ4Dr3.png), but it didn't help me. May be because this is C profile in representation?

**Comment by martin1cerny** [comment]
You can change deflection settings using `IModel.ModelFactors. DeflectionAngle`. Can you share the IFC file?

**Comment by Blogbotana** [comment]
Yes, sure. I'm trying to work with purlins
[out22.zip](https://github.com/xBimTeam/XbimEssentials/files/12061967/out22.zip)

**Comment by Blogbotana** [comment]
Could you repeat the same result?

**Comment by jomijomi** [comment]
> I found `CustomMeshingBehaviour `delegate, but don't understand how it works

You can use it something like this :

```
private Xbim3DModelContext.MeshingBehaviourResult MyCustomMeshingBehaviour(int elementId, int typeId, ref double linearDeflection, ref double angularDeflection)
{
	if (typeId == 571) //rebars, don't make them too detailed (i.e. do coarse tessellation)
	{
		linearDeflection *= 10;
		angularDeflection = 1.5;
	}
        
	return Xbim3DModelContext.MeshingBehaviourResult.Default;
}

IfcStore theModel = IfcStore.Open(theFileName);
var context = new Xbim3DModelContext(theModel);
context.CustomMeshingBehaviour = MyCustomMeshingBehaviour;
context.CreateContext();
```

**Comment by jomijomi** [comment]
Ok, now I actually looked at your images also, it's about the fillet radius, right?? Then you should be able to fiddle with the "ModelFactors", specifically "ProfileDefLevelOfDetail". From the comments in the code:
"Indicates level of detail for IfcProfileDefinitions, if 0 no fillet radii are applied, no leg slopes area applied, if 1 all details are applied"

/Mikael

**Comment by jomijomi** [comment]
Just tested, it works, just set
```
theModel.ModelFactors.ProfileDefLevelOfDetail = 1;
```
before calling CreateContext()
(First image below is with no fillet, the other two with fillet, i.e. ProfileDefLevelOfDetail set to one)

![No_fillet](https://github.com/xBimTeam/XbimEssentials/assets/11835690/1796d877-4171-4c68-bed9-a14424f3fa1a)
![Fillet_01](https://github.com/xBimTeam/XbimEssentials/assets/11835690/664ecd97-1273-43d4-a0ce-447b723a7373)
![Fillet_02](https://github.com/xBimTeam/XbimEssentials/assets/11835690/490a5b5f-bb57-43c4-a86c-616388ea3f3e)

**Comment by Blogbotana** [comment]
Thank you very much @jomijomi you helped me a lot 
![image](https://github.com/xBimTeam/XbimEssentials/assets/69924139/1405290b-f38e-4402-9b30-02413fedfdb3)
