### ISSUE TITLE
IFC2x3 or IFC2x3 TC1

### ISSUE THREAD

**Issue by GVladislavG** [xBimTeam/XbimEssentials#509]
Hello, team!
What version of IFC2x3 schema is used in xBim?
IFC2x3 or IFC2x3 TC1?

Thanks!

**Comment by martin1cerny** [comment]
We implement IFC2x3 TC1, which is an [official release](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/). 
![image](https://github.com/xBimTeam/XbimEssentials/assets/773078/4b75ea1e-a30d-4ac3-aa48-336bf0292aaf)
