### ISSUE TITLE
Is it OK to modify IfcStore in Parallel.ForEach loop?

### ISSUE THREAD

**Issue by shichongdong** [xBimTeam/XbimEssentials#518]
I want to use XbimGeometryEngine to create solids for many entities, so I will use Parallel.ForEach to improve performance. 

In earch Parallel.ForEach loop, it will use IXbimGeometryEngine.CreateXXX to create IXbimSolid, so I need modify IfcStore to add Ifc solids. 

I have done the code and make some testings. It works with some random exceptions, so my questions are:

1. Is it OK to do like that?
2. If it's OK, how can I fix the random exceptions?

#### Assemblies and versions affected:
"Xbim.Essentials" Version="6.0.423-develop"
"Xbim.Geometry" Version="5.1.666-develop"

```csharp
// GeometryFactory is wrapper around a new XbimGeometryEngine and a new IfcStore object
using (var geometryFactory = new GeometryFactory())
using (var txn = geometryFactory.Model.BeginTransaction())
{
                    // entities is a collection of objects
                    Parallel.ForEach(entities, new ParallelOptions(), entity =>
                    {
                              // create solid with XbimGeometryEngine and IfcStore
                    });
                    tx.commit();
}
```

**Comment by andyward** [comment]
Sure, it's basically what we do here: https://github.com/xBimTeam/XbimGeometry/blob/c4df872dc60f3f440b10fbb8e624055b34ae68eb/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L813

The underlying OpenCascade (OCC) geometry engine is generally supposed to be thread safe, but that's not to say there aren't edge cases / bugs. 

It may be worth using our latest v6 Geometry in the [netcore branch](https://github.com/xBimTeam/XbimGeometry/tree/feature/netcore) which has the latest OCC7.6

If you're seeing intermittent errors maybe try to isolate the inputs triggering the exception. It's usually invalid geometry that triggers issues (which can in turn manifest as threading issues)

**Comment by shichongdong** [comment]
@andyward , thanks for your reply. OK, I will check the code.
BTW, I can't find v6 Geometry in NuGet, so where can I find the pre-build packages or I need build it myself?

**Comment by andyward** [comment]
Sorry we only have a private nuget repo currently for v6. It's actually simple to build it yourself (and much quicker than the v5 branches in develop / master). Will see about getting it into Myget soon.

**Comment by 6ther** [comment]
`
using (var tran = model.BeginTransaction("test"))
{
                    Parallel.ForEach(entities, new ParallelOptions(), entity =>
                    {
                           //new instances
                           var newInstance = model.Instances.New<IfcBuildingElementProxy>();
                    });
                    tx.commit();
}

`
![1712653302224](https://github.com/xBimTeam/XbimEssentials/assets/46700515/d4a8a772-14c3-4c2e-9031-f06c60e1a66b)
it throw exception like the picture.

**Comment by andyward** [comment]
Looks to me that [MultiValueDictionary](https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Common/Collections/MultiValueDictionary.cs) is not thread safe. If you wanted to submit a PR replacing the inner `Dictionary` with a `ConcurrentDictionary` that should help.

Is it Revit that is imposing the Parallel foreach on your code, or is it your decision? While Parallel will help with the Geometry compute, I don't know how much gain you'll get with basic I/O.

**Comment by martin1cerny** [comment]
Hi @6ther,

while it is safe to read data in parallel, modifying the model is not designed to work in parallel. The transaction is supposed to be linear, which cannot be guaranteed in parallel. 

Creating/modifying data is usually very fast, so the common approach is to get the data ready (in parallel if that requires some heavy processing) and than create the IFC in one go.

What is your scenario for creating data in parallel? I can see you are trying to export some data from Revit and that is not very parallel friendly even for reading as I think that Addins run in the UI thread context.

**Comment by martin1cerny** [comment]
No, as I said earlier, none of our `IModel` implementations support parallel creation/editing.

**Comment by 6ther** [comment]
> No, as I said earlier, none of our `IModel` implementations support parallel creation/editing.不，正如我之前所说的，我们的 `IModel` 实现都不支持并行创建/编辑。

thanks a lot. I understand.
