### ISSUE TITLE
IfcAnnotation details?

### ISSUE THREAD

**Issue by seghier** [xBimTeam/XbimEssentials#524]
Hello
How can we get the details of the annotation dtails `IfcAnnotation `: (start , end) points and distance value?

i use this but i am not sure about it and what i need to get the details?

```
private void PrintHierarchy(IIfcObjectDefinition o, int level, DataTable resultTable)
{
    var newRow = resultTable.NewRow();
    newRow["Level"] = level;
    newRow["Name"] = o.Name;
    newRow["Type"] = o.GetType().Name;

    if (o is IfcAnnotation annotation)
    {
        //annotation .....?
    }
.............
.............
}
```

**Comment by andyward** [comment]
What are you trying to do? An IfcAnnotation is just a special form of IfcProduct and so will have Representation and ObjectPlacement from the parent. A good way to understand the relationships is to view the model in (XbimXplorer)[https://docs.xbim.net/downloads/xbimxplorer.html]

It's a complex area to work in if you're new to IFC and xbim, but take a look at the IFC docs at https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/schema/ifcproductextension/lexical/ifcannotation.htm

**Comment by seghier** [comment]
You need first check XbimXplorer if can read annotations and show them as dimensions

**Comment by andyward** [comment]
Closing. No time for time wasters...
