### ISSUE TITLE
SaveAs Truncating file

### ISSUE THREAD

**Issue by fpz016** [xBimTeam/XbimEssentials#534]
When opening and SaveAs on an existing IFC4 file all data except the header is removed.

The following lines are all that is found in the save as file

ISO-10303-21;
HEADER;
FILE_DESCRIPTION (('ViewDefinition [CoordinationView]'), '2;1');
FILE_NAME ('D:\\_Advanced Steel\\OneDrive_2023-10-09\\Jason Holden\\02 Sample Model\\ADVS Export\\P0042_01-IFC4 - Copy.ifc', '2023-11-07T12:20:35', (''), (''), 'IfcOpenShell v0.7.0-9cc1f5f0e', 'IfcOpenShell v0.7.0-9cc1f5f0e', '');
FILE_SCHEMA (('IFC4'));
ENDSEC;
DATA;
ENDSEC;
END-ISO-10303-21;

#### Assemblies and versions affected:

![image](https://github.com/xBimTeam/XbimEssentials/assets/52910353/93bd2984-4711-44d8-9fcb-d9bf69a2a521)

#### Steps (or code) to reproduce the issue:

public void GetIFCObj()
        {
            //var columns = model.Instances.OfType<IIfcColumn>(); //vertical beams
            //var braces = model.Instances.OfType<IIfcMember>(); //diagonal braces
            
            const string fileName = @"D:\\_Advanced Steel\\OneDrive_2023-10-09\\Jason Holden\\02 Sample Model\\ADVS Export\\P0042_01-IFC4 - Copy.ifc";

            XbimEditorCredentials ADN = new XbimEditorCredentials();
            ADN.ApplicationDevelopersName = "JH";
            
            using (model = IfcStore.Open(fileName, ADN, null, null, XbimDBAccess.ReadWrite))
            {
            }

            model.SaveAs(fileName);
            model.Dispose();
        }

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Then just drag & drop here*

[P0042_01-IFC4 - Copy.zip](https://github.com/xBimTeam/XbimEssentials/files/13358856/P0042_01-IFC4.-.Copy.zip)

#### Expected behavior:
Expect a full copy of the file to be saved

#### Actual behavior or exception details:

All data is removed except what is shown in file attached below
[P0042_01-IFC4 - Copy_postProcess.zip](https://github.com/xBimTeam/XbimEssentials/files/13358862/P0042_01-IFC4.-.Copy_postProcess.zip)

**Comment by martin1cerny** [comment]
Thank you for the code example, but I'd need to see what you actually do when you open the model. Do you commit the transaction after you make the changes? What are you trying to do? The best would be a minimalistic but complete code example, preferably in a form of a simple unit test.

**Comment by fpz016** [comment]
Wow. Awesome. Perfect. I'm a bit rusty at the moment. Thank you.
