### ISSUE TITLE
VRML

### ISSUE THREAD

**Issue by kozintsev** [xBimTeam/XbimEssentials#54]
Hello!
Can Xbim Essentials save the IFC file as VRML (Virtual Reality Modeling Language) ?
Or maybe there is another way to save IFC file as VRML?

**Comment by martin1cerny** [comment]
Hi @kozintsev , xBIM Essentials can't save model as VRML. But xBIM Geometry Engine processes IFC geometry into B-Rep, faceted B-Rep and triangulated geometry. So if you have/write any library able to create and store VRML you can easily save the geometry and any kind of semantic information using xBIM Essentials. I'm not an expert on VRML by after a brief look at the [specification](http://gun.teipir.gr/VRML-amgem/spec/part1/concepts.html#GeometryNodes) I would say it would be the best to save geometry as [IndexedFaceSet](http://gun.teipir.gr/VRML-amgem/spec/part1/nodesRef.html#IndexedFaceSet). VRML supports some basic primitives having their counterparts in IFC (like extrusion, sphere, cylinder and cone) but IFC geometry model is a lot more complex.

**Comment by kozintsev** [comment]
Thanks for the info!
