### ISSUE TITLE
[Question]Domain entities filling

### ISSUE THREAD

**Issue by theebow** [xBimTeam/XbimEssentials#56]
Hello,
i'm searching the greatest way to fill a list of all the entities from mep domain(electrical, plombing..)
But it seem to be have no link between an entity and its "MepDomain" in IFC4 ?

have you please got an idea ?

thanks for help

**Comment by martin1cerny** [comment]
Have you tried to use namespaces? 
![image](https://cloud.githubusercontent.com/assets/773078/19350184/0277eb6a-9157-11e6-83ed-d5480e5da915.png)

**Comment by theebow** [comment]
Thanks for your reactivy Martin
i don't understand what do you mean
i don't think is it possible throught xBim to do something like :

IfcStore myStore = ....
List<XXX> T_myListOfElectricalElt = myStore.Instances.ofType<XXX>().Where(x=>x.Namespace )

we have no namespace access in xBim from ifcProduct/ifcElement/...

**Comment by martin1cerny** [comment]
You need to use C# reflection and overloaded function `model.Instances.OfType(string typeName)`.

**Comment by theebow** [comment]
ok i think have understand, i'm going to talk about this solution with my team
Thanks Martin
Tell me if you want a great job in France one day :)

**Comment by martin1cerny** [comment]
Thanks @theebow. Will let you know once I decide to move to France. Just out of curiosity: Which company do you represent/work for?

**Comment by theebow** [comment]
Hi Martin, there is no problem to give you this information but it is just a confidentiality problem with the other societies in competition with us. Especially that they made the close-Bim choice.
i don't find a way to send you a private message, and there is too many Martin Cerny all over the world on facebook lol
Give me please a way to send you a MP/email
best regards

**Comment by martin1cerny** [comment]
[LinkedIn](https://www.linkedin.com/in/martin-%C4%8Dern%C3%BD-331b6852) might be the best for this. You can send me a message there.

**Comment by theebow** [comment]
i just sent you an invit/message on linkedIn ;)
