### ISSUE TITLE
Getting sub components of site

### ISSUE THREAD

**Issue by SunilApte** [xBimTeam/XbimEssentials#564]
We are currently replacing HOOPS with Xbim.
In HOOPS we have following code:
```
HPS.Component[] children = m_compIFCSites.GetSubcomponents();
                        foreach (Component compsurface in children.ToList())
                        {
                            var type = ComponentPropertyBuilder.FindStringPropertyTypecheck(compsurface);
                            if (type != "IFCBUILDING"/* && compsurface.GetName().ToLower().Contains("surface")*/)//Identity Data/Mark	Plot

                            {
```
I can get IfcSite using xbim. But how can I get sub components?
I can get buildings and spaces from ifcsite. But I need all sub components under site whose type is not building.

How to achieve this?

**Comment by martin1cerny** [comment]
When you say *subcomponents*, do you mean the geometrical parts (often terrain surface in case of `IfcSite`), or do you mean semantic breakdown (building(s), level(s), space(s))?

**Comment by martin1cerny** [comment]
You just need to iterate through the aggregation relation recursively.

```cs
private static void ExploreDecomposition(IIfcObjectDefinition entity, string indent)
{
    Console.WriteLine(indent + entity.Name);
    var children = entity.IsDecomposedBy.SelectMany(r => r.RelatedObjects);

    indent += "    ";
    foreach (var child in children)
    {
        ExploreDecomposition(child, indent);
    }
}

var site = model.Instances.FirstOrDefault<IIfcSite>();
ExploreDecomposition(site);
```

*Note: Code is subject to optimisation and refactoring before used in production.*
