### ISSUE TITLE
Xbim.Ifc4x3.GeometryResource.IfcCompositeCurve.Segments throws NotImplementedException

### ISSUE THREAD

**Issue by santiagoIT** [xBimTeam/XbimEssentials#566]
Hello,

the following AutoGenerated code:
![image](https://github.com/xBimTeam/XbimEssentials/assets/1231891/6a61129d-227a-4ff4-8b1c-78a30628fef5)

throws an exception when called.

I ran into this problem when opening an IFC file. This happens when an XbimWire is initialized from an IIfcCompositeCurve:
![image](https://github.com/xBimTeam/XbimEssentials/assets/1231891/a032c612-fb9d-441d-861b-aec58aafe869)

When line 861 is executed, the exception is thrown.

Since the IfcCompositeCurve file is generated by the Xbim.CodeGeneration tool, I have no idea on how to approach this problem.
If you provide some guidance I can attempt to solve it.

[test.zip](https://github.com/user-attachments/files/15568220/test.zip)

**Comment by andyward** [comment]
Sounds like there's a few IFC4.3 areas unimplememented on the cross schema interfaces.

So while we code-gen these files, any code within blocks starting and ending `//##` is preserved when re-generating.

In this case you'd just need to add the implementation as per IFC2x3 in place of the NotImplementedException. E.g. see

https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Ifc2x3/Interfaces/IFC4/IfcCompositeCurve.cs

(I'm not sure why, but the IFC2x3 code should have the same `//##` markers around it in case we regen IFC2x3. But that's a separate issue)

**Comment by santiagoIT** [comment]
In Ifc4 and lower the segments list is defined as:
`
private readonly ItemSet<IfcCompositeCurveSegment> _segments;
`

But starting with IFC4x3, the segments list is defined as:
`
private readonly ItemSet<IfcSegment> _segments;
`

it changed from IfcCompositeCurveSegment to IfcSegment

That is why I just cannot take over the code from earlier implementations.

This is how I implemented it:
```

[CrossSchemaAttribute(typeof(IIfcCompositeCurve), 1)]
IItemSet<IIfcCompositeCurveSegment> IIfcCompositeCurve.Segments 
{ 
	get
	{
        //##
        var test = new ItemSet<IIfcCompositeCurveSegment>(this, 0, 1);
		test.AddRange(@Segments.Where(x => x is IIfcCompositeCurveSegment).Cast<IIfcCompositeCurveSegment>());
        return new Common.Collections.ProxyItemSet<IIfcCompositeCurveSegment, IIfcCompositeCurveSegment>(test);
        //##
    }
}

```
Let me know if this looks ok, if so, I can create a pull request.

**Comment by santiagoIT** [comment]
What I posted above does not work. I get an Operation Out Of Transaction exception.

Trying to find a solution...

**Comment by santiagoIT** [comment]
This works, The 4.3 ifc file still does not open, but processing continues much further now.
There must be some other problem which I will investigate.

`
		[CrossSchemaAttribute(typeof(IIfcCompositeCurve), 1)]
		IItemSet<IIfcCompositeCurveSegment> IIfcCompositeCurve.Segments 
		{ 
			get
			{
                //## Custom code - not auto generated
                var compCurveSegs = @Segments.Where(x => x is IIfcCompositeCurveSegment)
                    .Cast<IIfcCompositeCurveSegment>();

                var list = new ItemSet<IIfcCompositeCurveSegment>(this, 0, 1);
                foreach (var seg in compCurveSegs)
                {
                    list.InternalAdd(seg); // no transaction available
                }
                return new Common.Collections.ProxyItemSet<IIfcCompositeCurveSegment, IIfcCompositeCurveSegment>(list);
                //##
            }
        }`

**Comment by andyward** [comment]
Should be done. Again I tweaked it. We don't have test coverage on this IIfcCompositeCurve.Segments code so please do retest my implementation.

**Comment by santiagoIT** [comment]
Tested your implementation, worked 👍
