### ISSUE TITLE
model.InsertCopy: missing step instance names inside file by using Esent

### ISSUE THREAD

**Issue by MichaelBuehler** [xBimTeam/XbimEssentials#58]
Hello,

I am copying from multiple ifc files the IfcShapeRepresentations into new created model, using
destinationModel.InsertCopy(toCopy, mapping, Filter, false, false);. This is used for a tool which shall convert ifc files containing generic BuildingElementProxy to correct ifc product type, with attributes defined inside a SQL database.

This works perfect as long as destinationModel is created by XbimStoreType.InMemoryModel. If EsentDatabase is used, no referenced step instance names are getting added inside file to ifc objects added by code:

destination file output:

```
#228=IFCCURTAINWALLTYPE('2jOin3JCn7r8OHsq71vF9B',#4,'Curtain Wall  test',$,'IfcCurtainWall',$,$,$,$,.USERDEFINED.);
#229=IFCLOCALPLACEMENT($,#193);
#230=IFCPRODUCTDEFINITIONSHAPE($,$,());
#231=IFCSHAPEREPRESENTATION($,'Body','SurfaceModel',());
```

Issue:
```
#228: should contain #229 and #230
#230: () should contain (#231)
#231 () should contain.. 
#231 is the object returned by InsertCopy. The references in lower nested objects are correct
```

Using InMemoryModel works! In debugger the objects are looking correct, with referenced objects.

Related to Nuget package 4.0.2 from 16 October 2016

Any idea?

(Note; I've edited the comment because some parts where mistakenly interpreted as references to issues from github. Claudio)

**Comment by CBenghi** [comment]
Hi Michael,
thanks for the question.
This sounds like a serious issue. But I've not understood the problem 100% which we need to reproduce.
Would you be able to produce a test case in Xbim.Essentials.Test?
If you do I'd add it to the solution for debugging (possibly via a pull request?)
You can add small files too, if needed, but ideally we'd like the code to be minimal to identify the offending API.
Thanks,
Claudio

**Comment by MichaelBuehler** [comment]
Unit test class Ifc2x3InsertCopyTest.cs to develop stream project Tests added. Note that I had include a 800KB ifc file generated from Autodesk Inventor - if the file is smaller (20KB) it works!

**Comment by MichaelBuehler** [comment]
I will upload once I figured out how.. 403 (Forbidden)..

**Comment by martin1cerny** [comment]
You can try pull request.

**Comment by MichaelBuehler** [comment]
Files uploaded to (https://github.com/xBimTeam/XbimEssentials/files/551164/Ifc2x3InsertCopyTest.zip)

**Comment by CBenghi** [comment]
Thanks, I'll put the files in the solution soon.

**Comment by martin1cerny** [comment]
No need @CBenghi. I found a bug and it is solved now. Thank you @MichaelBuehler very much. This was a very good one to spot out. The problem was actually not related to the `InsertCopy()` itself but to the way transactions work in `EsentModel`. It keeps track of modified entities and writes them to database at the end of transaction. But once this is done we were failing to add it there again. This in your code was combined with the fact that size of transaction is limited in Esent engine so with large `InsertCopy` it needs to flush the changes in the meantime with the same effect. The simple testing code is this:
```cs
[TestMethod]
public void EsentMultiTransactionTest()
{
    const string file = "test.ifc";
    using (var model = EsentModel.CreateTemporaryModel(new EntityFactory()))
    {
        IfcCurtainWall wall;
        using (var txn = model.BeginTransaction("New wall"))
        {
            wall = model.Instances.New<IfcCurtainWall>(w => w.Name = "Name");
            txn.Commit();
        }
        using (var txn = model.BeginTransaction("Edit wall"))
        {
            wall.Description = "Description";
            txn.Commit();
        }
        model.SaveAs(file);
    }

    using (var model = EsentModel.CreateTemporaryModel(new EntityFactory()))
    {
        model.CreateFrom(file, null, null, true, true);
        var wall = model.Instances.FirstOrDefault<IfcCurtainWall>();
        Assert.IsTrue(wall.Name == "Name");
        Assert.IsTrue(wall.Description == "Description");
    }
}
```
