### ISSUE TITLE
IfcFacilityPart not being processed

### ISSUE THREAD

**Issue by vulevukusej** [xBimTeam/XbimEssentials#583]
Hi - I'm trying to test out the IFC4x3 functionality using the latest Nuget package:

#### Assemblies and versions affected:

![image](https://github.com/user-attachments/assets/78cd04be-d5c5-49a7-b024-7a35ce482493)

#### Steps (or code) to reproduce the issue:

Loading the file using IfcStore.Open and then inspecting the model:
IfcStore.Open

#### Minimal file to reproduce the issue:
I'm using the IFC4x3 example found here: https://www.ifcwiki.org/index.php?title=KIT_IFC_Examples

#### Expected behavior:

I expect to see IfcFacilityPart

#### Actual behavior or exception details:

All IfcFacilityPart entities are ignored:
![image](https://github.com/user-attachments/assets/1c6892af-0f8a-4b20-ab80-1c7fd31e9f51)

#### Additional Details
![image](https://github.com/user-attachments/assets/ecff7a3a-f929-4357-a726-cf249f52f3a6)

**Comment by andyward** [comment]
Just took a look - this KIT example is a really old pre-release sample of IFC4.3 (RC2) and is seriously invalid according to the official schema. In particular between 4.3RC2 and the official IFC4X3_ADD1 schema release, `IFCFACILITYPART` [was made abstract](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcFacilityPart.htm#5.4.3.26.8-Changelog), so can't be instantiated. The sample should have been updated to use one of the sub-classes such as `IFCROADPART` instead.

If you just search and replace the IFCFACILITYPART occurrences for IFCROADPART it will get further (but note that were other changes (e.g the ordering of parameters changed). 

![image](https://github.com/user-attachments/assets/dd438b9f-a894-4ba0-b861-fe0d7b162618)

**Comment by vulevukusej** [comment]
Thanks for the quick response!  I'll check that tomorrow 👍

**Comment by vulevukusej** [comment]
I checked the file again and could immediately confirm what you said.  I blindly accepted that it was an up-to-date IFC4x3 file, so I'll try with other files.  Thanks for your help!
