### ISSUE TITLE
decimal properties value away zero

### ISSUE THREAD

**Issue by tcsabim2** [xBimTeam/XbimEssentials#587]
below is code fragment & print out
![image](https://github.com/user-attachments/assets/eb9fe66c-c5ce-443e-ac89-49e56a206d66)

![image](https://github.com/user-attachments/assets/45f06bd5-aa55-4702-8ac1-8affb82dabd8)

bonsai can display value correctly
![image](https://github.com/user-attachments/assets/a16d65a6-0b6d-41fc-af02-0b56455883aa)

**Comment by andyward** [comment]
Assuming you're talking about EMSD.TEST.Distance as  an example where it's showing 0.00 in your code and 443999.99 in Blender?

Can you debug your code a bit and ensure that the value is present? There are various ways to attach properties on an instance.

Supplying this test model may also be a useful next step

**Comment by tcsabim2** [comment]
Thanks your reply,
I try to switch dotnet sdk 8 to 6, then the program can correctly read the value.

**Comment by andyward** [comment]
Strange. My guess is that it's related to something like newer C# versions in net8, or perhaps a CultureInfo issue.
