### ISSUE TITLE
Exception, when Reading ifc Files with IfcBuildingElement

### ISSUE THREAD

**Issue by BjDi** [xBimTeam/XbimEssentials#6]
I know this class is abstract. Nevertheless there are Ifc File Reader (Solibri, DDS-CAD Viewer), that accept this Type.
I am working with your Framework, and it threw exceptions.
The IFC File was generated from 'Nemetschek Vectorworks, Inc.' with 'Vectorworks Architect 2015 SP3 R1 (Build 257190) (64-Bit) by Nemetschek Vectorworks, Inc.'

Wouldn't it be nice to accept such files even thoug they are 'invalid'

**Comment by SteveLockley** [comment]
Where would we stop if we start accepting illegal files. If you want build a version of essentials then it should be as simple as not making this class abstract but I think our goal is to stay true to the standard if we can. My vote us to try and be a reference tool uf we can and either ask the bim vendors to comply or edit the ifc file with notepad


Sent from Samsung Mobile


-------- Original message --------
From: BjDi
Date:13/07/2015 1:23 PM (GMT+00:00)
To: xBimTeam/XbimEssentials
Subject: [XbimEssentials] Exception, when Reading ifc Files with IfcBuildingElement (#6)


I know this class is abstract. Nevertheless there are Ifc File Reader (Solibri, DDS-CAD Viewer), that accept this Type.
I am working with your Framework, and it threw exceptions.
The IFC File was generated from 'Nemetschek Vectorworks, Inc.' with 'Vectorworks Architect 2015 SP3 R1 (Build 257190) (64-Bit) by Nemetschek Vectorworks, Inc.'

Wouldn't it be nice to accept such files even thoug they are 'invalid'

**Comment by BjDi** [comment]
Yes, it works removing the 'abstract' keyword. Thank you for your response.
