### ISSUE TITLE
Xbim.IO.IfcOutputStream & IfcConnectionPointGeometry

### ISSUE THREAD

**Issue by alorenzom** [xBimTeam/XbimEssentials#61]
Hi Everyone,

I have a problem with Xbim.IO.IfcOutputStream
(sorry if this is not the proper place to ask)

Here is what happens to me

I call, on an IfcOutputStream object, the Store method, 
passing an Xbim.XbimExtensions.XbimMemoryModel with all IfcConnectionPointGeometry with PointOnRelatingElement = a specific IfcVertexPoint

In my ifc file, generated by storage, then I found all those IfcVertexPoint and all those IfcConnectionPointGeometry, but these latter ones are with no arguments, like you see here:
172=IFCCONNECTIONPOINTGEOMETRY();
173=IFCCONNECTIONPOINTGEOMETRY();
174=IFCCONNECTIONPOINTGEOMETRY();
175=IFCCONNECTIONPOINTGEOMETRY();
176=IFCCONNECTIONPOINTGEOMETRY();
177=IFCCONNECTIONPOINTGEOMETRY();
178=IFCCONNECTIONPOINTGEOMETRY();
179=IFCCONNECTIONPOINTGEOMETRY();

**Comment by martin1cerny** [comment]
Hi @alorenzom , this is the right place to ask. However, can you please upgrade to the latest xBIM libraries first? Classes you use are not in xBIM for a while. With the latest code you just need to use `IfcStore` as a model and you can do anything you need with the model. Sample code would look like this:

```cs
var editor = new XbimEditorCredentials
{
    ApplicationDevelopersName = "Your Name",
    ApplicationFullName = "Your Application",
    ApplicationIdentifier = "ID of your application",
    ApplicationVersion = "0.1",
    EditorsFamilyName = "Santini Aichel",
    EditorsGivenName = "Johann Blasius",
    EditorsOrganisationName = "Independent Architecture"
};
using (var model = IfcStore.Create(editor, IfcSchemaVersion.Ifc4, XbimStoreType.InMemoryModel))
{
    using (var txn = model.BeginTransaction("Creating connections"))
    {
        var pointA = model.Instances.New<IfcCartesianPoint>(c => c.SetXYZ(123, 456, 789));
        var pointB = model.Instances.New<IfcCartesianPoint>(c => c.SetXYZ(321, 654, 987));
        var connection = model.Instances.New<IfcConnectionPointGeometry>(c =>
        {
            c.PointOnRelatedElement = pointA;
            c.PointOnRelatingElement = pointB;
        });
        txn.Commit();
    }
    model.SaveAs("model.ifc");
}

```

**Comment by alorenzom** [comment]
Hi @martin1cerny 

Thank you for your reply.

I downloaded the latest version as you suggested

I added to my app
- Xbim.CobieExpress.dll
- Xbim.Common.dll
- Xbim.Ifc.dll
- Xbim.Ifc.Extensions.dll
- Xbim.Ifc2x3.dll
- Xbim.Ifc2x3.IO.dll
- Xbim.Ifc4.dll
- Xbim.Tessellator.dll

I tried your sample code.

But Executing 

`model = IfcStore.Create(editor, IfcSchemaVersion.Ifc4, XbimStoreType.InMemoryModel)`

I got 

> Exception at 0x772F4118 in MyApp.exe: Exception Microsoft C++: EEFileLoadException at memory 0x00F7AB7C.
> Exception at 0x772F4118 in MyApp.exe: Exception Microsoft C++: [rethrow] at memory 0x00000000.
> Exception at 0x772F4118 in MyApp.exe: Exception Microsoft C++: [rethrow] at memory 0x00000000.
> Exception at 0x772F4118 in MyApp.exe: Exception Microsoft C++: [rethrow] at memory 0x00000000.
> Exception at 0x772F4118 in MyApp.exe: Exception Microsoft C++: [rethrow] at memory 0x00000000.
> Exception at 0x772F4118 in MyApp.exe: Exception Microsoft C++: EEFileLoadException at memory 0x00F7AB7C.
> Exception at 0x772F4118 in MyApp.exe: Exception Microsoft C++: [rethrow] at memory 0x00000000.
> Exception at 0x772F4118 in MyApp.exe: Exception Microsoft C++: [rethrow] at memory 0x00000000.
> Exception at 0x772F4118 in MyApp.exe: Exception Microsoft C++: [rethrow] at memory 0x00000000.
> Exception at 0x772F4118 in MyApp.exe: Exception Microsoft C++: [rethrow] at memory 0x00000000.

and it then crashes on later instructions

**Comment by alorenzom** [comment]
Esent.Interop.dll was missing

Now 

`model = IfcStore.Create(editor, IfcSchemaVersion.Ifc4, XbimStoreType.InMemoryModel)`

works, but some troubles happen later.

**Comment by martin1cerny** [comment]
I suggest you to use [NuGet distribution](https://www.nuget.org/packages/Xbim.Essentials/) which will take care for all the dependencies like Esent and Log4Net. The code I posted is for IFC4 so if you want to create IFC2x3 you need to change it to 

    model = IfcStore.Create(editor, IfcSchemaVersion.Ifc2x3, XbimStoreType.InMemoryModel)

If you want to create IFC4 you need to change your `usings` to use types from IFC4 namespaces.
I just finished some documentation about xBIM 4. It is just a draft but it might help you:
https://xbimteam.github.io/

**Comment by alorenzom** [comment]
[ NuGet distribution](https://www.nuget.org/packages/Xbim.Essentials/)  is where I downloaded latest version. In fact I have dependencies like Esent and Log4Net

I successfully used IfcSchemaVersion.Ifc2x3 for creating.

Now I'm trying using

`IfcStore.Open(string `filePath)`
`
like you say in [this issue](https://github.com/xBimTeam/XbimEssentials/issues/35)

unfortunately getting exception "Empty Stack"

**Comment by martin1cerny** [comment]
Can you provide the file? This sounds most likely like the file has a wrong syntax.

**Comment by alorenzom** [comment]
It was 

I succesfully moved to [xBIM Essentials 4.0.6](https://www.nuget.org/packages/Xbim.Essentials/) 

Thank you :)
