### ISSUE TITLE
NullReference exception when disposing EntityCollection

### ISSUE THREAD

**Issue by aoinas** [xBimTeam/XbimEssentials#63]
The line:
`_naturalOrder.Clear(); ` 
in EntityCollection class' Dispose method throws NullReference exception.

Version: Xbim.Essentials 4.0.0 from NuGet.

**Comment by martin1cerny** [comment]
Can you share more information about this exception please? We use this class quite heavily and this is the first report of such an issue.

**Comment by aoinas** [comment]
Sure. Next time it happens, I will report more information. It happens quite often.

**Comment by aoinas** [comment]
The application is a kind of IFC web server which hosts IFC files. It is a ASP.NET application. Project that is using Xbim uses .NET framework 4.5.

I have a wrapper class for MemoryModel, which keeps the IFC file open for a while and closes it using a timer after certain time period. Wrapper calls MemoryModel's Dispose method when it is disposing itself.

Here is a screenshot showing contents of the MemoryModel when exception happened. It seems it is empty.

![image](https://cloud.githubusercontent.com/assets/8026079/20095798/a3228e82-a5af-11e6-889d-470bba0da662.png)
