### ISSUE TITLE
IfcStore how to get the .xbim database file location

### ISSUE THREAD

**Issue by minhnguyenlinknode** [xBimTeam/XbimEssentials#65]
Hi,

I want to reuse .xbim database file to open it faster next time. So where is that location?

For ex:
_model = IfcStore.Open("file.ifc");

Next time I want to open it from .xbim instead to get faster:

_model = IfcStore.Open("file.xbim");

I don't know where it is now.

**Comment by martin1cerny** [comment]
You just need to save it.

Dne 9. 11. 2016 12:44 napsal uživatel "Minh Ng" <notifications@github.com>:

**Comment by minhnguyenlinknode** [comment]
Ok. So it is different with V3 a bit. 
Thanks,
