### ISSUE TITLE
IfcRepresentation.LayerAssignments throws null ref exception

### ISSUE THREAD

**Issue by aoinas** [xBimTeam/XbimEssentials#66]
I've got this null reference exception a few times when calling IfcRepresentation.LayerAssignments.Count():

![xbim_layer_exception](https://cloud.githubusercontent.com/assets/8026079/20479946/fd1a9130-afe8-11e6-85b6-ab7adaae6f3a.png)

**Comment by martin1cerny** [comment]
I can't see why this would be happening. Can you post the test data and code to present this problem please?

**Comment by aoinas** [comment]
I'm sorry, but I cannot post test data, since it is a model from 3rd party and I don't have permission to share it.

Ifc model is created with Autodesk Revit. 

I'll try to grab more debug data when exception happens again.

**Comment by martin1cerny** [comment]
Thanks. You can also use [IfcStore.InsertCopy()](https://xbimteam.github.io/examples/insert-copy-function.html) function to extract only piece of data which is causing the problem without sharing the model or any identity data. I'm sorry but I can't do more without more information.

**Comment by martin1cerny** [comment]
Hi @aoinas , any update on this or shall I close this issue?

**Comment by aoinas** [comment]
Hi, no updates sorry. You can close it. I will create a new one if it bothers me again ;)
