### ISSUE TITLE
Open Ifc file from Stream

### ISSUE THREAD

**Issue by GrzegorzBlok** [xBimTeam/XbimEssentials#69]
Hi,

I use following code to convert ifc file to wexbim. However I can't find a way to open Ifc file that comes as a Stream, e.g. MemoryStream. I don't have access to file system. Is there any way to open Ifc file and convert it to wexbim with the use of streams?

```
string ifcAbsolutePath = "c:\\file.ifc";

using (var wexBimStream = new MemoryStream())
using (var m = IfcStore.Open(ifcAbsolutePath))
{
    var geomContext = new Xbim3DModelContext(m);
    geomContext.CreateContext();

    using (var bw = new BinaryWriter(wexBimStream))
    {
        m.SaveAsWexBim(bw);
        bw.Close();
    }
    m.Close();
}
```

Regards

**Comment by martin1cerny** [comment]
Yes, it is just an overload to `IfcStore.Open()`:
```cs
public static IfcStore Open(Stream data, IfcStorageType dataType, IfcSchemaVersion schema, XbimModelType modelType, XbimEditorCredentials editorDetails = null, XbimDBAccess accessMode = XbimDBAccess.Read, ReportProgressDelegate progDelegate = null)
```
See this line: https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Ifc/IfcStore.cs#L167

**Comment by GrzegorzBlok** [comment]
Thank you! It looks like I just need to update my nuget packages :)
