### ISSUE TITLE
IfcTriangulatedFaceSet

### ISSUE THREAD

**Issue by JukkaMeklin** [xBimTeam/XbimEssentials#70]
Hi,
I am trying to create an IfcTriangulatedFaceSet but can't figure out how to initialize an ItemSet(of IfcPositiveInteger) to use with CoordIndex.Add method. VS says that it is not accessible in this content because of Friend. Could you please help me to find a right way to do this

Best Regards
Jukka

**Comment by martin1cerny** [comment]
All ItemSets are initialized by default. This is a special set in a way because it is a two dimensional array. To use it you have to do it like this:
```c#
var tfs = model.Instances.New<IfcTriangulatedFaceSet>();
var first = tfs.CoordIndex.GetAt(0);
var second = tfs.CoordIndex.GetAt(1);
var third = tfs.CoordIndex.GetAt(2);

first.AddRange(new [] { 0, 1, 2, 3 }.Select(i => new IfcPositiveInteger(i)));
second.AddRange(new [] { 4, 5, 6, 7}.Select(i => new IfcPositiveInteger(i)));
third.AddRange(new [] { 8, 9, 10, 11 }.Select(i => new IfcPositiveInteger(i)));
```
You can obviously just insert discrete values at the end using simple `.Add(5)` method.

**Comment by JukkaMeklin** [comment]
Thank you Martin, it works fine
