### ISSUE TITLE
How to change type of IFC object?

### ISSUE THREAD

**Issue by 1marcel1** [xBimTeam/XbimEssentials#74]
Hi, i am very new in xbim. I have exported two IFC files with the same object but different ifc entity type.
First is IFCBUILDINGELEMENTPROXY and second is IFCWALLSTANDARDCASE - rest informations like cartesian point, loops, etc are the same. I want open IFC file with IFCBUILDINGELEMENTPROXY type and only change it to IFCWALLSTANDARDCASE - is it possible to do in this way? I trying cast objects but this throws me an error. Thanks for any suggestions.

**Comment by martin1cerny** [comment]
Casting is not what you want to do. You can only cast an object to something it actually IS (like *IfcBuildingElement* to *IfcWall* if it **IS** a wall). What you would need to do in this case is to create new object *IfcWallStandardCase*, copy common attributes from *IfcBuildingElementProxy* and change all references in the model from proxy to the wall.

**Comment by 1marcel1** [comment]
Martin really thanks for your answer. What in case if i would like to use something like isertCopy method (for copy from model with _IfcBuildingElementProxy_ to new target model as _IfcWallStandardCase_)? The same way?

**Comment by martin1cerny** [comment]
You would need to do something similar to `InsertCopy()` but that is not designed to support your scenario at the moment. It only creates instance of the same type. To support your case you need to implement additional logic to identify matching attributes. You would also need to only create a shallow copy of the data where `InsertCopy()` is designed for a deep copy.

**Comment by 1marcel1** [comment]
Thanks, i will try to create my own version of `InsertCopy()` method for my case.
