### ISSUE TITLE
Extract IFC file hierarchy and geometry to recreate meshes in Unity

### ISSUE THREAD

**Issue by ani-rudh** [xBimTeam/XbimEssentials#75]
I am looking to load a .ifc file and relpicate the tree structure (hierarchy) in a game engine for developing Virtual Reality apps for AEC projects. 
Anyway,
My interest is to load an IFC file in Unity and rebuild the whole model with exact geometry in Unity. Please point me to right direction to get started. I am a total newbie to xBIM and  IFC in general.

The process I want to implement is somewhat like this:
1. load IFC files using xBIM.
2. Parse through the tree structure and replicate that in Unity (need geometric information and parent-child relation ship of each node in the IFC file)
3. For each IFC ENTITY (visible geometry), extract the transforms, triangulated mesh data and materials.
4. Use the info from step 3 to create meshes in Unity for further processing.
----------------------------------------------------------------------------------------------------------
Sorry for a duplicate question here ( I have asjed this in xBIMGeometry a well). I do not understand if this question is relevant to xBIMEssentials or xBIMGeometry!!!

**Comment by martin1cerny** [comment]
It is appropriate question here but I have already replied to the duplicate [here](https://github.com/xBimTeam/XbimWebUI/issues/59#issuecomment-285466089).
