### ISSUE TITLE
IFC hierarchy retrieveal - get elements under IfcSpace

### ISSUE THREAD

**Issue by ani-rudh** [xBimTeam/XbimEssentials#76]
@martin1cerny , thanks for the right pointer to hierarchy decomposition through this code in issue #73  
```
using System;
using System.Linq;
using Xbim.Ifc;
using Xbim.Ifc4.Interfaces;

namespace BasicExamples
{
    class SpatialStructureExample
    {
        public static void Show()
        {
            const string file = "SampleHouse.ifc";
            
            using (var model = IfcStore.Open(file))
            {
                var project = model.Instances.FirstOrDefault<IIfcProject>();
                PrintHierarchy(project, 0);
            }
        }

        private static void PrintHierarchy(IIfcObjectDefinition o, int level)
        {
            Console.WriteLine($"{GetIndent(level)}{o.Name} [{o.GetType().Name}]");
            foreach (var item in o.IsDecomposedBy.SelectMany(r => r.RelatedObjects))
                PrintHierarchy(item, level +1);
        }

        private static string GetIndent(int level)
        {
            var indent = "";
            for (int i = 0; i < level; i++)
                indent += "  ";
            return indent;
        }
    }
}
```

Anyway, this does not return the elements under the IfcSpace object.

For e.g, as attached pictures show, the code retireves the ifcSpace object, but it doesn"t get the ifcAirFlowTerminal that resides under that.

I tried on another code to get IfcSpatialStructureElement.getcontaineditems(), which retrieves the elements. 

Is there a way to do the same so that your example can retrieve the deeper levels of the tree structure?

You can consider me a noob if iI am missing something very simple/obvious! I need help, please!

Best,
Ani

![1](https://cloud.githubusercontent.com/assets/15331399/23825149/9e879d0a-0684-11e7-826b-7b84c54f2401.PNG)
![capture](https://cloud.githubusercontent.com/assets/15331399/23825150/9e8b44a0-0684-11e7-816d-41a3b405fb29.PNG)

**Comment by martin1cerny** [comment]
Yes, see the code you are referring to or the code in XbimXplorer please.

**Comment by ani-rudh** [comment]
So, I am doing this, which does give me very good results. Is there a better and a more efficient way to do this?

the 'spaceidset' and 'storeyidset' are a list of global ids of all the IfcBuildingStorey and IfcSpace instances.

> private static void PrintHierarchy(IIfcObjectDefinition o, int level, Dictionary<string, IfcSpace> spaceidset, Dictionary<string, IfcBuildingStorey> storeyidset)
        {
            Console.WriteLine($"{GetIndent(level)}{" >> " + o.Name} [{o.GetType().Name}{ " | " + o.EntityLabel }]");
            var item = o.IsDecomposedBy.SelectMany(r => r.RelatedObjects);

            foreach (var i in item)
            {
                PrintHierarchy(i, level + 2, spaceidset, storeyidset);

                var id = i.GlobalId.ToString();
                if (spaceidset.ContainsKey(id))
                {
                    IfcSpace spacenode;
                    spaceidset.TryGetValue(id, out spacenode);
                    var spacenodelelems = spacenode.GetContainedElements();

                    if (spacenodelelems.Count() > 0)
                    {
                        Console.WriteLine($"{GetIndent(level + 3)}" + "OBJECTS FOUND ARE: ");
                        foreach (var sne in spacenodelelems)
                        {
                            var parent = sne.IsContainedIn;
                            
                            Console.WriteLine($"{GetIndent(level + 4)}{" -> " + sne.Name} [{sne.GetType().Name}{ " | " + sne.EntityLabel }{"PARENT : " + parent}]");
                        }
                    }
                }

                else if (storeyidset.ContainsKey(id))
                {
                    IfcBuildingStorey bsnode;
                    storeyidset.TryGetValue(id, out bsnode);
                    var bsnodelelems = bsnode.GetContainedElements();

                    if (bsnodelelems.Count() > 0)
                    {
                        Console.WriteLine($"{GetIndent(level + 3)}" + "OTHER OBJECTS FOUND UNDER STOREY ARE: ");
                        foreach (var bsne in bsnodelelems)
                        {
                            var parent = bsne.IsContainedIn;
                            
                            Console.WriteLine($"{GetIndent(level + 4)}{" -> " + bsne.Name} [{bsne.GetType().Name}{ " | " + bsne.EntityLabel } {"PARENT : " + parent}]");

                            
                        }
                    }
                }


            }

        }

**Comment by CBenghi** [comment]
@ani-rudh,
I'm trying to tidy up the repositories, is it ok to close this issue?
I'm not sure I understand your last post, and what you are specifically asking for.
Thanks,
Claudio

**Comment by martin1cerny** [comment]
To answer the question: 
Yes, this works for IFC2x3 because `GetContainedElements()` is an extension method which is only implemented for IFC2x3 as well as all other extension methods. It is left there for a legacy purpose but I wouldn't recommend to use it in a new project. Extension methods are useful shortcuts but might not be very efficient. It is usually better to understand the [IFC schema](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/) and to implement the code which considers the underlying structure. For your case the most universal approach would be this:

```cs
using System;
using System.Linq;
using Xbim.Ifc;
using Xbim.Ifc4.Interfaces;

namespace BasicExamples
{
    class SpatialStructureExample
    {
        public static void Show()
        {
            const string file = "SampleHouse.ifc";
            
            using (var model = IfcStore.Open(file))
            {
                var project = model.Instances.FirstOrDefault<IIfcProject>();
                PrintHierarchy(project, 0);
            }
        }

        private static void PrintHierarchy(IIfcObjectDefinition o, int level)
        {
            Console.WriteLine($"{GetIndent(level)}{o.Name} [{o.GetType().Name}]");
            
            var spatialElement = o as IIfcSpatialStructureElement;
            if (spatialElement != null)
            {
                var containedElements = spatialElement.ContainsElements.SelectMany(rel => rel.RelatedElements);
                foreach (var element in containedElements)
                    Console.WriteLine($"{GetIndent(level)}    ->{element.Name} [{element.GetType().Name}]");
            }

            foreach (var item in o.IsDecomposedBy.SelectMany(r => r.RelatedObjects))
                PrintHierarchy(item, level +1);
        }

        private static string GetIndent(int level)
        {
            var indent = "";
            for (int i = 0; i < level; i++)
                indent += "  ";
            return indent;
        }
    }
}

```

**Comment by ani-rudh** [comment]
Ok, Thanks, will give it a try:)
