### ISSUE TITLE
Length unit assumption incorrect?

### ISSUE THREAD

**Issue by dbojadievski** [xBimTeam/XbimEssentials#77]
![scs for github metre problems](https://cloud.githubusercontent.com/assets/8057943/24142231/3cc71984-0e26-11e7-9b53-6a3552e61bf4.png)
I've been trying to measure distances in an app, and ran into valid math giving me suspicious length results. So, I took a peek at the IfcStore::CalculateModelFactors function and found something that stood out.

When we calculate the appropriate conversion factors, the length unit is assumed to be stated in metres; however, some models (and almost all of those I have available for testing) express length in millimetres. This discrepancy between the assumed and actual unit (as expressed by the 'Prefix' field of the IFCSIUnit class) doesn't seem to be taken into account.

Before I go into changing this, I wanted to ask if there's something I'm missing here? Is there a convention I don't know of, or is the toolkit compensating for this in another fashion I'm unaware of?

Or, to put it differently, should I change this and create a pull request, would those changes be accepted? It seems an awfully important thing.

**Comment by martin1cerny** [comment]
Before the switch statement we use `siUnit.Power` to calculate the scale as you can see on your own screenshot. So it gives the right answer as far as I know. We do use this internally and we never had a problem with it.

**Comment by dbojadievski** [comment]
That's kind of the origin of the entire uncertainty. The way the power is specified makes me think the calculation is valid, but the results I've gotten are pretty small. So small, in fact, to be suspicious. 

For an example, should I measure the distance between two points on a wall (the top and bottom points on the red, highlighted wall) on the FourWalls model (provided by Xbim), it results in a distance of ~0.028 metres; this seems to be an awfully small distance to me, unless the model is modelled to a very small scale.


![dist points](https://cloud.githubusercontent.com/assets/8057943/24143499/2d94d0a6-0e2a-11e7-8030-3d23b64be99a.PNG)

**Comment by dbojadievski** [comment]
Fair enough. Let's close the ticket, then; the misconception I've had about the conversion units has been cleared up.

**Comment by CBenghi** [comment]
Hi, just for completeness:
If you are using XbimXplorer, the view coordinates are transformed in meters in the loadgeometry function. There's a tool in the UI to measure distances with the ctrl button pressed as you click on model points. 
Distances are displayed in the status bar on the bottom and they are always expressed in meters.
Best,
Claudio
