### ISSUE TITLE
ifcstore.open - error message now

### ISSUE THREAD

**Issue by oliviersaintgobain** [xBimTeam/XbimEssentials#78]
Hello,
I'm working with the last version of xbimessentials, and something is not working now since last update.

I'm just trying to open an ifcfile from my webinstance. It works before upgrade.

The error message is :
Ligne 476 :        if (File.Exists(filePath))
Ligne 477 :        {            
Ligne 478 :            using (var model = IfcStore.Open(filePath))
Ligne 479 :            {
Ligne 480 :                var context = new Xbim3DModelContext(model);
  
 Fichier source :  C:\Users\olivier\Documents\Visual Studio 2015\WebSites\WebSite1\Default.aspx.cs    Ligne :  478 
Trace de la pile: 
[InvalidOperationException: Pile vide.]
   System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) +52
   System.Collections.Generic.Stack`1.Pop() +6780193
   Xbim.IO.Step21.XbimP21Parser.EndEntity() in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\XbimP21Parser.cs:204
   Xbim.IO.Parser.P21Parser.DoAction(Int32 action) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\StepP21Parser.y:107
   QUT.Gppg.ShiftReduceParser`2.Reduce(Int32 ruleNumber) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:330
   QUT.Gppg.ShiftReduceParser`2.Parse() in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Step21\Parser\ShiftReduceParserCode.cs:263
   Xbim.IO.Memory.MemoryModel.LoadStep21(Stream stream, Int64 streamSize, ReportProgressDelegate progDelegate) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:535
   Xbim.IO.Memory.MemoryModel.LoadStep21(String file, ReportProgressDelegate progDelegate) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.IO\Memory\MemoryModel.cs:550
   Xbim.Ifc.IfcStore.Open(String path, XbimEditorCredentials editorDetails, Nullable`1 ifcDatabaseSizeThreshHold, ReportProgressDelegate progDelegate, XbimDBAccess accessMode) in C:\BuildAgent\work\77d7b8e93613846d\Xbim.Ifc\IfcStore.cs:362
   _Default.Button3_Click(Object sender, EventArgs e) in C:\Users\o6305218\Documents\Visual Studio 2015\WebSites\WebSite1\Default.aspx.cs:478
   System.Web.UI.WebControls.Button.OnClick(EventArgs e) +9692746
   System.Web.UI.WebControls.Button.RaisePostBackEvent(String eventArgument) +108
   System.Web.UI.WebControls.Button.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument) +12
   System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument) +15
   System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData) +35
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3562

 Strange no ?

thanks for your help, I don't know hat happened...

**Comment by martin1cerny** [comment]
Can you share the file?

**Comment by oliviersaintgobain** [comment]
sure. just rename in .ifc ;)


[CP-IBR 400-BETONS.TXT](https://github.com/xBimTeam/XbimEssentials/files/864195/CP-IBR.400-BETONS.TXT)

**Comment by martin1cerny** [comment]
It is not a problem of xBIM but it is an invalid file. The first entity is

```
#1= IFCORGANIZATION(Olivier,'Olivier',$,$,$);
```

Where the first string is not in quotes so parser can't handle it properly. It should be

```
#1= IFCORGANIZATION('Olivier','Olivier',$,$,$);
                    ^       ^
```

If you had a [logger attached](http://docs.xbim.net/examples/watch-the-log.html) you would get a clear message:

```
ERROR - Illegal character found at line 17, column 27
```

**Comment by martin1cerny** [comment]
I assume you know you can [create IFC files](http://docs.xbim.net/examples/basic-model-operations.html) with xBIM too? xBIM can't ever create an invalid file like this.

**Comment by oliviersaintgobain** [comment]
I know it. For the moment, I'm using GeometryGym library but I will check the xbim creation file now ;)
thanks a lot for this.

Olivier
