### ISSUE TITLE
IfcOpenShell cast issue?

### ISSUE THREAD

**Issue by dontbmh** [xBimTeam/XbimEssentials#79]
Hi,

Xbim3DModelContext line 1160,                 
var shape = (IIfcGeometricRepresentationItem)Model.Instances[shapeId];

would throw invalid cast exception, when the shape is type of ifcopenshell.

Any suggestion?

Cheers.

**Comment by martin1cerny** [comment]
Can you post data + code please? Also this issue should really be asked in [XbimGeometry](https://github.com/xBimTeam/XbimGeometry/issues/) project

**Comment by dontbmh** [comment]
sorry, I'm closing this and reopen one with a test ifc file in XbimGeometry
