### ISSUE TITLE
XBimVector3D.Angle() returns wrong results

### ISSUE THREAD

**Issue by Jero9999** [xBimTeam/XbimEssentials#80]
There seems to be a bug in the logic when the vectors are short. 
Try getting the angle between [0, 0, 0.5] and [0, 0, 1] The result will be around 1.04. It should be 0.
In this case the logic does actually work for any vector longer than unit length.

**Comment by martin1cerny** [comment]
Angle between two vectors should only be 0 if they are collinear. In your case these two vectors are **not collinear** so there **must be an angle** between them.

**Comment by CBenghi** [comment]
@martin1cerny, 
I've not looked into the code, but I'm puzzled by your answer, the two vectors that @Jero9999 mentions both normalise to [0,0,1] is it right that the angle should not be 0?

**Comment by martin1cerny** [comment]
Sorry, I didn't realize that at first. You are right and the algorithm will only work for normalized vectors where it should consider size of the vectors. I'll delete my wrong reply.
