### ISSUE TITLE
Versions on Github

### ISSUE THREAD

**Issue by yauron** [xBimTeam/XbimEssentials#82]
Hello. I am particularly interested in the xbim project. Our company would like to use it, if we are able to run the sample project and then validate it to use. But unfortunately for the moment this is not the case, the sample project contains some syntax errors, which when corrected, makes a more delicate problem appear: it requires version 4.0.28-v013, and n ' Never arrives to update it since GitHub ... So what can we do? I have registered on myget, but for the moment, I still can not argue with the supplement nuget this source of package ... by the way, if we download it, nuget does not recognize this package as compliant. .It's very annoying.

**Comment by martin1cerny** [comment]
Hi @yauron ,

you don't need to register on MyGet to use our development feeds. See the [notes about compilation](http://docs.xbim.net/) please. Just open NuGet setting and create the two new feeds there. However, if you just want to try [sample code](http://docs.xbim.net/quick-start.html) 99% should just work with our NuGet releases.

Martin

**Comment by CBenghi** [comment]
One step at a time:

> The sample project contains some syntax errors, 

Can you let us know what is the syntax error so it can be fixed? 

> It requires version 4.0.28-v013, and n ' Never arrives to update it since GitHub ... 

It's unclear what requires version v013 of what else. You have posted this comment on Essentials, which has no dependencies to other XBim components.

> I have registered on myget, but for the moment, I still can not argue with the supplement nuget this source of package

as Martin says there's no need to register on myget, you need instead to add the nuget sources as mentioned in the compilation section of the notes that Martin has linked in the previous response.

> by the way, if we download it, nuget does not recognize this package as compliant. 

Can you be more specific? All nuget packages seem to work well in our experience.

> It's very annoying.

Yes, sometimes annoying stuff happens.

**Comment by yauron** [comment]
J thanks for replying.

 

To begin, i must give precision about IDE : I was working under visual studio 2013. And maybe it’s not important but I’m not familiar with each  C# syntax.

So :

1/ in VS2013 begin a string with $ give syntax error. So I replace them with @, then  it’s fine. And operator ?. not recognize before VS2015.

2/ VS 2013 used to ask for 4.0.28-V013 each compilation time, so never compile… I’m ok to say that Essential not in cause because of no dependency. Sure another ask for, I still not remember it name himself as required.
3/ I try hard for 8hour to resolved each problem, and at this time, the only google answers was “myget” because it had the version it ask.

4/ now I know that I wasn’t necessary to signup on myget to obtain the required version. But  Visual studio is able to manage with myget so it work.

5/ the first tentative on myget was to download .nupkg file, and to add nugget source on download folder… but he never see then as avaible nugget package.

 

Now I’m trying to learn more about xbim.explorer. Pretty hard to understand IFCPropertySet object.

 



 

De : Claudio Benghi [mailto:notifications@github.com] 
Envoyé : mardi 18 avril 2017 14:37
À : xBimTeam/XbimEssentials
Cc : yauron; Mention
Objet : Re: [xBimTeam/XbimEssentials] Versions on Github (#82)

 

One step at a time:

The sample project contains some syntax errors,

Can you let us know what is the syntax error so it can be fixed?

It requires version 4.0.28-v013, and n ' Never arrives to update it since GitHub ...

It's unclear what requires version v013 of what else. You have posted this comment on Essentials, which has no dependencies to other XBim components.

I have registered on myget, but for the moment, I still can not argue with the supplement nuget this source of package

as Martin says there's no need to register on myget, you need instead to add the nuget sources as mentioned in the compilation section of the notes that Martin has linked in the previous response.

by the way, if we download it, nuget does not recognize this package as compliant.

Can you be more specific? All nuget packages seem to work well in our experience.

It's very annoying.

Yes, sometimes annoying stuff happens.

**Comment by CBenghi** [comment]
Dear @yauron,
I've made some changes to the code in the XbimSamples application so that the solution is now compatible with VS2013. 
I hope this helps others in the future.
Thanks for your feedback.
Claudio

**Comment by yauron** [comment]
Thank you a lot.



Your closing gold is to use IFC data to list item and associate it with your estimating model. Next we may create a specific IFC file to share estimating cost to each user.

So, I works very hard the last 2 week, to be the most instructed people in my society about IFC. This also means, we are really in late because, we did not mind enough about BIM for more than 10 years.


We know that everything can’t be done automatically by programming, but we do our best to be able to present the most successful result.

But we are lack of BIM culture and IFC programming. So if you accept it, may i ask you some kindly questions to better understand IFC operations ?

 

As You pleased…

--/--

 

-          We are delighted by the quality of the work carried out by the xBimTeam, and therefore we would like to know if the xBimTeam will continue to keep its programming library up to date with the upcoming IFC 4, 5,. ..?

-          Have you a kind of link with SMARTBuilding ?

-          Is there an example IFC file showing how any component of a manufacturer catalog would be attached to an IFC component (wall, window, ...) ?

-          If we understand: the plurality of the actors ultimately generates the need to federate the IFC files to have only one file to share with several. We try to imagine how these contents, both very voluminous and with very different natures, coexist before this fusion. Is there an IFC (like include instruction in C ++) object referencing another IFC file so that the already very large geometric description, and the project description, is no more necessary to be repeated in a content intended to, for example, establish a cost estimate ?



Hope this will not annoying you too much.






 



 

De : Claudio Benghi [mailto:notifications@github.com] 
Envoyé : jeudi 27 avril 2017 18:52
À : xBimTeam/XbimEssentials
Cc : yauron; Mention
Objet : Re: [xBimTeam/XbimEssentials] Versions on Github (#82)

 

Dear  <https://github.com/yauron> @yauron,
I've made some changes to the code in the XbimSamples application so that the solution is now compatible with VS2013.
I hope this helps others in the future.
Thanks for your feedback.
Claudio

**Comment by yauron** [comment]
Sorry for my English skill…


“Your closing gold is…” -> “Our closest goal is…”

 



 

De : Claudio Benghi [mailto:notifications@github.com] 
Envoyé : jeudi 27 avril 2017 18:52
À : xBimTeam/XbimEssentials
Cc : yauron; Mention
Objet : Re: [xBimTeam/XbimEssentials] Versions on Github (#82)

 

Dear @yauron <https://github.com/yauron> ,
I've made some changes to the code in the XbimSamples application so that the solution is now compatible with VS2013.
I hope this helps others in the future.
Thanks for your feedback.
Claudio

**Comment by CBenghi** [comment]
You are welcome, 
never mind the language, English is second language for me as well, I know it's not easy.
At Northumbria University we also offer consultancy  services if your company wants a bit of help and assurance to be going in the right direction.
Best,
Claudio

**Comment by yauron** [comment]
Maybe yes.
Who must i call at Northumbria University ? Any number or email address ?

**Comment by CBenghi** [comment]
You can search for me on Skype (username is Bonghi, full name Claudio Benghi), 
or send an email to claudio.benghi@gmail.com for a first contact.
Best,
Claudio
