### ISSUE TITLE
INTEG.RAW File after Dirty Shutdown 

### ISSUE THREAD

**Issue by BjDi** [xBimTeam/XbimEssentials#83]
Hello, I sometimes get those files, but I don't know how to provoke them.
Now my question.
Can I set the path, where those file are written to, or what happens, if
a user doesn't have the permission for the folder, where the ...INTEG.RAW file is written to?

Is it produced via the Esentutl / repair tool?

**Comment by martin1cerny** [comment]
I never used these files but it should be a [report of database integrity check](https://technet.microsoft.com/en-us/library/aa998351(v=exchg.65).aspx) when your application crashed while working with Esent database (which is used by EsentModel).

**Comment by BjDi** [comment]
Hello Martin,
now I manually called the code to repair an xBim File (like you do it in your code, see PersistedEntityInstanceCache.cs AttachedDatabase with 
// try and fix the problem with the badly shutdown database
                        var startInfo = new ProcessStartInfo("EsentUtl.exe")
                        {
                            WindowStyle = ProcessWindowStyle.Hidden,
                            UseShellExecute = false,
                            CreateNoWindow = true,
                            Arguments = String.Format("/p \"{0}\" /o ", _databaseName)
};
)
and that produces such an ...INTEG.RAW file, too!!

**Comment by BjDi** [comment]
Well, I could partialy answer my question. It doesn't happen anything, the Esentutl tool get's a timeout.
But if I could set another folder, the tool could do it's job.

**Comment by CBenghi** [comment]
@BjDi,
can you maybe investigate this with the esentutl people?
Thanks,
Claudio

**Comment by BjDi** [comment]
Hi Claudio,
I think the problem isn't the tool. The tool does it's job if you call it from another folder with write access.
And in your code you handle the failure. So I think it's ok. 
It would just have been possible to call the tool from a folder with write access or a temp folder, if you are not interested in the file.
