### ISSUE TITLE
How to create XBimModel from .xBim binary file?

### ISSUE THREAD

**Issue by minhnguyenlinknode** [xBimTeam/XbimEssentials#9]
Hi,

I know how to create an instant of XBimModel from .ifc file.
But I don't know how to create an instant of XBimModel from .xBim binary file?

Something like this:
var model = new Xbim.IO.XbimModel();
model.CreateFrom(xBimFile,....);

The reason is my IFC file is very big then it takes ages to create instant of XBimModel in the first time then I don't want to parse IFC file everytime. Therefore I think I should parse the .xBim instead in the second time as it should be faster than IFC text format.

Any ideas?

**Comment by andyward** [comment]
CreateFrom parses from the various IFC formats. You need `model.Open()` to re-open an xbim file. That'll be much faster than re-parsing from IFC each time. Something like:

```
model.Open(xBimFile, XbimExtensions.XbimDBAccess.Read, null);
```

**Comment by minhnguyenlinknode** [comment]
Thanks Andy. I'll try it :)
