### ISSUE TITLE
IFC to JSON with IfcStore

### ISSUE THREAD

**Issue by lufimoreira** [xBimTeam/XbimEssentials#94]
Hi, I am able to convert my IFC files to wexbim, however, I also need the JSON. I've followed this post: https://github.com/xBimTeam/XbimWebUI/issues/3 and I realised that XBimModel is outdated. How do I do this with IfcStore?

**Comment by martin1cerny** [comment]
Producing JSON file for the whole file is not scalable solution so we don't actively develop this feature. If you want to update the code to work with IfcStore, feel free to do so and I'll be happy to accept your pull request. Better solution is to write your own services to serve data from the model in chunks.

**Comment by lufimoreira** [comment]
Thank you for the answer, however, can you tell me if converting to Json with XbimModel is still viable? Since I get this error:
![screenshot_1](https://user-images.githubusercontent.com/28949933/27794357-cd932d8e-5ff9-11e7-83b8-f9488de69db0.png)

**Comment by martin1cerny** [comment]
Just do what it says. Pass `IfcStore` in as a parameter.

**Comment by lufimoreira** [comment]
I apologize if my questions are stupid. I tried to use the old way you used and now it looks like this:
![screenshot_2](https://user-images.githubusercontent.com/28949933/27840308-c4bb9236-60ef-11e7-9bc4-0d3d04252019.png)

It doesn't give me any errors, but the files come like this:
![screenshot_3](https://user-images.githubusercontent.com/28949933/27840330-e731dcda-60ef-11e7-9c10-4f9948100646.png)

The Json file is empty and the JFM file only returns NULLS.

I also thank you for all your help.

**Comment by martin1cerny** [comment]
You use wrong classes which are only used internally as helpers (as their names suggest). You need to use the exchanger class:

```cs
var facilities = new List<Facility>();
var exchanger= new IfcToCOBieLiteUkExchanger(model, facilities);
facilities = exchanger.Convert();

//there might be more than one facilities in theory but 
//COBie is only designed to hold a single building in a file.
for(var i = 0; i < facilities.Count; i++)
{
    var facility = facilities[i];
    var file = $"facility_{i}.json";
    facility.WriteJson(file);
}
```

**Comment by lufimoreira** [comment]
Oh, I see. What/Where is the _Facility_ class? From _List<Facility>()_. I need to reference it.

**Comment by martin1cerny** [comment]
Xbim.COBieLiteUK

**Comment by lufimoreira** [comment]
It is almost working (I think), but now I get an error I'm trying to solve, but I'm not having success. I caught an exception:
![screenshot_5](https://user-images.githubusercontent.com/28949933/27962706-a1720868-632a-11e7-84b8-18a95e1fab30.png)
![screenshot_4](https://user-images.githubusercontent.com/28949933/27962711-a65a99e4-632a-11e7-9e0e-3b53121fcc5c.png)
It is in portuguese, but it translates to "could not load file or assembly 'NPOI...".

This happens when I try to write the file.
![screenshot_6](https://user-images.githubusercontent.com/28949933/27962789-deabc098-632a-11e7-9b63-1e817e672a57.png)

Stepping into leads me to the selected lines, which is where they throw the exception:
![screenshot_7](https://user-images.githubusercontent.com/28949933/27962827-fa3f2e26-632a-11e7-8a71-a3b8446b602b.png)

![screenshot_8](https://user-images.githubusercontent.com/28949933/27962834-fde0a73a-632a-11e7-89d6-33f36e7830bb.png)


This is the output after running(only the part that matters):
![screenshot_9](https://user-images.githubusercontent.com/28949933/27962872-17f14bc0-632b-11e7-9a0a-e6d3e8158c95.png)

**Comment by martin1cerny** [comment]
Do what it says. Add the NPOI NuGet package.

Dne 7. 7. 2017 16:45 napsal uživatel "lufimoreira" <notifications@github.com

**Comment by lufimoreira** [comment]
Oh, I didn't realize it was so simple, sorry about that. It is working now, but only for IFC4. I'm going to try and make it work also for IFC2x3, since I get an error on facility. Thanks for all the help and again, I apologize for all the stupid questions. If you need something I can help with you can just ask.

**Comment by martin1cerny** [comment]
Thank you, you are welcome.

Dne 9. 7. 2017 17:40 napsal uživatel "lufimoreira" <notifications@github.com
