### ISSUE TITLE
Aggregated elements missing

### ISSUE THREAD

**Issue by franky235** [xBimTeam/XbimEssentials#95]
Hi, Posted my issue here (https://github.com/xBimTeam/XbimExchange/issues/25) but I feel XbimEssentials is involved: I am converting IFC to wexbim and json, and subparts of aggregated elements (like slabs in roof) are ok in wexbim but missing in json.
The variable returned by IfcStore.Open is uncomplete for subparts (like RelatingStructure missing) and subsequently eliminated by COBieLiteUKHelper (as far as I unerstand the code)
Any guidance to help me solve this ?

**Comment by martin1cerny** [comment]
It is unlikely that objects would be missing when you open the IfcStore. If it is in the file and the file is valid IFC2x3 of IFC4 file it will be there. If you believe it is not the case, can you please share the code and data to test it?

Anything related to COBieLiteUK should only be asked in XbimExchange.

**Comment by franky235** [comment]
Thanks for your quick answer, very easy to test on your side
I only modified the provided CreateCobiePas1192 sample :

            using (var m = IfcStore.Open("Duplex_A_20110907_optimized.ifc"))
            //            using (var m = IfcStore.Open("Lakeside_Restaurant.ifc"))
            {
                var facilities = new List<Facility>();
                var ifcToCoBieLiteUkExchanger = new IfcToCOBieLiteUkExchanger(m, facilities);
                facilities = ifcToCoBieLiteUkExchanger.Convert();

                var facilityType = facilities.FirstOrDefault();
                if (facilityType == null)
                    return;
                //write the cobie data in json format
                facilityType.WriteJson("Cobie.json", true);
                //write the cobie data in xml format
                //facilityType.WriteXml("Cobie.xml", true);
                //write the cobie data in spreadsheet format                 
                //string errMsg;
                //facilityType.WriteCobie("Cobie.xls", out errMsg);
                System.Console.WriteLine("Press Return");
                System.Console.ReadLine();
            }

Ifc file can be found here: http://projects.buildingsmartalliance.org/files/?artifact_id=4278

I totally agree objects are not missing in the IfcStore, but they are returned such a way COBieLiteUK are filtering them afterwards, like the 4229 IfcSlab (and parts of IfcStairs, like IfcRailings), probably because some info are missing in the IfcStore (like the RelatingStructure) but I am not 100% sure

**Comment by martin1cerny** [comment]
I can guarantee that this kind of information **is not missing** in `IfcStore`. You will need to investigate conversion from IFC to COBieLiteUK. I'll add a comment to your question in XbimExchange.
