### ISSUE TITLE
Can XbimEssentials build on Linux with .net core?

### ISSUE THREAD

**Issue by AlexanderChen1989** [xBimTeam/XbimEssentials#98]
How to compile xbim on .net?

**Comment by martin1cerny** [comment]
Not out of the box. While the xBIM code itself should be possible to compile to .NET Core, there are dependencies which can't. One is Log4Net which supports .NET Core but upgrade + minor refactoring would be required. Second is ManagedEsent which is used to persist indexed data for fast random access with minimal memory footprint. This is a managed wrapper around Esent database engine which is built in all versions of Windows which makes it Windows dependant. However, it could be isolated/removed and you would still have MemoryModel as an implementation of IModel which is platform neutral. So, it is possible but not straightforward.

**Comment by AlexanderChen1989** [comment]
@martin1cerny thanks
