### ISSUE TITLE
New model with custom units

### ISSUE THREAD

**Issue by johnnyontheweb** [xBimTeam/XbimEssentials#99]
Sorry in advance for the stupid question, but I cannot find anywhere a sample for this.
I want to specify manually the units for my project (i.e. "m", "°C", etc....), how can I do that?

I can find only this in the Basic Models operations:
`project.Initialize(ProjectUnits.SIUnitsUK)`

but this obliges to use "mm" as length units.

Thanks.
ps.
there's a lot of issues still opened in the XbimSamples page.

**Comment by martin1cerny** [comment]
This is just a helper function to create default settings. Please, see the result and have a look at IFC documentation. You can than use standard xBIM functions to change/create IFC as you wish.

**Comment by johnnyontheweb** [comment]
Thanks for your reply. Sorry again for the stupi question, but I found too much difficult to inderstand how to correctly use xBIM ... can you provide a link to the proper documentation you mentioned? thanks a lot

**Comment by martin1cerny** [comment]
See UnitsInContext [here](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifckernel/lexical/ifcproject.htm).
